<?php 
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $group=$this->url(array('module'=>'group','controller'=>'index','action'=>'index'), null, true);
	  $other=$this->url(array('module'=>'other','controller'=>'index','action'=>'index'), null, true);
	  $old_report=$this->url(array('module'=>'allreport','controller'=>'index','action'=>'index'), null, true);
	  $report=$this->url(array('module'=>'report','controller'=>'index','action'=>'index'), null, true);
	  $loan_view=$this->url(array('module'=>'loan','controller'=>'index','action'=>'index'), null, true);
	  $accounting_view=$this->url(array('module'=>'accounting','controller'=>'index','action'=>'index'), null, true);
	  $teller=$this->url(array('module'=>'tellerandexchange','controller'=>'index','action'=>'index'), null, true);
	  $payroll_view=$this->url(array('module'=>'payroll','controller'=>'index','action'=>'index'), null, true);
	  $callecterall=$this->url(array('module'=>'callecterall','controller'=>'index','action'=>'index'), null, true);
	  $capital=$this->url(array('module'=>'capital','controller'=>'index','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvAcl','controller'=>'index','action'=>'index'), null, true);
      $setting=$this->url(array('module'=>'setting','controller'=>'index','action'=>'index'), null, true);
	  $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	  $item_arr=array(
		'index'=>'<li class="link">
							<a title="ទំព័រដើម" href="'.$home.'">
								<span>'.$tr->translate("ទំព័រដើម").'</span>
							</a>
						</li>',
	  	'other'=>'<li class="link">
			  		<a title="Parameter" href="'.$other.'">
			  		<span>'.$tr->translate("Parameter").'</span>
			  		</a>
			  		</li>',
	  	'group'=>'<li class="link">
						<a title="ព័ត៏មានរបស់អតិថិជន" href="'.$group.'">
							<span>'.$tr->translate("Group Member").'</span>
						</a>
					</li>',
	    'loan'=>'<li class="link">
						<a title="ព័ត៏មានប្រាក់កម្ចី" href="'.$loan_view.'">
							<span>'.$tr->translate("Loan View").'</span>
						</a>
					</li>',	 
	  /*	'callecterall'=>'<li class="link">
			  		<a title="" href="'.$callecterall.'">
			  			<span>'.$tr->translate("Callecterall").'</span>
			  		</a>
	  		</li>',
	  	'payroll'=>'<li class="link">
			  		<a title="ព័ត៏មានប្រាក់ខែ" href="'.$payroll_view.'">
			  			<span>'.$tr->translate("Payroll").'</span>
			  		</a>
	  		</li>',*/
	  	'tellerandexchange'=>'<li class="link">
			  		<a title="" href="'.$teller.'">
			  			<span>'.$tr->translate("TELLER Module").'</span>
			  		</a>
	    </li>',/*
	  	'capital'=>'<li class="link">
		  			<a title="ព័ត៏មានប្រាក់ខែ" href="'.$capital.'">
		  				<span>'.$tr->translate("Capital").'</span>
		  			</a>
	  			</li>',*/
	  	'accounting'=>'<li class="link">
			  		<a title="ព័ត៏មានចំណាយផ្សេងៗ" href="'.$accounting_view.'">
			  			<span>'.$tr->translate("Accounting").'</span>
			  		</a>
	  			</li>',
	  	'report'=>'<li class="link">
			  		<a title="Report" href="'.$report.'">
			  			<span>'.$tr->translate("Reports").'</span>
			  		</a>
			  		</li>',
	  	'rsvAcl'=>'<li class="link">
			  		<a title="acl" href="'.$acl.'">
			  			<span>'.$tr->translate("Module Mg").'</span>
			  		</a>
			  		</li>',
	    'backup'=>'<li class="link">
						<a title="BACKUP DATABASE" href="'.$backup.'">
							<span>'.$tr->translate("BACKUP DB").'</span>
						</a>
					 </li>',	  
	  
	  'setting'=>'<li class="link">
	  		<a title="USER" href="'.$setting.'">
	  		<span>'.$tr->translate("SETTING").'</span>
	  		</a>
	  		</li>',
	  );
?>  
<div id="menu">
	<ul>
		<?php
			foreach($item_arr as $key=>$value){
				if($module==$key){
					echo str_replace('class="link"', 'class="current"', $value);
				}
				else{
					echo $value;
				}
			} 
		?>
	</ul>
</div>