<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <?php $class='tundra';?>
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/tundra/<?php echo $class?>.css"/>
	
	<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link href="<?php echo $base_url;?>/cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<!-- table  -->
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>

	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
*{ padding:0;margin:0;}
    html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.fullside{ width:98%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:96%; font-family:'Khmer OS Battambang'}
		.normal,.alternate{ font-size:90% !important;}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
	</style>	
</head>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require('dijit.form.Form');
dojo.require('dijit.form.FilteringSelect');	
dojo.require('dijit.form.Button');
dojo.require('dijit.form.NumberTextBox');
dojo.require("dijit.form.CheckBox");     
dojo.require("dojo.number");
dojo.require('dojox.form.BusyButton');
dojo.require("dijit.form.RadioButton");
dojo.require("dijit.Dialog");

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.layout.AccordionContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.parser");
</script>
    <!-- <body class="soria">
    <body class="soria"> -->
    <body class="<?php echo $class;?>" style="overflow-y: hidden;">
        <div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 100%;">
            <!-- <div dojoType="dijit.layout.ContentPane" region="top">
             <img src='<?php //echo $base_url;?>images/logo.png' height="100px"/
            <?php 
				//$session_user=new Zend_Session_Namespace('auth');
			    //$username = $session_user->first_name;
        						?>
				កំពុង​ប្រើ​ប្រាស់ ដោយ: <a href="<?php //echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><font color="#006600"><?php //echo $username;?></font></a>
				 | <a href="<?php //echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"><font color="#006600">ចាក​ចេញ </font></a>
            </div>>-->
            <div dojoType="dijit.layout.ContentPane" region="top">
                <?php echo $this->render('header.phtml')?>
                 <?php if($action=='index'){?>
                 <a style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?></a>
				<?php }elseif($action=='add' OR $action=='edit'){?>	
					<a style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><<?php echo $tr->translate('GO_BACK');?></a>
				<?php }?>
                 <?php //echo $this->render('toolbar.phtml')?>
            </div>
           
             <?php if($module!='home'){?>
            <div dojoType="dijit.layout.ContentPane" region="left">
             <?php echo $this->render('menuleft.phtml')?>
             
             <?php //echo $this->render('subtoolbar.phtml')?>
            <!-- <div splitter="true" id="leftmenu" dojoType="dijit.layout.AccordionContainer" region="leading">
               
                <div class="mleft" style="background:#d0e9fc;" dojoType="dijit.layout.AccordionPane" title="pane #1">
                </div>
                <div dojoType="dijit.layout.AccordionPane" title="pane #2">
                    accordion pane #2
                </div>
                <div dojoType="dijit.layout.AccordionPane" title="pane #3">
                    accordion pane #3
                </div> 
            </div>-->
            </div>
            <?php }?>
            <?php 
            $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
            ?>
            <div dojoType="dijit.layout.AccordionPane" region="center">
          			 
			<div style="clear: both;"></div>
				<?php if($module=='report' AND $action!='rpt-paymentschedules'){?>
				<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					showLabel="false" type="button" onclick="doPrint();">Print</button>
					<div id="divPrint">
				<?php }?>
	                <?php echo $this->layout()->content; 
	               	if($module=='report' AND $action!='rpt-paymentschedules'){
	                ?>
                </div>
                <?php }?>
            </div>
            <div dojoType="dijit.layout.ContentPane" region="bottom">
<!--                <ul>
					<li><?php //echo $tr->translate("COPY_RIGHT")." &copy; ".$tr->translate("COPY_RIGHT_BY");?></li>
					<li><?php //echo $tr->translate("VERSION");?></li>
					<li><?php //echo $tr->translate("POWER_BY");?></li>
				</ul>  -->
            </div>
        </div>
    </body>
</html>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
</script>