<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('auth');
	$username = $session_user->first_name;
	$them_style =  $session_user->theme_style;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<script>dojoConfig = {parseOnLoad: true}</script>
	    <script>
		require(["dojo/parser",
		 "dojo/ready","dijit/form/DateTextBox","dijit/form/ValidationTextBox","dijit/form/Form",
         "dijit/form/FilteringSelect","dijit/form/Button","dijit/form/NumberTextBox",
         "dijit/form/CheckBox","dijit/form/CheckBox","dojo/number","dojox/form/BusyButton",
         "dijit/form/RadioButton","dijit/Dialog","dijit/layout/BorderContainer",
         "dijit/layout/TabContainer",
		 "dijit/layout/AccordionContainer","dijit/layout/ContentPane","dijit/layout/ContentPane"]);

</script>
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/<?php echo $them_style."/".$them_style?>.css"/>
	
	<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link href="<?php echo $base_url;?>cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<!-- table  -->
	<?php //if($action=='index'){ ?>
	
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>
	<?php //}?>
	<!-- export library -->
	 <script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/tableExport.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jquery.base64.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/html2canvas.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/sprintf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/jspdf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/base64.js"></script> 
	<!-- end -->
	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
		*{ padding:0;margin:0;}
        html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.add-link{  
				    background-color: rgb(90, 138, 237);
			  width: 90px;
			  margin-top: 2px;
			  color: #fff;
			  text-align: center;
			  font-size: 13px;
			  font-weight: 600;}
		.fullside{ width:98%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:96%; 
		font-family: 'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif;
		/*font-family:Arial,serif !important;*/ /*font-family:'Khmer OS Battambang'*/}
		.normal,.alternate{ font-size:90% !important;}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
		.border{ border: 1px solid #ccc; height: 100%; margin: 5px; padding: 5px;}
        .border1{ border: 1px solid #ccc; height: 100%; margin: 5px; margin-left:0px; padding: 5px;}
		
	</style>	
	
</head>
    <body class="<?php echo $them_style;?>" >
       <!--  <div data-dojo-type="dijit/layout/BorderContainer" style="width: 100%; height: 100%;"> -->
             <!-- <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'top'"> -->
            <table width="100%">
                <tr>
                	<td colspan="2" valign="top" style="position: fixed;width: 100%; z-index: 1;top: 0;background:rgb(243, 241, 241) none repeat scroll 0% 0%" >
                		 <?php echo $this->render('header.phtml')?>
			                <p style="font-size:13px !important; ">
						              <span style="padding-left: 3px;padding-right: 3px;float: left; font-weight:600;"><?php echo $tr->translate("USING_BY");?><a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><?php echo $username;?></a></span>  
							<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"> | <?php echo $tr->translate("SIGN_OUT");?></a>
			                 <?php if($action=='index' AND $module!='report' AND $module!='home'){?>
			                 <a class='add-link' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?></a>
							<?php }elseif($action=='add' OR $action=='edit' OR $module=='report'){?>
							 <span style="padding-left: 3px;padding-right: 3px; float: right; font-weight:600;"><a class='add-link' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><?php echo $tr->translate('GO_BACK');?></a></span>
							<?php }?>
							</p>
                	</td>
                </tr>
                <tr>
                	<td colspan="2" height="70px;"></td>
                </tr>
            	<tr>
            		<td valign="top" <?php if($module!='home') echo'width="220px"';  ?> >
            			 <?php if($module!='home'){?>
            			<?php echo $this->render('menuleft.phtml')?>
            			<?php }?>
            		</td>
            		<td valign="top">
            			<?php if($module=='report' AND $action!='index'){?>
							<div class="menureport">
								<ul>
									<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
									<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
									<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
								</ul>
							</div>
							<div style="clear:both;"></div>
							<?php }?>
            			<?php echo $this->layout()->content; ?>
            			<?php //echo $this->layout()->content; 
			               	if($module=='report' AND $action!='rpt-paymentschedules'){
			                ?>
		                <?php }?>
            		</td>
            	</tr>
            </table>
    </body>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php if($module=='report' AND $action!='index'){?>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
<?php }?>
</html>
