<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL Payment"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   
   <table>
   		<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('date_pay');?></td>
   			<td><?php echo $frm->getElement('due_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   		</tr>
   </table>

   <?php echo $this->list;?>
</form>

