<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'callecterall','controller'=>'Chengcallecterall','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>CHENG_CALLECTERALL_INFO</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("BRANCH")?></td>
							<td><?php echo $frm->getElement('branch')?></td>
							<td><?php echo $tr->translate("OWNER_CODE")?></td>
							<td><?php echo $frm->getElement('owner_code')?></td>	
							<td><?php echo $tr->translate("OWNER")?></td>
							<td><?php echo $frm->getElement('owner')?></td>	
						</tr>
						<tr>
							<td colspan="4"><?php echo $frm->getElement('detial')?></td>
							<td><?php echo $tr->translate("FROM")?></td>
							<td><?php echo $frm->getElement('from')?></td>	
								
						</tr>
						<tr>
							<td><?php echo $tr->translate("TO")?></td>
							<td><?php echo $frm->getElement('to')?></td>
							<td><?php echo $tr->translate("NAME_OWNER")?></td>
							<td><?php echo $frm->getElement('owners')?></td>	
							<td><?php echo $tr->translate("TYPE_CALLECTERALL")?></td>
							<td><?php echo $frm->getElement('personal')?></td>	
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('date')?></td>	
							<td><?php echo $tr->translate("NUMBER_NOTE")?></td>
							<td><?php echo $frm->getElement('numbernote')?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>	
						</tr>
						<tr>
					    	<td colspan="4"></td>	
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status')?></td>	
							
						</tr>
					</table>
					</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="hidden" name="exchangefrom" value="2" />
						<input type="hidden" name="inv_no" value="<?php echo $this->inv_no;?>">
						<input type="button" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button" 
							iconClass="dijitIconClear"  class="fixed_size" onclick="clearTextBox(1);"/>
						<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" label="រក្សាទុក+ថ្មី" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
var url_submiinfo = '<?php echo $this->url(array('module'=>'callecterall','controller'=>'chengcallecterall','action'=>'get-changeinfo')); ?>';
function popupCheckStaff(){
//	if(type==1){
//		values=dijit.byId("owner").get('value');
//	}else{
//		values=dijit.byId("from").get('value');
//	}
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'owner_id':dijit.byId("owner").get('value'),
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('from').attr('value',data.type_call);
			},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
	
}
</script>
