<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("COLLTERAL_INFO"));
	$frm=$this->frm_changeCollteral;
?>

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'callecterall','controller'=>'chengcallecterall','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table>
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('client_code');?></td>
			<td><?php echo $frm->getElement('client_name');?></td>
			<td><?php echo $frm->getElement('to');?></td>
			<td><?php echo $frm->getElement('from');?></td>
			<td><?php echo $frm->getElement('collteral_type')?>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
			
		</tr>
	</table>
	<?php echo $this->list;?>
</form>

