<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("ZONE_LIST"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'Zone','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <?php echo $frm->getElement("adv_search");?>
   <?php echo $frm->getElement('status');?>
 <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   <?php echo $this->list;?>
</form>
