<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Holiday'));
?>	
<?php  $holiday= $this->frm_holiday;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'holiday','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("Add Holiday");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Holiday Name")?></td>
							<td><?php  echo $holiday->getElement('holiday_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Start date")?></td>
							<td><?php  echo $holiday->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Amount Day")?></td>
							<td><?php  echo $holiday->getElement('amount_day');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("End Date")?></td>
							<td><?php  echo $holiday->getElement('end_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Note")?></td>
							<td><?php  echo $holiday->getElement('note');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $holiday->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="submit" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_techer").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<?php $base_url = Application_Form_FrmMessage::getUrl("/"); ?>
<script src="<?php echo $base_url;?>js/moment.min.js"  type="text/javascript"></script>
<script>
function CalculateDate(){
	
}
function CalculateDate(){
	pay_type = dijit.byId('start_date').value;
	amount_day = dijit.byId('amount_day').get('value');
	
	if(isNaN(amount_day)){
		//alert('សូមបញ្ចលចំនួនរយៈពេល​ !');
		dijit.byId('amount_day').focus();
	}else{
		start_date = dijit.byId("start_date").value;
		var a = new Date(start_date);
		/*if(pay_type==1){
			mm = a.getMonth()+amount_month+1;
		}else{*/
			//a.setDate(a.getDate() + (amount_day)); 
			var mm = a.getMonth() + 1;
			
		//}
			//alert(a.getDate()+parseInt(amount_day));
		var dd = a.getDate()+parseInt(amount_day);
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);
}
}
</script>