<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('BAD_LOAN'));
$frm = $this->frm_loan;
?>

<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id="add_province" action="<?php echo $this->url(array('module'=>'loan','controller'=>'BadLoan','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
    	if(dijit.byId('branch').get('value')==''){
     		alert('Please Select Branch');
     		dijit.byId('branch').focus();
     		return false;
   		}
		if(dijit.byId('client_nameadd').get('value')==''){
     		alert('Please Select Client Name');
     		dijit.byId('client_codeadd').focus();
     		return false;
   		}
		if(dijit.byId('client_codeadd').get('value')==0){
     		alert('សូមមេតាជ្រើសរើសប្រភេទកូដ CO');
     		dijit.byId('client_nameadd').focus();
     		return false;
   		}
    	return true;
   		}else {
    	return false;
   	}
	</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('BAD_LOAN');?></strong></legend>
					<table cellspacing="10"  width="100%">
					   <tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch');?></td>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><?php echo $frm->getElement('client_codeadd');?></td>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><?php echo $frm->getElement('client_nameadd')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("LOSS_DATE")?></td>
							<td><?php echo $frm->getElement('date_loss')?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
							<td><?php echo $tr->translate("CURRENCY")?></td>
							<td><?php  echo $frm->getElement('cash_type');?></td>							
						</tr>
						<tr>							
							<td><?php echo $tr->translate("TOTAL_PRINCEPLE")?></td>
							<td><?php echo $frm->getElement('Total_amount');?></td>
							<td><?php echo $tr->translate("INTERREST_AMOUNT")?></td>
							<td><?php echo $frm->getElement('Interest_amount');?></td>
							<td><?php echo $tr->translate("TERM")?></td>
							<td><?php  echo $frm->getElement('Term');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status');?></td>
						    <td><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('Note');?></td>
						</tr>
						<tr>
							<td align="center" colspan="6">
								<input type="submit" name="save" value="រក្សាទុក  + បន្ថែមថ្មី​​ " label="<?php echo $tr->translate('SAVENEW')?>" id="submitButton" dojoType="dijit.form.Button"
				 					iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 				<input type="submit" name="save_close"​​ value="រក្សាទុក​  + ចាកចេញ" label="<?php echo $tr->translate('SAVECLOSE')?>" id="submitBtn" dojoType="dijit.form.Button"
				 					iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 					
				 					
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
	</tr>	
</table>
</form>
		
<script type="text/javascript">
dojo.require("dijit.form.Textarea");

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'Badloan','action'=>'get-loaninfo')); ?>';
function getClientInfo(type){
    
	if(type==1){
		values = dijit.byId("client_nameadd").get('value');
	}else if(type==2){
		values = dijit.byId("client_codeadd").get('value');
	}else{
		values = dijit.byId("client_codeadd").get('value');
	} 
	dijit.byId('Total_amount').attr('value',0);
	//dijit.byId('Interest_amount').attr('value',0);
	//dijit.byId("cash_type").set('readOnly',false);
	//values=dijit.byId("client_code").get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'loan_id':values,
		  //  'type':type,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('Total_amount').attr('value',data.total_principal);
			dijit.byId('Interest_amount').attr('value',data.total_interest);
			dijit.byId('date_loss').attr('value',data.date_payment);
			dijit.byId('cash_type').attr('value',data.currency_type);
			dijit.byId("cash_type").set('readOnly',true);
			dijit.byId("client_nameadd").attr('value',values);
			dijit.byId("client_codeadd").attr('value',values);
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
	
}
</script>
