<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_loan;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id="add_province" action="<?php echo $this->url(array('module'=>'loan','controller'=>'BadLoan','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>BAD LOAN</strong></legend>
					<table cellspacing="10"  width="100%">
					
					   <tr>
					         <?php echo $frm->getElement('id');?>
							<td><?php echo $tr->translate("BRANCH")?></td>
							<td><?php echo $frm->getElement('branch');?></td>
							<td><?php echo $tr->translate("CLIENT_CODE")?></td>
							<td><?php echo $frm->getElement('client_code');?></td>
							<td><?php echo $tr->translate("CLIEN_NAME")?></td>
							<td><?php echo $frm->getElement('client_name')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NUMBER_CODE")?></td>
							<td><?php echo $frm->getElement('number_code');?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
							<td><?php echo $tr->translate("LOSS_DATE")?></td>
							<td><?php echo $frm->getElement('date_loss')?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("TOTAL_AMOUNT")?></td>
							<td><?php echo $frm->getElement('Total_amount');?></td>
							<td><?php echo $tr->translate("INTERREST_AMOUNT")?></td>
							<td><?php echo $frm->getElement('Interest_amount');?></td>
							<td><?php echo $tr->translate("TEM")?></td>
							<td><?php  echo $frm->getElement('Term');?></td>
						</tr>
						    <td><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('Note');?></td>
						<tr>
						
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");

function getClientInfo(type){
	if(type==1){
		id = dijit.byId("client_name").get('value');
	}else if(type==2){
		id = dijit.byId("number_code").get('value');
	}else{
		id = dijit.byId("client_code").get('value');
	}
	
	dijit.byId("client_code").attr('value',id);
	dijit.byId("client_name").attr('value',id);
	dijit.byId("number_code").attr('value',id);
	
	
		
} 
</script>
