<?php 
 $frm = $this->frm_loan;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'BadLoan','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">	<table>
	<table>	
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch');?></td>
			<td><?php echo $frm->getElement('client_name');?></td>
			<td><?php echo $frm->getElement('client_code');?></td>
			<td><?php echo $frm->getElement('status');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
			
		</tr>
	</table>
<?php echo $this->list;?>
</form>
