<?php 
 $frm = $this->frm_loan;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'BadLoan','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">	<table>
	<table>	
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch');?></td>
			<td><?php echo $frm->getElement('client_name');?></td>
			<td><?php echo $frm->getElement('client_code');?></td>
			<td><?php echo $frm->getElement('Term');?></td>
		</tr>
		<tr>
		 
			<td><?php echo $frm->getElement('cash_type');?></td>
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><?php echo $frm->getElement('status');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
			<td></td>
		</tr>
	</table>
<?php echo $this->list;?>
</form>
