<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Client '));
?>	
<?php  $frm = $this->frm_loan;?>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="80%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("Add Client");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Is Group")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("CO Name")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Currency Type")?></td>
							<td><?php  echo $frm->getElement('currency_type');?></td>
							<td><?php echo $tr->translate("Zone")?></td>
							<td><?php  echo $frm->getElement('zone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Total Amount")?></td>
							<td><?php  echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("Interest Rate")?></td>
							<td><?php  echo $frm->getElement('interest_rate');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Release Date")?></td>
							<td><?php  echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("Period")?></td>
							<td><?php  echo $frm->getElement('period');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("First Payment")?></td>
							<td><?php  echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("NO Time")?></td>
							<td><?php  echo $frm->getElement('time');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Pay Every")?></td>
							<td><?php  echo $frm->getElement('pay_every');?></td>
							<td><?php echo $tr->translate("Repaymet Method")?></td>
							<td><?php  echo $frm->getElement('repayment_method');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("Holiday")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
							<td><?php echo $tr->translate("ID Card(N.)")?></td>
							<td><?php  echo $frm->getElement('id_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Description")?></td>
							<td colspan="3"><?php  echo $frm->getElement('desc');?></td>
						</tr>
						<tr>
							<td colspan="4" align="center">
							<input type="submit" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId('add_client').submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>