<center><h1>You can link of all pages ...</h1></center>
<?php $url=$this->url(array('action'=>'rpt-khmer'))?>
<?php $active=$this->url(array('action'=>'active'))?>
<?php $col_sheet=$this->url(array('action'=>'coletion-sheet'))?>
<?php $fix_asset=$this->url(array('action'=>'fixed-asset'))?>
<?php $incom=$this->url(array('action'=>'income'))?>
<?php $index=$this->url(array('action'=>'indexn'))?>
<?php $reportn=$this->url(array('action'=>'reportn'))?>
<?php $zendhtml=$this->url(array('action'=>'zendhtml'))?>
<table style="width:80%;">
<tr>    
       <th><a href="<?php echo $index?>">Index</a></th>
       <th><a href="<?php echo $url?>">Report Khmer</a></th>
       <th><a href="<?php echo $active?>">Active</a></th>
       <th><a href="<?php echo $col_sheet?>">Colection Sheet</a></th>
       <th><a href="<?php echo $fix_asset?>">Fixed Asset</a></th>
       <th><a href="<?php echo $incom?>">Income</a></th>
       
       <th><a href="<?php echo $reportn?>">Report</a></th>
       <th><a href="<?php echo $zendhtml?>">Hello Stadar</a></th>
</tr>
 </table>