<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("LIST_REPORT_CLIENT");?></title>
</head>

<body>
	<h2 align="center"><?php echo $tr->translate("REPORT_CLIENT");?></h2>
	<table width="100%" border="1" style="border-collapse:collapse;" bordercolor="black">
    	<tr​>
        	<th style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUM");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("CLIENT_NO");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("CLIENTNAME_KH");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("CLIENTNAME_EN");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("SEX");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("STATUS");?></th>
<!--             <th>ID Type</th> -->
<!--             <th>ID N<sup>0</sup></th> -->
            <th style="padding:5px 0px;"><?php echo $tr->translate("PHONE");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("VILLAGE");?></th>
             <th style="padding:5px 0px;"><?php echo $tr->translate("COMMUNE");?></th>
             <th style="padding:5px 0px;"><?php echo $tr->translate("DISTRICT");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("PROVINCE");?></th>
            <!--<td style="padding:5px 0px;"><?php //echo $tr->translate("SPOUSE");?></td>-->
            <th style="padding:5px 0px;"><?php echo $tr->translate("HOUSE");?></th>
            <th style="padding:5px 0px;"><?php echo $tr->translate("STREET");?></th>
            
        </tr>
      <?php for($i=0;$i<15;$i++){ ?>
      <tr align="center">
        	<td><?php echo $i+1;?></td>
            <td></td>
            <td style="font-family:'Khmer OS Battambang'; font-size:14px;">សេន​​ រដ្ធា</td>
            <td>Sen ratha</td>
            <td>M</td>
            <td>single</td>
<!--             <td></td> -->
           <!--  <td><?php //echo $i+1;?></td>-->
            <td>097 63 62 333</td>
            <td>tangun</td>
            <td>kakap</td>
            <td>Borsen chey</td>
            <td>PP</td>
<!--             <td></td> -->
            <td>#45</td>
            <td>,1986</td>
        </tr>
        <?php } ?>
       
       
    </table>
</body>
</html>