<table width="80%" align="center" border="1" style="border-collapse:collapse;">
	<tr>
   	  <td style="padding-left:20px;"><h2 style="margin-top: 20px;">Individual loan agreement</h2>
        	
        <img src="../../table.jpg" width="180px"  style="float:right; margin-top:-67px;">
            <p>Contect Code:-/14/600-4/10014/314</p>
            <p>THIS AGREEMENT IS MADE the 11.7.2014 BETWEEN</p>
            <p>(1) YOUR NFI("the loan"):and</p>
            <p>(2) YOUR NFI("the loan"):and 2014 djfal dfjdpp djfj </p>
        <P>IT IS HERE BY AGREED as follows</P>
        
            	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1)	An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals </p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2)An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3)An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4)An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                (3)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                (3)An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?
                An organized collection of people, procedures, software, databases, and devices used to provide routine 
                information to managers and decision makers 	A formal collection of people and other resources established 
                to accomplish a set of goals13.	Please Find one type that can be Input and output device and Explain too14.	
                What is Application Software?15.	What is Basic Application software?</p>

        </td>
    </tr> 
</table>