<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
      <table border="1" width="100%" >
​​​    ​   <tr​​ > 
         <td >  &nbsp;  &nbsp;  &nbsp; &nbsp; </td>
          <th colspan="2"><h1>អង្គការ សុខាមីក្រូហិរញ្ញវត្តុ</h1>
              <h2>SOKHA Microfinance Organization </h2>
          </th>
       </tr>
       <tr>
           <td><h2>សាខារាជធានីភ្នំពេញ</h2>
           ​​    
           </td>
       </tr>
       <tr>
           <td><p>លេខកូដអតិថិជនៈ....</p><br>
                &nbsp;&nbsp;១.<input type="checkbox" name="ch1">កម្មសិទ្ធិរបស់អ្នកខ្ខីប្រាក់
           </td>
       
       </tr>
      
      </table>
</body>
</html>
