<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
    <table width="100%" border="1">
	  <tr>
	    <td>
         <h1> hello stadar</h1>
        
        	<table width="70%">
            	<tr align="center">
                	<th align="left" width="100">Frist Name:</th>
                    <td align="left">Lysa</td>
                    <th align="left">Gender:</th>
                    <td align="left"> F</td>
                </tr>
                <tr align="center">
                	<th align="left">Last Name:</h5></th>
                    <td  align="left"> Teang Ravy</td>
                    <th  align="left">ID Number:</th>
                    <td align="left">1020</td>
                </tr>
                <tr align="center">
                	<th  align="left">Father Name:</th>
                    <td align="left"></td>
                    <th align="left">Date of birth:</th>
                    <td align="left">4/13/1997</td>
                </tr>
            </table>
            <img src="Pictuers_001_ (102).gif" align="right"/>
            <img src="Pictuers_001_ (102).gif" align="right"/>
            <img src="Pictuers_001_ (102).gif" align="right"/>
             <p><h3>personal address</h3></p>
                 <table width="70%" style="border:1px solid #000;">
                    <tr align="center">
                       <th align="left">Distict:</th>
                       <td align="left">Komphong Cham</td>
                       <td align="left" width="200"><h5>City:</h5></td>
                       <td align="left" width="300">ACCR</td>
                    </tr>
                    <tr>
                       <th align="left" width="100px">Adress:</th>
                       <td colspan="3">phanet phanet phanet phanet phanet phanetphanetphanet phanet phanet phanet phanet phanet 
                                       phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet </tr>
                    <tr>
                       <th align="left">phone:</th>
                       <td>004-992-435</td>
                       
                    </tr>
            
                </table>
                <img src="Pictuers_001_ (103).gif" align="right"  />
                <img src="Pictuers_001_ (103).gif" align="right"  />
                <img src="Pictuers_001_ (103).gif" align="right"  />
                 
                <p><h3>personal address</h3></p>
                   <table width="70%" style="border:1px solid #000;">
                    <tr align="center">
                       <th align="left">Distict:</th>
                       <td align="left">Komphong Cham</td>
                       <td align="left" width="200"><h5>City:</h5></td>
                       <td align="left" width="300">ACCR</td>
                    </tr>
                    <tr>
                       <th align="left" width="100px">Adress:</th>
                       <td colspan="3">phanet phanet phanet phanet phanet phanetphanetphanet phanet phanet phanet phanet phanet 
                                       phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet phanet </tr>
                    <tr>
                       <th align="left">phone:</th>
                       <td>004-992-435</td>
                       
                    </tr>
                    <tr>
                       <th align="left">phone:</th>
                       <td>004-992-435</td>
                       
                    </tr>
                </table>
                  <table border="1" width="100%">
                    <tr bgcolor="#999999">
                        <th>Conteact Code</h5></td>
                        <th>Status</th>
                        <th>amount</th>
                        <th>OLB</th>
                        <th>Creation Data</th>
                        <th>start data</th>
                        <th>Close data</th>
                        <th>Group</th>
                        <th>Late day</th>
                        <th>ATR</th>
                    </tr>
                    <tr>
                        <td>01111/02222/0333</td>
                        <td>close</td>
                        <td>100.00</td>
                        <td>100.00</td>
                        <td>0.00</td>
                        <td>8/2/2013</td>
                        <td>8/2/2014</td>
                        <td>-</td>
                        <td>1392</td>
                        <td>no</td>
                    </tr>
                      <tr>
                        <td>01111/02222/0333</td>
                        <td>close</td>
                        <td>100.00</td>
                        <td>100.00</td>
                        <td>0.00</td>
                        <td>8/2/2013</td>
                        <td>8/2/2014</td>
                        <td>-</td>
                        <td>1392</td>
                        <td>no</td>
                    </tr>
                 </table>
                 <table width="100%" border="1" >
                      <tr bgcolor="#0099CC">
                         <th>Saving code</th>
                         <th>Balance</th>
                         <th>ProductName</th>
                         <th>Proudct code</th>
                         <th>Product type</th>
                         <th>Cretion data</th>
                         <th>Close data</th>
                         
                      </tr>
                      <tr>
                        <td>11122334455</td>
                        <td>950 00</td>
                        <td>BAYSAVE</td>
                        <td>100</td>
                        <td>Saving book</td>
                        <td>8/2/2013</td>
                        <td></td>
                      </tr>
                 </table>
           </td>
	  </tr>
    </table>
</body>
</html>
