 <input type="button" label="អតិថិជនជាបុគ្គល" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-individual-client')); ?>';"/>
  
  <input type="button" label="អតិថិជនជាក្រុម" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-group-client')); ?>';"/>
  
  <input type="button" label="កិច្ចព្រមព្រៀងអតិថិជន" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-client-agreement')); ?>';"/>
  
 