<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<input type="button" label=" <?php echo $tr->translate("LIST_INDIVIDUAL_CLIENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-individual-client')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_GROUP_CLIENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-group-client')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_CLIENT_AGREEMENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-client-agreement')); ?>';"/>
  
 