<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<div id="divPrint">
   <table width="70%" align="center" >
     <h3 align="center">របាយការបើកប្រាក់បៀវតិ៏ន</h3>

           <tr>
              <td>ឈ្មោះបុគ្គល</td>
              <td>ភេទ</td>
              <td>តួនាទី</td>
           </tr>
            <tr>
              <td>Basic salary</td>
              <td>200</td>
              <td>for month</td>
           </tr>
        </table>
       <h3 align="center">ប្រាក់បន្ថែម</h3>
         <table width="70%" align="center">
          <tr>
             <td>Basic Salary</td>
          </tr>
          <tr>
             <td>Bonus</td>
          </tr>
          <tr>
             <td>Petro</td>
          </tr>
          <tr>
             <td>Bad Customer</td>
          </tr>
          <tr>
             <td>Total<hr /></td>
             <td></td>
              <td>ប្រាក់ត្រូវបើក</td>
          </tr>
          

         </table>
   </div>
   </body>
</html>
