 <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
 <input type="button" label=" <?php echo $tr->translate("LIST_LOAN_FIXED_ASSET");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-fixed-asset')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_LOAN_BUY_FIXED_ASSET");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-buy-fixed-asset')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_LOAN_SALE_FIXED_ASSET");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-sale-fixed-asset')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_LOAN_CHARTACCOUNT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-chartaccount')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_ACCOUNT_NAME");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-account-name')); ?>';"/>
  
   <input type="button" label=" <?php echo $tr->translate("LIST_JURNAL");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-jurnal')); ?>';"/>
  
   <input type="button" label=" <?php echo $tr->translate("LIST_LEGER");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-leger')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_BALANCE");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_INCOME_STATEMENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income-statement')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_BALANCE_SHEET");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance-sheet')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_OWNER_EQUITY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-ower-equity')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_CASHFLOW");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-cashflow')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_CLOSING");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-closing')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_INCOME");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income')); ?>';"/>