 <input type="button" label="Fixed Asset" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-fixed-asset')); ?>';"/>
  
  <input type="button" label="Buy FixedAsset" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-buy-fixed-asset')); ?>';"/>
  
  <input type="button" label="Sale Fixed Asset" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-sale-fixed-asset')); ?>';"/>
  
  <input type="button" label="Chart Account" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-chartaccount')); ?>';"/>
  
  <input type="button" label="Account Name" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-account-name')); ?>';"/>
  
   <input type="button" label="Jurnal" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-jurnal')); ?>';"/>
  
   <input type="button" label="Leger" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-leger')); ?>';"/>
  
  <input type="button" label="Balance" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance')); ?>';"/>
  
  <input type="button" label="Income Statement" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income-statement')); ?>';"/>
  
  <input type="button" label="Balanc Sheet" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance-sheet')); ?>';"/>
  
  <input type="button" label="Ower's Equity" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-ower-equity')); ?>';"/>
  
  <input type="button" label="Cashflow" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-cashflow')); ?>';"/>
  
  <input type="button" label="rpt-Closing" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-closing')); ?>';"/>
  
  <input type="button" label="rpt-Income" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income')); ?>';"/>