 <input type="button" label="ទ្រព្យសកម្មរយៈពេលវែង" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-disburse')); ?>';"/>
  
  <input type="button" label="ចំណាយផ្សេងៗ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-group-disburse')); ?>';"/>
  
  <input type="button" label="ចំណូលផ្សេងៗ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-ilpayment')); ?>';"/>
  
  <input type="button" label="ទ្រព្យសកម្ម" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-group-payment')); ?>';"/>
  
  <input type="button" label="GeneralJurnal" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-general-jurnal')); ?>';"/>
  
   <input type="button" label="Accountcate" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-accountcate')); ?>';"/>
  
   <input type="button" label="ChartAccount" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-chartaccount')); ?>';"/>
  
  <input type="button" label="Ownerequity" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-ownerequity')); ?>';"/>
  
   <input type="button" label="Balancsheet" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balancsheet')); ?>';"/>