<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
    
        <h3 align="center">Netincome</h3>
        <h4>Asset</h4>
        <table>
          <tr style="padding-left:10px;">
            <td>Cash------------------------------</td>
            <td>10$</td>
          </tr>
           <tr>
            <td>Land------------------------------</td>
            <td>10$</td>
          </tr>
           <tr>
            <td>Total------------------------------</td>
            <td>20$</td>
          </tr>
          </table>
          <h4>Liability Total</h4>
          <table>
          <tr>
            <td>Home------------------------------</td>
            <td>5$</td>
          </tr>
          <tr>
            <td>car-------------------------------</td>
            <td>5$</td>
          </tr>
          <tr>
            <td>Total------------------------------</td>
            <td>10$</td>
          </tr>
        </table>
        <h4>Epuety</h4>
        <table>
          <tr>
            <td>------------------------------------</td>
            <td>5$</td>
          </tr>
          <tr>
            <td>------------------------------------</td>
            <td>5$</td>
          </tr>
          <tr>
            <td>Total----------------------------------</td>
            <td>10$</td>
          </tr>
          <tr>
            <td>Total Asset------------------------------</td>
            <td>20$</td>
          </tr>
        </table>
        </table>
        
</body>
</html>
