<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Edit Village'));
?>	
<?php  $commune = $this->frm_village;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("Edit Village");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Village Name")?></td>
							<td><?php  echo $commune->getElement('village_name');?>
								<?php  echo $commune->getElement('id');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Province Name")?></td>
							<td><?php  echo $commune->getElement('province_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("District Name")?></td>
							<td><?php  echo $commune->getElement('district_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Commune Name")?></td>
							<td><?php  echo $commune->getElement('commune_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $commune->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="submit" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_techer").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>