<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_VILLAGE'));
?>	
<?php  $commune = $this->frm_village;?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

dojo.ready(function(){
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		pro_id:"<?php echo $this->row['pro_id'];?>"
	},            
	required: false,		           
	name: "district_name",
	id: "district_name",
	searchAttr: "name",
	value: "<?php echo $this->row['dis_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district_name");

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		district_id: "<?php echo $this->row['dis_id'];?>"
	},            
	required: false,		           
	name: "commune_name",
	id: "commune_name",
	value: "<?php echo $this->row['commune_id'];?>",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
  }
	}, "commune_name");

	
});
function filterDistrict(){
	dijit.byId('district_name').query.pro_id = dijit.byId('province_name').get('value');
}
function filterCommune(){
	//alert();
	dijit.byId('commune_name').query.district_id = dijit.byId('district_name').get('value');
}
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("EDIT_VILLAGE");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						 <tr>
							<td><?php echo $tr->translate("VILLAGE_KH")?></td>
							<td><?php  echo $commune->getElement('village_namekh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("VILLAGE_NAME")?></td>
							<td><?php  echo $commune->getElement('village_name');?>
								<?php  echo $commune->getElement('id');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISPLAY_BY")?></td>
							<td><?php  echo $commune->getElement('display'); echo $commune->getElement('id')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PROVINCE_NAME")?></td>
							<td><?php  echo $commune->getElement('province_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISTRICT_NAME")?></td>
							<td><input id="district_name" ><?php  //echo $commune->getElement('district_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("COMMUNE_NAME")?></td>
							<td><input id="commune_name" > <?php  //echo $commune->getElement('commune_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $commune->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							  <input type="reset" label="សំអាត" id="" dojoType="dijit.form.Button"
				                  iconClass="dijitIconClear" />
							<input type="submit" value="កែប្រែទិន្នន័យ" label="កែប្រែទិន្នន័យ" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass=""/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>