<?php print_r($this->result['province_name']);?>
<script type="text/javascript">  
dojo.require("dojo.data.ObjectStore");

dojo.ready(function(){
	dijit.byId('province_name').attr('value',<?php echo $this->result['province_name'];?>);
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		pro_id: "<?php echo $this->result['province_name'];?>"
	},            
	required: false,		           
	name: "district_name",
	id: "district_name",
	searchAttr: "name",
	class: 'fullside',
	value:"<?php echo $this->result['district_name'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district_name");

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		district_id: "<?php echo $this->result['district_name'];?>"
	},            
	required: false,		           
	name: "commune_name",
	id: "commune_name",
	searchAttr: "name",
	class: 'fullside',
	value:"<?php echo $this->result['commune_name'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
  }
	}, "commune_name");

	
});
function filterDistrict(){
	dijit.byId('district_name').query.pro_id = dijit.byId('province_name').get('value');
}
function filterCommune(){
	dijit.byId('commune_name').query.district_id = dijit.byId('district_name').get('value');
}
</script>
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VILLAGE_LIST"));
$frm = $this->frm_village;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   	<td><?php echo $frm->getElement("adv_search");?></td>
		   	<td><?php  echo $frm->getElement('province_name');?></td>
		   	<td><input id="district_name" ></td>
		   	<td><input id="commune_name" ></td>
		    <td><?php echo $frm->getElement('search_status');?></td>
		    <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	   </tr>
   </table>
   
   
    <?php echo $this->list;?>
</form>
