 <input type="button" label="កន្លែងបង់ប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-teller')); ?>';"/>
  
  <input type="button" label="សេវាប្ថូរប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-chang-money')); ?>';"/>
  
  <input type="button" label="អាត្រាប្ថូរប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-exchang-money')); ?>';"/>
  
  <input type="button" label="កំណត់អាត្រាប្ថូរប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-scope-chang-money')); ?>';"/>
  
  <input type="button" label="ពិនិត្យអាត្រាប្ថូរប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-list-chang-money')); ?>';"/>
  
   <input type="button" label="ប្រភេទប្រាក់ប្ថូរ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-type-chang-money')); ?>';"/>
  
 