 <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
 <input type="button" label=" <?php echo $tr->translate("LIST_TELLER");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-teller')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("CHANGE_MONEY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-chang-money')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_EXCHANGE_MONEY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-exchang-money')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_SCOPE_CHANGE_MONEY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-scope-chang-money')); ?>';"/>
  
  <input type="button" label=" <?php echo $tr->translate("LIST_CHANGE_MONEY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-list-chang-money')); ?>';"/>
  
   <input type="button" label=" <?php echo $tr->translate("TYPE_CHANGE_MONEY");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'teller','action'=>'rpt-type-chang-money')); ?>';"/>
  
 