
 <?php 
   $rows=$this->list;
//    print_r($rows);
 ?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Client Info</title>
</head>

<body>
	<h2 align="center">កន្លែងបង់ប្រាក់</h2>
	
	<table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th>NUM</th>
        	<th>Term</th>
            <th>Loan N.</th>
            <th>Date Due</th>
            <th>OS</th>
            <th>Principal</th>
            <th>Interest Rate</th>
            <th>Paid Principal</th>
            <th>Paid Interest Rate</th>
            
            <th>CO</th>
            <th>By</th>
            <th>Status</th>
        </tr>
  
    </table>
  
</body>
</html>