<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
 <?php 
   $rows=$this->list;
//    print_r($rows);
 ?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("CLIENT INFO");?>Client Info</title>
</head>

<body>
<div id="divPrint">
	<h2 align="center">កន្លែងបង់ប្រាក់</h2>
	
	<table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th><?php echo $tr->translate("NUM");?></th>
        	<th><?php echo $tr->translate("TERM");?></th>
            <th><?php echo $tr->translate("LOAN_NO");?></th>
            <th><?php echo $tr->translate("DATE_DUE");?></th>
            <th><?php echo $tr->translate("OS");?></th>
            <th><?php echo $tr->translate("PRINCIPAL");?></th>
            <th><?php echo $tr->translate("INTEREST");?></th>
            <th><?php echo $tr->translate("PAID_PRINCIPAL");?></th>
            <th><?php echo $tr->translate("PAID_INTEREST_RATE");?></th>
            <th><?php echo $tr->translate("CO");?></th>
            <th><?php echo $tr->translate("BY");?></th>
            <th><?php echo $tr->translate("STATUS");?></th>
        </tr>
  
    </table>
 </div> 
</body>
</html>