<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Client List"));
$frm = $this->frm_search;
?>
<style>
.input-search .dijitTextBox{ width:190px; height: 25px;}
</style>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <div class="input-search">
   <?php echo $frm->getElement("btn_search");?>
   <?php echo $frm->getElement("adv_search");?>
   <?php echo $frm->getElement("customer_code");?>
   <?php echo $frm->getElement("member");?>
   <?php echo $frm->getElement("repayment_method");?>
   <?php echo $frm->getElement('branch_id');?>
   <?php echo $frm->getElement('co_id');?>
   <?php echo $frm->getElement('from_date');?>
   <?php echo $frm->getElement('to_date');?>
   <?php echo $frm->getElement('status');?>
   </div>
   <?php echo $this->list;?>
</form>
<script>
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}


</script>