<?php
	$this->headTitle('Loan System | Show Exchange Rate'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript">
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.layout.ContentPane");
</script>
<div style="width:720px;" >
<div id="mainTabContainer" style="width: 100%; height: 700px; " dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
		<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="អត្រាប្តូរប្រាក់នៅ ធនាគា អេស៊ីលីដា" selected="true">
			<div style="width:695px;text-align:center; padding-top:1px; margin-bottom:2px; font-family:'Khmer MEF2'; background:#008; color:gold; border-top: 2px solid #ca9812;">អត្រាប្តូរប្រាក់នៅ ធនាគា អេស៊ីលីដា</div>
			<div style=" width:695px; height:566px;overflow-x:hidden;  overflow-y:hidden;  background:#ccc;">
				<iframe scrolling="no" frameborder="0" src="http://www.acledabank.com.kh/kh/eng/ps_cmforeignexchange.php"
			 		style="overflow-x: hidden;overflow-y: hidden; height:840px; margin-top: -320px; width:700px; margin-left: 0px;">
			 </iframe>
			 <div style="width:100%;text-align:center; padding-top:1px; font-family:'Khmer MEF2'; background:#008; color:gold; border-top: 2px solid #ca9812;">អត្រាប្តូរប្រាក់នៅ ធនាគា អេស៊ីលីដា</div>
			</div>
		</div>
		<div class="tabContentSection" dojoType="dijit.layout.ContentPane"  title="អត្រាប្តូរប្រាក់នៅ លីហួរ ប្តូរប្រាក់" selected="false">
			<div style="width:695px;text-align:center; padding-top:1px; font-family:'Khmer MEF2'; background:#008; color:gold; border-top: 2px solid #ca9812;">អត្រាប្តូរប្រាក់នៅ លីហួរ ប្តូរប្រាក់</div>
			<div style=" width:695px; height:585px;overflow-x:hidden;  overflow-y:hidden;  background:#ccc;">
				<iframe scrolling="no" frameborder="0" src="http://www.everyday.com.kh/en/exchangerate.html"
			 		style="overflow-x: hidden;overflow-y: hidden; height:860px; margin-top: -320px; width:700px; margin-left: 0px;">
			 </iframe>
			 <div style="width:100%;text-align:center; padding-top:1px; font-family:'Khmer MEF2'; background:#008; color:gold; border-top: 2px solid #ca9812;">អត្រាប្តូរប្រាក់នៅ លីហួរ ប្តូរប្រាក់</div>
			</div>
		</div>	
</div>		
</div>				