<input type="button" label="អតិថិជន" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client')); ?>';"/>
  
<input type="button" label="ក្រុម" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-group')); ?>';"/>

<input type="button" label="កិច្ចព្រមព្រៀង" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-agreement')); ?>';"/>

<input type="button" label="Calleteral" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>

<input type="button" label="Calleteral_Value" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-value')); ?>';"/>