<input type="button" label="បញ្ជីឈ្មោះអតិថិជន" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client')); ?>';"/>
  
<input type="button" label="បញ្ជីឈ្មោះក្រុម" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-group')); ?>';"/>

<input type="button" label="បញ្ជីកិច្ចព្រមព្រៀង" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-agreement')); ?>';"/>

<input type="button" label="បញ្ជីបង់រំលោះ" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>

<input type="button" label="បញ្ជីតំលៃបង់រំលោះ" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-value')); ?>';"/>