<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
?>
<input type="button" label="<?php echo $tr->translate("LIST_OF_CLIENT");?>" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client')); ?>';"/>
  
<input type="button" label=" <?php echo $tr->translate("CLIENT_CALLETERAL");?>" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>

<input type="button" label=" <?php echo $tr->translate("CHANGE_CALLETERAL");?>" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change')); ?>';"/>

<input type="button" label=" <?php echo $tr->translate("RETURN_CALLETERAL");?>" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-returncollteral')); ?>';"/>

<input type="button" label=" <?php echo $tr->translate("CLINET_BLACKLIST");?>" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-clientblacklist')); ?>';"/>