<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("RPT AGREEMENT");?></title>
<html>
<head>
<meta charset="utf-8">

</head>

<body>
	<h2 align="center"><?php //echo $this->data['Report_Agreement'];?></h2><br/>
	<div id="divPrint">
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB" >
        	<th><?php echo $tr->translate("NUM");?></th>
            <th><?php echo $tr->translate("CLIENT_NO");?></th>
            <th><?php echo $tr->translate("NAME_KHMER");?></th>
            <th><?php echo $tr->translate("NAME_EN");?></th>
            <th><?php echo $tr->translate("SEX");?></th>
            <th><?php echo $tr->translate("HOUSE");?></th>
            <th><?php echo $tr->translate("STREET");?></th>
            <th><?php echo $tr->translate("VILLAGE");?></th>
            <th><?php echo $tr->translate("SPOUSE_NAME");?></th>
           
         </tr>

    </table>
    </div>
</body>
</html>