<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$frms=$this->frm_client;
?>
<title><?php echo $tr->translate("REPORT CLIENT");?></title>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<table style="font-family: 'Khmer OS Content';float: right;width: 85%; " >
	<tr>  
      <td><?php echo $frm->getElement("adv_search");?></td>
      <td><?php echo $frm->getElement('branch_id');?></td>
      <td><?php echo $frms->getElement('province');?></td>
      <td><?php echo $frm->getElement('status');?></td>
      <td><?php echo $frm->getElement('start_date');?></td>
      <td><?php echo $frm->getElement('end_date');?></td>
      <td><?php echo $frm->getElement("btn_search");?></td>
	</tr>
</table>
<div style=" width:98%; margin:0 auto; ">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>

<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<!--  <h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2> -->
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['brand_client'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%" class="style" style="font-size: 9px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		        </tr>   
            </table>
</td>
</tr>
</table>
<body>
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">   
    	<tr bgcolor="#BBBBBB" >
	        	<th aling=center;><?php echo $tr->translate("NUM");?></th>
	            <th style="white-space: pre;"><?php echo $tr->translate("CUSTOMER_CODE");?></th>
	            <th style="white-space: pre;"><?php echo $tr->translate("CLIENTNAME_KH");?></th>
	            <th><?php echo $tr->translate("CLIENTNAME_EN");?></th>
	            <th><?php echo $tr->translate("SEX");?></th>
	             <th><?php echo $tr->translate("BRANCH_NAME");?></th>
	            <th style="white-space: pre;"><?php echo $tr->translate("PHONE");?></th>
	            <th><?php echo $tr->translate("ADRESS");?></th>
	            <th style="white-space: pre;"><?php echo $tr->translate("SPOUSE_NAME");?></th>
	            <th><?php echo $tr->translate("DATE");?></th>
          </tr>
          <?php foreach($this->client_list as $key =>$row){?>
		   <tr>
			   <td>&nbsp;<?php echo $key+1; ?></td>
		       <td>&nbsp;<?php echo $row['client_number']?></td>
			   <td>&nbsp;<?php echo $row['name_kh']?></td>
			   <td>&nbsp;<?php echo $row['name_en']?></td>
			   <td>&nbsp;<?php echo $row['sex']?></td>
			   <td>&nbsp;<?php echo $row['branch_name']?></td>
			   <td style="white-space: pre;">&nbsp;<?php echo $row['phone']?></td>
			   <td style="max-width: 200px;">&nbsp;<?php echo $row['house'].", ".$row['street'].", ".$row['village_name'].", ".$row['com_name'].", ".$row['dis_name'].", ".$row['pro_name']?></td>
			   <td>&nbsp;<?php echo$row['spouse_name']?></td>
			   <td>&nbsp;<?php echo$row['create_date']?></td>
		   </tr>
		  <?php }?>

    </table>
</body>
</div>
</div>
</html>