<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$frm=$this->frm_callteral;
?>
<title>Loan Released By CO</title>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<table style="font-family: 'Khmer OS Content';float: right;"  >
	<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
		
		</tr>
</table>
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
</style>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint" style="width: 100%;">
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['rpt_loan_release_co'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                <div>
                   <?php  
                    $id='';
	               if(!empty($this->calleteral_list)) foreach($this->calleteral_list as $key =>$row){
	              
               ?>
                <?php 
                if($id!=$row['client_id']){
                	
                ?>
                <?php if($key>0){?>
                <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                
                <?php } ?>
             <?php ?>
                <tr class="style">
                	<td colspan="6">&nbsp;<span style="text-align:center; font-size:9px; font-family:'Khmer OS Muol'"><?php echo $tr->translate("CUSTOMER_NAME");?> </span><?php  echo $row['client_code'].' , '.$row['name_kh'].' - '.$row['client_name']; ?></td>
                </tr>
                 <tr class="style" align="center" style="font-weight:bold; line-height: 14px; font-size:9px; padding:5px 0px; ">
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUM");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("COLLTERAL_CODE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("STAFF_NAME");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("SPOUSE_NAME");?> </td>                    
                    <td style="padding:5px 0px;"><?php echo $tr->translate("COLETERAL_TYPE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("OWNER_NAME");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUMBER_COLLTERAL");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NOTE");?> </td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("DATE");?> </td>
                </tr>
                <?php }
                $id = $row['client_id'];
                ?>
					<tr align="center" style="font-size: 9px;" class="style">
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['collecteral_code']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['co_id']; ?>&nbsp;</td>						
						<td style="white-space:nowrap;">&nbsp;<?php echo $row['collecteral_type']; ?>&nbsp;</td>
						<td style="white-space:nowrap;">&nbsp;<?php echo $row['collecteral_title_en']." -  ".$row['collecteral_owner']; ?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo $row['join_with']; ?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo $row['number_collecteral']; ?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo $row['note']; ?>&nbsp;</td>
						<td>&nbsp;<?php echo date('d-M-Y',strtotime($row['date']));?>&nbsp;</td>
					</tr>
				<?php }?>
            
            <br />
              </table>
    	</td>
    </tr>
</table>
</div>
</div>
