<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
?>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_CLIENT_BLACKLIST");?></title>
</head>
<body> 
<form method="post">
<table style="font-family: 'Khmer OS Content';width:28.5cm; margin: 0 auto;"  >
	<tr>
   		<td><?php echo $frm->getElement("adv_search");?></td>
   		<td><?php echo $frm->getElement("branch_id");?></td>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
</form>
<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	
	<div id="divPrint">
	<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
	    <table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<!--  <h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>-->
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $tr->translate("REPORT_CLIENT_BLACKLIST");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
                	</td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr >
                				<td width="45%" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				
		                </table>
		              </td>
		           </tr>   
    </table>
	<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    	<tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; " >
        	<th>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
            <th><?php echo $tr->translate("BRANCH_NAME");?></th>
            <th><?php echo $tr->translate("CLIENT_NUM");?></th>
            <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
            <th><?php echo $tr->translate("SEX");?></th>
            <th><?php echo $tr->translate("DATOFBIRTH");?></th>
            <th><?php echo $tr->translate("SITU_STATUS");?></th>
            <th><?php echo $tr->translate("NATIONAL_ID");?></th>
            <th><?php echo $tr->translate("NUMBER");?></th>
            <th width="200px;"><?php echo $tr->translate("ADDRESS");?></th>
            <th><?php echo $tr->translate("REASON");?></th>
            <th><?php echo $tr->translate("DATE");?></th>
         </tr>
         <?php if(!empty($this->calleteral_list)) foreach($this->calleteral_list as $key =>$row){?>
         <tr style="line-height:15px;">
        	<td>&nbsp;<?php echo $key+1;?></td>
        	<td>&nbsp;<?php echo $row['branch_name']?></td>
            <td>&nbsp;<?php echo $row['client_number'];?></td>
            <td>&nbsp;<?php echo $row['client_name']?></td>
		    <td>&nbsp;<?php echo $row['sex']?></td>
            <td>&nbsp;<?php echo date("d/m/Y",strtotime($row['dob']));?></td>
            <td>&nbsp;<?php echo $row['situation']?></td>
            <td>&nbsp;<?php echo $row['doc_name']?></td>
            <td>&nbsp;<?php echo $row['id_number']?></td>
            <td>&nbsp;<?php echo $row['street'].','.$row['house'].','.$row['village_name'].','.$row['commune_name'].','.$row['district_name'].','.$row['province_name']; ?></td>
            <td>&nbsp;<?php echo $row['reason']?></td>
            <td>&nbsp;<?php echo date("d/m/Y",strtotime($row['date']));?></td>
         </tr>
         <?php }?>
    </table>
    <br />
    <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    </div>
    </div>
</body>
</html>