 <!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Client Info</title>
</head>

<body>
	<h2 align="center">Client Personal</h2>
	<table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th>Contact Code</th>
        	<th>Status</th>
            <th>Amount</th>
            <th>OLB</th>
            <th>Creatin Date</th>
            <th>Start Date</th>
            <th>Close Date</th>
            <th>Group</th>
            <th>Late Day</th>
            
            <th>ATR</th>
        </tr>

      
    </table>
  
</body>
</html>