<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CHANGE_COLLTERAL_INFO"));
	$frm=$this->frm_changeCollteral;
?>
<title><?php echo $tr->translate("RPT AGREEMENT");?>report Calleteral Value</title>
<html>
<head>
<meta charset="utf-8">

</head>
<body>
<table style="font-family: 'Khmer OS Content';float: right;"  >
	<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('client_code');?></td>
			<td><?php echo $frm->getElement('client_name');?></td>
			<td><?php echo $frm->getElement('to');?></td>
		    <td><?php echo $frm->getElement('from');?></td>
			<td><?php echo $frm->getElement('collteral_type')?>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
			<td></td>
		</tr>
</table>
<div style="clear: both;"></div>
	<h2 align="center"><?php //echo $this->data['brand_rep_va'];?></h2><br/>
	<div id="divPrint">
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    	<tr bgcolor="#BBBBBB" >
        	<th><?php echo $tr->translate("NUM");?></th>
            <th><?php echo $tr->translate("BRANCH_NAME");?></th>
            <th><?php echo $tr->translate("CUSTOMER_CODE");?></th>
            <th><?php echo $tr->translate("OWNER_NAME");?></th>
            <th><?php echo $tr->translate("TO_COLL");?></th>
            <th><?php echo $tr->translate("COLLTERAL_TYPE");?></th>
            <th><?php echo $tr->translate("NUMBER_COLLTERAL");?></th>
            <th><?php echo $tr->translate("OWNER_NAME");?></th>
            <th><?php echo $tr->translate("DATE");?></th>
            <th><?php echo $tr->translate("NOTE");?></th>
            <th><?php echo $tr->translate("BY");?></th>
         </tr>
         <?php foreach($this->calleteral_list as $key =>$row){?>
         <tr>
        	<td>&nbsp;<?php echo $key+1;?></td>
		    <td>&nbsp;<?php echo $row['branch_id']?></td>
            <td>&nbsp;<?php echo $row['owner_code_id']?></td>
            <td>&nbsp;<?php echo $row['owner_id']?></td>
            <td>&nbsp;<?php echo $row['fromd_id']?></td>
            <td>&nbsp;<?php echo $row['to_id']?></td>
            <td>&nbsp;<?php echo $row['collteral_type']?></td>
            <td>&nbsp;<?php echo $row['number_code']?></td>
            <td>&nbsp;<?php echo $row['date']?></td>
            <td>&nbsp;<?php echo $row['note']?></td>
            <td>&nbsp;<?php echo $row['owner']?></td>
         </tr>
         <?php }?>
    </table>
    </div>
</body>
</html>