<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Client Black List"));
	$frm = $this->frm_search;
?>
<html>
<head>
<meta charset="utf-8">

</head>
<body> 
<table style="font-family: 'Khmer OS Content';float: right;"  >
	<tr>
   		<td><?php echo $frm->getElement("adv_search");?></td>
   		<td><?php echo $frm->getElement("branch_id");?></td>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement('status_search');?></td>
   		<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div style="clear: both;"></div>
	<h2 align="center"><?php //echo $this->data['brand_rep_va'];?></h2><br/>
	<div id="divPrint">
	    <table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<!--  <h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>-->
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['brand_clientblacklist'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				
		                </table>
		              </td>
		           </tr>   
    </table>
	<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    	<tr bgcolor="#BBBBBB" >
        	<th><?php echo $tr->translate("NUM");?></th>
            <th><?php echo $tr->translate("BRANCH_NAME");?></th>
            <th><?php echo $tr->translate("COMMUNE_NAME_KH");?> - <?php echo $tr->translate("COMUNE_NAME_EN");?></th>
            <th><?php echo $tr->translate("CUSTOMER_CODE");?></th>
            <th><?php echo $tr->translate("SEX");?></th>
            <th><?php echo $tr->translate("REASON");?></th>
            <th><?php echo $tr->translate("IN_BLACKLIST");?></th>
            <th><?php echo $tr->translate("DATE");?></th>
         </tr>
         <?php if(!empty($this->calleteral_list)) foreach($this->calleteral_list as $key =>$row){?>
         <tr>
        	<td>&nbsp;<?php echo $key+1;?></td>
		    <td>&nbsp;<?php echo $row['branch_id']?></td>
             <td>&nbsp;<?php echo $row['name_kh']." - ".$row['name_en']?></td>
            <td>&nbsp;<?php echo $row['client_number']?></td>
            <td>&nbsp;<?php echo $row['sex']?></td>
            <td>&nbsp;<?php echo $row['reasonblack_list']?></td>
            <td>&nbsp;<?php echo $row['is_blacklist']?></td>
            <td>&nbsp;<?php echo $row['date_blacklist']?></td>
         </tr>
         <?php }?>
    </table>
    </div>
</body>
</html>