<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Loan Management System</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
<style>
.tundra .dijitBorderContainer-child{
	 overflow: hidden;
}
</style>
<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$client=$this->url(array('module'=>'group','controller'=>'index','action'=>'index'), null, true);
$collecteral=$this->url(array('module'=>'group','controller'=>'Callteral','action'=>'index'), null, true);
$chagen_coll=$this->url(array('module'=>'group','controller'=>'changecollteral','action'=>'index'), null, true);
$indi_loan=$this->url(array('module'=>'loan','controller'=>'index','action'=>'index'), null, true);
$disburse_loan=$this->url(array('module'=>'loan','controller'=>'GroupDisburse','action'=>'index'), null, true);
$indi_payment=$this->url(array('module'=>'loan','controller'=>'IlPayment','action'=>'index'), null, true);
$group_payment=$this->url(array('module'=>'loan','controller'=>'GroupPayment','action'=>'index'), null, true);
$repay_schedule=$this->url(array('module'=>'loan','controller'=>'RepaymentSchedule','action'=>'index'), null, true);
$quickpayment=$this->url(array('module'=>'loan','controller'=>'QuickPayment','action'=>'index'), null, true);
$co=$this->url(array('module'=>'payroll','controller'=>'co','action'=>'index'), null, true);
$bad_loan=$this->url(array('module'=>'loan','controller'=>'BadLoan','action'=>'index'), null, true);
?>
 </head>
<body class="fixed-top">
   <div id="container" class="row-fluid">
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav metro-fix-view">
                    <div class="metro-nav-block nav-block-green long">
                        <a href="<?php echo $client;?>" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="icon-user"></i>
                            </span>
                        </a>
                         <div class="status" align="center"><?php echo $tr->translate('CLIENT_INFO');?></div>
                    </div>
                    <div class="metro-nav-block nav-block-orange">
                        <a href="<?php echo $collecteral;?>" data-original-title="">
                            <i class="icon-user"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('CLIENT_COLLETERAL');?></div>
                        </a>
                    </div>

                   <div class="metro-nav-block nav-block-green">
                       <a href="<?php echo $chagen_coll;?>" data-original-title="">
                           <i class="icon-comments-alt"></i>
                           <div class="info"></div>
                           <div class="status"><?php echo $tr->translate('CHANGE_COLLETERAL');?></div>
                       </a>
                   </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $indi_loan;?>" data-original-title="">
                            <i class="icon-tasks"></i>
                            <div class="info">$37624</div>
                            <div class="status"><?php echo $tr->translate('LOAN_IL');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-yellow">
                        <a href="<?php echo $disburse_loan;?>" data-original-title="">
                            <i class="icon-tags"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('INFO_LOANGROUP');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $indi_payment;?>" class="text-center" data-original-title="">
                            <i class="icon-bar-chart"></i>
                            <div class="status"><?php echo $tr->translate('IL_PAYMENT');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-orange">
                        <a href="<?php echo $repay_schedule;?>" data-original-title="" class="text-center">
                            <i class="icon-star-empty"></i>
                            <div class="status">កាលវិភាគថ្មី</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-red double">
                        <a href="<?php echo $group_payment;?>" data-original-title="">
                            <i class="icon-bar-chart"></i>
                            <div class="status">សងប្រាក់ជាក្រុម</div>
                        </a>
                    </div>
                    
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $quickpayment;?>" data-original-title="">
                            <i class="icon-eye-open"></i>
                            <div class="info"></div>
                            <div class="status">សងប្រាក់តាមមន្ត្រីឥនទាន </div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-red">
                        <a href="<?php echo $co;?>" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status">មន្ត្រីឥនទាន</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey">
                        <a href="<?php echo $bad_loan;?>" data-original-title="">
                            <i class="icon-remove-sign"></i>
                            <div class="info"></div>
                            <div class="status">កម្ចីខូច</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple">
                        <a href="#" data-original-title="" class="text-center">
                            <i class="icon-cogs"></i>
                            <div class="status">បញ្ជីកម្ចីបុគ្គល</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-blue">
                        <a href="#" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status">បញ្ជីកម្ចីជាក្រុម</div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-green double">
                        <a href="#" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status">បញ្ជីឈ្មោះត្រូវសង</div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-blue double">
                        <a href="#" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status">ចំណូលពីសេវារដ្ឋបាល</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey">
                        <a href="#" class="text-center" data-original-title="">
                            <i class="icon-dashboard"></i>
                            <div class="status">អតិជនសងរួច</div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-yellow">
                        <a href="#" class="text-center" data-original-title="">
                            <i class=" icon-puzzle-piece"></i>
                            <div class="status">Warning</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-orange">
                        <a href="#" class="text-center" data-original-title="">
                            <i class="icon-signout"></i>
                            <div class="status">Other</div>
                        </a>
                    </div>
                   
                </div>

                <div class="space10"></div>
                <!--END METRO STATES-->
            </div>
            <!-- END PAGE CONTENT-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
      &copy;CopyRight by VSS Consultancy.
   </div>
   <!-- END FOOTER -->

   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.3.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->

   <!--common script for all pages-->
   <script src="<?php echo $this->baseUrl()?>/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->   
</body>
<!-- END BODY -->
</html>