<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
	<h2 align="center">Rpt-CustomerPayment</h2>
	<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th>N<sub>0</sub></th>
            <th>Client N<sub>0</sub></th>
            <th>Name Khmer</thd>
            <th>Name Eng</th>
            <th>Principale</th>
            <th>Total Interest</th>
            <th>Total amount</th>
            <th>Total Resive</th>
            <th>Balance</th>
        </tr>
        <?php for($i=0;$i<=10;$i++){?>
        <tr align="center">
        	<td><?php echo $i+1;?></td>
            <td></td>
            <td style="font-family:'Khmer OS Battambang'; font-size:14px;">សេន​ រដ្ធា</td>
            <td>Sen ratha</td>
            <td>$200</td>
            <td>$156</td>
            <td>$356</td>
            <td>$467</td>
            <td>$44</td>
        </tr>
        <?php }?>
        <tr align="center">
        	<td>12</td>
        	<td colspan="4">TOTAL</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</body>
</html>