
<meta charset="utf-8">
<title>Disbursement</title>
<table width="80%" align="center"  cellspacing="0" style="margin-left: 50px;">
	<tr>
    	<td>
        	<h2>Disbursements</h2>
            <p>5.12.2014.all Currencies-Pound</p>
  <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
                    <tr bgcolor="#888888" align="center">
                        <th>Contract code</th>
                        <th>District</th>
                        <th>Loan Product</th>
                        <th>first Name</th>
                        <th>Last Name</th>
                        <th>Cycle</th>
                        <th>Loan officer</th>
                        <th>Branch</th>
                        <th>Disbursment</th>
                        <th>Amount</th>
                        <th>Interest</th>
                        <th>fee</th>
                    </tr>
                    <tr height="40px">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                     
                    </tr>
                    <tr height="40px">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        
                    </tr>
                    <tr bgcolor="#888888">
                        <td>Total</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                       
                    </tr>
                </table>
   		</td>
  	 </tr>
  </table>