<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LIST_LOAN_INCOME"));
$frm = $this->frm_search;
?>
<form method="post">
<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
</form>
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_INCOME");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
                </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size:11px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; border:1px solid #000; line-height: 14px; font-size:10px; padding:5px 0px; ">
                    <th style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("LOAN_NO");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("CLIENT_NUM");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("RECIEPT_NO");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("PRINCIPLE_PERMONTH");?></th>                    
                    <th style="padding:5px 0px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("SERVICE CHARGE");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("PAY_DATE");?></th>
                </tr>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;
                ?>
                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal_permonth'];
		               		$amn_r2 = $amt_r2+$rs['total_interest'];
		               		$amn_r3 = $amt_r3+$rs['penalize_amount'];
		               		$amn_r4 = $amt_r4+$rs['service_charge'];
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal_permonth'];
							$amt_d2 = $amt_d2+$rs['total_interest'];
							$amt_d3 = $amt_d3+$rs['penalize_amount'];
							$amt_d4 = $amt_d4+$rs['service_charge'];
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal_permonth'];
							$amn_b2 = $amn_b2+$rs['total_interest'];
							$amn_b3 = $amn_b3+$rs['penalize_amount'];
							$amn_b4 = $amn_b4+$rs['service_charge'];
		               }
               ?>
                <tr >
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["client_number"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["client_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?></td>
               		<td >&nbsp;&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?></td>
               		<td>&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_input"]));?></td>
                </tr>
                <?php }?>
            </table>
            <br />
            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; font-size:10px;" cellspacing="0">
            	<tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; padding:5px 0px; ">
                  <th><?php echo $tr->translate("NUM");?></th>
                  <th><?php echo $tr->translate("BRANCH_NAME");?></th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</th>
                  <th style="padding:5px 0px;"> &nbsp;<?php echo $tr->translate("RELEASE_DATE");?>&nbsp;</th>
                  <th>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</th>
                  <th style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</th>
                  <th><?php echo $tr->translate("AMIN_FEE");?></th>                    
                  <th><?php echo $tr->translate("OTHER_FEE");?></th>
                  <th style="padding:5px 0px;font-size: 8px;"><?php echo $tr->translate("FOR_LOAN_TYPE");?></th>
                </tr>
                <?php $r1=0; $r2=0;$d1=0;$d2=0;$b1=0;$b2=0;?>
                <?php foreach ($this->LoanFee_list as $key => $row){ ?>
                <?php 
                if($row['curr_type']==1){
		               		$r1 = $r1+$row['admin_fee'];
		               		$r2 = $r2+$row['other_fee'];
		               }elseif($row['curr_type']==2){
							$d1 = $d1+$row['admin_fee'];
							$d2 = $d2+$row['other_fee'];
		               }else{
		               		$b1 = $b1+$row['admin_fee'];
							$b2 = $b2+$row['other_fee'];
		               }
		         ?>
                <tr>
               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo $row["branch_name"];?></td>
               		<td >&nbsp;&nbsp;<?php echo $row["loan_number"];?></td>
					<td>&nbsp;<?php echo $row['client_number'];?>&nbsp;</td>
					<td align="left" style="font-size:9px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_khname']; ?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_line']));?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
               		<td >&nbsp;&nbsp;<?php echo number_format( $row["admin_fee"],2).' '.$row['currency_type'];?></td>               		
               		<td >&nbsp;&nbsp;<?php echo number_format($row["other_fee"],2).' '.$row['currency_type'];?></td>
               		<td style="font-size: 8px;">&nbsp;<?php 
							if ($row['loantype']==1){echo 'indi';}
							else {
								echo 'group';
							}
							; ?>&nbsp;</td>
                </tr>
                <?php }?>
            </table>
            <br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                <tr​ bgcolor="#ccc" style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                	 <th rowspan="2" align="center"><?php echo $tr->translate("CURRENT_TYPE");?></th>
                	 <th colspan="3" style=" border-right: 3px double #000;"><?php echo $tr->translate("INCOME_FROMPAYMENT");?></th>
                	 <th colspan="2"><?php echo $tr->translate("INCOME_FROMLOAN_DISBURSE");?></th>
                	 <th rowspan="2"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr bgcolor="#ccc" style="font-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <th><?php echo $tr->translate("INTEREST");?></th>
                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style=" border-right: 3px double #000;"><?php echo $tr->translate("SERVICE CHARGE");?></th>
                    <th><?php echo $tr->translate("AMIN_FEE");?></th>
                    <th><?php echo $tr->translate("OTHER_FEE");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px;  font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td style=" border-right: 3px double #000;">&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2+$amt_d3+$amt_d4+$d1+$d2,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td style=" border-right: 3px double #000;">&nbsp;&nbsp;<?php echo number_format($amn_r4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2+$amn_r3+$r1+$r2,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?></td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td style=" border-right: 3px double #000;">&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2+$amn_b3+$b1+$b2,2);?>&nbsp;</td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
<br />
 <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
</div>
</div>
</div>
