<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$type = array(1=>$tr->translate("COTOC0"),2=>$tr->translate("CLIENTTOC0"),3=>"LOANTOCO");

?>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_TRASFER_LOAN");?></title>
<form method="post">
	<table style="width:28.7cm; margin: 0 auto;">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
		</tr>
		<tr>
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><?php echo $filter->getElement('btn_search');?></td>
			<td></td>
		</tr>
	</table>
	</form>
<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_TRASFER_LOAN");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
                	</td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr >
                				<td  style="font-size: 11px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <th>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
                    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th><?php echo $tr->translate("FROM_CO");?></th>
                    <th><?php echo $tr->translate("TO_CO");?></th>
                    <th><?php echo $tr->translate("CLIENT_NO");?></th>
                    <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
                    <th><?php echo $tr->translate("LOAN_NO");?></th>
                    <th><?php echo $tr->translate("NOTE");?></th>
                    <th><?php echo $tr->translate("TYPE");?></th>
                    <th><?php echo $tr->translate("DATE");?></th>
                </tr>
               <?php 
               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
               $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
               if(!empty($this->loantrasfer)) foreach($this->loantrasfer as $key =>$row){?>
					<tr align="center" style="line-height: 18px;">
					<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
					<td >&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['from_coname'];?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['to_coname'];?>&nbsp;</td>
					<td align="center">&nbsp;<?php
						if($row['type']==1){
							echo "-";
						}else{
							echo $row['client_number'];
						}
					?>&nbsp;</td>
					<td align="center" style="line-height:15px;">&nbsp;
						<?php 
						if($row['type']==1){
							echo "-";
						}else{
							echo $row['client_name'];
						}?>&nbsp;
					</td>	
					<td align="center">&nbsp;
					<?php 
						if($row['type']==1){
							echo "-";
						}else{
							echo $row['loan_number'];
						}?>&nbsp;</td>
					<td align="left"><span style="line-height:15px;">&nbsp;<?php echo $row['note']; ?></span>&nbsp;</td>	
					<td align="left">&nbsp;<?php echo $type[$row['type']]; ?>&nbsp;</td>				
					<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date']));?>&nbsp;</td>
					</tr>
				<?php }?>
            </table>
              <table align="center" width="100%">
				   <tr style="font-size: 11px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>	
    	</td>
    </tr>
</table>
</div>
</div>