<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("LOAN_OUTSTANDING");?></title>
<html>
<head>
<meta charset="utf-8">
<title></title>

</head>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
	<tr>
		<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['rpt_loan_outstanding'];?></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo 'សំរាប់ថ្ងៃទី';?></h2>
                	</td>
                    
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 11px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
	</tr>
	<tr>
	   <td>
			  <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 14px; font-size:11px; padding:5px 0px; ">
                    <td style="padding:5px 0px;">លរ</td>
                    <td style="padding:5px 0px;">លេខឥណទាន</td>
                    <td style="padding:5px 0px;">ឈ្មោះអតិថជន</td>
                    <td style="padding:5px 0px;">កាលបរិឆ្ឆេទខ្ចី</td>
                    <td style="padding:5px 0px;">រយះពេលខ្ចី</td>
                    <td style="padding:5px 0px;">ចំនួនប្រាក់កម្ចី</td>
                    <td style="padding:5px 0px;">ថ្លៃរដ្ឋបាល</td>
                    <td style="padding:5px 0px;">អត្រាការប្រាក់</td>
                    <td style="padding:5px 0px;">ឈ្មោះមន្ត្រីឥណទាន</td>
                    
                </tr>
               <?php 
               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
//                print_r($this->loanrelease_list);
               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
               <?php 
               if($row['curr_type']==1){
               		$amt_r = $amt_r+$row['total_capital'];
               		$amn_r = $amn_r+$row['admin_fee'];
               }elseif($row['curr_type']==2){
               		$amt_d = $amt_d+$row['total_capital'];
               		$amn_d = $amn_d+$row['admin_fee'];
               }else{
               		$amt_b = $amt_b+$row['total_capital'];
               		$amn_b = $amn_b+$row['admin_fee'];
               }
               ?>
					<tr align="center">
					<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
					<td align="left">&nbsp;<?php echo $row['client_id'].'- '.$row['client_name']; ?>&nbsp;</td>
					<td style="white-space:nowrap;" >&nbsp;<?php echo $row['date_release']; ?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['total_duration'].' '.$row['name_en']?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['admin_fee'],2).' '.$row['currency_type']?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['interest_rate'].'%'; ?>&nbsp;</td>
					
					<td>&nbsp;<?php echo $row['co_name']; ?>&nbsp;</td>					
					</tr>
				<?php }?>
            </table>
		     </td>
     </tr>
</div>
</div>
</html>