<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$xchange= $this->Loanxchange_list;
$frm = $this->frm_search;
$client = $this->client;
?>

<meta charset="utf-8">
<title><?php echo $tr->translate("LIST_LOAN_XCHANGE");?></title>
<style>

</style>
<form method="post">
<table style="font-family: 'Khmer OS Content';float: left;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php //echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
</form>
<br/>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height:50px;">
 
</div>
<div style=" width:26cm;min-height:20cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_XCHANGE");?></h2></td>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel"  border="1"​ style="border-collapse:collapse;border:1px solid #000; " width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#BBBBBB" align="center" style="font-weight:bold; line-height: 24px;font-size:10px; font-family: 'Khmer OS Content'">
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUM");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RECIEPT_NO");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("FROM_AMOUNT");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("TO_AMOUNT");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("EXCHANGE_RATE");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RECIEVED_AMOUNT");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RETURN_AMOUNT");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("DATE");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("FROM_TO");?></td>
                    <td style=" font-size:12px; font-family:'Khmer MEF2'"><?php echo $tr->translate("IS_SPACIAL_CUSTOMER");?></td>
                    
                </tr>
                <?php foreach ($xchange as $row){ $i=1;?>
               <tr style="font-size: 11px;" align="left">
               		<td style="text-align: center;"><?php echo $i++;?></td>
               		<td>&nbsp;<?php echo $row['branch_name']?></td>
               		<td>&nbsp;<?php echo $row['client_name']?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['recieptNo']?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['fromAmount'].$row['fromAmountType'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['toAmount'].$row['toAmountType'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['rate'].$row['toAmountType'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['recievedAmount'].$row['fromAmountType'];?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['changedAmount'].$row['fromAmountType'];?>&nbsp;</td>
               		<td>&nbsp;<?php echo date('d-m-Y',strtotime($row['statusDate']))?>&nbsp;</td>
               		<td>&nbsp;<?php echo $row['from_to']?>&nbsp;</td>
               		<td>&nbsp;<?php echo ($row['specail_customer']==1)?"Yes":"No"?>&nbsp;</td>
               		
               </tr>
               <?php }?>
            </table>
       		<br />
       		 <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>