<?php 
//error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
//echo $this->headTitle($tr->translate("IL Payment"));
$frm = $this->frm_search;
$end_dat=$this->date_show;
?>
<title><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></title>
<form method="post">
<table style="font-family: 'Khmer OS Content';float: right;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement('paymnet_type');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
</form>

<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
                	 $co_id = null;
                ?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("D-d-M-Y",strtotime($this->start_date)).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->date_show));?></h2>
               </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
</table>
<div id="exportExcel">
<table  width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
		        <tr class="style" bgcolor="#ccc" align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
			      <th><?php echo $tr->translate("NUM");?></th>
			      <th><?php echo $tr->translate("BRANCH_NAME");?></th>
			      <th><?php echo $tr->translate("LOAN_NO");?></th>
			      <th><?php echo $tr->translate("CLIENT_NO");?></th>
			      <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
			      <th><?php echo $tr->translate("PHONE");?></th>
			      <th><?php echo $tr->translate("LOAN_AMOUNT");?></th>
			      <th><?php echo $tr->translate("INTEREST RATE");?></th>
			      <th><?php echo $tr->translate("LOAN_PERIOD");?></th>
			      <th><?php echo $tr->translate("RELEASE_DATE");?></th>
			      <th><?php echo $tr->translate("LIFE_LOAN");?></th>
			      <th><?php echo $tr->translate("PRINCIPLE_PERMONTH");?></th>  
			      <th><?php echo $tr->translate("INTEREST");?></th>  
			      <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
			      <th><?php echo $tr->translate("SERVICE_CHARGE");?></th>
			      <th><?php echo $tr->translate("PAYMENT");?></th>
			      <th><?php echo $tr->translate("COLLECT_DATE");?></th>
			      <th><?php echo $tr->translate("PAY_DATE");?></th>
			   	</tr>
<?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){?>
	
     <?php if($co_id!=$rs["co_id"]){ ?>
				<tr>
					<td colspan="20" style="font-size: 14px; font-weight:500; background:#CADEE3;"><b><?php echo $rs["co_name"];?></b></td>
				</tr>
	<?php $co_id = $rs["co_id"];}?>
			   	<tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 11px;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 11px;"><?php echo $rs["branch"];?></td>
               		<td style="font-size: 11px;"><?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 11px;"><?php echo $rs["client_code"];?></td>
               		<td style="font-size: 11px;"><?php echo $rs["client_name"];?></td>
               		<td style="font-size: 11px; white-space: nowrap;"><?php echo $rs["phone"];?></td>
               		<td style="font-size: 11px;"><?php echo number_format( $rs["capital"],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 11px;"><?php echo $rs["interest_rate"]." %";?></td>
               		<td style="font-size: 11px;"><?php echo $rs["total_duration"]." ".$rs["name_en"];?></td>
               		<td style="font-size: 11px;">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_release"]));?>&nbsp;</td>
               		<td style="font-size: 11px;">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_line"]));?>&nbsp;</td>
               		<td style="font-size: 11px;"><?php echo number_format( $rs["principal_permonth"],2).' '.$rs['currency_type'];?></td>  
               		<td style="font-size: 11px;"><?php echo number_format( $rs["total_interest"],2).' '.$rs['currency_type'];?></td>             		
               		<td style="font-size: 11px;"><?php echo number_format($rs["penelize_amount"],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 11px;"><?php echo number_format($rs["service_charge"],2).' '.$rs['currency_type'];?></td>
               		<td style="font-size: 11px;"><?php echo number_format($rs["total_payment"],2).' '.$rs['currency_type'];?></td>
               		
               			
               			<?php 
				               if($rs['curr_type']==1){
				               		$amt_r1 = $amt_r1+$rs['principal_permonth'];
				               		$amn_r2 = $amt_r2+$rs['total_interest'];
				               		$amn_r3 = $amt_r3+$rs["penelize_amount"];
				               		$amn_r4 = $amt_r4+$rs["total_payment"];
				               		$amn_r5 = $amt_r5+$rs['service_charge'];
				               		$total_r=$amn_r4;
				               }elseif($rs['curr_type']==2){
									$amt_d1 = $amt_d1+$rs['principal_permonth'];
									$amt_d2 = $amt_d2+$rs['total_interest'];
									$amt_d3 = $amt_d3+$rs["penelize_amount"];
									$amt_d4 = $amt_d4+$rs["total_payment"];
									$amt_d5 = $amt_d5+$rs['service_charge'];
									$total_d=$amt_d4;
				               }else{
				               		$amn_b1 = $amn_b1+$rs['principal_permonth'];
									$amn_b2 = $amn_b2+$rs['total_interest'];
									$amn_b3 = $amn_b3+$rs["penelize_amount"];
									$amn_b4 = $amn_b4+$rs["total_payment"];
									$amn_b5 = $amn_b5+$rs['service_charge'];
									$total_b=$amn_b4;
				               }
		           // }
		               ?>
               		
               		<td style="font-size: 11px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_input"]));?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo date("d-M-Y",strtotime($rs["date_payment"]));?></td>
                </tr>

<?php  }?>
</table>

<br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td style="font-size: 12px;"></td>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PRINCIPLE_PERMONTH");?></th>                    
                    <th style="font-size: 12px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PAYMENT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
                
              </table>
	            <br />
	            <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
</div>
</div>
</div>
</div>
