<title>Loan Released</title>
<meta charset="utf-8">
<title>out standing loan</title>
<table style="font-family: 'Khmer OS Content';float: right;"  >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<style>
.style{
	line-height: 20px !important;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint" style="width: 100%;">
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $this->data['rpt_loan_outstanding'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 11px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 13px; font-size:11px;padding: 5px 0px;">
                    <th>&nbsp;លរ&nbsp;</th>
                    <th>&nbsp;សាខា&nbsp;</th>
                    <th>&nbsp;ថ្ងៃខ្ចី&nbsp;</th>
                    <th>&nbsp;លេខឥណទាន&nbsp;</th>
                    <th>&nbsp;ឈ្មោះអតិថជន&nbsp;</th>
                    <th>&nbsp;ចំនួនប្រាក់កម្ចី&nbsp;</th>
                    <th>&nbsp;ចំនួនប្រាក់ប្រមូលមកវិញ&nbsp;</th>
                    <th>&nbsp;អត្រាសង(%)&nbsp;</th>
                    <th>&nbsp;ប្រាក់មិនទាន់សង&nbsp;</th>
                </tr>
               <?php 
               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
//                print_r($this->loanrelease_list);
               if(!empty($this->outstandloan)) foreach($this->outstandloan as $key =>$row){?>
               <?php 
               if($row['curr_type']==1){
               		$amt_r = $amt_r+$row['total_capital'];
               		$amn_r = $amn_r+$row['total_payment'];
               }elseif($row['curr_type']==2){
               		$amt_d = $amt_d+$row['total_capital'];
               		$amn_d = $amn_d+$row['total_payment'];
               }else{
               		$amt_b = $amt_b+$row['total_capital'];
               		$amn_b = $amn_b+$row['total_payment'];
               }
               ?>
					<tr align="center">
					<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
					<td style="line-height: 12px; white-space: nowrap;">&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
					<td align="left" style="font-size:9px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_name']; ?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_payment'],2);?>&nbsp;</td>
					<td>&nbsp;<?php echo (round(($row['total_payment']/$row['total_capital']),2)*100).' %';?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['total_capital']-$row['total_payment'];?>&nbsp;</td>
					</tr>
				<?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;">
                    <td></td>
                    <td>ចំនួនប្រាក់កម្ចីសរុប</td>
                    <td>ចំនួនប្រាក់ប្រមូលសរុប</td>
                    <td>អត្រាសង(%)</td>
                    <td>ប្រាក់មិនទាន់សងសរុប</td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;ដុល្លា  / ($)</td>
                    <td>&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format(($amn_d/$amt_d)*100,2).' %';?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format(($amt_d-$amn_d)*100,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;រៀល  / (R)</td>
                    <td>&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format(($amn_r/$amt_r)*100,2).' %';?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_r-$amn_r);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;បាត / (B)&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format(($amn_b/$amt_b)*100,2).' %';?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format(($amt_b-$amn_d),2);?>&nbsp;</td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
</div>
</div>
