<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

?>
<meta charset="utf-8">
<title><?php echo $tr->translate("GROUP_DISBURS");?></title>
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.3cm">
<div id="divPrint">
	<table style="font-family: 'Khmer OS Content'; width:100%;">
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
	                	<td width="60%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LOAN_DISBURSE");?></h2>
	                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
	                	</td>
	                    <td width="20%"></td>
	                </tr> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr >
	                				<td  style="font-size: 11px;">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
										<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td width="65%"></td>
	                				
	                			</tr>
				               
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
	                 <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
	                    <th>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
	                    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th><?php echo $tr->translate("LOAN_NO");?></th>
	                    <th><?php echo $tr->translate("CLIENT_NO");?></th>
	                    <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                    <th><?php echo $tr->translate("CO_NAME");?></th>
	                    <th><?php echo $tr->translate("LOAN_AMOUNT");?></th>
	                    <th><?php echo $tr->translate("ADMIN_FEE");?></th>
	                    <th><?php echo $tr->translate("OTHER_FEE");?></th>
	                    <th><?php echo $tr->translate("INTEREST RATE");?></th>
	                    <th><?php echo $tr->translate("TERM_BORROW");?></th>
	                    <th><?php echo $tr->translate("RELEASED_DATE");?></th>
	                    <th><?php echo $tr->translate("LIFE_LOAN");?></th>
	                    <th><?php echo $tr->translate("LOAN_TYPE");?></th>
	                </tr>
	               <?php 
	               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;
	               $other_fee_r=0; $other_fee_b=0; $other_fee_d=0;$total_r=0;$total_b=0;$total_d=0;
	               if(!empty($this->loanmember_list)) foreach($this->loanmember_list as $key =>$row){?>
	               <?php 
	               		$amt_r = $amt_r+$row['total_capital'];
	               		$amn_r = $amn_r+$row['admin_fee'];
	               		$other_fee_r=$other_fee_r+$row['other_fee'];
	               		$total_r=$amt_r+$amn_r+$other_fee_r;
	               ?>
					<tr align="center">
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo $row['branch_name']; ?></a>&nbsp;</td>
						<td><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo $row['loan_number'];?></a>&nbsp;</td>
						<td><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo $row['client_number'];?></a>&nbsp;</td>
						<td align="left" style="line-height:15px;">&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>"><?php echo $row['client_name']; ?></a>&nbsp;</td>	
						<td align="left"><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo $row['co_name']; ?>&nbsp;</a></td>	
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>"><?php echo number_format($row['admin_fee'],2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>"><?php echo number_format($row['other_fee'],2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>"><?php echo $row['interest_rate'].'%'; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>"><?php echo $row['total_duration'].$row['name_en'];?>&nbsp;</a></td>
						<td style="white-space:nowrap;" ><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?></a>&nbsp;</td>
						<td style="white-space:nowrap;" ><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-memberschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?></a>&nbsp;</td>
						<td align="left" style="font-size:8px;">&nbsp;<?php echo $row['loan_type']; ?>&nbsp;</td>	
					</tr>
					
					<?php
					if(!empty($this->loanmember_list))if(count($this->loanmember_list)== $key+1){?>
					<tr align="center">
						<td>&nbsp;<?php echo $key+2;?>&nbsp;</td>
						<td align="left" colspan="5"><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['group_id'];?>">&nbsp;For Group &nbsp;</a></td>	
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($amt_r,2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['group_id'];?>"><?php echo number_format($amn_r,2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['group_id'];?>"><?php echo number_format($other_fee_r,2).' '.$row['currency_type']; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['group_id'];?>"><?php echo $row['interest_rate'].'%'; ?>&nbsp;</a></td>
						<td>&nbsp;<a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['group_id'];?>"><?php echo $row['total_duration'].$row['name_en'];?>&nbsp;</a></td>
						<td style="white-space:nowrap;" ><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo date('d/m/Y',strtotime($row['date_release']));?></a>&nbsp;</td>
						<td style="white-space:nowrap;" ><a style="color:black;" target="_blank" href="<?php echo $this->baseUrl();?>/report/loan/rpt-groupschedules/id/<?php echo $row['member_id'];?>">&nbsp;<?php echo date('d/m/Y',strtotime($row['date_line']));?></a>&nbsp;</td>
						<td align="left" style="font-size:8px;">&nbsp;<?php echo $row['loan_type']; ?>&nbsp;</td>	
					</tr>
                   <?php }?>
					<?php }?>
	            </table>
	              <br />
	              <table align="center" width="100%">
					   <tr style="font-size: 11px;">
					        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
					        <th></th>
					        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
					        <th></th>
					        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
					   </tr>
				</table>	
	    	</td>
	    </tr>
	</table>
  </div>
 </div>