<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("PAY_OFF"));
$frm = $this->frm_search;
?>
<style>
<!--
.style td{font-size: 12px !important;font-family: 'Khmer OS Content';}
th{font-size: 12px !important;font-family: 'Khmer OS Content';}
-->
</style>
<form method="post">
<table style="font-family: 'Khmer OS Content';float: right;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
</form>
<br/><br/><br/><br/><br/>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_PAYOFF");?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
                <tr align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
                    <th style="font-size: 9px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("CO_NAME");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Recirpt No");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("LOAN_NO");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("PRINCIPLE");?></th>                    
                    <th style="font-size: 9px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>                    
                    <th style="font-size: 9px;"><?php echo $tr->translate("SERVICE CHARGE");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("PAYMENT");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("AMOUNT");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("DAY_PAYMENT");?></th>
                </tr>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$amt_r6 = 0;$amt_r7 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$amt_d6 = 0;$amt_d7 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$amn_b6 = 0;$amn_b7 = 0;
                ?>
                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal_permonth'];
		               		$amn_r2 = $amt_r2+$rs['total_interest'];
		               		$amn_r3 = $amt_r3+$rs['penalize_amount'];
		               		$amn_r5 = $amt_r5+$rs['service_charge'];
		               		$amn_r6 = $amt_r6+$rs['total_payment'];
		               		$amn_r7 = $amt_r7+$rs['amount_payment'];
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal_permonth'];
							$amt_d2 = $amt_d2+$rs['total_interest'];
							$amt_d3 = $amt_d3+$rs['penalize_amount'];
							$amt_d5 = $amt_d5+$rs['service_charge'];
							$amt_d6 = $amt_d6+$rs['total_payment'];
							$amt_d7 = $amt_d7+$rs['amount_payment'];
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal_permonth'];
							$amn_b2 = $amn_b2+$rs['total_interest'];
							$amn_b3 = $amn_b3+$rs['penalize_amount'];
							$amn_b5 = $amn_b5+$rs['service_charge'];
							$amn_b6 = $amn_b6+$rs['total_payment'];
							$amn_b7 = $amn_b7+$rs['amount_payment'];
		               }
               ?>
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 9px;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["branch"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["co_name"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["team_group"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["total_payment"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["amount_payment"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;text-align: center;"><?php echo $rs["date_pay"];?></td>
                </tr>
                <?php }?>
            </table>
            <br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td></td>
                    <th><?php echo $tr->translate("TOTAL_PRINCEPLE");?></th>                    
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <th><?php echo $tr->translate("PRINCIPAL_PERMONTH");?></th>
                    <th><?php echo $tr->translate("TOTAL SERVICE CHARGE");?></th>
                    <th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
                    <th><?php echo $tr->translate("TOTAL_AMOUNT_PAYMENT");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d6,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d7,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r6,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r7,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
				   <td>&nbsp;&nbsp;<?php echo number_format($amn_b6,2);?>&nbsp;</td>
				   <td>&nbsp;&nbsp;<?php echo number_format($amn_b7,2);?>&nbsp;</td>
                </tr>
              </table>
               <br />
              <table align="center" width="100%">
				    <tr style="font-size: 12px;">
				        <th style="width:20%;"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>
