<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$search = $this->$search;
?>
<title><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></title>

<form method="post">
<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>   			
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>   			
   			<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
</form>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint">
<style type="text/css">
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
                   </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
	                <tr bgcolor="#ccc" class="style" align="center" style="padding:2px 0;height: 20px;">
	                    <th rowspan="2"><?php echo $tr->translate("NUM");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("LOAN_NO");?></th>	  
	                    <th rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></th>                  
	                    <th rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("CO_NAME");?></th>
	                    <th colspan="5"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>    
	                    <th rowspan="2" style="white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("PAYMENTED");?></th>
	                    <!--<th><?php //echo $tr->translate("RETURN_AMOUNT");?></th>-->
	                    <th rowspan="2"><?php echo $tr->translate("BALANCE");?></th>
	                </tr>
	                <tr class="style">
	                	<th><?php echo $tr->translate("PRINCIPLE");?></th>                   
	                    <th><?php echo $tr->translate("INTEREST");?></th>
	                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
	                    <th><?php echo $tr->translate("SERVICE CHARGE");?></th>	                    
	                    <th><?php echo $tr->translate("TOTAL");?></th>
	                </tr>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
                	 $i=1;
                	 //$total_penilize_amount_r=0;$total_penilize_amount_d=0;$total_penilize_amount_b=0;
                	 $total_d=0;$total_b=0;$total_r=0;
                ?>
                <?php if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
                <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal_permonth'];
		               		$amn_r2 = $amt_r2+$rs['total_interest'];
		               		$amn_r3 = $amt_r3+$rs['penalize_amount'];
		               		$amn_r5 = $amt_r5+$rs['service_charge'];
		               		$total_r=$amt_r1+$amn_r2+$amn_r3+$amn_r5;
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal_permonth'];
							$amt_d2 = $amt_d2+$rs['total_interest'];
							$amt_d3 = $amt_d3+$rs['penalize_amount'];
							$amt_d5 = $amt_d5+$rs['service_charge'];
							$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal_permonth'];
							$amn_b2 = $amn_b2+$rs['total_interest'];
							$amn_b3 = $amn_b3+$rs['penalize_amount'];
							
							$amn_b5 = $amn_b5+$rs['service_charge'];
							$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
		               }
               ?>
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>                 		
               		<td>&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>               		
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs["total_payment"],2).' '.$rs['currency_typeshow'];;?>&nbsp;</td>
               		<td style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_pay"]));?>&nbsp;</td>
               		<td style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_input"]));?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
               		<td style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs["total_payment"],2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<!--<td>&nbsp;<?php //echo number_format($rs["return_amount"],2);?>&nbsp;</td>-->
               		<td style="font:bolder 11px Arial;">&nbsp;<?php $balance=$rs["total_payment"]-$rs["total_payment"]; if($balance<0){echo '('.abs($balance).')';}else {echo $balance=0;};echo $rs['currency_typeshow'];?>&nbsp;</td>
                </tr>
                <?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate("CURRENT_TYPE");?></td>
                    <th><?php echo $tr->translate("PRINCIPAL");?></th>                    
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <th><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></th>
                    <th><?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?></th>
                    <th><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo $total_d;?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo $total_r;?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo $total_b;?>&nbsp;</td>
                </tr>
              </table>
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>