<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL Payment"));
$frm = $this->frm_search;
?>
<style>
<!--
.style td{font-size: 12px !important;font-family: 'Khmer OS Content';}
th{font-size: 12px !important;font-family: 'Khmer OS Content';}
-->
</style>
<title><?php echo $tr->translate("RPT PAYMENT");?></title>
<table style="font-family: 'Khmer OS Content';float: right;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement('paymnet_type');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
<br/><br/><br/><br/>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $this->data['rpt_loan_collections'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
                <tr align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
                    <th style="font-size: 9px;"><?php echo $tr->translate("ID");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Branch");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Recirpt No");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Loan No");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Principle");?></th>                    
                    <th style="font-size: 9px;"><?php echo $tr->translate("Interest");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Penalize Amount");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Service Charge");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Date Pay");?></th>
                </tr>
                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;
                ?>
                <?php foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_principal_permonth'];
		               		$amn_r2 = $amt_r2+$rs['total_interest'];
		               		$amn_r3 = $amt_r3+$rs['penalize_amount'];
		               		$amn_r4 = $amt_r4+$rs['service_charge'];
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['total_principal_permonth'];
							$amt_d2 = $amt_d2+$rs['total_interest'];
							$amt_d3 = $amt_d3+$rs['penalize_amount'];
							$amt_d4 = $amt_d4+$rs['service_charge'];
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_principal_permonth'];
							$amn_b2 = $amn_b2+$rs['total_interest'];
							$amn_b3 = $amn_b3+$rs['penalize_amount'];
							$amn_b4 = $amn_b4+$rs['service_charge'];
		               }
               ?>
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 9px;text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["branch"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;text-align: center;"><?php echo $rs["date_pay"];?></td>
                </tr>
                <?php }?>
            </table>
            <br />
            <table width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
            	<tr align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
                    <th style="font-size: 9px;"><?php echo $tr->translate("ID");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Branch");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Loan No");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Admin Fee");?></th>                    
                    <th style="font-size: 9px;"><?php echo $tr->translate("Other Fee");?></th>
                    <th style="font-size: 9px;"><?php echo $tr->translate("Date Pay");?></th>
                </tr>
                <?php foreach ($this->LoanFee_list as $key => $row){ ?>
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 9px;text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $row["branch"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo $row["loan_number"];?></td>
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format( $row["admin_fee"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td style="font-size: 9px;">&nbsp;&nbsp;<?php echo number_format($row["other_fee"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 9px;text-align: center;"><?php echo $row["date_release"];?></td>
                </tr>
                <?php }?>
            </table>
            <br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;font-family: 'Khmer OS Content';">
                    <td></td>
                    <th><?php echo $tr->translate("Principle");?></th>                    
                    <th><?php echo $tr->translate("Interest");?></th>
                    <th><?php echo $tr->translate("Penalize Amount");?></th>
                    <th><?php echo $tr->translate("Payment");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;ដុល្លា  / ($)</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;រៀល  / (R)</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r4,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;បាត / (B)&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                </tr>
              </table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>
