<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<title>group disburse</title>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div style=" width="100%"  margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                			</tr>
			              </table>
		              </td>
		           </tr>   
            </table>
	<table width="96%" align="center"  cellspacing="0" style="margin-left: 10px;">
	<tr>
    	<td>
  	<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
                    <tr bgcolor="#888888" align="center">
                    	<th><?php echo $tr->translate("NUM");?></th>
                        <th><?php echo $tr->translate("LOAN_NO");?></th>
                        <th><?php echo $tr->translate("FIRST_NAME");?></th>
                        <th><?php echo $tr->translate("LAST_NAME");?></th>
                        <th><?php echo $tr->translate("AMOUNT");?></th>
                        <th><?php echo $tr->translate("INTEREST RATE");?></th>
                        <th><?php echo $tr->translate("FEE");?></th>
                        <th><?php echo $tr->translate("PAMENT_METHOD");?></th>
                        <th><?php echo $tr->translate("BRANCH_NAME");?></th>
                        <th><?php echo $tr->translate("LOAN PURPOSE");?></th>
                    </tr>
                    <?php if(!empty($this->loancllect_list)) foreach ($this->loancllect_list as $index => $rs){ ?>
                    <tr height="40px">
                        <td><?php echo $index+1;?></td>
                        <td><?php echo $rs['member_id']?></td>
                        <td><?php echo $rs['member_id']?></td>
                        <td><?php echo $rs['loan_number']?></td>
                        <td><?php echo $rs['graice_period']?></td>
                        <td><?php echo $rs['payment_method']?></td>
                        <td><?php echo $rs['currency_type']?></td>
                        <td><?php echo $rs['collect_typeterm']?></td>
                        <td><?php echo $rs['branch_id']?></td>
                        <td><?php echo $rs['group_id']?></td>
                    </tr>
                    <?php }?>
                    
                   
                </table>
   		</td>
  	 </tr>
  </table>
  </td>
  </tr>
  </table>
  </div>