<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->headTitle($tr->translate("UPDATE_CLIENT_COLLTERAL"));
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'Callteral','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("WITHDRAWAL_COLLERAL_LETTER");?></strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td width="16%"><?php echo $tr->translate("BRANCH ");?><?php echo $frm->getElement('id');?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("COLLTERAL_CODE")?></td>
							<td><?php echo $frm->getElement('cod_cal');?></td>
							<td width="16%"><?php echo $tr->translate("STAFF_NAME")?></td>
							<td><?php echo $frm->getElement('co_name');?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("CLIENT_NAME")?></td>
						    <td><?php echo $frm->getElement('borrower')?></td>
							<td><?php echo $tr->translate("	AND_NAME")?></td>
							<td><?php echo $frm->getElement('name')?></td>
							<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
							<td><?php echo $frm->getElement('names')?></td>
						</tr>
						<tr>
								<td><?php echo $tr->translate("OWNER_NAME")?></td>
								<td><?php echo $frm->getElement('owner')?></td>
								<td><?php echo $tr->translate("	AND_NAME")?></td>
								<td><?php echo $frm->getElement('and_name')?></td>
								<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
								<td><?php echo $frm->getElement('and_names')?></td>
							</tr>
						
							<tr>
								<td><?php echo $tr->translate("OWNER")?></td>
								<td><?php echo $frm->getElement('personal')?></td>
								<td><?php echo $tr->translate('COLLTERAL_TYPE')?></td>
								<td><?php echo $frm->getElement("collteral_type")?></td>
								<td><?php echo $tr->translate("CONTRACT_CODE")?></td>
								<td><?php echo $frm->getElement('contract_code');?></td>
								
							</tr>
							<tr>
								<td><?php echo $tr->translate("NOTE ")?></td>
								<td><?php echo $frm->getElement('note')?></td>
								<td><?php echo $tr->translate("DATE ")?></td>
								<td><?php echo $frm->getElement('date_estate')?></td>
								<td><?php echo $tr->translate("STATUS ")?></td>
								<td><?php echo $frm->getElement('Stutas')?></td>
							</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
