<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CLIENT_COLLTERAL"));
	$frm=$this->frm_callteral;
?>

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'Callteral','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table>
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('co_name');?></td>
			<td><?php echo $frm->getElement('collteral_type');?></td>
			<td><?php echo $frm->getElement('client_code');?></td>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
			
		</tr>
	</table>
	<?php echo $this->list;?>
</form>
