<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Staff Permistion"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'payroll','controller'=>'permission','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table border=1 width=100%>
		<tr>
			<td><?php  echo $frm->getElement('employee');?></td>
		   	<td><?php echo $frm->getElement("adv_search");?></td>
		   	<td><?php echo $frm->getElement('status');?></td>
		    <td><?php echo $frm->getElement("btn_search");?></td>
	   	</tr>
   </table>
   <?php echo $this->list;?>
</form>
