<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Staff Permistion"));
// $frm = $this->frm_search;
$frm = $this->frm_permistion;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'payroll','controller'=>'permission','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table width=100%>
		<tr>
			<td><?php echo $frm->getElement("adv_search");?></td>
			<td><?php  echo $frm->getElement('employee');?></td>
			<td><?php  echo $frm->getElement('branch_id');?></td>
			<td><?php  echo $frm->getElement('approve_by');?></td>
			<td><?php  echo $frm->getElement('type');?></td>
			<td><?php  echo $frm->getElement('from_date');?></td>
			<td><?php  echo $frm->getElement('to_date');?></td>
		   	<td><?php echo $frm->getElement('status_search');?></td>
		    <td><?php echo $frm->getElement("btn_search");?></td>
	   	</tr>
   </table>
   <?php echo $this->list;?>
</form>
