<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH')); 
?>
<?php  $frm_branch = $this->frm_branch;?>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'branch')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_BRANCH");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("ID")?></td>
										<td><?php echo $frm_branch->getElement("br_id");?></td>
										<td><?php echo $tr->translate("Name(Khmer)");?></td>
										<td><?php echo $frm_branch->getElement("branch_namekh");?></td>
										<td><?php echo $tr->translate("Name(English)");?></td>
										<td><?php echo $frm_branch->getElement("branch_nameen");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Branch Address")?></td>
										<td><?php echo $frm_branch->getElement("br_address");?></td>
										<td><?php echo $tr->translate("Tell");?></td>
										<td><?php echo $frm_branch->getElement("branch_tel");?></td>
                                        <td><?php echo $tr->translate("Branch code");?></td>
										<td><?php echo $frm_branch->getElement("branch_code");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Fax")?></td>
										<td><?php echo $frm_branch->getElement("_fax");?></td>
										<td><?php echo $tr->translate("Other")?></td>
										<td><?php echo $frm_branch->getElement("br_other");?></td>
										<td><?php echo $tr->translate("Status");?></td>
										<td><?php echo $frm_branch->getElement("br_status");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Display");?></td>
										<td><?php echo $frm_branch->getElement("branch_display");?></td>
										<td colspan="4"></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
										  <input type="reset" label="សំអាត" id="" dojoType="dijit.form.Button"
				                              iconClass="dijitIconClear" />
										  <input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" 
									          iconClass="dijitEditorIcon dijitEditorIconSave"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>