<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'capital','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form Add Capital</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td>Note</td>
							<td><?php echo $frm->getElement('note')?></td>
							<td></td>
							<td></td>
							<td></td>	
							<td></td>
						</tr>
						<tr>
							<td>សាខា</td>
							<td><?php echo $frm->getElement('brance')?></td>
							<td>Date</td>	
							<td><?php echo $frm->getElement('date')?></td>
							<td><?php echo $tr->translate("Stutas")?></td>
							<td><?php echo $frm->getElement('status')?></td>
						</tr>
						<tr>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil')?></td>
							
						</tr>
					</table>
				</fieldset>
				
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.DateTextBox");
</script>
