<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'chartaccount','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form Chart Account</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
						      <?php echo $frm->getElement('id');?>
							<td>លេខគនេយ្យ</td>
							<td><?php echo $frm->getElement('account_No')?></td>	
							<td>ឈ្មោះលេខគនេយ្យ</td>
							<td><?php echo $frm->getElement('account_Name')?></td>
							<td>ប្រភេទលេខគនេយ្យជាអង់គ្លេស</td>
							<td><?php echo $frm->getElement('account_Nameen')?></td>
						</tr>
						<tr>
						    ​​​​​​​<td>ប្រភេទលេខគនេយ្យ</td>
							<td><?php echo $frm->getElement('account_Type')?></td>
						    <td>ប្រតិបត្ដិការ</td>
							<td><?php echo $frm->getElement('none')?></td>
						    <td>ប្រភេទ</td>
							<td><?php echo $frm->getElement('category')?></td>	
						    
						</tr>
						<tr>
						    <td>ប្រភេទមេ</td>
							<td><?php echo $frm->getElement('parent')?></td>
						    <td>ប្រភេទមេ</td>
							<td><?php echo $frm->getElement('parents')?></td>
						</tr>
						
						<tr>
							<td>តុល្យភាព</td>
							<td><?php echo $frm->getElement('Balance')?></td>	
							<td>កាលបរិច្ឆេទ</td>
							<td><?php echo $frm->getElement('date')?></td>
							<td>ស្ថានភាព</td>
							<td><?php echo $frm->getElement('status')?></td>
						</tr>
						
					</table>
					
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
