<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;

?>
<title> <?php echo $tr->translate("COLLECTERALL_TYPE")?></title>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'Callecteralltype','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
      <?php echo $frm->getElement("btn_search");?>
      <?php echo $frm->getElement("adv_search");?>
      <?php echo $frm->getElement('status_search');?>
       <?php echo $this->list;?>
</form>
