 <input type="button" label="បញ្ជីទ្រព្យសកម្មថេរ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-fixed-asset')); ?>';"/>
  
  <input type="button" label="បញ្ជីទិញទ្រព្យសកម្មថេរ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-buy-fixed-asset')); ?>';"/>
  
  <input type="button" label="បញ្ជីលក់ទ្រព្យសកម្មថេរ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-sale-fixed-asset')); ?>';"/>
  
  <input type="button" label="បញ្ជីគណនីគំនូសតាង" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-chartaccount')); ?>';"/>
  
  <input type="button" label="បញ្ជីឈ្មោះគណនី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-account-name')); ?>';"/>
  
   <input type="button" label="បញ្ជីទិនានុប្បវត្តិ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-jurnal')); ?>';"/>
  
   <input type="button" label="សៀវភៅធំ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-leger')); ?>';"/>
  
  <input type="button" label="បញ្ជីតុល្យភាព" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance')); ?>';"/>
  
  <input type="button" label="បញ្ជីរបាយការណ៍ប្រាក់ចំណូល" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income-statement')); ?>';"/>
  
  <input type="button" label="បញ្ជីតារាងតុល្យការ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-balance-sheet')); ?>';"/>
  
  <input type="button" label="បញ្ជីម្ចាស់កម្មសិទ្ធ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-ower-equity')); ?>';"/>
  
  <input type="button" label="បញ្ជីលំហូរសាច់ប្រាក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-cashflow')); ?>';"/>
  
  <input type="button" label="របាយការណ៏បិទបញ្ជី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-closing')); ?>';"/>
  
  <input type="button" label="របាយការណ៏ប្រាក់ចំណូល" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-income')); ?>';"/>