<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Fixed asset</title>
</head>
<body>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div id="divPrint">
	<h2>Report Fixed Asset</h2>
	<table width="100%" border="1" style="border-collapse:collapse;" cellpadding="7">
    	<tr style="text-transform:uppercase;">
        	<th>ឈ្មោះទ្រព្យសកម្ម</th>
            <th>ប្រភេទ</th>
            <th>COST</th>
            <th>Useful life</th>
            <th>Salvage value</th>
            <th>Method</th>
            <th>Branch</th>
            <th>Date</th>
        </tr>
        <tr>
        	<td>ម៉ូតូ</td>
            <td>Short term</td>
            <td>1000$</td>
            <td>5year</td>
            <td>2000$</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
            <tr>
        	<td>Cash</td>
            <td>Long term</td>
            <td>100$</td>
            <td>1 year</td>
            <td>200</td>
            <td>Sum of the year</td>
            <td>Branch</td>
            <td>01.01.2014</td>
        </tr>
    </table>
</div>
</body>
</html>
