<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<div id="divPrint">
  <h2>Collection Sheet</h2>
  <p>05.12.2014-05.12.2014</p>
  <table style="border-collapse:collapse;" width="80%">
  
      <tr bgcolor="#666666">
         <td>Firstname</td>
         <td>Lastnamae</td>
         <td>Phonenumber</td>
         <td>District</td>
         <td>City</td>
         <td>Contractcode</td>
         <td>Loanofficer</td>
         <td>Activity</td>
         <td>Amount</td>
         <td>OLB </td>
         <td>interest</td>
         <td>Principal</td>
         <td>Total</td>
       </tr>
       <tr> 
          <td colspan="13">12/5/2014 </td>
       </tr>
       <tr height="30px"> 
          <td colspan="13" > </td>
       </tr>
       <tr>
         <td>peti</td>
         <td>smit</td>
         <td></td>
         <td>London District</td>
         <td>London</td>
         <td>LDH/01/02/03/12</td>
         <td>Admin</td>
         <td>Singer</td>
         <td>900.000</td>
         <td>900.00 </td>
         <td>27.00</td>
         <td>300.00</td>  
         <td>327.00</td>
        </tr>
         <tr bgcolor="#999999"> 
          <td colspan="8">Subtotalfor12/5/2014 </td>
          <td>900.00</td>
          <td>900.00</td>
          <td>27.00</td>
          <td>300.00</td>    
          <td>327.00</td>
       </tr>
       
         <tr bgcolor="#006699"> 
          <td colspan="8">TOTAL </td>
          <td>900.00</td>
          <td>900.00 </td>
          <td>27.00</td>
          <td>300.00</td>  
          <td>327.00</td>
       </tr>
     
  
      </table>
  </div>
</body>
</html>
