<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
	<h2 align="center">Rpt-CustomerPayment</h2>
	<table width="100%" border="1" style="border-collapse:collapse;" bordercolor="black">
    
    	<tr>
        	<td>N<sub>0</sub></td>
        	<td>Gross Profit</td>
            <td>Total amount</td>
        </tr>
        <tr align="left">
        	<td>1</td>
        	<td>Loanfee</td>
            <td>$5 000</td>
        </tr>
        <tr>
        	<td>2</td>
        	<td>Interest rate</td>
            <td>$1 000</td>
        </tr>
        <tr>
        	<td></td>
        	<td>Total</td>
            <td><b><u>$6 000</u></b></td>
        </tr>
        <tr >
            <td>N<sub>0</sub></td>
            <td>Exspend Name</td>
            <td>Total amount</td>
        </tr>
        <tr>
            <td>1</td>
            <td>staff</td>
            <td>$ 100</td>
       	</tr>
        <tr>
            <td>2</td>
            <td>Salary</td>
            <td>$ 500</td>
       	</tr>
        <tr>
            <td></td>
            <td>Total</td>
            <td><b><u>$600</u></b></td>
       	</tr>
        <tr>
            <th colspan="2">Net income</th>
            
            <th>$6600</td>
       	</tr>
    </table>
</body>
</html>