<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DISTRICT_LIST"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'District','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <?php echo $frm->getElement("btn_search");?>
   <?php echo $frm->getElement("adv_search");?>
   <?php echo $frm->getElement('status');?>
   <?php echo $this->list;?>
</form>
