<input type="button" label="បញ្ជីឈ្មោះអតិថិជន" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client')); ?>';"/>
  
<input type="button" label="ទ្រពបញ្ចំាអតិថិជន" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleterals')); ?>';"/>

<input type="button" label="ប្តូរទ្រព្យបញ្ចំា" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change')); ?>';"/>

<input type="button" label="បញ្ជីបង់រំលោះ" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>

<input type="button" label="បញ្ជីតំលៃបង់រំលោះ" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-value')); ?>';"/>