<input type="button" label="individul" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-individul')); ?>';"/>
  
<input type="button" label="Client Information" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client-information')); ?>';"/>

<input type="button" label="Client Agreement" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client-agreement')); ?>';"/>
 
<input type="button" label="Calleteral" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>