<input type="button" label="rpt-Client" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client')); ?>';"/>
  
<input type="button" label="rpt-Group" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-group')); ?>';"/>

<input type="button" label="rpt-Agreement" dojoType="dijit.form.Button" 
onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-agreement')); ?>';"/>
 
<input type="button" label="rpt-Calleteral" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral')); ?>';"/>
 <input type="button" label="rpt-Calleteral Value" dojoType="dijit.form.Button" 
 onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-value')); ?>';"/>