<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title></title>
</head>

<body>
	<h2 align="center">Report Client</h2><br/>
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB" >
        	<th>NUM</th>
            <th>Client N.</th>
            <th>Name Khmer</th>
            <th>Name Eng</th>
            <th>Sex</th>
            <th>Status</th>
            <th>Branch</th>
            <th colspan=4>Adress</th>
            <th>Spouse Name</th>
            <th>Phone</th>
          </tr>
          <?php foreach($this->client_list as $key =>$row){?>
		   <tr align="center">
		   <td><?php echo $key+1; ?></td>
	       <td><?php echo $row['client_number']?></td>
		   <td><?php echo $row['name_kh']?></td>
		   <td><?php echo $row['name_en']?></td>
		   <td><?php echo $row['sex']?></td>
		   <td><?php echo $row['status']?></td>
		   <td><?php echo $row['branch_name']?></td>
		   <td colspan=4><?php echo $row['pro_id'].$row['dis_id'].$row['com_id'].$row['village_id']?></td>
		   <td><?php echo$row['spouse_name']?></td>
		   <td><?php echo$row['phone']?></td>
		   </tr>
		  <?php }?>

    </table>
</body>
</html>