<?php $tran = $this->tran_schedule;
$client = $this->client;
?>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>

<div style=" width:29cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label>សុខាមីក្រូហិរញ្ញវត្ថុ</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'">បព្ជីទ្រពបញ្ចំា</h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					ផ្ទះលេខ ១៦២ ផ្លូវលេខ ១៥០ សង្កាត់ ទឹកល្អក់១ ទូលគោក ភ្នំពេញ
								<br />TEL :(855) 10 78 55 44
                				
		                </table>
		              </td>
		           </tr>   
            </table>
   
            

     <table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th>N<sup>0</sup></th>
            <th>សាខា </th>
            <th>លេខកូដបញ្ចាំ</th>
            <th>ឈ្មោះ CO</th>
            <th>ឈ្មោះអ្នកទទូល</th>
            <th>ឈ្មោះអ្នកប្រគល់</th>
            <th>ថ្ងៃប្រគល់</th>
            <th>លេខកូដអតិថិជន</th>
            <th>អ្នកខ្ចីប្រាក់ឈ្មោះ</th>
            <th>និងឈ្មោះ</th>
            <th>ត្រូវជា</th>
            <th>ម្ចាស់កម្មសិទ្ធិឈ្មោះ</th>
            <th>និងឈ្មោះ</th>
            <th>ត្រូវជា</th>
            <th>ប្រភេទទ្រពបញ្ចំា</th>
            <th>លេខសំគាល់</th>
            <th>ចុះថ្ងៃទី</th>
            
            </tr>
            <?php foreach($this->calleteral_list as $key =>$row){?>
			<tr>
		     <td>&nbsp;<?php echo $key+1;?></td>
		     <td>&nbsp;<?php echo $row['branch_id']?></td>
			 <td>&nbsp;<?php echo $row['code_call']?></td>
		     <td>&nbsp;<?php echo $row['co_id']?></td>
			 <td>&nbsp;<?php echo $row['getter_name']?></td>
			 <td>&nbsp;<?php echo $row['giver_name']?></td>
			 <td>&nbsp;<?php echo $row['date_delivery']?></td>
			 <td>&nbsp;<?php echo $row['client_code']?></td>
			 <td>&nbsp;<?php echo $row['contracts_borrow']?></td>
			 <td>&nbsp;<?php echo $row['with']?></td>
			 <td>&nbsp;<?php echo $row['relativewith']?></td>
			 <td>&nbsp;<?php echo $row['owner']?></td>
			 <td>&nbsp;<?php echo $row['withs']?></td>
			 <td>&nbsp;<?php echo $row['relativewiths']?></td>
			 <td>&nbsp;<?php echo $row['callate_type']?></td>
			 <td>&nbsp;<?php echo $row['note']?></td>
			 <td>&nbsp;<?php echo $row['date_registration']?></td>

			</tr>
			 <?php }?>
			 
		 <?php for($i=$key; $i<=8;$i++){?>
			<tr align="center">
			 <td><?php echo $i+1; ?></td>
		     <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 </tr>
		 <?php }?>
			 
      </table>
    </div>