<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form General jurnal</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td>សាខា</td>
							<td><?php echo $frm->getElement('brance')?></td>
							<td>Add_Date</td>
							<td><?php echo $frm->getElement('add_date')?></td>	
							<td>Account_Number</td>
							<td><?php echo $frm->getElement('account_number')?></td>
							
						</tr>
						<tr>
							<td>Account_name</td>
							<td><?php echo $frm->getElement('account_name')?></td>
							<td>Note</td>
							<td colspan="3"><?php echo $frm->getElement('note');?></td>
							
						</tr>
						<tr>
							
							<td>Debit</td>
							<td><?php echo $frm->getElement('debit')?></td>
							<td>Cradit</td>
							<td><?php echo $frm->getElement('credit');?></td>
							<td></td>
							<td></td>
						</tr>
						
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
