index
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL Payment"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'Client','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <?php //echo $frm->getElement("btn_search");?>
   <?php //echo $frm->getElement("adv_search");?>
   <?php //echo $frm->getElement('status');?>
   <?php //echo $this->list;?>
</form>
