<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_DISTRICT'));
?>	
<?php  $frm= $this->frm_district;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'District','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("EDIT_DISTRICT");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("DISTRICT_NAME_KHMER")?></td>
							<td><?php  echo $frm->getElement('district_namekh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISTRICT_NAME")?></td>
							<td><?php  echo $frm->getElement('district_name');?>
								<?php  echo $frm->getElement('id');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISPLAY_BY")?></td>
							<td><?php  echo $frm->getElement('display');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PROVINCE_NAME")?></td>
							<td><?php  echo $frm->getElement('province_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="reset" label="សំអាត" id="" dojoType="dijit.form.Button"
				                 iconClass="dijitIconClear" />
							<input type="submit" value="កែប្រែទិន្នន័យ" label="កែប្រែទិន្នន័យ" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass=""/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>