<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Open salary | Agent add page'); 
	echo $this->headTitle();
	$form = $this->frm;
?>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>

<form action="<?php echo $this->url(array('module'=>'payroll','controller'=>'salary','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន បើកប្រាក់ខែរ</strong></legend>
					<table width="100%" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $form->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("លេខកូដបុគ្គលិក")?></td>
							<td><?php echo $form->getElement('staff_code');?></td>
							<td><?php echo $tr->translate("ឈ្មោះបុគ្គលិក")?></td>
							<td><?php echo $form->getElement('staff_name');?></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("ភេទ")?></td>
							<td><?php echo $form->getElement('sex');?></td>
							<td><?php echo $tr->translate("ទួនាទី")?></td>
							<td><?php echo $form->getElement('position');?></td>
							<td><?php echo $tr->translate("ប្រាក់ខែគោល")?></td>
							<td><?php echo $form->getElement('basic_salary');?></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចូលធ្វើការ")?></td>
							<td><?php echo $form->getElement('date_start');?></td>
							<td><?php echo $tr->translate("ថ្ងៃបើកប្រាក់ខែ")?></td>
							<td><?php echo $form->getElement('date_get_salary');?></td>
							<td><?php echo $tr->translate("Status")?></td>
							<td><?php echo $form->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="6">
								<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
									 <table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
											<tr id="head_title" class="head-title" align="center"></tr>
									</table>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<input id="add-append"  label="បន្ថែម" dojoType="dijit.form.Button" iconClass="dijitIconApplication" Onclick="addAmountTypeMoney();" />
							</td>
						</tr>

					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>
<script type="text/javascript">
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.ready(function(){
	addAmountTypeMoney();		
	
});  
    
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
		
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
	
}
	curr_dollar_amountoption = '<?php echo "<option>testing</option>";?>';
	
	temp='';
	r = 0;
	fund_title=0;
	function addAmountTypeMoney(){
			r++;
			if(fund_title!=1){
				thead='<th>លុប</th>';
				thead+='<th>ប្តូពី</th>';
				thead+='<th>ប្រភេទ</th>';
				thead+='<th>អាត្រាប្តូប្រាក់</th>';
				thead+='<th>ចំនួនប្តូរ</th>';
				thead+='<th>ចំនួនទទួលបាន</th>';
				thead+='<th>សម្គាល់ </th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
	        }
			temp='<td style="width:30px !important;"><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			temp+='<td><input type="text" required="true"  name="date1_'+r+'" id="date1_'+r+'" dojoType="dijit.form.TextBox"/></td>';
			temp+='<td><select style=" width:70%;" id="currency_type1_'+r+'" name="currency_type1_'+r+'" dojoType="dijit.form.FilteringSelect"  >'+curr_dollar_amountoption+'</select></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="amount1_'+r+'" id="amount1_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="recieve1_'+r+'" id="recieve1_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="return1_'+r+'" id="return1_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" name="note1_'+r+'" id="note1_'+r+'" dojoType="dijit.form.TextBox" s/></td>';
			tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
			tmp+="</tr>";
			
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").value!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
	}	
	
//sub money
	sub_title=0;
	s=0;

</script>