<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Salary"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'payroll','controller'=>'salary','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table width=100%>
		<tr>
			<td><?php echo $frm->getElement("adv_search");?></td>
			<td><?php echo $frm->getElement('employee');?></td>
			<td><?php echo $frm->getElement('branch_id');?></td>
			<td><?php echo $frm->getElement('position');?></td>
		   	<td><?php echo $frm->getElement('status');?></td>
		    <td><?php echo $frm->getElement("btn_search");?></td>
	   	</tr>
   </table>
   <?php echo $this->list;?>
</form>
