<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_changeCollteral;
echo $this->headTitle($tr->translate("RETURN_COLLTERAL_INFO"));
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.collteral{
	color:blue;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'Returncollteral','action'=>'add')); ?>" 
dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
                    alert('Please Select Branch !');
                    dijit.byId('branch_id').focus();
                    return false;
                }
                if(dijit.byId('client_name').get('value')==''){
                    alert('Please Select Client Name !');
                    dijit.byId('client_name').focus();
                    return false;
                }
               if(dijit.byId('record_row').get('value')==''){
                    alert('Can not submit without record !');
                    return false;
                }
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("RETURN_COLLTERAL_INFO");?></strong></legend>
					<table cellspacing="10"  width="100%"> 
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="client_code" /><?php //echo $frm->getElement('client_code');?></td>
							<td ><?php echo $tr->translate("OWNER_NAME")?></td>
							<td><input id="client_name" /><?php //echo $frm->getElement('client_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("GIVER_NAME")?></td>
							<td><?php echo $frm->getElement('receiver_name')?></td>
							<td><?php echo $tr->translate("RECEIVER_NAME")?></td>
							<td><?php echo $frm->getElement('giver_name');?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('_note')?></td>
						</tr>
						<tr>
								<td><?php echo $tr->translate("DATE")?></td>
								<td><?php echo $frm->getElement('date')?></td>
								<td><?php echo $tr->translate("STATUS")?></td>
								<td><?php echo $frm->getElement('Stutas')?></td>
								<td><?php //echo $tr->translate("NOTE")?></td>
								<td><?php //echo $frm->getElement('note')?></td>
						</tr>
						<tr>
							<td colspan="6"><strong><?php echo $tr->translate("RETURN_COLLTERAL_INFO")?></strong></td>
						</tr>
						
					</table>
				</fieldset>
		</td>
	</tr>	
	<tr>
		<td align="center">
				<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
				<!--<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
							<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
				</table>-->
				<div  id="lbl_table"></div>	
		</td>
	<tr>		
	<tr>
		<td align="center">
				<input type="reset" value="សំអាត" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"/>
	            <input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate("SAVECLOSE")?>" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
				<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate("SAVENEW")?>" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
		</td>
	</tr>	
</table>
</form>
<?php 
	echo $this->frmpupopclient;
	echo $this->frmPopupCO;
?>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

require(["dojo/ready"], function(ready){
	 var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: true,		           
	name: "client_name",
	id: "client_name",
	searchAttr: "name",
	onChange: function() {
		getClientInfo(2);
    }
	}, "client_name");

	 var client_number = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->allclient_number));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            		           
	name: "client_code",
	id: "client_code",
	searchAttr: "name",
	onChange: function() {
		getClientInfo(1);
}
	}, "client_code");
	 
	});

temp='';

r = 0;
collect_option = '<?php echo $this->collect_option;?>';
owner_option = '<?php echo $this->owner_type;?>';

function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_name').query.branch_id = branch_id;
	dijit.byId('client_code').query.branch_id = branch_id;
	dijit.byId('client_code').reset();
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('client_code').get('value');
		dijit.byId('client_name').attr('value',customer_code);
		getClientCollateral();
	}else{
		customer_code= dijit.byId('client_name').get('value');
		dijit.byId('client_code').attr('value',customer_code);
	}
	client_name = dijit.byId('client_name').attr('displayedValue');
	dijit.byId('giver_name').attr('value',client_name);
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
}
	
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}

function popupCheckCO(){
	if(dijit.byId('co_name').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}

function checkClientCode(){
	client_name= dijit.byId('client_name').get('value');
	dijit.byId('client_code').attr('value',client_name);
}
fund_title=0;
var url_clientcall = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientcollateral')); ?>';
function getClientCollateral(){
		dojo.xhrPost({
	    url: url_clientcall,	
		content:{ 
			'client_id':dijit.byId('client_name').get('value')
			},		    
		handleAs:"json",
		load: function(data) {	
			if(data==''){
				alert('No collateral to return !');
			}
			dojo.query("#lbl_table").append('');
			tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
			tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
			tmp+='</table>';
			dojo.query("#lbl_table").append(tmp);
				thead='<th><?php echo $tr->translate("DEL");?></th>';
				thead+='<th><?php echo $tr->translate("COLETERAL_TYPE");?></th>';
				thead+='<th><?php echo $tr->translate("COLETERAL_TYPE");?></th>';
				thead+='<th><?php echo $tr->translate("OWNER_NAME");?></th>';
				thead+='<th><?php echo $tr->translate("NUMBER_COLLTERAL");?></th>';
				thead+='<th><?php echo $tr->translate("NOTE");?> </th>';
				dojo.query("#head_title").append(thead);
				dijit.byId('record_row').attr('value','');
				
			for(i=0;i<data.length;i++){
			r++;
				temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				temp+='<td><select style=" width:200px;background:#fff; padding-left:5px;" readonly="true" id="collect_type'+r+'" name="collect_type'+r+'" dojoType="dijit.form.FilteringSelect"  >'+collect_option+'</select></td>';
			    temp+='<td><select style=" width:200px; background:#fff; padding-left:5px;" readonly="true" id="owner_type'+r+'" name="owner_type'+r+'" dojoType="dijit.form.FilteringSelect" ">'+owner_option+'</select></td>';
				temp+='<td><input style=" width:200px" type="text" required="true"  readonly="true" name="owner_name'+r+'" id="owner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
				temp+='<td><input style=" width:200px" type="text" required="true" readonly="true" name="number_collteral'+r+'" id="number_collteral'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
				temp+='<td><input style=" width:200px" type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="coid'+r+'" dojoType="dijit.form.TextBox" /> </td>';

			
			tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
			tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").get('value')!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}
			
			dijit.byId('collect_type'+r).attr('value',data[i].collecteral_type);
			dijit.byId('owner_type'+r).attr('value',data[i].owner_type);
			dijit.byId('owner_name'+r).attr('value',data[i].owner_name);
			//dijit.byId('toowner_name'+r).attr('value',data[i].owner_name);
			
			dijit.byId('number_collteral'+r).attr('value',data[i].number_collecteral);
			dijit.byId('coid'+r).attr('value',data[i].id);
			
			setOwnerNameCollecteralById(r);
			
			}
		},
		error: function(err) {
		}
	});
}
function setOwnerNameCollecteralById(index){
	label='';
	owner_type = dijit.byId('toowner_type'+index).get('value');
	if(owner_type==1){
		label = dijit.byId('client_name').attr('displayedValue');
	}else{
		label = dijit.byId('owner').get('value');
	}
	dijit.byId('owner_name'+index).attr('value',label);
}
</script>
