<?php
	$this->headTitle('Add IL Payment'); 
	echo $this->headTitle();
	$frm = $this->frm_ilpayment;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$ilPayent = $this->ilPayent;
	$client_id = $this->client_id;
	$client_code = $this->client_code;
	$loan_number = $this->loan_number;
	//print_r($loan_number);
	$ilPaymentById = $this->ilPaymentById;
	$keycode = $this->keycode;
	$user_name = $this->user_name;
	$graiceperiod = $this->graiceperiod;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//print_r($ilPaymentById);
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_group_pay' action="<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
				service_charge = dijit.byId('service_charge').get('value');
				receive_amount = dijit.byId('amount_receive').get('value');
				option_pay = dijit.byId('option_pay').get('value');
				dijit.byId('total_payment').attr('value',total_amount);
				total_payments = dijit.byId('total_payment').get('value');
				if(option_pay==2 || option_pay==3 || option_pay==4){
					if(receive_amount<total_payments){
						alert('You Can not paymnet in this option! Please Input Recieve Amount more than or squar Total Paymnet!');
						dijit.byId('amount_receive').focus();
						return false;
					}
				}
				//if(option_pay==1){
 				//	if(receive_amount<service_charge){
				//		alert('Recieve Amount Can not less than Service charge!!');
				//		dijit.byId('amount_receive').focus();
				//		return false;
 				//	}
				//}
				if(receive_amount==""){
					alert('Please fill Recieve Amount');
					dijit.byId('amount_receive').focus();
					return false;
				}
			
			co_id = dijit.byId('co_id').get('value');
			client = dijit.byId('client_id').get('value');
           	branch_id = dijit.byId('branch_id').get('value');
		    if (branch_id=='' || branch_id==-1){
		  	   alert('Please Select Branch Name!');
			   dijit.byId('branch_id').focus();
			   return false;
		    }
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('client_id').focus();
				return false;
			}if(co_id=='' || co_id==-1){
				alert('Please Select CO Name !');
				dijit.byId('co_id').focus();
				return false;
			} 
		}else {
			return false;
		}
</script>
<?php echo $frm->getElement('id');?>
<style>
.center tr{text-align:left;}
</style>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php $tr->translate("IL_PAYMENT_INFO");?></strong></legend>
					<table class="center" cellspacing="10" >
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><?php echo $tr->translate("កម្រិតកម្ខី")?></td>
							<td><?php echo $frm->getElement('load_level');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("ស្គែន/បញ្ចូលលេខកូដកម្ចី")?></td>
							<td><?php echo $frm->getElement('loan_number');?></td>
							<td><?php echo $tr->translate("កាលបរិច្ឆេទខ្ចីប្រាក់")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះអតិថិជន")?></td>
							<td><?php //echo $frm->getElement('client_id');?> <input id="client_id"></td>
							<td><?php echo $tr->translate("លេខកូដអតិថិជន")?></td>
							<td><?php //echo $frm->getElement('client_code');?> <input id="client_code"></td>
							<td><?php echo $tr->translate("ឈ្មោះ មន្ត្រីឥណទាន")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ចំនួនប្រាក់ខ្ចីសរុប")?></td>
							<td><?php echo $frm->getElement('total_amount_loan');?></td>
							<td><?php echo $tr->translate("រយៈពេលខ្ចី")?></td>
							<td><?php echo $frm->getElement('loan_period');?></td>
							<td><?php echo $tr->translate("លក្ខខណ្ឌបង់ប្រាក់")?></td>
							<td><?php echo $frm->getElement('payment_term');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អត្រាការប្រាក់")?></td>
							<td><?php  echo $frm->getElement('interest_rate');?></td>
							<td><?php echo $tr->translate("វិធីសាស្រ្តបង់ប្រាក់")?></td>
							<td><?php  echo $frm->getElement('payment_method');?></td>
							<td><?php echo $tr->translate("ប្រភេទរូបិយបណ្ណ")?></td>
							<td><?php echo $frm->getElement('currency_type');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("AMOUNT BEFORE CACULATE")?></strong></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><?php echo $tr->translate("វិក័យបត្រ")?></td>
							<td><?php echo $frm->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រាក់ដើមនៅសល់")?></td>
							<td align="left"><?php echo $frm->getElement('priciple_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ដើមត្រូវសង")?></td>
							<td><?php echo $frm->getElement('os_amount');?></td>
							<td><?php echo $tr->translate("ការប្រាក់ត្រូវសង")?></td>
							<td><?php echo $frm->getElement('total_interest');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រភេទបង់ប្រាក់")?></td>
							<td><?php  echo $frm->getElement('option_pay');?></td>
							<td><?php echo $tr->translate("បង់ថ្លៃសេវា")?></td>
							<td><?php echo $frm->getElement('service_charge');echo $frm->getElement('old_service_charge');?></td>
							<td><?php echo $tr->translate("ប្រាក់ផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('penalize_amount');?><?php echo $frm->getElement('old_penelize');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃទទួលប្រាក់"); //echo $tr->translate("ថ្ងៃប្រមូលប្រាក់");//echo $tr->translate("ថ្ងៃបង់ជាក់ស្តែង")?></td>
							<td><?php echo $frm->getElement('collect_date');//echo $frm->getElement('using_date');?></td>
							<td><?php echo $tr->translate("ប្រាក់ត្រូវបង់សរុប")?></td>
							<td><?php echo $frm->getElement('total_payment');?><input type="hidden" dojoType="dijit.form.TextBox" name="oldTotalPay" id="oldTotalPay" /></td>
							<td><?php echo $tr->translate("ប្រាក់ទទួលបាន")?></td>
							<td><?php echo $frm->getElement('amount_receive');?></td>
							
						</tr>
						<tr>
							<td><?php //echo $tr->translate("ថ្ងៃទទួលប្រាក់"); //echo $tr->translate("ថ្ងៃប្រមូលប្រាក់")?></td>
							<td><?php echo $frm->getElement('date_input'); //echo $frm->getElement('collect_date');?></td>
							<td><?php echo $tr->translate("ប្រាក់អាប់")?></td>
							<td><?php  echo $frm->getElement('amount_return');?></td>
							<td><?php echo $tr->translate("ប្រាក់នៅសល់")?></td>
							<td><?php echo $frm->getElement('remain');?></td>
						</tr>
						<tr>
							<td><?php //echo $tr->translate("ថ្ងៃទទួលប្រាក់");?></td>
							<td><?php echo $frm->getElement('last_payment_date'); ?></td>
							<td><?php echo $frm->getElement('installment_date');?></td>
							<td><?php echo $frm->getElement('amount_payment_term');?></td>
							<td><?php echo $tr->translate("កំណត់សម្គាល់")?></td>
							<td><?php echo $frm->getElement('note');?></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
			<td align="center">
			   <input type="button" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave" OnClick="submitNew();"/>
			   <input type="button" value="រក្សាទុក & បិទ" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="submit_close" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave" OnClick="submitClose();"/>
			   <input type="button" value="រក្សាទុក & បោះពុម្ព" label="<?php echo $tr->translate('SAVEPRINT');?>" id="saveprint" dojoType="dijit.form.Button" 
			   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="showReciept();"/>
			   
<!-- 			   <input type="submit" name="cancel" value="cancel" label="<?php //echo $tr->translate('CANCEL');?>" id="cancelButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconDelete" /> -->
			</td>
		</tr>
		<tr>
			<td>
				<div id="mainTabContainer" style=" max-width:1135px;height: 394px;" dojoType="dijit.layout.TabContainer" region="center"  >
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="ការវិភាគបង់ប្រាក់" selected="true">
								 <div id='data_table' name='data_table'></div>
								<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
										<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
								</table>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane"  title="ប្រវត្តិនៃការបង់ប្រាក់" selected="false">
							 <div id='data_table1' name='data_table1'></div>
								<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
									<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
								</table>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane"  title="ប្រវត្តិនៃការបង់ប្រាក់លម្អិត" selected="false">
							 <div id='data_table_loan_haspay' name='data_table_loan_haspay'></div>
						</div>
				 </div>
		 </td>
	</tr>		
</table>

<input type="hidden" dojoType="dijit.form.TextBox" name="identity" id="identity">
<input type="hidden" dojoType="dijit.form.TextBox" name="record_id" id="record_id">
<input type="hidden" dojoType="dijit.form.TextBox" name="curr" id="curr">
<?php  echo $frm->getElement('reciever');?>
</form>
<div class="dijitHidden">
	
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បោះពុម្ភ វិក័យបត្រ', onCancel:hideDialog" id="frm_client" style="width:800px">
	<div id="rpt_print" class="print">
	<style type="text/css">
		td.border {
			border-bottom: 1px dashed cadetblue;
		}
		div #rpt_print{font-size:12px !important; margin:0 auto;}
		 
		 .fontsize{ font-size:10px !important; margin:0 auto;}
	</style>
		<table cellspacing="10" class='fullside fontsize'>
				   <tr>
					   	<td align="center" colspan="6">	
					   <table  width="100%" cellspacing="0" cellpadding="0">
					   		<tr style="line-height:10px;">
					   			<td width="25%" rowspan="2" style="valign:top;"><img style="margin-top: 1px;" src="<?php echo $base_url;?>images/logobrand.jpg" height="60px;"/></td>
						   		<td align="right"><strong style="font-family:'KH Koulen';white-space: nowrap;font-size:11px;font-weight:bold; text-align:center;"><?php echo $this->keycode['il_payment_title'];?></strong></td>
							</tr>
					   	</table>
			            </td>	   	        
				   </tr> 
				   <tr>
					   	<td align="center" colspan="6" style="font-family:'KH Koulen';font-size:13px; border-bottom:1px solid #000"><?php echo $this->keycode['il_payment'];?></td>	   	        
					</tr> 
				   <tr>
					    <td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>កាលបរិច្ឆេទ :</td>
						<td align="left" style="font-size: 8pt;" >
							 <?php echo date('d-m-Y H:i:s');?><br/>
						</td>
				   </tr>
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>ឈ្មោះបុគ្គលិក :</td>
					<td class="border">
						<strong class="fonttel" style="font-size:12px;"><label id="lblinvioice"><?php print($this->user_name);?></label></strong>
					</td>
			</tr>
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>លេខវិក័យបត្រ :</td>
					<td class="border">
								<strong class="fonttel" style="font-size:12px;"><label style="color:blue" id="lbl_reciept_no"></label></strong>
					</td>
					
			</tr>
			<tr class="fontsize">
					<td>ឈ្មោះអតិថិជន :</td>
					<td class="border"><lable id="lbl_group_member"></lable></td>
					<td>លេខកូដអតិថិជន :</td>
					<td class="border"><lable id="lbl_group_code"></lable></td>
					<td>លេខកូដកម្ចី :</td>
					<td class="border"><lable id="lbl_laon_nomber"></lable></td>
					
			</tr>
			<tr class="fontsize">
					<td class="fontsize">សាខា :</td>
					<td class="border"><lable id="lbl_branch_id"></lable></td>
					<td>ឈ្មោះ CO :</td>
					<td class="border"><lable id="lbl_co_id"></lable></td>
					<td></td>
					<td></td>
					
			</tr>
			<tr class="fontsize">
					<td>ប្រាក់ដើមនៅសល់ :</td>
					<td class="border"><lable id="lbl_priciple_amount"></lable></td>
					<td>ប្រាក់ដើមត្រូវសង :</td>
					<td class="border"><lable id="lbl_os_amount"></lable></td>
					<td>អាត្រាការប្រាក់ :</td>
					<td class="border"><lable id="lbl_total_interest"></lable></td>
			</tr>
			<tr class="fontsize">
					<td>ប្រាក់ផាកពិន័យ :</td>
					<td class="border"><lable style="color:red" id="lbl_penalize_amount"></lable></td>
					<td>ប្រាក់ត្រូវបង់សរុប :</td>
					<td class="border"><lable id="lbl_total_payment"></lable></td>
					<td>បង់ថ្លៃសេវា :</td>
					<td class="border"><lable id="lbl_service_charge"></lable></td>
					
			</tr>
			<tr class="fontsize">
					<td>ថ្ងៃទទួលប្រាក់ :</td>
					<td class="border"><lable id="lbl_collect_date"></lable></td>
					<td>ប្រាក់ទទួលបាន :</td>
					<td class="border"><lable style="color:red" id="lbl_amount_receive"></lable></td>
					<td>ប្រាក់អាប់ :</td>
					<td class="border"><lable style="color:red" id="lbl_amount_return"></lable></td>
			</tr>
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>កំណត់សម្គាល់ :</td>
					<td class="border"><lable id="lbl_note"></lable></td>
			</tr>
			<tr class="fontsize" style="margin-top:20px;line-height: 60px">
					<td></td>
					<td></td>
					<td colspan="2" align="center">ហត្ថលេខា អ្នកទទួល </td>
					<td colspan="2" align="center">ហត្ថលេខាអ្នក បង់ប្រាក់ </td>
			</tr>
			<tr class="fontsize" style="margin-top:20px;line-height: 20px">
					<td></td>
					<td></td>
					<td colspan="2" align="center">.............................. </td>
					<td colspan="2" align="center">.............................. </td>
			</tr>
		</table>
		</div>
		<input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" 
				   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="print();"/>
	</div>
</div>
<iframe name=print_frame width='0' height='0' frameborder='0' src=about:blank></iframe>

<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
var graice_period = <?php echo $graiceperiod["value"] ?>;
function submitNew(){
	dijit.byId("frm_add_group_pay").submit();
}

function submitClose(){
	dijit.byId("frm_add_group_pay").submit();
	window.location.href ="<?php echo $this->baseUrl();?>/loan/il-payment";
}
function showReciept(){
	var client_id = dijit.byId('client_id').get('value');
	if(client_id==""){
		alert("No Result To Show! Please Choose Client and Try again");
	}else{
		var client_name = dijit.byId('client_id').attr('displayedValue');
		var arrays = client_name.split(',');
		
		for(var i=0;i<1;i++){
			document.getElementById('lbl_group_member').innerHTML = arrays[0];
		}
		document.getElementById('lbl_reciept_no').innerHTML = dijit.byId('reciept_no').attr('displayedValue');
		document.getElementById('lbl_group_code').innerHTML = dijit.byId('client_code').attr('displayedValue');
		document.getElementById('lbl_laon_nomber').innerHTML = dijit.byId('loan_number').attr('displayedValue');
		document.getElementById('lbl_branch_id').innerHTML = dijit.byId('branch_id').attr('displayedValue');
		document.getElementById('lbl_co_id').innerHTML = dijit.byId('co_id').attr('displayedValue');
		document.getElementById('lbl_collect_date').innerHTML = dijit.byId('collect_date').attr('displayedValue');
		document.getElementById('lbl_priciple_amount').innerHTML = dijit.byId('priciple_amount').attr('displayedValue');
		document.getElementById('lbl_os_amount').innerHTML = dijit.byId('os_amount').attr('displayedValue');
		document.getElementById('lbl_total_interest').innerHTML = dijit.byId('total_interest').attr('displayedValue');
	 	document.getElementById('lbl_penalize_amount').innerHTML = dijit.byId('penalize_amount').attr('displayedValue');
	 	document.getElementById('lbl_total_payment').innerHTML = dijit.byId('total_payment').attr('displayedValue');
	 	document.getElementById('lbl_note').innerHTML = dijit.byId('note').attr('displayedValue');
	 	document.getElementById('lbl_service_charge').innerHTML = dijit.byId('service_charge').attr('displayedValue');
	 	document.getElementById('lbl_amount_receive').innerHTML = dijit.byId('amount_receive').attr('displayedValue');
	 	document.getElementById('lbl_amount_return').innerHTML = dijit.byId('amount_return').attr('displayedValue');
		dijit.byId('frm_client').show();
		//submitData();
	}
}

dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

dojo.ready(function(){	
	var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->client));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "<?php echo $this->branch_id;?>"
	},            
	required: false,		           
	name: "client_id",
	id: "client_id",
	searchAttr: "name",
	value: "<?php echo $this->client_id;?>",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
//			   getLaonPayment(3);
//			   getAllLaonPayment(3);
	   }
}
	}, "client_id");

	var clientCode_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->clientCode));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: clientCode_data}),
	autoComplete: true,
	query: {
		branch_id: "<?php echo $this->branch_id;?>"
	},            
	required: false,		           
	name: "client_code",
	id: "client_code",
	searchAttr: "name",
	value: "<?php echo $this->client_id;?>",
	class: 'fullside',
	onChange: function() {
		if(not_submit==0){
//			   getLaonPayment(2);
//			   getAllLaonPayment(2);
	   }
	}
	}, "client_code");
	not_submit = 0;
	document = dojo.byId("loan_number");
	dojo.connect(document, "onkeyup", function(event) {
		key_number = (event.keyCode);
		if(key_number==13){
			not_submit = 1;
			//getLaonPayment(1);
			getAllLaonPayment(1);
			//getLastPayDate();
			getLaonHasPayByLoanNumber();
		}
	});

	
});
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_id').query.branch_id = branch_id;
	dijit.byId('client_code').query.branch_id = branch_id;
	//alert(dijit.byId('branch_id').get('value'));
	dijit.byId('client_id').reset();
	dijit.byId('client_code').reset();
}
    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
	function print(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	function hideDialog() {		
		dijit.byId("frm_client").hide();
		//submitData()
		window.location.href ="<?php echo $this->baseUrl();?>/loan/il-payment";
	}

	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('frm_client').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
function submitData(){
	//var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'IlPayment','action'=>'edit')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
			},
			error: function(e) {
				//alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			//alert(err);
		//alert("Your message could not be sent, please try again!.");
				        
		}
	});
}

function payOption(){
	var ids =dijit.byId('record_id').get('value');
	var arrays = ids.split(',');
	for(var i=0;i<arrays.length;i++){
    	for(var i=0;i<arrays.length;i++) {
 			trRow(arrays[i]);
    	}
	}
}
function trRow(x){
	pay_option = dijit.byId('option_pay').get('value');
	if(pay_option==1){
		dijit.byId('identity').attr('value',1);
		if(x==1){
			document.getElementById('tr_'+x).style.background='none';
			$('#mfdid_'+x).attr('checked',true);
			$('#mfdid_'+x).attr('onclick',"return true", 'onkeydown',"return true");
		}else{
			document.getElementById('tr_'+x).style.background='#eee';
			$('#mfdid_'+x).attr('checked',false);
			$('#mfdid_'+x).attr('onclick',"return false", 'onkeydown',"return false");
		}
	}else if(pay_option==4){
			$('#mfdid_'+x).attr('onclick',"return false", 'onkeydown',"return false");
			document.getElementById('tr_'+x).style.background='#eee';
			$('#mfdid_'+x).attr('checked',true);
	}else{
		document.getElementById('tr_'+x).style.background='none';
		$('#mfdid_'+x).attr('onclick',"return true", 'onkeydown',"return true");
		if(x==1){
			$('#mfdid_'+x).attr('checked',true);
		}else{
			$('#mfdid_'+x).attr('checked',false);
		}
	}
	//calculateTotal();
}
dojo.ready(function(){
	getAllLaonPayment(1);
	getLoanPaymentbyId();
	//getLastPayDate();
	getLaonHasPayByLoanNumber();
	dijit.byId('currency_type').attr('readOnly','readOnly');
	dijit.byId("option_pay").getOptions("4").disabled = true;
	$("#option_pay option[value='4']").attr("disabled","disabled");
});
function getLoanPaymentbyId(){
	var total_pay = <?php echo $ilPaymentById["total_payment"];?>;
	var recieve_amount =<?php echo $ilPaymentById["recieve_amount"];?>;
	var return_amount = <?php echo $ilPaymentById["return_amount"];?>;
	
	//alert(total_pay);
	
	dijit.byId('old_penelize').attr('value','<?php echo $ilPaymentById["penalize_amount"];?>');
	dijit.byId('old_service_charge').attr('value','<?php echo $ilPaymentById["service_charge"];?>');
	$('#installment_date').val('<?php echo $ilPaymentById["last_paydate"];?>');
	dijit.byId('interest_rate').attr('value','<?php echo $ilPaymentById["interest_rate"];?>');
	dijit.byId('branch_id').attr('value','<?php echo $ilPaymentById["branch_id"];?>');
	dijit.byId('loan_number').attr('value','<?php echo $ilPaymentById["loan_numbers"];?>');
	dijit.byId('priciple_amount').attr('value','<?php echo number_format($ilPaymentById["principal_amount"],2);?>');
	dijit.byId('os_amount').attr('value','<?php echo number_format($ilPaymentById["total_principal_permonth"],2);?>');
	dijit.byId('total_payment').attr('value','<?php echo number_format($ilPaymentById["total_payment"],2);?>');
	dijit.byId('amount_receive').attr('value',parseFloat(recieve_amount));
	dijit.byId('total_interest').attr('value','<?php echo number_format($ilPaymentById["total_interest"],2);?>');
	dijit.byId('amount_return').attr('value',parseFloat(return_amount));
	dijit.byId('currency_type').attr('value','<?php echo $ilPaymentById["currency_type"];?>');
	dijit.byId('oldTotalPay').attr('value','<?php echo $ilPaymentById["total_payment"]-$ilPaymentById["penalize_amount"]-$ilPaymentById["service_charge"];?>');
	dijit.byId('option_pay').attr('value','<?php echo $ilPaymentById["payment_option"];?>');
	dijit.byId('payment_term').attr('value','<?php echo $ilPaymentById["collect_typeterm"];?>');
	dijit.byId('amount_payment_term').attr('value','<?php echo $ilPaymentById["amount_term"];?>');
	dijit.byId('collect_date').attr('value','<?php echo $ilPaymentById["date_input"];?>');
	dijit.byId('penalize_amount').attr('value','<?php echo number_format($ilPaymentById["penalize_amount"],2);?>');
	dijit.byId('service_charge').attr('value','<?php echo number_format($ilPaymentById["service_charge"],2);?>');
	dijit.byId('load_level').attr('value','<?php echo $ilPaymentById["level"];?>');
	dijit.byId('release_date').attr('value','<?php echo $ilPaymentById["date_release"];?>');
	dijit.byId('total_amount_loan').attr('value','<?php echo $ilPaymentById["total_capital"];?>');
	dijit.byId('loan_period').attr('value','<?php echo $ilPaymentById["total_duration"];?>');
	dijit.byId('payment_method').attr('value','<?php echo $ilPaymentById["payment_method"];?>');
	dijit.byId('co_id').attr('value','<?php echo $ilPaymentById["co_id"];?>');
	dijit.byId('note').attr('value','<?php echo $ilPaymentById["note"];?>');
	dijit.byId('reciept_no').attr('value','<?php echo $ilPaymentById["receipt_no"];?>');
	getPayment();
	doTotalBypene();
	doTotalByServ();
}
function getPayment(){
	try{
	status='<label style="color:red;">នៅឡើយ</lable>';
	tem='';	//is_set=0;
	tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
		+'<thead><tr><th class="tdheader">ល.រ</th>'
		+'<th class="tdheader"><input type="checkbox" OnChange="checkAll();" name="check_all" id="check_all" checked="checked" /></th>'
		+'<th class="tdheader">កូដអតិថិជន</th>'
		+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
		+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
		+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
		+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
		+'<th class="tdheader">ប្រាក់ការ</th>'
		+'<th class="tdheader">ប្រាក់ផាកពិន័យ</th>'
		+'<th class="tdheader">ប្រាក់សេវាកម្ម</th>'
		+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
		+'<th class="tdheader">មេគុណផាកពិន័យ</th>'
		+'<th class="tdheader">ស្ថានភាព</th>'
		+'<th class="tdheader">កំណត់សម្គាល់</th></tr>'
	+'</thead>';
	num=0;
	total_payment=0;
	totalos_amount=0;
	total_interest=0;
	<?php if(!empty($ilPayent)) {
		foreach($ilPayent AS $i=>$r){
			$inx = $i+1;
	?>
	is_set =0;
	if(is_set==0){
		dijit.byId('reciever').attr('value',<?php echo $r["receiver_id"]?>);
		is_set=1;
	}
	d = new Date(<?php echo $r["date_payment"];?>);
	str_day = getDayString(d.getDay());
	curr =getCurrencyType(<?php echo $r["currency_type"]?>);
	
	tem+= '<tr id=tr_'+<?php echo $inx;?>+'>';
    tem += '<td>'+<?php echo $inx;?>+'<input type="hidden" name="curr" id="curr" value="<?php echo $r['currency_id']?>" /></td>';
    tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+<?php echo $inx;?>+'" id="mfdid_'+<?php echo $inx;?>+'" value="'+<?php echo $r["lfd_id"];?>+'" OnChange="calculateTotal('+<?php echo $inx;?>+')" Checked="checked"/></td>';
    tem += '<td>&nbsp;<?php echo $r["client_number"];?>&nbsp;<input type="hidden" name="client_id_'+<?php echo $inx;?>+'" id="client_id_'+<?php echo $inx;?>+'" value="'+<?php echo $r["client_id"];?>+'" /></td>';
    tem += '<td>&nbsp;<?php echo $r["name_kh"];?>&nbsp;</td>';
    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
    tem += '<td style="white-space: nowrap;">&nbsp;<?php echo $r["date_payment"];?><input type="hidden" name ="date_payment_'+<?php echo $inx;?>+'" id ="date_payment_'+<?php echo $inx;?>+'" value ="<?php echo $r["date_payment"];?>"/><input type="hidden" name="last_date_payment_'+<?php echo $inx;?>+'" id="last_date_payment_'+<?php echo $inx;?>+'" value="<?php echo $r["last_pay_date"];?>" /></td>';
    tem += '<td>&nbsp;'+<?php echo $r["capital"];?>+' '+curr+'&nbsp;<input type="hidden" name="total_priciple_'+<?php echo $inx;?>+'" id="total_priciple_'+<?php echo $inx;?>+'" value="'+<?php echo $r["capital"];?>+'" /></td>';
    tem += '<td>&nbsp;'+<?php echo $r["principal_permonth"];?>+' '+curr+'&nbsp;<input type="hidden" name="principal_permonth_'+<?php echo $inx;?>+'" id="principal_permonth_'+<?php echo $inx;?>+'" value="'+<?php echo $r["principal_permonth"];?>+'" /></td>';
    tem += '<td>&nbsp;'+<?php echo $r["total_interest"];?>+' '+curr+'&nbsp;<input type="hidden" name="interest_'+<?php echo $inx;?>+'" id="interest_'+<?php echo $inx;?>+'" value="'+<?php echo $r["total_interest"];?>+'" /></td>';
    tem += '<td>&nbsp;<label id="lb_penelize_'+<?php echo $inx;?>+'">'+<?php echo $r["penelize_amount"];?>+' '+curr+'</label>&nbsp;<input type="hidden" name="penelize_'+<?php echo $inx;?>+'" id="penelize_'+<?php echo $inx;?>+'" value="'+<?php echo $r["penelize_amount"];?>+'" /><input type="hidden" name="old_penelize_'+<?php echo $inx;?>+'" id="old_penelize_'+<?php echo $inx;?>+'" value="'+<?php echo $r["penelize_amount"];?>+'" /></td>';
    tem += '<td>&nbsp;'+<?php echo $r["service_charge"];?>+' '+curr+'&nbsp;<input type="hidden" name="service_'+<?php echo $inx;?>+'" id="service_'+<?php echo $inx;?>+'" value="'+<?php echo $r["service_charge"];?>+'" /></td>';
    tem += '<td>&nbsp;<label id="payment_'+<?php echo $inx;?>+'">'+<?php echo $r["total_payment"];?>+' '+curr+'</label>&nbsp;<input type="hidden" name="payment_'+<?php echo $inx;?>+'" id="payment_'+<?php echo $inx;?>+'" value="'+<?php echo $r["total_payment"];?>+'" /></td>';
    tem += '<td>&nbsp;<?php echo $r["pay_after"];?><input type="hidden" name="multiplier_'+<?php echo $inx;?>+'" id="multiplier_'+<?php echo $inx;?>+'" value="<?php echo $r["pay_after"];?>" /></td>';
    
    if(<?php echo $r["is_completed"];?> == 1){
		status = '<label style="color:blue;">បង់រួច</label>';
		if(<?php echo $r["is_completed"];?>==1){is_appr='<label style="color:blue;">Approved</label>';}
	}else{
		status='<label style="color:red;">នៅឡើយ</lable>';
		is_appr='';
	}
	tem += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
	tem += '<td>&nbsp;<label style="font-size:10px;">'+is_appr+'</label></td>';
    tem += '</tr>';
    if(<?php echo $inx;?>!=1) {
			var identity = dijit.byId('record_id').get('value');
			dijit.byId('identity').attr('value',identity+','+<?php echo $inx;?>);
			dijit.byId('record_id').attr('value',identity+','+<?php echo $inx;?>);
		} else {
			dijit.byId('identity').attr('value',<?php echo $inx;?>);
			dijit.byId('record_id').attr('value',<?php echo $inx;?>);
		}
    <?php }?>
    tem+='</table>';
	dojo.byId('data_table').innerHTML = tem;
	//calculateTotal();
    <?php }?>
	}catch(e){
		//alert(e);
	}
}

function getLaonPayment(type){
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('client_id').get('value');
	}
	var clientId = dijit.byId('client_id').get('value');
	var clientCode = dijit.byId('client_code').get('value');
	var loanNumbers = dijit.byId('loan_number').get('value');
	var client_id = '<?php echo $client_id?>';
	var client_code = '<?php echo $client_code?>';
	var loan_numbers = '<?php echo $loan_number?>'; 
	if(type==3 && client_id == clientId){
		getLoanPaymentbyId();
		dijit.byId('client_code').attr('value',clientId);
		dijit.byId('loan_number').attr('value',loan_number);
	}else if(type==2 && client_code == clientCode){
		getLoanPaymentbyId();
		dijit.byId('client_id').attr('value',clientCode);
		dijit.byId('loan_number').attr('value',loan_number);
	}else if(type==1 && loan_numbers==loan_number){
		getLoanPaymentbyId();
		dijit.byId('client_id').attr('value',client_id);
		dijit.byId('client_code').attr('value',client_code);
	}else{
		getLoanById(type);
		getAllLaonPayment(type);
	}
}

function getAllLaonPayment(types){
	if(types==1){
		var loan_numbers = dijit.byId('loan_number').get('value');
	}else if(types==2){
		var loan_numbers = dijit.byId('client_code').get('value');
	}else if(types==3){
		var loan_numbers = dijit.byId('client_id').get('value');
	}
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'get-all-il-loan-Detail')); ?>';
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_numbers':loan_numbers,
			    'types':types,
			},	
			handleAs:"json",
			load: function(data) {
				status='<label style="color:red;">នៅឡើយ</lable>';
				temp='';	//is_sets=0;
				temp='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader">ល.រ</th>'
					+'<th class="tdheader">កូដអតិថិជន</th>'
					+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
					+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
					+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
					+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
					+'<th class="tdheader">ប្រាក់ការ</th>'
					+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
					+'<th class="tdheader">មេគុណផាកពិន័យ</th>'
					+'<th class="tdheader">ស្ថានភាព</th>'
				+'</thead>';
				nums=0;
				if(data!=""){
					for(j=0;j<data.length;j++){
						status='<label style="color:red;">នៅឡើយ</lable>';
						++nums;
						d = new Date(data[j].date_payment);
						str_day = getDayString(d.getDay());
						curr =getCurrencyType(data[j].currency_type);
						 temp+= '<tr>';
						 temp += '<td>&nbsp;'+nums+'</td>';
						 temp += '<td>&nbsp;'+data[j].client_number+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+data[j].name_kh+'&nbsp;</td>';
						 temp += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
						 temp += '<td style="white-space: nowrap;">&nbsp;'+data[j].date_payment+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+dojo.number.format(data[j].total_principal)+' '+curr+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+dojo.number.format(data[j].principal_permonth)+' '+curr+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+dojo.number.format(data[j].total_interest)+' '+curr+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+dojo.number.format(data[j].total_payment)+' '+curr+'&nbsp;</td>';
						 temp += '<td>&nbsp;'+data[j].pay_after+'&nbsp;</td>';
							if(data[j].is_completed==1){
								status = '<label style="color:blue;">បង់រួច</label>';
								if(data[j].is_approved==1){is_appr='<label style="color:blue;">Approved</label>';}
							}else{
								is_appr='';
							}
						temp += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
						temp += '</tr>';
					}
				}
				temp+='</table>';
				dojo.byId('data_table1').innerHTML = temp;
			},
			error: function(e) {
				//alert(e);
			}
		});
}
function getLoanById(type){
	tem='';	is_set=0;num=0;
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('client_id').get('value');
	}

	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'get-il-loan-Detail')); ?>';
	dojo.xhrPost({
	    url: url_submit,
	    content : { 
		    'loan_number':loan_number,
		    'type':type,
		},	
		handleAs:"json",
		load: function(respone) {
			tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
				+'<thead><tr><th class="tdheader">ល.រ</th>'
				+'<th class="tdheader"><input type="checkbox" OnChange="checkAll();" name="check_all" id="check_all" /></th>'
				+'<th class="tdheader">កូដអតិថិជន</th>'
				+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
				+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
				+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
				+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
				+'<th class="tdheader">ប្រាក់ការ</th>'
				+'<th class="tdheader">ប្រាក់ផាកពិន័យ</th>'
				+'<th class="tdheader">ប្រាក់សេវាកម្ម</th>'
				+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
				+'<th class="tdheader">មេគុណផាកពិន័យ</th>'
				+'<th class="tdheader">ស្ថានភាព</th>'
				+'<th class="tdheader">កំណត់សម្គាល់</th></tr>'
			+'</thead>';
			if(respone!=""){
				num=0;
				for(i=0;i<respone.length;i++){
					inx = i+1;
					num++;
					date = new Date(respone[i].date_payment);
					str_day = getDayString(date.getDay());
					curr =getCurrencyType(respone[i].currency_type);
					client_id = respone[i].client_id;
					total_principal = respone[i].total_principal;
					principal_permonth = respone[i].principle_after;
					interest = respone[i].total_interest_after;
					payment = respone[i].total_payment_after;
					multiplier = respone[i].pay_after;
					pay_before = respone[i].pay_before;
					date_pay = respone[i].date_payments;
					id = respone[i].id;
					pay_option = dijit.byId('option_pay').get('value');
						if(pay_option==1){
							if(inx==1){
								tem+= '<tr id=tr_'+inx+' style="background-color:none">';
								tem += '<td>&nbsp;'+num+'</td>';
								tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" checked="checked"/></td>';
							}else{
								tem+= '<tr id=tr_'+inx+' style="background-color:#eee">';
								tem += '<td>&nbsp;'+num+'</td>';
								tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" onclick="return false" onkeydown="return false" /></td>';
							}
						}else{
							if(inx==1){
								tem+= '<tr id=tr_'+inx+' style="background-color:none">';
								tem += '<td>&nbsp;'+num+'</td>';
								tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" checked="checked"/></td>';
							}else{
								tem+= '<tr id=tr_'+inx+' style="background-color:none">';
								tem += '<td>&nbsp;'+num+'</td>';
								tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" /></td>';
							}
						}
					    tem += '<td>&nbsp;'+respone[i].client_number+'&nbsp;<input type="hidden" name="client_id_'+inx+'" id="client_id_'+inx+'" value="'+client_id+'" /></td>';
					    tem += '<td>&nbsp;'+respone[i].name_kh+'&nbsp;</td>';
					    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
					    tem += '<td style="white-space: nowrap;">&nbsp;'+date_pay+'&nbsp;<input type="hidden" name="date_payment_'+inx+'" id="date_payment_'+inx+'" value="'+respone[i].date_payment+'" /><input type="hidden" name="last_date_payment_'+inx+'" id="last_date_payment_'+inx+'" value="'+respone[i].last_pay_date+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_principal)+' '+curr+'&nbsp;<input type="hidden" name="total_priciple_'+inx+'" id="total_priciple_'+inx+'" value="'+total_principal+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].principle_after)+' '+curr+'&nbsp;<input type="hidden" name="principal_permonth_'+inx+'" id="principal_permonth_'+inx+'" value="'+principal_permonth+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_interest_after)+' '+curr+'&nbsp;<input type="hidden" name="interest_'+inx+'" id="interest_'+inx+'" value="'+interest+'" /></td>';
					    tem += '<td>&nbsp;<label id="lb_penelize_'+inx+'">'+dojo.number.format(respone[i].penelize)+' '+curr+'</label>&nbsp;<input type="hidden" name="penelize_'+inx+'" id="penelize_'+inx+'" value="'+respone[i].penelize+'" /><input type="hidden" name="old_penelize_'+inx+'" id="old_penelize_'+inx+'" value="'+respone[i].penelize+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].service_charge)+' '+curr+'&nbsp;<input type="hidden" name="service_'+inx+'" id="service_'+inx+'" value="'+respone[i].service_charge+'" /></td>';
					    tem += '<td>&nbsp;<label id="lb_payment_'+inx+'">'+dojo.number.format(respone[i].total_payment_after)+' '+curr+'</label>&nbsp;<input type="hidden" name="payment_'+inx+'" id="payment_'+inx+'" value="'+payment+'" /></td>';
					    tem += '<td>&nbsp;'+respone[i].pay_after+'&nbsp;<input type="hidden" name="multiplier_'+inx+'" id="multiplier_'+inx+'" value="'+multiplier+'" /></td>';
						if(respone[i].is_completed==1){
							status = '<label style="color:blue;">បង់រួច</label>';
							if(respone[i].is_approved==1){is_appr='<label style="color:blue;">Approved</label>';}
						}else{
							status='<label style="color:red;">នៅឡើយ</lable>';
							if(is_set!=1){
								getdataPaymentToForm(respone[i]);
								$('#installment_date').val(respone[i].last_pay_date);
								is_set=1;
							}
							is_appr='';
						}
						tem += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
						tem += '<td>&nbsp;<label style="font-size:10px;">'+is_appr+'</label></td>';
					    tem += '</tr>';
					    dijit.byId('identity').attr('value',1);
 					    if(inx!=1) {
 							var identity = dijit.byId('record_id').get('value');
 							dijit.byId('record_id').attr('value',identity+','+inx);
 						} else {
 							dijit.byId('record_id').attr('value',inx);
 						}
				}
			}else{
				var clientId = dijit.byId('client_id').get('value');
				var clientCode = dijit.byId('client_code').get('value');
				var loanNumber = dijit.byId('loan_number').get('value');
				if(type==1){
					dijit.byId('client_id').attr('value','');
					dijit.byId('client_code').attr('value','');
				}else if(type==2){
					dijit.byId('loan_number').attr('value','');
					dijit.byId('client_id').attr('value',clientCode);
				}else{
					dijit.byId('loan_number').attr('value','');
					dijit.byId('client_code').attr('value',clientId);
				}
				alert("No Result!");
				dijit.byId('identity').attr('value',"");
				dijit.byId('priciple_amount').attr('value',0);
				dijit.byId('os_amount').attr('value',0);
				dijit.byId('total_payment').attr('value',0);
				dijit.byId('amount_receive').attr('value',0);
				dijit.byId('discount').attr('value',0);
				dijit.byId('service_charge').attr('value',0);
				dijit.byId('penalize_amount').attr('value',0);
				dijit.byId('total_interest').attr('value',"");
				dijit.byId('amount_return').attr('value',0);
				dijit.byId('payment_term').attr('value',"");
				dijit.byId('currency_type').attr('value',"");
			}
			tem+='</table>';
			dojo.byId('data_table').innerHTML = tem;
			calculateTotal();
			doTotalByServ();
			totalReturn();
		},
		error: function(e) {
			//alert(e);
		}
	});
}

function getLaonHasPayByLoanNumber(){
	try{
		var loan_number = dijit.byId('loan_number').get('value');
		var url_submits = '<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'get-loan-has-pay-by-loan-number')); ?>';
			dojo.xhrPost({
			    url: url_submits,
			    content : { 
				    'loan_number':loan_number,
				},	
				handleAs:"json",
				load: function(data_loan) {
					tmp='';	
					tmp='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
						+'<thead><tr><th class="tdheader">ល.រ</th>'
						+'<th class="tdheader">លេខវិក័យបត្ត្រ</th>'
						+'<th class="tdheader">កូដអតិថិជន</th>'
						+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
						+'<th class="tdheader" >ថ្ងៃត្រូវបង់ប្រាក់</th>'
						+'<th class="tdheader" >ថ្ងៃបង់ប្រាក់</th>'
						+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
						+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
						+'<th class="tdheader">ប្រាក់ការត្រូវសង</th>'
						+'<th class="tdheader">ថ្លៃសេវា</th>'
						+'<th class="tdheader">ប្រាក់ផាកពិន័យ</th>'
						+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
						+'<th class="tdheader">ប្រាក់បានបង់</th>'
					+'</thead>';
					num1s=0;
					
					if(data_loan!=""){
						for(k=0;k<data_loan.length;k++){
							++num1s;
							var is_apprs="";
							date_pay = new Date(data_loan[k].date_payment);
							str_day_pay = getDayString(date_pay.getDay());
							date_get = new Date(data_loan[k].date_input);
							str_day_get = getDayString(date_get.getDay());
							currs =getCurrencyType(data_loan[k].currency_type);
							tmp+= '<tr>';
								tmp += '<td>&nbsp;'+num1s+'</td>';
								tmp += '<td>&nbsp;'+data_loan[k].receipt_no+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+data_loan[k].client_code+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+data_loan[k].client_name+'&nbsp;</td>';
								tmp += '<td style="white-space: nowrap;">&nbsp;'+data_loan[k].date_payment+'&nbsp;</td>';
								tmp += '<td style="white-space: nowrap;">&nbsp;'+data_loan[k].date_input+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].capital)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].total_principal_permonth)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].total_interest)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].service_charge)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].penalize_amount)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].total_payment)+' '+currs+'&nbsp;</td>';
								tmp += '<td>&nbsp;'+dojo.number.format(data_loan[k].recieve_amount)+' '+currs+'&nbsp;</td>';
								tmp += '</tr>';
						}
					}
					tmp+='</table>';
					dojo.byId('data_table_loan_haspay').innerHTML = tmp;
				},
				error: function(e) {
					//alert(e);
				}
			});
	}catch(err){
		//alert(err);
	}
}
function popupCheckCO(){
}
function calculateTotal(index){
	//alert(1);
	dijit.byId('old_service_charge').attr('value',0);
	dijit.byId('service_charge').attr('value',0);
	try{
		var total_payment = 0;
		var os_amount = 0;
		var total_interest = 0;
		var priciple_amount = 0;
		var total_interest_late = 0;
		var after_discount = 0;
		var totalAmount = 0;
		var payOption = dijit.byId('option_pay').get('value');
		var payment_term = dijit.byId('payment_term').get('value');
		var interest_rate = dijit.byId('interest_rate').get('value');
		var date_collect = dijit.byId('collect_date').get('value');
		var amount_collect_term = dijit.byId('amount_payment_term').get('value');
		var old_installment_date = $('#installment_date').val();
		var installment_date= new Date(old_installment_date); 

		if(payOption==4){
			var ids =dijit.byId('record_id').get('value');
  	  		dijit.byId('identity').attr('value',ids);
		}else{
			var ids =dijit.byId('identity').get('value');
		}
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {//calculate record row
			if(arrays[i] == index) arrays.splice(i,1);
			if($('#mfdid_'+index).attr('checked')){
				if(dijit.byId("identity").get('value')!="") {
					dijit.byId("identity").attr('value',ids+','+index);
				}else { 
					dijit.byId("identity").attr('value',index);
				}
			 }else{
				var strings = arrays.join(',');
				dijit.byId('identity').attr('value',strings);
			}
		}
		if(payOption==4){
			var ids =dijit.byId('record_id').get('value');
  	  		dijit.byId('identity').attr('value',ids);
		}else{
			var ids =dijit.byId('identity').get('value');
		}
		
	   var arrays = ids.split(',');
	   graice_period = '<?php echo $graiceperiod["value"]?>';
	   
		if(arrays!=""){
			for(var i=0;i<arrays.length;i++) {
				last_payment_date=0;
				var oneDay = 24*60*60*1000;
				if($('#mfdid_'+arrays[i]).attr('checked')){
					var ps = $('#multiplier_'+arrays[i]).val();
					
		          	var os_amount = os_amount+parseFloat($('#principal_permonth_'+arrays[i]).val());
		          	var priciple_amount = parseFloat($('#total_priciple_'+arrays[i]).val()) - parseFloat($('#principal_permonth_'+arrays[i]).val());
		          	var total_interest = total_interest+parseFloat($('#interest_'+arrays[i]).val());
		          	var totalPayment = parseFloat($('#payment_'+arrays[i]).val());
		          	var principlePerMonth = $('#principal_permonth_'+arrays[i]).val();
		          	var interest = parseFloat($('#interest_'+arrays[i]).val());
		          	var penelize = parseFloat($('#penelize_'+arrays[i]).val());
		          	var service_charge = parseFloat($('#service_'+arrays[i]).val());
		          	
		          	last_payment_date= $('#last_date_payment_'+arrays[i]).val();
		          	//alert(principlePerMonth);
		          	if(last_payment_date=="null" || last_payment_date==null || last_payment_date=="" ){
						pay_date= new Date($('#date_payment_'+arrays[i]).val());
					}else{
						pay_date = new Date(last_payment_date);
					}
					var late_day = Math.round((date_collect - pay_date)/(oneDay));
					if(late_day>0){
						if(last_payment_date=="null" || last_payment_date==null || last_payment_date==""){
							total_late_day = late_day - graice_period;
						}else{
							total_late_day = late_day;
						}
					}else{
						total_late_day = late_day;
					}
						totalPay =  parseFloat(principlePerMonth) + parseFloat(interest);
						
					if(total_late_day>0){
						if(payment_term==1){
							total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/1)*parseFloat(total_late_day);
							totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
						}
						if(payment_term==2){
							total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/7)*parseFloat(total_late_day);
							totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
						}
						if(payment_term==3){
							total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/30)*parseFloat(total_late_day);
							totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
						}
					}else if(total_late_day==0){
						total_interest_late = total_interest_late +0;
						totalAmount = totalAmount + parseFloat(totalPay)+penelize+service_charge;
					}else{
						dijit.byId('option_pay').attr('readOnly',false);
						if(payment_term==1){
			  	  	  			if(payOption==1){
			  	  	  				total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==2){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==3){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				total_interest = 0;
			  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==4){
				  	  	  			total_interest_late = total_interest_late + 0;
					  	  	  		total_interest = 0;
						  	  	  	priciple_amount = 0;
					  	  	  		os_amounts=0;
						  	  	  	installment_date=old_installment_date==""?new Date($('#old_release_date').val()):installment_date;
						  	  	  	practical_date  = Math.round((date_collect - installment_date)/(oneDay));
						  	  	  	
							  	  	var ids =dijit.byId('record_id').get('value');
								  	  var arraysn = ids.split(',');
								  	  for(var j=0;j<arraysn.length;j++){
						  	  	  			principlePerMonth = $('#principal_permonth_'+arraysn[j]).val();
						  	  	  			os_amounts = parseFloat(os_amounts) + parseFloat(principlePerMonth);
						  	  	  		}
									 total_interest = ((os_amounts*interest_rate/100)/30)*practical_date;
						  	  		totalAmount = os_amounts+total_interest+penelize+service_charge+total_interest_late;
					  	  	  		}
		  	  			}else if(payment_term==2){
				  				dijit.byId('option_pay').attr('readOnly',false);
			  	  	  			if(payOption==1){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==2){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==3){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				total_interest = 0;
			  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==4){
				  	  	  			total_interest_late = total_interest_late + 0;
					  	  	  		total_interest = 0;
						  	  	  	priciple_amount = 0;
					  	  	  		os_amounts=0;
						  	  	  	installment_date=old_installment_date==""?new Date($('#old_release_date').val()):installment_date;
						  	  	  	practical_date  = Math.round((date_collect - installment_date)/(oneDay));
						  	  	  	
							  	  	var ids =dijit.byId('record_id').get('value');
								  	  var arraysn = ids.split(',');
								  	  for(var j=0;j<arraysn.length;j++){
						  	  	  			principlePerMonth = $('#principal_permonth_'+arraysn[j]).val();
						  	  	  			os_amounts = parseFloat(os_amounts) + parseFloat(principlePerMonth);
						  	  	  		}
									 total_interest = ((os_amounts*interest_rate/100)/30)*practical_date;
						  	  		totalAmount = os_amounts+total_interest+penelize+service_charge+total_interest_late;
			  	  	  			}
		  	  			}else if(payment_term==3){
				  				if(payOption==1){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==2){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==3){
				  	  	  			total_interest_late = total_interest_late + 0;
			  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
			  	  	  			}else if(payOption==4){
				  	  	  			total_interest_late = total_interest_late + 0;
					  	  	  		total_interest = 0;
						  	  	  	priciple_amount = 0;
					  	  	  		os_amounts=0;
						  	  	  	installment_date=old_installment_date==""?new Date($('#old_release_date').val()):installment_date;
						  	  	  	practical_date  = Math.round((date_collect - installment_date)/(oneDay));
						  	  	  	
							  	  	var ids =dijit.byId('record_id').get('value');
								  	  var arraysn = ids.split(',');
								  	  for(var j=0;j<arraysn.length;j++){
						  	  	  			principlePerMonth = $('#principal_permonth_'+arraysn[j]).val();
						  	  	  			os_amounts = parseFloat(os_amounts) + parseFloat(principlePerMonth);
						  	  	  		}
									 total_interest = ((os_amounts*interest_rate/100)/30)*practical_date;
						  	  		totalAmount = os_amounts+total_interest+penelize+service_charge+total_interest_late;
			  	  	  			}
		  	  			}
					}
				}
			  }
			}else{
				totalAmount=0;
				total_interest_late=0;
				os_amount=0;
				total_interest=0;
				priciple_amount=0;
			}
		dijit.byId('oldTotalPay').attr('value',totalAmount.toFixed(2));
		dijit.byId('amount_receive').attr('value',totalAmount.toFixed(2));
		dijit.byId('amount_return').attr('value',0);
		dijit.byId('penalize_amount').attr('value',total_interest_late.toFixed(2));
		dijit.byId('old_penelize').attr('value',total_interest_late.toFixed(2));
		dijit.byId('total_payment').attr('value',totalAmount.toFixed(2));
		dijit.byId('os_amount').attr('value',os_amount.toFixed(2));
		dijit.byId('total_interest').attr('value',total_interest.toFixed(2));
		dijit.byId('priciple_amount').attr('value',priciple_amount.toFixed(2));
		var identity = dijit.byId('identity').get('value');
		var recored = dijit.byId('record_id').get('value');
		if(identity==recored){
			$('#check_all').attr('checked');
		}

		//totalReturn();
	}catch(err){
		//alert(err);
	}
}
function checkAll(index){
	//alert("check"+1);
	var total_payment = 0;
	var os_amount = 0;
	var total_interest = 0;
	var priciple_amount = 0;
	var total_interest_late = 0;
	var after_discount = 0;
	var totalAmount = 0;
	var payOption = dijit.byId('option_pay').get('value');
	var payment_term = dijit.byId('payment_term').get('value');
	var interest_rate = dijit.byId('interest_rate').get('value');
	var date_collect = dijit.byId('collect_date').get('value');
	var amount_collect_term = dijit.byId('amount_payment_term').get('value');
	var old_installment_date = $('#installment_date').val();
	var installment_date= new Date(old_installment_date); 
	if($('#check_all').attr('checked')){
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = true;  
		});
		var ids =dijit.byId('record_id').get('value');
		dijit.byId('identity').attr('value',ids);
    	var arrays = ids.split(',');
    	graice_period = '<?php echo $graiceperiod["value"]?>';
    	if(arrays!=""){
    		for(var i=0;i<arrays.length;i++) {
    			last_payment_date=0;
    			var oneDay = 24*60*60*1000;
    			if($('#mfdid_'+arrays[i]).attr('checked')){
    				//getLastPaymentDate(arrays[i]);
    				var ps = $('#multiplier_'+arrays[i]).val();
    	          	var os_amount = os_amount+parseFloat($('#principal_permonth_'+arrays[i]).val());
    	          	var priciple_amount = parseFloat($('#total_priciple_'+arrays[i]).val()) - parseFloat($('#principal_permonth_'+arrays[i]).val());
    	          	var total_interest = total_interest+parseFloat($('#interest_'+arrays[i]).val());
    	          	var totalPayment = parseFloat($('#payment_'+arrays[i]).val());
    	          	var principlePerMonth = $('#principal_permonth_'+arrays[i]).val();
    	          	var interest = parseFloat($('#interest_'+arrays[i]).val());
    	          	var penelize = parseFloat($('#penelize_'+arrays[i]).val());
    	          	var service_charge = parseFloat($('#service_'+arrays[i]).val());
    	          	
    	          	last_payment_date= $('#last_date_payment_'+arrays[i]).val();
    	          	
    	          	pay_date=last_payment_date=="null"?new Date($('#date_payment_'+arrays[i]).val()):new Date(last_payment_date);
    	          	//alert(pay_date);
    				var late_day = Math.round((date_collect - pay_date)/(oneDay));
    				if(late_day>0){
    					if(last_payment_date!="null"){
    						total_late_day = late_day;
    					}else{
    						total_late_day = late_day - graice_period;
    					}
    				}else{
    					total_late_day = late_day;
    				}
    					totalPay =  parseFloat(principlePerMonth) + parseFloat(interest);
    				if(total_late_day>0){
    					dijit.byId('option_pay').attr('value',1);
    					dijit.byId('option_pay').attr('readOnly',true);
    					if(payment_term==1){
    						total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/1)*parseFloat(total_late_day);
    						totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    					}
    					if(payment_term==2){
    						total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/7)*parseFloat(total_late_day);
    						//totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late);
    						totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    					}
    					if(payment_term==3){
    						total_interest_late = total_interest_late + parseFloat(totalPay)*(parseFloat(ps*(interest_rate/100))/30)*parseFloat(total_late_day);
    						//totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late);
    						totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    					}
    				}else if(total_late_day==0){
    					dijit.byId('option_pay').attr('value',1);
    					dijit.byId('option_pay').attr('readOnly',true);
    					
    					total_interest_late = total_interest_late +0;
    					totalAmount = totalAmount + parseFloat(totalPay)+penelize+service_charge;
    				}else{
    					dijit.byId('option_pay').attr('readOnly',false);
    					if(payment_term==1){
    		  	  	  			if(payOption==1){
    		  	  	  				total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==2){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==3){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				total_interest = 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==4){
    			  	  	  			var ids =dijit.byId('record_id').get('value');
    				  	  	  		dijit.byId('identity').attr('value',ids);
    				  	  	  		var arrays = ids.split(',');
    				  	  	  		for(var i=0;i<arrays.length;i++){
    					  	  	  		os_amount=0;
    				  	  	  			var ids =dijit.byId('record_id').get('value');
    					  	  	  		dijit.byId('identity').attr('value',ids);
    					  	  	  		var arrays = ids.split(',');
    					  	  	  		for(var i=0;i<arrays.length;i++){
    					  	  	  			priciple_amount = 0;
    					  	  	  			principlePerMonth = $('#principal_permonth_'+arrays[i]).val();
    					  	  	  			os_amount = parseFloat(os_amount) + parseFloat(principlePerMonth);
    					  	  	  		}
    						  	  	  	installment_date=old_installment_date==""?new Date($('#release_date').val()):installment_date;
    					  	  	  		practical_date  = Math.round((date_collect - installment_date)/(oneDay));
    						  	  	  	total_interest = ((os_amount*(interest_rate/100)/1))*practical_date;
    						  	  		totalAmount = os_amount+total_interest+penelize+service_charge;
    				  	  	  		}
    		  	  	  			}
    	  	  			}else if(payment_term==2){
    			  				dijit.byId('option_pay').attr('readOnly',false);
    		  	  	  			if(payOption==1){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==2){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==3){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				total_interest = 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==4){
    			  	  	  			os_amount=0;
    			  	  	  			var ids =dijit.byId('record_id').get('value');
    				  	  	  		dijit.byId('identity').attr('value',ids);
    				  	  	  		var arrays = ids.split(',');
    				  	  	  		for(var i=0;i<arrays.length;i++){
    					  	  	  		installment_date=old_installment_date==""?new Date($('#release_date').val()):installment_date;
    				  	  	  			priciple_amount = 0;
    				  	  	  			principlePerMonth = $('#principal_permonth_'+arrays[i]).val();
    				  	  	  			os_amount = parseFloat(os_amount) + parseFloat(principlePerMonth);
    				  	  	  			document.getElementById('tr_'+arrays[i]).style.background='#eee';
    				  	  	  		}
    				  	  	  		practical_date  = Math.round((date_collect - installment_date)/(oneDay));
    					  	  	  	total_interest = ((os_amount*interest_rate/100)/7)*practical_date;
    					  	  		totalAmount = os_amount+total_interest+penelize+service_charge;
    		  	  	  			}
    	  	  			}else if(payment_term==3){
    			  				dijit.byId('option_pay').attr('readOnly',false);
    			  				if(payOption==1){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==2){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(totalPay)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==3){
    			  	  	  			total_interest_late = total_interest_late + 0;
    		  	  	  				total_interest = 0;
    		  	  	  				totalAmount = totalAmount + parseFloat(principlePerMonth)+parseFloat(total_interest_late)+penelize+service_charge;
    		  	  	  			}else if(payOption==4){
    		  	  	  				os_amount=0;
    			  	  	  			var ids =dijit.byId('record_id').get('value');
    				  	  	  		dijit.byId('identity').attr('value',ids);
    				  	  	  		var arrays = ids.split(',');
    				  	  	  		for(var j=0;j<arrays.length;j++){
    					  	  	  		installment_date=old_installment_date==""?new Date($('#release_date').val()):installment_date;
    					  	  	  	
    				  	  	  			priciple_amount = 0;
    				  	  	  			principlePerMonth = $('#principal_permonth_'+arrays[j]).val();
    				  	  	  			os_amount = parseFloat(os_amount) + parseFloat(principlePerMonth);
    				  	  	  			practical_date  = Math.round((date_collect - installment_date)/(oneDay));
    				  	  	  		}
    					  	  	  	total_interest = ((os_amount*interest_rate/100)/30)*practical_date;
    					  	  		totalAmount = os_amount+total_interest+penelize+service_charge;
    		  	  	  			}
    	  	  			}
    				}
    			}
    		  }
    		}
		
    	dijit.byId('oldTotalPay').attr('value',totalAmount);
    	dijit.byId('amount_receive').attr('value',totalAmount);
    	dijit.byId('amount_return').attr('value',0);
    	dijit.byId('penalize_amount').attr('value',total_interest_late);
    	dijit.byId('total_payment').attr('value',totalAmount);
    	dijit.byId('os_amount').attr('value',os_amount);
    	dijit.byId('total_interest').attr('value',total_interest);
    	dijit.byId('priciple_amount').attr('value',priciple_amount);
	}else{
		dijit.byId('identity').attr('value','');
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = false;//deselect all checkboxes with class "checkbox1" 
            this.disabled=false; 
        });
		dijit.byId('penalize_amount').attr('value',0);
        dijit.byId('total_payment').attr('value',0);
		dijit.byId('total_payment').attr('value',0);
		dijit.byId('os_amount').attr('value',0);
		dijit.byId('total_interest').attr('value',0);
		dijit.byId('priciple_amount').attr('value',0);
		dijit.byId('amount_receive').attr('value',0);
	}
}
function getDayString(num){
	var days= ["ច័ន្ទ", "អង្គារ", "ពុធ", "ព្រហ","សុក្រ","សៅរ៏","អាទិត្យ"];
	return days[num];
}
function getCurrencyType(type){
	var option=["៛","$","B"];
	return option[type-1];
}

function doTotalBypene(type){
	var old_recieveAmount = '<?php echo number_format($ilPaymentById["recieve_amount"],2);?>';
	var loan_numbers = '<?php echo $loan_number?>'; 
	var loanNumber = dijit.byId('loan_number').get('value'); 
		old_penelize = dijit.byId('old_penelize').get('value');
		penelize = dijit.byId('penalize_amount').get('value');
		old_total_pay = dijit.byId('total_payment').get('value');
		penelize = penelize==""?0:penelize;
		service_charge = dijit.byId('service_charge').get('value');
		total_pay = parseFloat(old_total_pay - old_penelize)+parseFloat(penelize);
		dijit.byId('total_payment').attr('value',total_pay.toFixed(2));
		
		if(loan_numbers==loanNumber){
			dijit.byId('amount_receive').attr('value',old_recieveAmount);
		}else{
			dijit.byId('amount_receive').attr('value',total_pay.toFixed(2));
		}
		dijit.byId('old_penelize').attr('value',penelize.toFixed(2));
}
function doTotalByServ(type){
	var old_recieveAmount = '<?php echo number_format($ilPaymentById["recieve_amount"],2);?>';
	var loan_numbers = '<?php echo $loan_number?>'; 
	var loanNumber = dijit.byId('loan_number').get('value'); 
		old_service_charge = dijit.byId('old_service_charge').get('value');
		service_charge = dijit.byId('service_charge').get('value');
		old_total_pay = dijit.byId('total_payment').get('value');
		service_charge = service_charge==""?0:service_charge;
		penelize = dijit.byId('penalize_amount').get('value');
		total_pay = parseFloat(old_total_pay - old_service_charge)+parseFloat(service_charge);
		dijit.byId('total_payment').attr('value',total_pay.toFixed(2));
		if(loan_numbers==loanNumber){
			dijit.byId('amount_receive').attr('value',old_recieveAmount);
		}else{
			dijit.byId('amount_receive').attr('value',total_pay.toFixed(2));
		}
		dijit.byId('old_service_charge').attr('value',service_charge.toFixed(2));
}

function getdataPaymentToForm(data){//use
	is_change = 1;
	dijit.byId('loan_number').attr('value',data.loan_number);
	dijit.byId('branch_id').attr('value',data.branch_id);
	dijit.byId('client_id').attr('value',data.client_id);
	dijit.byId('client_code').attr('value',data.client_id);
	dijit.byId('co_id').attr('value',data.co_id);
	dijit.byId('interest_rate').attr('value',data.interest_rate);
	dijit.byId('payment_term').attr('value',data.collect_typeterm);
	dijit.byId('currency_type').attr('value',data.currency_type);
	dijit.byId('reciever').attr('value',data.collect_by);
	dijit.byId('amount_payment_term').attr('value',data.amount_collect_principal);
	dijit.byId('release_date').attr('value',data.date_release);
	dijit.byId('load_level').attr('value',data.level);
	dijit.byId('total_amount_loan').attr('value',data.total_capital);
	dijit.byId('loan_period').attr('value',data.total_duration);
	dijit.byId('payment_method').attr('value',data.payment_method);
	dijit.byId('load_level').attr('value',data.level);
	var today = new Date();
	dijit.byId('collect_date').attr('value',today);
	totalReturn();
}
function totalReturn(){
	service_charge = dijit.byId('service_charge').get('value');
	receive_amount = dijit.byId('amount_receive').get('value');
	total_payment = dijit.byId('oldTotalPay').get('value');
	option_pay = dijit.byId('option_pay').get('value');
	service_charge=isNaN(service_charge)?0:service_charge;
	total_amount = parseFloat(service_charge) + parseFloat(total_payment);
	total_payments = dijit.byId('total_payment').get('value');
	amonut_return = parseFloat(receive_amount)-parseFloat(total_payments);
	remain_amount = parseFloat(total_payments)-parseFloat(receive_amount);
	if(amonut_return<0){
		dijit.byId('amount_return').attr('value',0);
	}else{
		dijit.byId('amount_return').attr('value',amonut_return.toFixed(2));
	}
	if(remain_amount>0){
		dijit.byId('remain').attr('value',remain_amount.toFixed(2));
	}else{
		dijit.byId('remain').attr('value',0);
	}
}
</script>
