<style>
	img{ padding:15px;}
</style>
<script language="javascript">

</script>
<title>Show Barcodes</title>
<div class="right">
			<div id="print_content">
					<table style="width:850px; margin:0 auto;" cellspacing="0">
						<tr>
							<td align="center"><br />
								<?php //foreach ($this->pro_id as $v) {?>
									<?php $url = $this->url(array("module"=>"loan","controller"=>"IlPayment","action"=>"generate-barcode"),null,true);?>												<?php $url = $this->url(array("module"=>"loan","controller"=>"IlPayment","action"=>"generate-barcode","id"=>2),null,true);?>
												<img src="<?php echo $url;?>" />
								<?php //}?>
							</td>
						</tr>
					</table>
		</div><!-- print content -->
		</div>
	</div>
</div>
