<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
 <?php 
   $rows=$this->list;
//    print_r($rows);
 ?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("CLIENT INFO");?>Client Info</title>
</head>

<body>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div id="divPrint">
	<h2 align="center">កន្លែងបង់ប្រាក់</h2>
	
	<table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB">
        	<th><?php echo $tr->translate("NUM");?></th>
        	<th><?php echo $tr->translate("TERM");?></th>
            <th><?php echo $tr->translate("LOAN_NO");?></th>
            <th><?php echo $tr->translate("DATE_DUE");?></th>
            <th><?php echo $tr->translate("OS");?></th>
            <th><?php echo $tr->translate("PRINCIPAL");?></th>
            <th><?php echo $tr->translate("INTEREST");?></th>
            <th><?php echo $tr->translate("PAID_PRINCIPAL");?></th>
            <th><?php echo $tr->translate("PAID_INTEREST_RATE");?></th>
            <th><?php echo $tr->translate("CO");?></th>
            <th><?php echo $tr->translate("BY");?></th>
            <th><?php echo $tr->translate("STATUS");?></th>
        </tr>
  
    </table>
 </div> 
</body>
</html>