<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'callecterall','controller'=>'Callecteralllist','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Callecterall Type</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
						        <?php echo $frm->getElement('id');?>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo$frm ->getElement('branch')?></td>
							<td><?php echo $tr->translate("លេខវិក័យបត្រ")?></td>
						​	<td><?php echo $frm->getElement('receipt')?></td>
						    <td><?php echo $tr->translate("លេខកូដបពាំ្ច")?></td>
							<td><?php echo $frm->getElement('code_call')?></td>		
						 </tr>
					     <tr>
					        ​​​<td><?php echo $tr->translate("លេខកូដ")?></td>
							<td><?php echo $frm->getElement('cus_code')?></td>
					        <td><?php echo $tr->translate("ឈ្មោះអតិថជន")?></td>
							<td><?php echo $frm->getElement('customer_name')?></td>	
							<td><?php echo $tr->translate("ប្រភេទទ្រព្យបពាំ្ច")?></td>
							<td><?php echo $frm->getElement('callecterall_type')?></td>	
						    
					     </tr>
					      <tr>
					      
					        <td><?php echo $tr->translate("ម្ចាស់កម្មសិទ្ធ")?></td>
							<td><?php echo $frm->getElement('nameouner')?></td>
							<td><?php echo $tr->translate("លេខសំគាសអចលនវត្ថុ")?></td>
							<td><?php echo $frm->getElement('callnumber')?></td>
							<td><?php echo $tr->translate("ថ្ញៃបពាំ្ច")?></td>
							<td><?php echo $frm->getElement('date_call')?></td>	
							
						
					     </tr>
					     <tr>
							<td><?php echo $tr->translate("រយះពេលខ្ចីគិតជា")?></td>
							<td><?php echo $frm->getElement('time_think')?></td>
							<td><?php echo $tr->translate("ចំនូនរយះពេលខ្ចី")?></td>
							<td><?php echo $frm->getElement('time_boro')?></td>	
							<td><?php echo $tr->translate("ថ្ញៃផុតកំណត់")?></td>
							<td><?php echo $frm->getElement('dayless')?></td>
							
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("ប្រភេទប្រាក់")?></td>
							<td><?php echo $frm->getElement('cash_type')?></td>	
							<td><?php echo $tr->translate("ចំនួនខ្ចី")?></td>
							<td><?php echo $frm->getElement('much_boro')?></td>	
							<td><?php echo $tr->translate("សំគាល់")?></td>
							<td><?php echo $frm->getElement('note')?></td>
					    </tr>
					</table>
					</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
