 <?php 
 $tr = Application_Form_FrmLanguages::getCurrentlanguage();
 ?>
 <input type="button" label="បញ្ជីឈប់សំរាក" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-holiday')); ?>';"/>
  
   <input type="button" label="បញ្ជីតាមតំបន់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-zone')); ?>';"/>
  
  <input type="button" label="បញ្ជីបុគ្គលិក" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-staff')); ?>';"/>
  <input type="button" label="របាយការភូមិ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-village')); ?>';"/>
  <input type="button" label="របាយការបស់សាខា" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-branch')); ?>';"/>