<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title></title>
</head>

<body>
	<h2 align="center">របាយការណ៍តាមតំបន់</h2><br/>
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB" >
        	<th>NUM</th>
            <th>Zone Name</th>
            <th>Zone Number</th>
            <th>Date</th>
           
            
         </tr>
        <?php foreach($this->zone_list as $key =>$row){?>
		   <tr align="center">
		     <td><?php echo $key+1; ?></td>
		     <td><?php echo $row['zone_name']?></td>
			 <td><?php echo $row['zone_num']?></td>
			 <td><?php echo $row['modify_date']?></td>
			
			 </tr>
		<?php }?>

    </table>
</body>
</html>