<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VILLAGE_LIST"));
$frm = $this->frm_village;
?>
<title><?php echo $tr->translate("RPT_VILLAGE");?></title>
<form name="frm_rptholiday" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-village')); ?>" dojoType="dijit.form.Form" method="post">
<table style="float: right;">
	<tr>
		   	<td><?php echo $frm->getElement("adv_search");?></td>
		   	<td><?php  echo $frm->getElement('province_name');?></td>
		   	<td><?php  echo $frm->getElement('district_name');?></td>
		    <td><?php echo $frm->getElement('search_status');?></td>
		    <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button></td>
   	   </tr>
</table>
</form>
<div style=" width:80%; margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';

}
</style>

<table style="font-family: 'Khmer OS Content'; width:100%;"  >

	<tr>
    	<td align="center">
    	<div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr >
                				<td width="45%" class='style' style="font-size: 10px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        	<table align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <tr bgcolor="#BBBBBB">
				        <th>N<sup><u>o</u></sup></th>
				        <th><?php echo $tr->translate("VILLAGE_KHMER");?></th>
				        <th><?php echo $tr->translate("VILLAGE_NAME");?></th>
				        <th><?php echo $tr->translate("COMMMUNE_NAME");?></th>
				        <th><?php echo $tr->translate("DISTRICT_NAME");?></th>
				        <th><?php echo $tr->translate("PROVINCE_NAME");?></th>
				        <th><?php echo $tr->translate("DATE");?></th>
				        
				    </tr>
					<?php 
					 foreach($this->village_list as $key =>$row){
					 	?>
					     <tr align="center">
					        <td><?php echo $key+1; ?></td>
					        <td><?php echo $row['village_namekh']?></td>
					        <td><?php echo $row['village_name']?></td>
					        <td><?php echo $row['commune_name']?></td>
					        <td><?php echo $row['district_name']?></td>
					        <td><?php echo $row['province_en_name']?></td>
					        <td><?php echo $row['modify_date']?></td>
					    </tr>
					    <?php }?>
				   </table>
			</div>
			</td>
		</tr>
</table>
 </div>
 