<title>Report Holiday</title>
<div style=" width:21cm; margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';

}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['តារាងថ្ងៃឈប់សំរាក'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['ផ្ទះលេខ ១៦២ ផ្លូវលេខ ១៥០ សង្កាត់ ទឹកល្អក់១ ទូលគោក ភ្នំពេញ'];?>
								<br /><?php echo $this->data['TEL :(855) 10 78 55 44 '];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        <table align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <tr bgcolor="#BBBBBB">
				        <th>N<sup>0</sup></th>
				        <th>Holiday Name</th>
				        <th>Date</th>
				        <th>Amount</th>
				        <th>Note</th>
				    </tr>
					<?php $amount_day = 0;
					 foreach($this->holiday_list as $key =>$row){
					 	$amount_day=$amount_day+$row['amount_day'];
					 	?>
					     <tr align="center">
					        <td><?php echo $key+1; ?></td>
					        <td><?php echo $row['holiday_name']?></td>
					        <td><?php echo $row['start_date']?></td>
					        <td><?php echo $row['amount_day']?></td>
					        <td><?php echo $row['note']?></td>
					    </tr>
					    <?php }?>
					 <?php for($i=$key; $i<=14;$i++){?>
						  <tr align="center">
						        <td><?php echo $i+1; ?></td>
						        <td></td>
						        <td></td>
						        <td></td>
						        <td></td>
						    </tr>
					 <?php }?>
				
				    <tr align="center">
				        <td colspan="2"></td>
				        <th>Total</th>
				        <td><?php echo $amount_day; ?></td>
				        <td></td>
				    </tr>
				   </table><br />
				   <table align="center" width="100%">
				    <tr >
				        <th style="width:20%;border-bottom:1px dashed black;">Approved By</th>
				        <th></th>
				        <th style="width:20%;border-bottom:1px dashed black;">Verifyed By</th>
				        <th></th>
				        <th style="width:20%;border-bottom:1px dashed black;">Prepare By</th>
				   </tr>
				   </table>
 </div>