<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add CO'));
?>	
<?php  $techer= $this->frm_position;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'payroll','controller'=>'position','action'=>'Add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="90%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend><strong><?php echo $tr->translate("ព៌ត័មាន តួនាទី មន្ត្រីឥណទាន");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("តូនាទីជាភាសាខ្មែរ")?></td>
							<td><?php  echo $techer->getElement('position_kh');?></td>
							<td><?php echo $tr->translate("តួនាទីជាភាអង់គ្លេស")?></td>
							<td><?php  echo $techer->getElement('position_en');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("បង្ហាញជាភាសាខ្មែរ/English")?></td>
							<td><?php  echo $techer->getElement('display');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
						</tr>
					</table>	
					<div style="text-align: center; margin: 10px 0px;"> 
						<input type="hidden" name="exchangefrom" value="2" />
						<input type="hidden" name="inv_no" value="<?php echo $this->inv_no;?>">
						<input type="button" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button" 
							iconClass="dijitIconClear"  class="fixed_size" onclick="clearTextBox(1);"/>
						<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" label="រក្សាទុក+ថ្មី" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</div>	`
		</fieldset>
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
	function clearTextBox(curr_type){
		if(curr_type==1){
		   dijit.byId('position_kh').attr('value',0);	
		   dijit.byId('position_en').attr('value',0);	
		   dijit.byId('display').attr('value','');	
		   dijit.byId('status').attr('value','');	
		}
	}
</script>