<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("STAFF_POSITION"));
$frm = $this->frm_position;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'payroll','controller'=>'position','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td><?php echo $frm->getElement('status_search');?></td>
		   <td><?php echo $frm->getElement("btn_search");?></td>
	   </tr>
   </table>
   <?php echo $this->list;?>
</form>
