<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("IL_PAYMENT"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'il-payment','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   
   <table style="width: 100%">
   		<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   		</tr>
   		<tr>
   			
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement('paymnet_type');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   		</tr>
   </table>

   <?php echo $this->list;?>
</form>

