<?php
	$this->headTitle('Add Loan IL'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
.fullside {
	width: 100%;
	height: 30px;
}
</style>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
			zone = dijit.byId('zone').get('value');
			co_id = dijit.byId('co_id').get('value');
			client = dijit.byId('member').get('value');
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}else if(co_id=='' || co_id==-1){
				alert('Please Select CO Name !');
				dijit.byId('co_id').focus();
				return false;
			}else if(zone=='' || zone==-1){
				alert('Please Select Zone !');
				dijit.byId('zone').focus();
				return false;
			}
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន ឥណទានទោល</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("ឥណទានវគ្គទី")?></td>
							<td><?php echo $frm->getElement('level');?></td>
							<td>Admin Fee</td>
							<td><?php echo $frm->getElement('loan_fee');?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("ឈ្មោះអតិថិជន")?></td>
							<td><?php echo $frm->getElement('member');?></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							<td><?php echo $tr->translate("លេខតំបន់")?></td>
							<td><?php  echo $frm->getElement('zone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចេញ")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("រយះពេលខ្ចី")?></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("រយះពេលគិតជា")?></td>
							<td><?php echo $frm->getElement('pay_every');?></td>
							
								
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃយកប្រាក់ដំបូង")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("ម៉ោងយកប្រាក់")?></td>
							<td><?php echo $frm->getElement('time');?></td>
							<td><?php echo $tr->translate("ថ្ងៃឈប់សំរាក")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("បង់មុនថ្ងៃកំណត់")?></td>
							<td><?php echo $frm->getElement('pay_before');?></td>
							<td><?php echo $tr->translate("បង់យឺតផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('pay_late');?></td>
							<td><?php echo $tr->translate("រយៈពេលបង់ប្រាក់")?></td>
							<td><?php echo $frm->getElement('amount_collect');?></td>
							
						</tr>
					</table>
				</fieldset>
				<fieldset>
					<legend><strong>ព៌ត័មាន កម្ចីសាច់ប្រាក់</strong></legend>
					<table cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("រូបិយប័ណ្ណ")?></td>
							<td align="left"><?php echo $frm->getElement('currency_type');?></td>
							<td><?php echo $tr->translate("ចំនួនប្រាក់ខ្ចី")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("ការប្រាក់")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("វិធីសាស្រ្ត")?></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
							<td><?php echo $tr->translate("រយៈពេលអនុគ្រោះប្រាក់ដើម")?></td>
							<td><?php echo $frm->getElement('graice_pariod');?></td>
							<td><label id="lbl_payment"><?php echo $tr->translate("រយៈពេលបង់រំលោៈដើម")?></label></td>
							<td><?php echo $frm->getElement('amount_collect_pricipal');?></td>
						</tr>
					</table>
				</fieldset>
				<input type="hidden" name="invoice_no" id="invoice_no" >
				<input type="hidden" name="s_name" id="s_name">
		</td>
	</tr>		
	<tr>
		<td align="center">
		 <div id="tran_list"></div>		
		</td>
	</tr>
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">	
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
//dojo.require("dojox.grid.DataGrid");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
    var tran_store  = getDataStorefromJSON('','name',null);
	var url_submit = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'add')); ?>';
	var tran_status = {};
	var baseurl = '<?php echo $baseurl;?>';
</script>
<script type="text/javascript">
function chechPaymentMethod(){
	
	method_id = dijit.byId('repayment_method').get('value');
	if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="ចំនួនទឹកប្រាក់បង់ថេរ";
		dijit.byId('amount_collect_pricipal').attr('value','');
		dijit.byId('amount_collect_pricipal').focus();
		}
	else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}
}
function submitData(){
	var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
				//alert(data);
				
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function popupCheckClient(){
	if(dijit.byId('group_id').get('value')==-1){
		 dijit.byId('frm_client').show();
	}
}
function popupCheckCO(){
	if(dijit.byId('co_id').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}
function popupCheckZone(){
	if(dijit.byId('zone').get('value')==-1){
		 dijit.byId('frm_zone').show();
	}
}
function popupCheckDistrict(){
	if(dijit.byId('district').get('value')==-1){
		 dijit.byId('frm_district').show();
	}
}
function popupCheckCommune(){
	if(dijit.byId('commune').get('value')==-1){
		 dijit.byId('frm_commune').show();
	}
}
function popupCheckVillage(){
	if(dijit.byId('village').get('value')==-1){
		 dijit.byId('frm_village').show();
	}
}

var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add-newclient')); ?>';
function addNewClient(){
		dojo.xhrPost({
	    url: url_submit,	
		form: dojo.byId("form_client"),		    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('frm_client').reset(); 
			dijit.byId('frm_client').hide();
		},
		error: function() {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitzone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
		dojo.xhrPost({
	    url: url_submitzone,	
		form: dojo.byId("form_zone"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_zone').reset(); 
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}



</script>
<?php 
 echo $this->frmpupopclient;
 echo $this->frmPopupCO;
 echo $this->frmPopupZone;
 echo $this->frmPopupCommune;
 echo $this->frmPopupDistrict;
 echo $this->frmPopupVillage;
 
 
?>