<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Update Staff'));
?>	

<?php  $techer= $this->frm_co;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="98%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend><strong><?php echo $tr->translate("ព៌ត័មាន បុគ្កលិក");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php  echo $techer->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("លេខកូដសំគាល់")?></td>
							<td><?php  echo $techer->getElement('co_id'); echo $techer->getElement('id');?></td>
							<td><?php echo $tr->translate("ឈ្មោះជាភាសាអង់គ្គេស")?></td>
							<td><?php  echo $techer->getElement('first_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះជាភាសាខ្មែរ")?></td>
							<td><?php  echo $techer->getElement('name_kh');?></td>
							<td><?php echo $tr->translate("បង្ហាញជា")?></td>
							<td><?php  echo $techer->getElement('display');?></td>
							<td><?php echo $tr->translate("តួនាទី")?></td>
							<td><?php  echo $techer->getElement('position');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ភេទ")?></td>
							<td><?php  echo $techer->getElement('co_sex');?></td>
							<td><?php echo $tr->translate("លេខអត្តសញ្ញាណប័ណ្ណ")?></td>
							<td><?php  echo $techer->getElement('national_id');?></td>
							<td><?php echo $tr->translate("ទីកន្លែងកំណើត")?></td>
							<td><?php  echo $techer->getElement('pob');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អាស័យដ្ឋានបច្ចុប្បន្ន")?></td>
							<td><?php  echo $techer->getElement('address');?></td>
							<td><?php echo $tr->translate("កំរិតសិក្សា")?></td>
							<td><?php  echo $techer->getElement('degree');?></td>
							<td><?php echo $tr->translate("ទូរស័ព្ទ")?></td>
							<td><?php  echo $techer->getElement('tel');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អ៊ីម៉ែល")?></td>
							<td><?php  echo $techer->getElement('email');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
							<td><?php echo $tr->translate("រូបថត")?></td>
							<td><?php  echo $techer->getElement('photo');?>
							</td>
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("ផ្នែក")?></td>
							<td valign="top"><?php  echo $techer->getElement('department_id');?></td>
							<td valign="top"><?php echo $tr->translate("លេខស្នាមម្រាមដៃ")?></td>
							<td valign="top"><?php  echo $techer->getElement('figer_print_id');?></td>
							<td></td>
							<td> <img height="60px" src="<?php echo $this->baseUrl().'/images/'.$this->photo;?>" />
							</td>
						</tr>
					</table>
					<fieldset>
						<legend><strong>ព័ត៏មានប្រាក់បៀវត្សន៍</strong></legend>
							<table style="margin: 0 auto; width: 95%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("ប្រាក់ខែគោល")?></td>
									<td><?php  echo $techer->getElement('basic_salary');?></td>
									<td><?php echo $tr->translate("ថ្ងៃចូលធ្វើការ")?></td>
									<td><?php  echo $techer->getElement('start_date');?></td>
									<td><?php echo $tr->translate("ថ្ងៃបញ្ចប់កុងត្រា")?></td>
									<td><?php  echo $techer->getElement('end_date');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("លេខកុងត្រាការងារ")?></td>
									<td><?php  echo $techer->getElement('contract_no');?></td>
									<td><?php echo $tr->translate("សំគាល់")?></td>
									<td><?php  echo $techer->getElement('note');?></td>
									<td><?php echo $tr->translate("វេនធ្វើការ")?></td>
									<td><?php  echo $techer->getElement('shift');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("ម៉ោងធ្វើការ")?></td>
									<td><?php  echo $techer->getElement('workingtime');?></td>
									<td><?php echo $tr->translate("ចំនួនឈប់ប្រចាំឆ្នាំ")?></td>
									<td><?php  echo $techer->getElement('annual_lives');?></td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="submit" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
									</td>
								</tr>
							</table>
					</fieldset>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
	function calculateDay(){
		start_date = dijit.byId("start_date").get('value');
		var a=new Date(start_date);
		m=a.getMonth()+1;
		d=a.getDate();
		if(d<15){
			m=m-1;
		}
		t_day=18*(12-m)/12;
		dijit.byId('annual_lives').attr('value',t_day);
	}
</script>