<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("STAFF"));
$frm = $this->frm_co;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width=60%>
   	<tr>
	   <td><?php echo $frm->getElement("adv_search");?></td>
	   <td width="35%"><?php echo $frm->getElement("degree");?></td>
	   <td><?php echo $frm->getElement('status_search');?></td>
	   <td><?php echo $frm->getElement("btn_search");?></td>
	</tr>
   </table>
    <?php echo $this->list;?>
</form>
