<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'FixedAsset','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>ពត័មានទ្រព្យសកម្ម</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch')?></td>
							<td><?php echo $tr->translate("កូដទ្រព្យសកម្ម")?></td>
							<td><?php echo $frm->getElement('asset_code')?></td>	
							<td colspan="2"></td>
						</tr>
						   
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះទ្រព្យសកម្ម")?></td>
							<td><?php echo $frm->getElement('asset_name');?></td>
							<td><?php echo $tr->translate("ប្រភេទទ្រព្យសកម្ម")?></td>
							<td><?php echo $frm->getElement('asset_type');?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("Paid_Type")?></td>
							<td><?php echo $frm->getElement('paid_type')?></td>
							 <td><?php echo $tr->translate("Some_Payamount")?></td>
							<td><?php echo $frm->getElement('some_payamount')?></td>	
							
						
						</tr>
				
						<tr>
							<td><?php echo $tr->translate("Asset cost")?></td>
							<td><?php echo $frm->getElement('asset_cost')?></td>
							<td><?php echo $tr->translate("Useful life")?></td>
							<td><?php echo $frm->getElement('usefull_life');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Salvage value")?></td>
							<td><?php echo $frm->getElement('salvage_value')?></td>		
							<td><?php echo $tr->translate("Payment method")?></td>
							<td><?php echo $frm->getElement('payment_method')?></td>					
						</tr>
						<tr>
							<td><?php echo $tr->translate("Depreciation Start Date")?></td>
							<td><?php echo $frm->getElement('start_date')?></td>		
							<td><?php echo $tr->translate("Date")?></td>
							<td><?php echo $frm->getElement('date')?></td>		
						</tr>
						<tr>
						   	<td><?php echo $tr->translate("Note")?></td>
							<td><?php echo $frm->getElement('note')?></td>
							
							<td><?php echo $tr->translate("Stutas")?></td>
							<td><?php echo $frm->getElement('status')?></td>	
						</tr>
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
