<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Add Fixed Asset Name</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("Asset Name(KH)")?></td>
							<td><?php echo $frm->getElement('asset_name_khmer');?></td>
							<td><?php echo $tr->translate("Asset Name(EN)")?></td>
							<td><?php echo $frm->getElement('asset_name_english');?></td>
							<td><?php echo $tr->translate("Display Type")?></td>
							<td><?php echo $frm->getElement('display_type')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Date")?></td>
							<td><?php echo $frm->getElement('Date')?></td>
							<td><?php echo $tr->translate("Status")?></td>
							<td><?php echo $frm->getElement('status');?></td>
							<td><?php echo $tr->translate("")?></td>
							<td><?php echo $frm->getElement('');?></td>
						</tr>
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
