<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <?php $class='tundra';?>
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<script>dojoConfig = {parseOnLoad: true}</script>
	    <script>
		require(["dojo/parser",
		 "dojo/ready","dijit/form/DateTextBox","dijit/form/ValidationTextBox","dijit/form/Form",
         "dijit/form/FilteringSelect","dijit/form/Button","dijit/form/NumberTextBox",
         "dijit/form/CheckBox","dijit/form/CheckBox","dojo/number","dojox/form/BusyButton",
         "dijit/form/RadioButton","dijit/Dialog","dijit/layout/BorderContainer",
         "dijit/layout/TabContainer",
		 "dijit/layout/AccordionContainer","dijit/layout/ContentPane","dijit/layout/ContentPane"]);

</script>
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/tundra/<?php echo $class?>.css"/>
	
	<script src="<?php echo $base_url;?>js/help.js"  type="text/javascript"></script>
	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link href="<?php echo $base_url;?>cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<!-- table  -->
	<?php //if($action=='index'){ ?>
	
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>
	<?php //}?>
	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
		*{ padding:0;margin:0;}
    html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.fullside{ width:98%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:96%; font-family:'Khmer OS Battambang'}
		.normal,.alternate{ font-size:90% !important;}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
	</style>	
</head>
    <!-- <body class="soria">
    <body class="soria"> -->
    <body class="<?php echo $class;?>" style="overflow-y: hidden;">
        <div data-dojo-type="dijit/layout/BorderContainer" style="width: 100%; height: 100%;">
             <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'top'">
                <?php echo $this->render('header.phtml')?>
                <p style="font-size:11px !important;  padding-left: 16px;">
                <?php $session_user=new Zend_Session_Namespace('auth');
			          $username = $session_user->first_name;
        		?>
				​ប្រើ​ប្រាស់ ដោយ: <a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><?php echo $username;?></a>
				<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"> | ចាក​ចេញ</a>
                 <?php if($action=='index'){?>
                 <a style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?></a>
				<?php }elseif($action=='add' OR $action=='edit'){?>	
					<a style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><<?php echo $tr->translate('GO_BACK');?></a>
				<?php }?>
				</p>
            </div>
           
             <?php if($module!='home'){?>
             <div  style="width: 183px;" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'left'">
             	<?php echo $this->render('menuleft.phtml')?>
            </div><!-- end left -->
            <?php }?>
            <?php 
            	$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
            ?>
             <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'">
					<div style="clear: both;"></div>
				<div style="height: auto; width:100%;">
				<?php if($module=='report' AND $action!='rpt-paymentschedules'){?>
				<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					showLabel="false" type="button" onclick="doPrint();">Print</button>
					<div id="divPrint">
				<?php }?>
	                <?php echo $this->layout()->content; 
	               	if($module=='report' AND $action!='rpt-paymentschedules'){
	                ?>
                </div>
                <?php }?>
                <div style="clear: both;"></div>
                </div>
            </div><!-- end center -->
        </div>
    </body>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
</script>
</html>
