	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
		/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		$arr_param_menu=array( 
			'home'=>array(
						'index'=>'<li><a href="">'.$tr->translate("HOME").'</a></li>',
			),
			'loan'=>array(
				'index'=>'<li><a href="" title="">'.$tr->translate("IL Disburse").'</a></li>',
				'GroupDisburse'=>'<li><a href="" title="">'.$tr->translate("Group Disburse").'</a></li>',
				'ILpayment'=>'<li><a href="" title="">'.$tr->translate("IL Payment").'</a></li>',
				'GroupPayment'=>'<li><a href="" title="">'.$tr->translate("Group Payment").'</a></li>',
				'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Quick Payment").'</a></li>',
				'LoanCycle'=>'<li><a href="" title="">'.$tr->translate("Loan Cycle").'</a></li>',
			),
			'report'=>array(
				'index/rpt-loadrelease'=>'<li><a href="" title="">'.$tr->translate("Loan Release").'</a></li>',
				'index/rpt-paymentdetail'=>'<li><a href="" title="">'.$tr->translate("Client Due to Pay").'</a></li>',
				'index/rpt-paymentschedule'=>'<li><a href="" title="">'.$tr->translate("Payment Schedule").'</a></li>',
				'index/rpt-ilpaymentdetail'=>'<li><a href="" title="">'.$tr->translate("Payment Detail").'</a></li>',
			//	'GroupDisburse'=>'<li><a href="" title="">'.$tr->translate("Gross Loan Portfolio").'</a></li>',
				'GroupPayment'=>'<li><a href="" title="">'.$tr->translate("Gross Loan Portfolio By CO").'</a></li>',
				'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Loan Information Detail").'</a></li>',
			    'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Bad Loan Detail").'</a></li>',
				'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Reverse Disbursement").'</a></li>',
			    'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Reverse Disbursement").'</a></li>',
			    'QuickPayment'=>'<li><a href="" title="">'.$tr->translate("Reverse Payment").'</a></li>',
				'index/paymentschedule-list'=>'<li><a href="" title="">'.$tr->translate("Loan Release").'</a></li>',
				),
				
			'accounting'=>array(				
				'FixedAsset'=>'<li><a href="">'.$tr->translate("ទ្រព្យសកម្មរយៈពេលវែង").'</a></li>',				
				'expense'=>'<li><a href="">'.$tr->translate("ចំណាយផ្សេងៗ").'</a></li>',
				'income'=>'<li><a href="">'.$tr->translate("ចំណូលផ្សេងៗ").'</a></li>',
				'asset'=>'<li><a href="">'.$tr->translate("ទ្រព្យសកម្ម").'</a></li>',
				'Generaljurnal'=>'<li><a href="">'.$tr->translate("Generaljurnal").'</a></li>',
				'Accountcate'=>'<li><a href="">'.$tr->translate("accountcate").'</a></li>',
				'Chartaccount'=>'<li><a href="">'.$tr->translate("Chartaccount").'</a></li>',
				'Ownerequity'=>'<li><a href="">'.$tr->translate("Ownerequity").'</a></li>',
				'Balancsheet'=>'<li><a href="">'.$tr->translate("Balancsheet").'</a></li>',
				
					
					
					
			),
			'global'=>array(
					'dept-list'=>"<li><span class''><a href='".$baseurl."/global/index/dept-list'>".$tr->translate("FACULTIES")."</a></span></li>",
					'major-list'=>"<li><span class''><a href='".$baseurl."/global/index/major-list'>".$tr->translate("MAJORS")."</a></span></li>",
					'room-list'=>"<li><span class''><a href='".$baseurl."/global/index/room-list'>".$tr->translate("ROOM_NAME")."</a></span></li>",
					'teacher-lis'=>"<li><span class''><a href='".$baseurl."/global/index/teacher-list'>".$tr->translate("LACTURER")."</a></span></li>",
					'subject-list'=>"<li><span class''><a href='".$baseurl."/global/index/subject-list'>".$tr->translate("SUBJECT_EXAM")."</a></span></li>",
					'province-list'=>"<li><span class''><a href='".$baseurl."/global/index/province-list'>".$tr->translate("CITY_PROVINCE")."</a></span></li>",
					'setting'=>"<li><span class''><a href='".$baseurl."/global/index/setting'>".$tr->translate("SETTING")."</a></span></li>",
					'icon'=>"<li><span class''><a href='".$baseurl."/global/index/icon'>".$tr->translate("icon")."</a></span></li>",
			),
			
			'other'=>array(
						'position'=>'<li><a href="">'.$tr->translate("Staff Position").'</a></li>',
						'co'=>'<li><a href="">'.$tr->translate("Credit Officer/Staff").'</a></li>',
						'Province'=>'<li><a href="">'.$tr->translate("Province").'</a></li>',
						'District'=>'<li><a href="">'.$tr->translate("District").'</a></li>',
						'Commune'=>'<li><a href="">'.$tr->translate("Commune").'</a></li>',
						'Village'=>'<li><a href="">'.$tr->translate("Village").'</a></li>',
						'Zone'=>'<li><a href="">'.$tr->translate("Zone Area").'</a></li>',
						'Holiday'=>'<li><a href="">'.$tr->translate("Holiday").'</a></li>',
						'ReversePayment'=>'<li><a href="">Reverse Payment</a></li>' ,
						'ReverseDisburse'=>'<li><a href="">'.$tr->translate("ReverseDisburse").'</a></li>',
						'ReverseBadLoan'=>'<li><a href="">'.$tr->translate("Reverse Bad Loan").'</a></li>',
			),
			'group'=>array(
						'client'=>'<li><a href="">'.$tr->translate("Individual Client").'</a></li>',
						'index'=>'<li><a href="">'.$tr->translate("Group Client").'</a></li>',
						'agreement'=>'<li><a href="">'.$tr->translate("Client Agreement").'</a></li>',
						'Callteral'=>'<li><a href="">'.$tr->translate("Calleteral").'</a></li>',
				),
		   'payroll'=>array(
						'client'=>'<li><a href="">'.$tr->translate("Individual Client").'</a></li>',
						'index'=>'<li><a href="">'.$tr->translate("Group Client").'</a></li>',
						'agreement'=>'<li><a href="">'.$tr->translate("Client Agreement").'</a></li>',
				),
			'expend'=>array(
						'client'=>'<li><a href="">'.$tr->translate("Individual Client").'</a></li>',
						'index'=>'<li><a href="">'.$tr->translate("Group Client").'</a></li>',
						'agreement'=>'<li><a href="">'.$tr->translate("Client Agreement").'</a></li>',
				),
			'user'=>array(
				'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
			),	
			'rsvAcl'=>array(
					 	'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
					    'acl'=>'<li><a href="">'.$tr->translate("ACL").'</a></li>',
						'user'=>'<li><a href="">'.$tr->translate('USER').'</a></li>',
						'userAccess'=>'<li><a href="">'.$tr->translate("USER_ACCESS").'</a></li>',
						'userType'=>'<li><a href="">'.$tr->translate("USER_TYPE").'</a></li>',
				),
			'backup'=>array(
						'index'=>'<li><a href="">'.$tr->translate("Backup List").'</a></li>',
				),
			'allreport'=>array(
				'rpt-student-list'=>"<li><span class''><a href='".$baseurl."/allreport/foundation/rpt-student-list'>".$tr->translate("បញ្ជីឈ្មោះនិស្សិត")."</a></span></li>",
				'poc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-exam-degree'>".$tr->translate('បញ្ជីរាយនាមបេក្ខជនប្រលង')."</a></li>",
				'legal-document'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-final-exams'>".$tr->translate("បេក្ខជនប្រលងជាប់ជាស្ថាពរ")."</a></li>",
				'rfm'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-stuid'>".$tr->translate('បេក្ខជនបានធ្វើកាតរ')."</a></li>",
				'pam'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-foundation'>".$tr->translate("បេក្ខជនបានធ្វើកាតរ")."</a></li>",
				'prc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-drop-out'>".$tr->translate("បេក្ខជនប្រលងជ្រើសរើសចូលរៀន")."</a></li>",
				'budget-regulation'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-total-attendance'>".$tr->translate("បញ្ជីសរុបអវត្តមាន")."</a></li>",
				'da'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("បញ្ជីស្រង់ពិន្ទសំរាប់គ្រូ")."</a></li>",
				'asd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-student-attendance'>".$tr->translate("បញ្ជីស្រង់អវត្តមាន")."</a></li>",
				'asdf'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-amount-student'>".$tr->translate("បញ្ជីសរុបចំនួននិស្សិត")."</a></li>",
				//''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("REF_SOP")."</a></li>",
				'rpt-allresult'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-allresult'>".$tr->translate("បញ្ជីលទ្ទផលប្រលងប្រចាំឆ្នាំ")."</a></li>",
				''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-certificate'>".$tr->translate("ឆ្នាំសិក្សាមូលដ្ឋាន ")."</a></li>",
				'asasfd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-full-result'>".$tr->translate("ប្រាក់ចំណូលរបស់និស្សិត")."</a></li>",
				'rpt-daily'=>"<li><a href='".$baseurl."/allreport/receiptionist/rpt-daily'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//accounting
				'rpt-account-rec'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-account-rec'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-gep-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-gep-list'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-list'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-invoice'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-invoice'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-list-of-item'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-list-of-item'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part1'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part1'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part2'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part2'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part3'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part3'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-studentpayment'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-studentpayment'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-tuition-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-tuition-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
			),	
			'callteral'=>array(
				'badloan'=>'<li><a href="">'.$tr->translate("BADLAON").'</a></li>',
				'callteral'=>'<li><a href="">'.$tr->translate("CALLTERAL").'</a></li>',
			),
			'fixedasset'=>array(
				'asset'=>'<li><a href="">'.$tr->translate("FIXED ASSET").'</a></li>',
				'index'=>'<li><a href="">'.$tr->translate("").'</a></li>',
			),
			'Salary'=>array(
				'salary'=>'<li><a href="">'.$tr->translate("ADD SALARY").'</a></li>',
				),
			'tellerandexchange'=>array(
				'teller'=>'<li><a href="">'.$tr->translate("កន្លែងបង់ប្រាក់").'</a></li>',
				'exchange'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
				'exchanges'=>'<li><a href="">'.$tr->translate("អាត្រាប្តូរប្រាក់").'</a></li>',
				'exchangerate'=>'<li><a href="">'.$tr->translate("កំណត់អាត្រាប្តូរប្រាក់").'</a></li>',
				'showrate'=>'<li><a href="">'.$tr->translate("ពិនិត្យអាត្រាប្តូរប្រាក់").'</a></li>',
				'xchange'=>'<li><a href="">'.$tr->translate("ប្រភេទប្រាក់ប្តូ").'</a></li>',
				
				
				),
				
			'exchange'=>array(
						'index'=>'<li><a href="">'.$tr->translate("កន្លែងបង់ប្រាក់").'</a></li>',
						'exchange'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						'exchangerate'=>'<li><a href="">'.$tr->translate("កំណត់អាត្រាប្តូរប្រាក់").'</a></li>',
						'showrate'=>'<li><a href="">'.$tr->translate("ពិនិត្យអាត្រាប្តូរប្រាក់").'</a></li>',
				
				),
		); 
	?>
	<div id="header-left">
	<ul>
			<?php 
// 				$request=Zend_Controller_Front::getInstance()->getRequest();
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;					
			?>
	</ul>																
	</div>