<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_Frmcallecterall;
?>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'callecterall','controller'=>' refundcallecterall','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("REFUND_CALLECTERALL")?></strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
								
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><?php echo $frm->getElement('customer_name')?></td>	
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><?php echo $frm->getElement('cus_code')?></td>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CALLECTERALL_TYPE")?></td>
							<td><?php echo $frm->getElement('callecterall_type')?></td>								
							<td><?php echo $tr->translate("CALLECTERALL_CODE")?></td>
							<td><?php echo $frm->getElement('callecterall_code')?></td>	
							<td><?php echo $tr->translate("CASH_TYPE")?></td>
							<td><?php echo $frm->getElement('cash_type')?></td>									
						</tr>
						<tr>								
							<td><?php echo $tr->translate("MUCH_BROR")?></td>
							<td><?php echo $frm->getElement('much_boro')?></td>
							<td><?php echo $tr->translate("FUND_AMONT")?></td>
							<td><?php echo $frm->getElement('fund_amount')?></td>
							<td><?php echo $tr->translate("TERM_FUN")?></td>
							<td><?php echo $frm->getElement('term_fun')?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("CHARGE_TERM")?></td>
							<td><?php echo $frm->getElement('charge_term')?></td>
							<td><?php echo $tr->translate("AMOUN_MONEY")?></td>
							<td><?php echo $frm->getElement('amount_money')?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('date')?></td>	
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("INNALIZATION")?></td>
							<td><?php echo $frm->getElement('innalization')?></td>	
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status')?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>		
							
						</tr>
					</table>
					</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
