<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
?>
<style>	
.fullside{
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()){
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន កិច្ចសន្យាខ្ចីប្រាក់</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("Customer Name")?></td>
							<td><?php echo $frm->getElement('customer_name');?></td>
							<td><?php echo $tr->translate("Fist Name")?></td>
							<td><?php echo $frm->getElement('first_name');?></td>
							<td><?php echo $tr->translate("Customer Code")?></td>
							<td><?php echo $frm->getElement('customer_code');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Total Amount")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("Branch Name CO")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("Group ID")?></td>
							<td><?php  echo $frm->getElement('group_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចេញ")?></td>
							<td><?php echo $frm->getElement('date');?></td>
							<td><?php echo $tr->translate("Note")?></td>
							<td><?php echo $frm->getElement('note');?></td>
							<td></td>
							<td></td>								
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
</script>