<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_BRANCH​​_INFO')); 
?>
<?php  $frm = $this->frm_branch;?>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'branch','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("UPDATE_BRANCH​​_INFO");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("BR_ID")?></td>
										<td><?php echo $frm->getElement("br_id");?></td>
										<td><?php echo $tr->translate("BRANCH_NAMEKH")?></td>
										<td><?php echo $frm->getElement("branch_namekh");?></td>
										<td><?php echo $tr->translate("BRANCH_NAMEEN")?></td>
										<td><?php echo $frm->getElement("branch_nameen");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BRANCH_ADDRESS")?></td>
										<td><?php echo $frm->getElement("br_address");?></td>
										<td><?php echo $tr->translate("BRANCH_TEL")?></td>
										<td><?php echo $frm->getElement("branch_tel");?></td>
                                        <td><?php echo $tr->translate("BRANCH_CODE")?></td>
										<td><?php echo $frm->getElement("branch_code");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BRNACH_FAX")?></td>
										<td><?php echo $frm->getElement("fax");?></td>
										<td><?php echo $tr->translate("BRANCH_NOTE")?></td>
										<td><?php echo $frm->getElement("branch_note");?></td>
										<td><?php echo $tr->translate("BRANCH_STATUS")?></td>
										<td><?php echo $frm->getElement("branch_status");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BRANCH_DISPLAY")?></td>
										<td><?php echo $frm->getElement("branch_display");?></td>
										<td colspan="4"></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
										  <input type="reset" label="សំអាត" id="" dojoType="dijit.form.Button"
				                              iconClass="dijitIconClear" />
										  <input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button" 
									          iconClass="dijitEditorIcon dijitEditorIconSave"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>