<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add CO'));
?>	
<?php  $techer= $this->frm_co;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="90%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend><strong><?php echo $tr->translate("ព៌ត័មាន មន្ត្រីឥណទាន");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("លេខកូដសំគាល់")?></td>
							<td><?php  echo $techer->getElement('co_id');?></td>
							<td><?php echo $tr->translate("ឈ្មោះជាភាសាខ្មែរ")?></td>
							<td><?php  echo $techer->getElement('name_kh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះជាភាសាអង់គ្គេស")?></td>
							<td><?php  echo $techer->getElement('first_name');?></td>
							<td><?php echo $tr->translate("បង្ហាញជា")?></td>
							<td><?php  echo $techer->getElement('display');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ភេទ")?></td>
							<td><?php  echo $techer->getElement('co_sex');?></td>
							<td><?php echo $tr->translate("លេខអត្តសញ្ញាណប័ណ្ណ")?></td>
							<td><?php  echo $techer->getElement('national_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ទីកន្លែងកំណើត")?></td>
							<td><?php  echo $techer->getElement('pob');?></td>
							<td><?php echo $tr->translate("អាស័យដ្ឋានបច្ចុប្បន្ន")?></td>
							<td><?php  echo $techer->getElement('address');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("កំរិតសិក្សា")?></td>
							<td><?php  echo $techer->getElement('degree');?></td>
							<td><?php echo $tr->translate("ទូរស័ព្ទ")?></td>
							<td><?php  echo $techer->getElement('tel');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អ៊ីម៉ែល")?></td>
							<td><?php  echo $techer->getElement('email');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="4" align="center">
							<input type="submit" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_techer").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>