<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>

  <table width="80%"  style="border-collapse:collapse;" align="center">
  
  <tr height="30px">
        <td colspan="9"><h2>Active Loans</h2>
  <p>05.12.2014. All Currencies->Pound. All branches</p></td>
      </tr>
    <tr bgcolor="#666666" id="exportExcel">
        <td>Loan Product</td>
        <td>Contracts</td>
        <td>Individual</td>
        <td>Group</td>
        <td>Comporate</td>
        <td>Clients</td>
        <td>In Groups</td>
        <td>Projecst</td>
        <td>OLB</td>
        
    </tr>
    <tr>
        <td>Albun launch</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>7</td>
        
    </tr>
     <tr bgcolor="#CCCCCC">
        <td>Instument Personal loan</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>7</td>
        
    </tr>
     <tr>
        <td>Recording loan</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>7</td>
        
    </tr>
     <tr bgcolor="#CCCCCC">
        <td>Tour preperation</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>7</td>
        
        
    </tr>
     <tr  bgcolor="#666666">
        <td>TOTAL</td>
         <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>7</td>
      </tr>
      <tr height="30px">
        <td colspan="9"></td>
      </tr>
      <tr bgcolor="#666666">
        <td>Activity</td>
        <td>Contracts</td>
        <td>Individual</td>
        <td>Group</td>
        <td>Comporate</td>
        <td>Clients</td>
        <td>In Groups</td>
        <td>Projecst</td>
        <td>OLB</td>
       </tr>
       <tr >
         <td>Bassist</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
       <tr bgcolor="#CCCCCC">
         <td>Drummer</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr >
         <td>Guitarist</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr bgcolor="#CCCCCC">
         <td>Keybord player</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr >
         <td>Lable</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr bgcolor="#CCCCCC">
         <td>Maneger</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr >
         <td>Singer</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr bgcolor="#666666">
         <td>TOTAL</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
      <tr height="30px">
        <td colspan="9"></td>
      </tr>
       <tr bgcolor="#666666">
        <td>District</td>
        <td>Contracts</td>
        <td>Individual</td>
        <td>Group</td>
        <td>Comporate</td>
        <td>Clients</td>
        <td>In Groups</td>
        <td>Projecst</td>
        <td>OLB</td>
       </tr>
       <tr bgcolor="#CCCCCC">
         <td>Leverpor district</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr>
         <td>London district</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr bgcolor="#666666">
         <td>TOTAL</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
        <tr height="30px">
        <td colspan="9"></td>
      </tr>
       <tr bgcolor="#666666">
        <td>Cunrency</td>
        <td>Contracts</td>
        <td>Individual</td>
        <td>Group</td>
        <td>Comporate</td>
        <td>Clients</td>
        <td>In Groups</td>
        <td>Projecst</td>
        <td>OLB</td>
       </tr>
        <tr>
         <td>Pund</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
       <tr bgcolor="#666666">
         <td>TOTAL</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
         </tr>
        <tr height="30px">
        <td colspan="9"></td>
      </tr>
       <tr bgcolor="#666666">
        <td>Loand officer</td>
        <td>Contracts</td>
        <td>Individual</td>
        <td>Group</td>
        <td>Comporate</td>
        <td>Clients</td>
        <td>In Groups</td>
        <td>Projecst</td>
        <td>OLB</td>
       </tr>
         <tr>
         <td>Admin admin</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
         <tr  bgcolor="#CCCCCC">
         <td>Loand officer1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
         <tr>
         <td>Loand officer2</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
         <tr  bgcolor="#CCCCCC">
         <td>Team Maneger1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
         <tr  bgcolor="#666666">
         <td>TOTAL</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>1</td>
         <td>8</td>
       </tr>
       
       
  </table>
</body>
</html>
