 <input type="button" label="បញ្ជីតារាងបង់ប្រាក់របស់អតិថិជន" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'paymentschedule-list')); ?>';"/>
 <input type="button" label="Loan Release" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-released')); ?>';"/>
  
  <input type="button" label="បញ្ជីប្រាក់កម្ចីក្រុមបានផ្តល់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-group-disburse')); ?>';"/>
  
  <input type="button" label="បញ្ជីការប្រមូលប្រាក់កម្ចី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect')); ?>';"/>
  
  <input type="button" label="បញ្ជីការទូទាត់ប្រាក់កម្ចី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment')); ?>';"/>
  
  <input type="button" label="បញ្ជីកាលវិភាគទូទាត់ប្រាក់កម្ចី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment-schedule')); ?>';"/>
  
  <input type="button" label="បញ្ជីសេវាឥណទានយឺត" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late')); ?>';"/>
  
  <input type="button" label="បញ្ជីប្រាក់កម្ចីដំណើរការ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-outstanding')); ?>';"/>
  
  <input type="button" label="បញ្ជីប្រាក់កម្ចីមិនដំណើរការ" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-badloan')); ?>';"/>
  
  <input type="button" label="បញ្ជីប្រាក់ដែលបានផ្តល់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-berelease')); ?>';"/>
  
  <input type="button" label="ថ្ងៃចេញប្រាក់កម្ចី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-dateline')); ?>';"/>
  
  <input type="button" label="បញ្ជីមន្រ្តីប្រមូលបា្រក់" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco')); ?>';"/>
  
  <input type="button" label="បញ្ជីប្រមូលប្រាក់សរុប" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-total-collect')); ?>';"/>