  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
  <input type="button" label="<?php echo $tr->translate("LIST_MAYMENT_FOR_CLIENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'paymentschedule-list')); ?>';"/>

  <input type="button" label="<?php echo $tr->translate("LOAN_DISBURSE");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-disburse')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-disburse-co')); ?>';"/>
  
   <input type="button"  label="<?php echo $tr->translate("LOAN_OUTSTADING");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-outstanding')); ?>';"/>
  
   
   <input type="button" label="<?php echo $tr->translate("BAD_LOAN");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-badloan')); ?>';"/>
  
 
  <input type="button" label="<?php echo $tr->translate("GROUP_DISBURS");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-group-disburse')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("LOAN_COLLECT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("PAYMENT_COLLECT_BY_CO");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("LOAN_PAYMENT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment')); ?>';"/>
  
 <!--  <input type="button" label="បញ្ជីកាលវិភាគទូទាត់ប្រាក់កម្ចី" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php //echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment-schedule')); ?>';"/> -->
  
  <input type="button" label="<?php echo $tr->translate("LOAN_LATE");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late')); ?>';"/>
  
 
  <input type="button" label="<?php echo $tr->translate("LOAN_BERELEASE");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-berelease')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("DAY_OUT_BORROW");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-dateline')); ?>';"/>
  
  <input type="button" label="<?php echo $tr->translate("LOAN_PAYMENT_COLLECTTION");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-total-collect')); ?>';"/>
  <input type="button" label="<?php echo $tr->translate("PROFIT");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-income')); ?>';"/>
  <input type="button" label="<?php echo $tr->translate("PAY_OFF");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-payoff')); ?>';"/>
  <input type="button" label="<?php echo $tr->translate("EXPECTED_INCOME");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-expect-income')); ?>';"/>
<!--   <input type="button" label="បញ្ជីឥណទានខូច" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php //echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-badloan')); ?>';"/> -->
   <input type="button" label="<?php echo $tr->translate("LOAN_WRITE_OFF");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-writoff')); ?>';"/>
   <input type="button" label="<?php echo $tr->translate("LOAN_XCHANGE");?>" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-xchange')); ?>';"/>