<title>Loan Released</title>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<table style="font-family: 'Khmer OS Content'; width:100%;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div style=" width:21cm; margin:0 auto; ">
<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php //echo $this->data['brand_out'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 24px;">
                    <td>លរ</td>
                    <td>លេខកំម្ជី</td>
                    <td>ឈ្មោះអតិថជន</td>
                    <td>ចំនួនប្រាក់បានចេញ</td>
                    <td>អត្រាការប្រាក់</td>
                    <td>រយៈពេលខ្ចី</td>
                    <td>កាលបរិឆ្ឆេទ</td>
                    <td>ឈ្មោះមន្ត្រីឥណទាន</td>
                    
                    <td>ថ្លែរដ្នបាល</td>
                    <td>គោលបំណងកម្ចី</td>
                </tr>
               <?php if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
					<tr align="center">
					<td><?php echo $key+1; ?></td>
					<td><?php echo$row['loan_number']?></td>
					<td><?php echo$row['client_id']?></td>
					<td><?php echo$row['total_capital']?></td>
					<td><?php echo$row['interest_rate']?></td>
					<td><?php echo$row['total_duration']?></td>
					<td><?php echo$row['date_release']?></td>
					<td><?php echo$row['co_name']?></td>
					
					<td><?php echo$row['admin_fee']?></td>
					<td><?php echo$row['loan_purpose']?></td>
					</tr>
				<?php }?>
            </table>
    	</td>
    </tr>
</table>
</div>
</div>
