<title>rpt_payment</title>
<div style="width:21cm; margin:0 auto;">
<table width="100%">
	<tr>
    	<td>
    		<h4 style="font-size:14px; font-family:'Khmer OS Muol';​​​" align="center"><?php echo $this->data['brand_pay'];?></h4>
    	</td>
   	</tr>
    <tr>
    	<td>
        	<table width="100%">
            	<tr>
                	<td><p><?php echo $this->data['brand_siha'];?></td>
                 </tr>
                 <tr>
                    <td><?php echo $this->data['brand_loanpay'];?></td>
                 </tr>
                 <tr>
                    <td><?php echo $this->data['brand_from'];?></td>
                </tr>
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
                <tr align="center" bgcolor="#FFFFCC">
                    <td>date</td>
                    <td>payData</td>
                    <td>code</td>
                    <td>Applicatio</td>
                    <td>month</td>
                    <td>year</td>
                    <td>total</td>
                </tr>
            </table>
            <hr style="height: 2px; width:100%; color: #005;">
    	</td>
    </tr>
</table>
</div>
