<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $tr->translate("UNITILED DOCUMENT");?></title>
</head>

<body>
	<h2 align="center">Rtp-badloan</h2>
	<table width="100%" border="1" style="border-collapse:collapse;" bordercolor="black">
    	<tr​>
        	<th><?php echo $tr->translate("NO");?></th>
            <th><?php echo $tr->translate("NAME");?></th>
            <th><?php echo $tr->translate("BRANCH");?></th>
            <th><?php echo $tr->translate("DATE");?></th>
            <th><?php echo $tr->translate("PRINCIPAL_AMOUNT");?></th>
            <th><?php echo $tr->translate("CO");?></th>
            <th><?php echo $tr->translate("NOTE");?></th>
           
        </tr>
      <?php for($i=0;$i<7;$i++){ ?>
      <tr align="center">
        	<td><?php echo $i+1;?></td>
            <td>dara</td>
            <td></td>
            <td>05 04 2014</td>
            <td></td>
            <td></td>
            <td></td>
           
        </tr>
        <?php } ?>
        <tr>
        	<th colspan="5">Total</th>
            <th></th>
            <th></th>
        </tr>
       
       
    </table>
</body>
</html>