<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<title>group disburse</title>
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label>(សាខា ទី ២)</label></h2>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                			</tr>
			              </table>
		              </td>
		           </tr>   
            </table>
	<table width="96%" align="center"  cellspacing="0" style="margin-left: 10px;">
	<tr>
    	<td>
  	<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
                    <tr bgcolor="#888888" align="center" class="style" align="center" style="font-weight:bold; line-height: 16px; font-size:11px; padding:5px 0px; ">
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></td>
                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CO_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("LOAN_NO");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CLIENT_NO");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
                     
                    <td style="padding:5px 0px;"><?php echo $tr->translate("LOAN_AMOUNT");?></td>
                    <!-- - <td style="padding:5px 0px;">ថ្លៃរដ្ឋបាល</td>-->
                    <td style="padding:5px 0px;"><?php echo $tr->translate("INTEREST RATE");?></td>
                    
                    <td style="padding:5px 0px;"><?php echo $tr->translate("AMIN_FEE");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("OTHER_FEE");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("LOAN_TYPE");?></td>
                    
                    <td style="padding:5px 0px;"><?php echo $tr->translate("RELEASED_DATE");?></td>
                    </tr>
                    <?php if(!empty($this->loancllect_list)) foreach ($this->loancllect_list as $index => $rs){ ?>
                    <tr height="40px">
                        <td><?php echo $index+1;?></td>
                        <td><?php echo $rs['branch_name'];?></td>
                        <td><?php echo $rs['co_kh']?></td>
                        <td><?php echo $rs['loan_number']?></td>
                        <td><?php echo $rs['customer_number']?></td>
                        <td><?php echo $rs['name_kh']?></td>
                        <td><?php echo $rs['total_capital']?></td>
                        <td><?php echo $rs['interest_rate']?></td>
                        <td><?php echo $rs['admin_fee']?></td>
                        <td><?php echo $rs['other_fee']?></td>
                        <td><?php echo $rs['for_loan_type']?></td>
                        
                        <td><?php echo $rs['date_release']?></td>
                    </tr>
                    <?php }?>
                    
                   
                </table>
   		</td>
  	 </tr>
  </table>
  </td>
  </tr>
  </table>
  </div>