<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("LOANCOLLECT");?></title>
<html>
<head>
<meta charset="utf-8">
<title></title>

</head>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<!--<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
 	<tr> -->
<!-- 		<td align="right"> -->
<!-- 			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox" -->
<!-- 			 style="width: 320px;  height: 30px;" value='<?php //echo $this->txtsearch;?>'/>-->
<!-- 			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button> -->
<!-- 		</td> -->
<!-- 	</tr> -->
<!-- </table> -->
<div id="divPrint">
<body>
	<table width="100%" border="1" style="border-collapse:collapse;" bordercolor="black">
    	<tr bgcolor="#BBBBBB">
        	<th><?php echo $tr->translate("NO");?></th>
            <th><?php echo $tr->translate("LOAN_CODE");?></th>
            <th style="white-space: pre;"><?php echo $tr->translate("CLIENT_NAMEKH");?></th>
            <th><?php echo $tr->translate("BRANCH");?></th>
            <th><?php echo $tr->translate("CO");?>Co</th>
            <th><?php echo $tr->translate("PRINCIPAL");?></th>
            <th><?php echo $tr->translate("ENTEREST");?></th>
            <th><?php echo $tr->translate("PENALIIZE");?></th>
            <th style="white-space: pre;"><?php echo $tr->translate("TOTAL__PAYMENT");?></th>
            <th><?php echo $tr->translate("DATE");?></th>
         </tr>
         <?php foreach($this->loancllect_list as $key =>$row){?>
		   <tr>
		     <td>&nbsp;<?php echo $key+1; ?></td>
		     <td>&nbsp;<?php echo $row['loan_number']?></td>
			 <td>&nbsp;<?php echo $row['client_name']?></td>
			 <td>&nbsp;<?php echo $row['branch_id']?></td>
			 <td>&nbsp;<?php echo $row['co']?></td>
			 <td>&nbsp;<?php echo $row['total_principal']?></td>
			 <td>&nbsp;<?php echo $row['total_interest']?></td>
			 <td>&nbsp;<?php echo $row['STATUS']?></td>
			 <td>&nbsp;<?php echo $row['total_payment']?></td>
			 <td>&nbsp;<?php echo $row['date_payment']?></td>
			 
			</tr>
		<?php }?>
        <?php for($i=0;$i<=7;$i++){?>
        <tr align="center">
        	<td><?php echo $i+1;?></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <?php }?>
     </table>
</body>
</div>
</html>