<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<title>Delinquent Loans</title>
<div id="divPrint">
<table width="100%" align="center" cellspacing="0">
	<tr>
    	<td>
        	<h2 align="center">Delinquent Loans</h2>
            <p>5.12.2014.all Currencies-Pound</p>
            <table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
                
                <tr bgcolor="#BBBBBB" align="center" >
                    <td><?php echo $tr->translate("CONTACT_CODE");?></td>
                    <td><?php echo $tr->translate("FIRST_NAME");?></td>
                    <td><?php echo $tr->translate("LAST NAME");?></td>
                    <td><?php echo $tr->translate("DISTRICT");?></td>
                    <td><?php echo $tr->translate("START_DATE");?></td>
                    <td><?php echo $tr->translate("END_DATE");?></td>
                    <td><?php echo $tr->translate("AMOUNT");?></td>
                    <td><?php echo $tr->translate("PADPRINCIPAL");?></td>
                    <td><?php echo $tr->translate("OLB");?></td>
                    <td><?php echo $tr->translate("LATE_PRINCIPAL");?></td>
                    <td><?php echo $tr->translate("START_DATE");?></td>
                    <td><?php echo $tr->translate("LATE_INTEREST");?></td>
                    <td><?php echo $tr->translate("PENALTY");?></td>
                    <td><?php echo $tr->translate("LATE_DAYS");?></td>
                </tr>
                <tr height="30px">
                    <td colspan="13"></td>
                </tr>
                <tr>
                    <th colspan="12">Loan Officer1-Instrument Personal loan(IL)</th>
               
                </tr>
                 <?php foreach ($this->loandateline_list as $index => $rs){ ?>
                <tr>
               		<td><?php //echo $rs["g_id"];?></td>
               		<td><?php echo $rs["first_name"];?></td>
               		<td><?php echo $rs["last_name"];?></td>
               		<td><?php echo $rs["zone_id"];?></td>
               		<td><?php echo $rs["create_date"];?></td>
               		<td><?php echo $rs["date_line"];?></td>
               		<td><?php echo $rs["total_duration"];?></td>
               		<td><?php echo $rs["first_payment"];?></td>
               		<td><?php echo $rs["holiday"];?></td>
               		<td><?php echo $rs["payment_method"];?></td>
               		<td><?php echo $rs["teller_id"];?></td>
               		<td><?php echo $rs["collect_typeterm"];?></td>
               		<td><?php echo $rs["date_release"];?></td>
                </tr>
                <?php }?>
                 <tr>
                    <th colspan="6">&nbsp;SubTotal-loan Oficer1-Instrument Personal loan(IL)</th>
                    <td>&nbsp;16.0000</td>
                    <td>&nbsp;5.30000</td>
                    <td>&nbsp;20.7788</td>
                    <td>&nbsp;23.5556</td>
                    <td>&nbsp;2345</td>
                    <td>&nbsp;12356</td>
                    <td>&nbsp;1203</td>
                </tr>
                
                
                
                
                
                
                
               <tr height="30px">
                    <td colspan="13"></td>
                </tr>
                
                 <tr>
                    <th colspan="12">Loan Officer2-Instrument Personal loan(IL)</th>
               
                </tr>
                
                <?php for($i=1;$i<=7;$i++) {?>
                <tr>
                    <td>&nbsp;LDH/14/1l-2/17/19</td>
                    <td>&nbsp;Jimmy</td>
                    <td>&nbsp;page</td>
                    <td>&nbsp;Londong District</td>
                    <td>&nbsp;28.07.2014</td>
                    <td>&nbsp;28.10.2014</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;00000</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;300</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;79</td>
                </tr>
                <?php }?>
                 <tr>
                    <th colspan="6">SubTotal-loan Oficer1-Instrument Personal loan(IL)</th>
                    <td>&nbsp;16.0000</td>
                    <td>&nbsp;5.30000</td>
                    <td>&nbsp;20.7788</td>
                    <td>&nbsp;23.5556</td>
                    <td>&nbsp;2345</td>
                    <td>&nbsp;12356</td>
                    <td>&nbsp;1203</td>
                </tr>
                
                
                
                
                
                
                
                <tr height="30px">
                    <td colspan="13"></td>
                </tr>
                
                 <tr>
                    <th colspan="12">Team Manager1-Album launch(Label)(All)</th>
               
                </tr>
                
            
                <tr>
                    <td>&nbsp;LDH/14/1l-2/17/19</td>
                    <td>&nbsp;Jimmy</td>
                    <td>&nbsp;page</td>
                    <td>&nbsp;Londong District</td>
                    <td>&nbsp;28.07.2014</td>
                    <td>&nbsp;28.10.2014</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;00000</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;300</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;79</td>
                </tr>
            
                 <tr>
                    <th colspan="6">SubTotal-Team Manager1-Album launch(Label)(All)</th>
                    <td>&nbsp;16.0000</td>
                    <td>&nbsp;5.30000</td>
                    <td>&nbsp;20.7788</td>
                    <td>&nbsp;23.5556</td>
                    <td>&nbsp;2345</td>
                    <td>&nbsp;12356</td>
                    <td>&nbsp;1203</td>
                </tr>
                
                
                
                
                
                
                
                <tr height="30px">
                    <td colspan="13"></td>
                </tr>
                
                 <tr>
                    <th colspan="12">Team Manager1-Reccording loan(RL)</th>
               
                </tr>
                
            
                <tr>
                    <td>&nbsp;LDH/14/1l-2/17/19</td>
                    <td>&nbsp;Jimmy</td>
                    <td>&nbsp;page</td>
                    <td>&nbsp;Londong District</td>
                    <td>&nbsp;28.07.2014</td>
                    <td>&nbsp;28.10.2014</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;00000</td>
                    <td>&nbsp;300000</td>
                    <td>&nbsp;300</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;30</td>
                    <td>&nbsp;79</td>
                </tr>
            
                 <tr>
                    <th colspan="6">SubTotal-Team Manager1-Reccording loan(RL)</th>
                    <td>&nbsp;16.0000</td>
                    <td>&nbsp;5.30000</td>
                    <td>&nbsp;20.7788</td>
                    <td>&nbsp;23.5556</td>
                    <td>&nbsp;2345</td>
                    <td>&nbsp;12356</td>
                    <td>&nbsp;1203</td>
                </tr>
                <tr>
                    <th colspan="6">&nbsp;TOTAL</th>
                    <td>16.0000</td>
                    <td>5.30000</td>
                    <td>20.7788</td>
                    <td>23.5556</td>
                    <td>2345</td>
                    <td>12356</td>
                    <td>1203</td>
                </tr>
               
            </table>
	
        </td>
    </tr>
</table>
</div>
