<?php  $tran = $this->tran_schedule;
// print_r($tran);

$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();												
?>
<?php  $end_dat=$this->date_show;
?>
<?php //$db = $this->getAdapter();
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<style type="text/css">
.fullside {
width: 98%;
height: 25px;
}
.tundra .dijitArrowButtonInner {
width: 7px;
height: 7px;
margin: -4px 4px 0 4px;
}
</style>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("LIST_LOAN_COLLECT");?></title>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height:105px;">
 <div dojoType="dijit.layout.ContentPane" region="top" style="height: auto;">
 <form method="post">
	<table width="100%">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
		</tr>
		<tr>
			
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><?php echo $filter->getElement('btn_search');?></td>
		</tr>
	</table>
	</form>
 </div>
</div>
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<div style=" width:27cm; min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
	<div id="divPrint">
	
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label><?php ?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></h2></td>
	                    <td width="20%"></td>
	                </tr>
	                <?php 
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr class='style'>
	                				<td width="40%">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td></td>
	                				
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel"  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%">
	                 <tr class="style" align="center" bgcolor="#BBBBBB">
	                 	
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRANCH_KH");?></td>
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUMBER_CODE");?></td>
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("CO_NAME");?></td>
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PHONE");?></td>
	                    
	                    <td rowspan="2" style=" font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("DAY_PAYMENT");?></td>
	                    <!-- <td>ចំនួនថ្ងៃ</td> -->
	                    <td rowspan="2" style="text-align:center ;font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PRINCIPLE");?></td>
	                    <td colspan="6" style="text-align:center ; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PAYMENT");?></td>
	                    
	                    <td rowspan="2" style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PAYMENT");?></td>
	                    <td rowspan="2" style="min-width:85px; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("OTHER");?></td>
	                    
	                </tr>
	                <tr class="style" bgcolor="#BBBBBB">
	                    <!--<td>ចំនួនថ្ងៃ</td>-->
	                    <td  style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PRINCIPLE_PERMONTH");?></td>
	                    <td style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("INTEREST");?></td>
	                    <td  style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LATE_DAY");?></td>
	                    
	                    <td  style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PAY_AFTER");?></td>
	                    <td  style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("INTEREST_RATE");?></td>
	                    <td  style="text-align:center ; font-size:9px; font-family:'Khmer MEF2'"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
	                </tr>
	               <?php foreach($tran as $key =>$row){?>
	               	<tr align="center" style="font-size:10px; height: 20px;" class="style">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <td align="left">&nbsp;<?php echo $row['branch_kh'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['co_name'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['phone_number'];?>&nbsp;</td>
	                    
	                   
	                   
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    
	                    <td align="center"><?php echo date('d-m-Y',strtotime($row['date_payment']));
	                    //$last_pay=$row['date_payment'];
	                    //$total_day=$end_dat-$last_pay;
	                     ?>&nbsp;</td>
	                   <!--  <td><?php //echo $row['is_completed']?></td> -->
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_principal'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['principal_permonth'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest'],2));?>&nbsp;</td>
	                    
	                   	
	                    <?php 
	                    $remain = $row['total_principal']-$row['principal_permonth']
	                    ?>
	                    
	                	<td><?php if ($row['last_pay_date']==null){
	                					$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
										$all_day=$total_day/(60*60*24);
										echo $all_day;
										
										}
									else {
											$total_day=strtotime($end_dat)-strtotime($row['last_pay_date']);
											$all_day=$total_day/(60*60*24);
											echo $all_day;
									}
							?>
							</td>	
							 <td><?php echo $row['pay_after'];?></td>
	                  		 <td><?php echo $row['interest_rate'];?></td>	
	                   <td><?php $pay_term=$row['collect_typeterm'];
	                   			if($all_day<=$free_day){ 
									$all_day=0;$result=0;
									echo $result;

	                   				}
	                   			else {
	                   				$total_late=($row['principal_permonth']+$row['total_interest']);
									 //$total_late=str_replace('.00', '', number_format($total_late,2));
									 if ($pay_term==1){
									 	$result=$total_late*($row['pay_after']*($row['interest_rate']/100)/1)*($all_day-$free_day);
									 	echo $total_late."+"."(".$row['pay_after']."*"."(".$row['interest_rate']."/100)/30)*(".$all_day."-".$free_day.")";
									 	echo str_replace('.00', '', number_format($result,2));;
									 }
									 if ($pay_term==2){
									 	$result=$total_late*($row['pay_after']*($row['interest_rate']/100)/7)*($all_day-$free_day);
									 	echo str_replace('.00', '', number_format($result,2));;
									 }
									 if ($pay_term==3){
									 	$result=$total_late*($row['pay_after']*(($row['interest_rate']/100)/30))*($all_day-$free_day);
									 	//echo $total_late."+"."(".$row['pay_after']."*"."(".$row['interest_rate']."/100)/30)*(".$all_day."-".$free_day.")=".$result;
									 	echo str_replace('.00', '', number_format($result,2));;
									 }
									}
	                   			
	                   							
	                   	?>
	                   </td>
	                 
	                  <td align="left">&nbsp;<?php echo str_replace('.00', '', number_format(($result+$row['total_payment']),2)); ?>&nbsp;</td>
	                   <td><?php echo "";?></td>
	                </tr>
	                
	               <?php }
	               	//for($record = $key;$record<11;$record++){
	               //?>
	               		
	               <?php //}?>
	            </table>
	            <br />
              <table align="center" width="100%">
				    <tr style="font-size: 12px;">
				        <th style="width:20%;"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>
