<meta charset="utf-8">
<title>group disburse</title>
<div style=" width="100%"  margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['group_disburse'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                			</tr>
			              </table>
		              </td>
		           </tr>   
            </table>
<table width="80%" align="center"  cellspacing="0" style="margin-left: 50px;">
	<tr>
    	<td>
  <table width="100%" border="1" style="border-collapse:collapse;font-size:12px;" bordercolor="black">
    
                    <tr bgcolor="#888888" align="center">
                    	<th>NO</th>
                        <th>LOAN CODE</th>
                        <th>FIRST NAME</th>
                        <th>LAST NAME</th>
                        <th>AMOUNT</th>
                        <th>IS_RATE</th>
                        <th>FEE</th>
                        <th>PAMENT_METHOD</th>
                        <th>BRANCH</th>
                        <th>LOAN PURPOSE</th>
                    </tr>
                    <?php foreach ($this->loancllect_list as $index => $rs){ ?>
                    <tr height="40px">
                        <td><?php echo $index+1;?></td>
                        <td><?php echo $rs['member_id']?></td>
                        <td><?php echo $rs['member_id']?></td>
                        <td><?php echo $rs['loan_number']?></td>
                        <td><?php echo $rs['graice_period']?></td>
                        <td><?php echo $rs['payment_method']?></td>
                        <td><?php echo $rs['currency_type']?></td>
                        <td><?php echo $rs['collect_typeterm']?></td>
                        <td><?php echo $rs['branch_id']?></td>
                        <td><?php echo $rs['group_id']?></td>
                    </tr>
                    <?php }?>
                    
                   
                </table>
   		</td>
  	 </tr>
  </table>