<meta charset="utf-8"><meta charset="utf-8">
<title>Report Loan Payment Detail</title>
<div style="width:21cm; margin:0 auto;">
<table width="100%">
	<tr>
    	<td>
    		<h4 style="font-size:14px; font-family:'Khmer OS Muol';​​​" align="center">របាយការណ៏បង់ប្រាក់</h4>
    	</td>
   	</tr>
    <tr>
    	<td>
        	<table width="100%">
            	<tr>
                	<td><p>Branch Apple sihanoukville</td>
                 </tr>
                 <tr>
                    <td><p >Pay Status Normal Loan Payment</p></td>
                 </tr>
                 <tr>
                    <td><p>FromData 6/13/2014 ToData 6/13/2014</p></td>
                </tr>
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
                <tr align="center" bgcolor="#FFFFCC">
                    <td>date</td>
                    <td>payData</td>
                    <td>code</td>
                    <td>Applicatio</td>
                    <td>month</td>
                    <td>year</td>
                    <td>total</td>
                </tr>
            </table>
            <hr style="height: 2px; width:100%; color: #005;">
    	</td>
    </tr>
</table>
</div>
