<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
?>
<title><?php echo $tr->translate("RPT PAYMENT");?></title>

<form method="post">
<table style="font-family: 'Khmer OS Content';float: left;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>   			
   			<td><?php echo $frm->getElement('client_name');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>   			
   			<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
</form>
<br/><br/><br/><br/><br/>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_PAYMENT");?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr>
                				<td  style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
	              	<tr><td colspan="8" class="style"><?php if(!empty($this->loantotalcollect_list)) 
	              	foreach ($this->loantotalcollect_list as $index => $rs)
	              			if ($index==0) {
	              				 echo $tr->translate("LOAN_NO").':'.$rs["loan_number"].','.$tr->translate("CUSTOMER_NAME").':'.$rs["client_name"].',';
	              				 echo $tr->translate("SEX").':';
	              					if ($rs['sex']==1){
	              					echo "M";
	              				}
	              				else {
	              					echo "F";
	              				}
	              			}
	              			else {
	              				echo  "";

	              			}
	              			?>
	              	</td></tr>
	                <tr bgcolor="#ccc" class="style" align="center" style="padding:5px 0;height: 20px;">
	                    <th><?php echo $tr->translate("NUM");?></th>
	                    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th><?php echo $tr->translate("PRINCIPLE");?></th>                   
	                    <th><?php echo $tr->translate("INTEREST");?></th>
	                    
	                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
	                    <th><?php echo $tr->translate("SERVICE CHARGE");?></th>	 
	                    <th><?php echo $tr->translate("TOTAL");?></th>                   
	                    <th><?php echo $tr->translate("PAY_DATE");?></th>
	                    <th bgcolor="#999"><?php echo $tr->translate("RECIEPT_NO");?></th>
	                    
	                    <th bgcolor="#999"><?php echo $tr->translate("PAYMENTED");?></th>
	                     <th bgcolor="#999"><?php echo $tr->translate("RETURN_AMOUNT");?></th>
	                      <th bgcolor="#999"><?php echo $tr->translate("BALANCE");?></th>
	                      <th bgcolor="#999"><?php echo $tr->translate("INPUT_DATE");?></th>
	                </tr>
                <?php $principle_r = 0;$interst_r = 0;$penalize_r = 0;$service_charge_r = 0;$balane_r = 0;
                	  $principle_b = 0;$interst_b = 0;$penalize_b = 0;$service_charge_b = 0;$balane_b = 0;
                	 $principle_d = 0; $interst_d = 0; $penalize_d= 0; $service_charge_d = 0;$balane_d = 0;
                	 $i=1;
                	?>
                <?php if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
                <?php $balance=$rs["amount_payment"]-$rs["total_payment"];?>
                 <?php 
		               if($rs['currency_type']==1){
		               		$principle_r = $principle_r+$rs['total_principal_permonth'];
		               		$interst_r = $interst_r+$rs['total_interest'];
		               		$penalize_r = $penalize_r+$rs['penalize_amount'];
		               		$service_charge_r = $service_charge_r+$rs['service_charge'];
		               		$balane_r=$balane_r+$balance;
		               		
		               }elseif($rs['currency_type']==2){
							$principle_d = $principle_d+$rs['total_principal_permonth'];
							$interst_d = $interst_d+$rs['total_interest'];
							$penalize_d = $penalize_d+$rs['penalize_amount'];
							$service_charge_d = $service_charge_d+$rs['service_charge'];
							$balane_d=$balane_d+$balance;
							
		               }else{
		               		$principle_b = $principle_b+$rs['total_principal_permonth'];
							$interst_b = $interst_b+$rs['total_interest'];
							$penalize_b = $penalize_b+$rs['penalize_amount'];
							$service_charge_b = $service_charge_b+$rs['service_charge'];
							$balane_b=$balane_b+$balance;
						
		               }
               ?>	
               
               
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
               		<td>&nbsp;&nbsp;<?php echo $rs["branch_name"];?></td>
               		
               		               		
               		
               		
               		<td>&nbsp;&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?></td>
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?></td>
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["total_payment"],2);?>
               		<td>&nbsp;&nbsp;<?php echo $rs["date_pay"];?></td>
               		<td>&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
               		
               		</td>
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["amount_payment"],2);?></td>
               		<td>&nbsp;&nbsp;<?php echo number_format($rs["return_amount"],2);?></td>
               		<td>&nbsp;&nbsp;<?php   if($balance<0){echo '('.abs($balance).')';}else {echo $balance=0;};?></td>
               		<td>&nbsp;&nbsp;<?php echo $rs["date_input"];?></td>
                </tr>
                <?php }?>
                <br />
                <tr>
                	<td colspan="13">&nbsp;</td>
                </tr>
                  <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center;" >
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("CURRENT_TYPE");?>&nbsp;</th>
	                    <th style="padding:5px 0px;" colspan="3">&nbsp;<?php echo $tr->translate("TOTAL_PRINCIPLE");?>&nbsp;</th>
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_INTEREST");?>&nbsp;</th>
	                    <th style="padding:5px 0px;"colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_PENELIZE");?>&nbsp;</th>
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?>&nbsp;</th>
	                    <th style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_BALANCE");?>&nbsp;</th>
	                    
	                </tr>
                	 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td colspan="3">&nbsp;<?php echo number_format($principle_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($interst_d,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($penalize_d,2);?>&nbsp;</td>
					<td colspan="2">&nbsp;<?php echo number_format($service_charge_d,2);?>&nbsp;</td>
               		<td colspan="2">&nbsp;<?php if($balane_d<0){echo '('.abs($balane_d).')';}else {echo $balane_d=0;};?>&nbsp;</td>
                </tr>
                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td colspan="3">&nbsp;<?php echo number_format($principle_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($interst_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($penalize_r,2);?>&nbsp;</td>
					<td colspan="2">&nbsp;<?php echo number_format($service_charge_r,2);?>&nbsp;</td>
               		<td colspan="2">&nbsp;<?php  if($balane_r<0){echo '('.abs($balane_r).')';}else {echo $balane_r=0;};?>&nbsp;</td>
                </tr>
                <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td colspan="2">&nbsp;<?php echo $tr->translate("BATH");?></td>
                    <td colspan="3">&nbsp;<?php echo number_format($principle_b,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($interst_b,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($penalize_b,2);?>&nbsp;</td>
					<td colspan="2">&nbsp;<?php echo number_format($service_charge_b,2);?>&nbsp;</td>
               		<td colspan="2">&nbsp;<?php if($balane_b<0){echo '('.abs($balane_b).')';}else {echo $balane_b=0;};?>&nbsp;</td>
                </tr>
                
            </table>
           
            
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>