<?php  $tran = $this->tran_schedule;

$filter = $this->frm_search;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();												
?>
<?php  $end_dat=$this->date_show;
?>
<?php 
$db_keycode = new Application_Model_DbTable_DbKeycode();
$key_code= $db_keycode->getSystemSetting(9);
$free_day=$key_code['value'];
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height:105px;">
 <div dojoType="dijit.layout.ContentPane" region="top" style="height: auto;">
 <form method="post">
	<table width="100%">
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('branch_id');?></td>
			<td><?php echo $filter->getElement('client_name');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
		</tr>
		<tr>
			
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><?php echo $filter->getElement('btn_search');?></td>
		</tr>
	</table>
	</form>
 </div>
</div>

<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style=" width:29cm; min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 5px;">
	<div id="divPrint">
	<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label><?php ?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></h2>
	                	<h2 style="text-align:center; font-size:13px;"><?php echo date("D-d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
                    </td>
	                    <td width="20%"></td>
	                </tr>
	                <?php 
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%">
	                			<tr class='style'>
	                				<td width="40%">
	                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
	                				</td>
	                				<td></td>
	                				
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel"  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%">
	                 <tr class="style" align="center" bgcolor="#ccc">
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("LOAN_NO");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("PHONE");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("CO_NAME");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("RELEASE_DATE");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("LIFE_LOAN");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("LOAN_AMOUNT");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("DAY_PAYMENT");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("TIME_COLLECT");?></th>
	                    <th colspan="5" style="padding:5px 0px;"><?php echo $tr->translate("PAYMENT");?></th>
	                    <th rowspan="2" style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("LATE_DAY");?></th>
	                    <th rowspan="2" style="padding:5px 0px;"><?php echo $tr->translate("OTHER");?></th>
	                </tr>
	                <tr class="style" bgcolor="#ccc">
	                    <th style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("PRINCIPAL_PERMONTH");?></th>
	                    <th style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("INTEREST");?></th>
	                    <th  style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
	                    <th  style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
	                 	<th  style="text-align:center ;padding:5px 0px;"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
	                </tr>
	                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
		             ?>
	               <?php foreach($tran as $key =>$row){?>
	               	<tr align="center" style="font-size:10px; height: 20px;" class="style">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <td align="left">&nbsp;<?php echo $row['branch_kh'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
	                     <td align="left" style="white-space: nowrap;">&nbsp;<?php echo $row['phone_number'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo $row['co_name'];?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo date("d-M-Y",strtotime($row['date_release']));?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo date("d-M-Y",strtotime($row['date_line'])) ;?>&nbsp;</td>
	                     <td align="left">&nbsp;<?php echo number_format($row['total_capital'],2) ;?>&nbsp;</td>
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    <td align="center"><?php echo date('d-m-Y',strtotime($row['date_payment']));?>&nbsp;</td>
	                    <td align="center"><?php echo str_replace(' ', '',$row['time_collect']);?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['principle_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php 
	                    $total_pay=($row['principle_after']+$row['total_interest_after']);
	                    if ($row['last_pay_date']==null or $row['last_pay_date']==""){
	                    	$total_day=strtotime($end_dat)-strtotime($row['date_payment']);
	                    	$amount_lateday=$total_day/(60*60*24)-$free_day;
	                    }else {
	                    	$total_day=strtotime($end_dat)-strtotime($row['last_pay_date']);
	                    	$amount_lateday=$total_day/(60*60*24);
	                    }
	                    $pay_term=$row['collect_typeterm'];
	                    if($amount_lateday<0){
	                    	$amount_lateday=0;
	                    	$result=0;
	                    }
	                    else {
	                    	$total_late=($row['principle_after']+$row['total_interest_after']);
	                    	if ($pay_term==1){
	                    		$result=$total_pay*($row['pay_after']*($row['interest_rate']/100)/1)*($amount_lateday);
	                    	}
	                    	if ($pay_term==2){
	                    		$result=$total_pay*($row['pay_after']*($row['interest_rate']/100)/7)*($amount_lateday);
	                    	}
	                    	if ($pay_term==3){
	                    		$result=$total_pay*($row['pay_after']*(($row['interest_rate']/100)/30))*($amount_lateday);
	                    	}
	                    }
	                    $penelize = $row['penelize']+$result;
	                    //echo $penelize;
	                    echo str_replace('.00', '', number_format($penelize,2));?>&nbsp;
	                    </td>
	                   	<td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['service_charge'],2));?>&nbsp;</td>
	                    <td><?php 
	                    		$total_payment = $penelize+$row['principle_after']+$row['total_interest_after']+$row['service_charge'];
	                    		echo str_replace('.00', '', number_format($total_payment,2));?> 
	                   </td>
	                   <td><?php
	                          echo $amount_lateday;
							?></td>
	                   <td>&nbsp;&nbsp;</td>
	                   
	                </tr>
	                
		                <?php //if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $row){ ?>
		                <?php 
				               if($row['currency_type']==1){
				               		$amt_r1 = $amt_r1+$row['principle_after'];
				               		$amn_r2 = $amt_r2+$row['total_interest_after'];
				               		$amn_r3 = $amt_r3+$penelize;
				               		$amn_r4 = $amt_r4+$total_payment;
				               		$amn_r5 = $amt_r5+$row['service_charge'];
				               		$total_r=$amn_r4;
				               }elseif($row['currency_type']==2){
									$amt_d1 = $amt_d1+$row['principle_after'];
									$amt_d2 = $amt_d2+$row['total_interest_after'];
									$amt_d3 = $amt_d3+$penelize;
									$amt_d4 = $amt_d4+$total_payment;
									$amt_d5 = $amt_d5+$row['service_charge'];
									$total_d=$amt_d4;
				               }else{
				               		$amn_b1 = $amn_b1+$row['principle_after'];
									$amn_b2 = $amn_b2+$row['total_interest_after'];
									$amn_b3 = $amn_b3+$penelize;
									$amn_b4 = $amn_b4+$total_payment;
									$amn_b5 = $amn_b5+$row['service_charge'];
									$total_b=$amn_b4;
				               }
		            // }
		               ?>
	                <?php }?>
	                
	            </table>
	            
	            <br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" bgcolor="#ccc" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td style="font-size: 12px;"></td>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PRINCIPLE");?></th>                    
                    <th style="font-size: 12px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("SERVICE_CHARGE");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("PAYMENT");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r4,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($total_r,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b4,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($total_b,2);?>&nbsp;</td>
                </tr>
                
              </table>
	            <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>