<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
//echo $this->headTitle($tr->translate("IL Payment"));
$frm = $this->frm_search;
?>
<title><?php echo $tr->translate("RPT PAYMENT");?></title>
<form method="post">
<table style="font-family: 'Khmer OS Content';float: right;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement('paymnet_type');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
</form>

<div dojoType="dijit.layout.BorderContainer" style="width: 100%; ">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<style>
.style{
	line-height: 20px;font-size: 11px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
                	 $co_id = null;
                ?>
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_COLLECT_BY_CO");?></h2>
                	<h2 style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></h2>
               </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
</table>
<div id="exportExcel">
<table  width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
		        <tr class="style" bgcolor="#ccc" align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
			      <th><?php echo $tr->translate("NUM");?></th>
			      <th ><?php echo $tr->translate("BRANCH_NAME");?></th>
			      <th ><?php echo $tr->translate("CO_NAME");?></th>
			      <th ><?php echo $tr->translate("RECIEPT_NO");?></th>
			      <th ><?php echo $tr->translate("LOAN_NO");?></th>
			      <th ><?php echo $tr->translate("CLIENT_NAMEKH");?></th>
			      <th ><?php echo $tr->translate("PRINCIPLE");?></th>                    
			      <th ><?php echo $tr->translate("INTEREST RATE");?></th>
			      <th ><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
			      <th ><?php echo $tr->translate("PAYMENT");?></th>
			      <th ><?php echo $tr->translate("SERVICE_CHARGE");?></th>
			      <th ><?php echo $tr->translate("PAY_DATE");?></th>
			   	</tr>
<?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){?>
	
     <?php if($co_id!=$rs["co_id"]){ ?>
				<tr>
					<td colspan="12" style="font-size: 14px; font-weight:500; background:#CADEE3;"><b><?php echo $rs["co_name"];?></b></td>
				</tr>
	<?php $co_id = $rs["co_id"];}?>
			   	<tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 11px;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["branch"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["co_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["receipt_no"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["team_group"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format( $rs["total_principal_permonth"],2).' '.$rs['currency_typeshow'];?></td>               		
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format($rs["penalize_amount"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format($rs["amount_payment"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format($rs["service_charge"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo $rs["date_pay"];?></td>
                </tr>

<?php  }?>
</table>
</div>
</div>
</div>
</div>
