<?php 
error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LIST_EXPECT_INCOME"));
$frm = $this->frm_search;
?>

<form method="post">
<table style="font-family: 'Khmer OS Content';float: right;" >
	<tr>
   			<td><?php echo $frm->getElement("advance_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   		</tr>
   		<tr>   			
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement("btn_submit");?></td>
   	</tr>
</table>
</form>
<br/><br/><br/><br/><br/>
<div style="width:100%; margin:0 auto;">
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint">
<table width="100%">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_EXPECT_INCOME");?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;" cellspacing="0">
                <tr align="center" style="font-weight:bold; line-height: 24px; font-size:11px; padding:10px 0px; ">
                    <th style="font-size: 12px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                     <th style="font-size: 12px;"><?php echo $tr->translate("LOAN_NO");?></th> 
                      <th style="font-size: 12px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>                   
                    <th style="font-size: 12px;"><?php echo $tr->translate("INTEREST");?></th>
                    <th style="font-size: 12px;"><?php echo $tr->translate("DAY_PAYMENT");?></th>
                </tr>
                <?php $amt_r1 = 0;
                	  $amt_d1 = 0;
                	 $amn_b1 = 0; 
                ?>
                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
                <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$rs['total_interest'];
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$rs['total_interest'];
		               }else{
		               		$amn_b1 = $amn_b1+$rs['total_interest'];
		               }
		               //print_r($rs);exit();
               ?>
                <tr class="style" style="font-family: 'Khmer OS Content';">
               		<td style="font-size: 11px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["branch"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["loan_number"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo $rs["client_name"];?></td>
               		<td style="font-size: 11px;">&nbsp;&nbsp;<?php echo number_format($rs["total_interest"],2).' '.$rs['currency_typeshow'];?></td>
               		<td style="font-size: 11px;text-align: center;"><?php echo $rs["date_payment"];?></td>
                </tr>
                <?php }?>
            </table>
            <br /><br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:12px;font-family: 'Khmer OS Content';">
                    <td></td>                 
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:11px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                </tr>
              </table>
               <br />
              <table align="center" width="100%">
				    <tr style="font-size: 12px;">
				        <th style="width:20%;"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>
