<?php $tran = $this->tran_schedule;
$client = $this->client;
?>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<table style="font-family: 'Khmer OS Content'; width:60%; float: right;" >
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height:50px;">
 
</div>
<div style=" width:21cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<div id="divPrint">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td>sss</td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 24px;">
                    <td>លរ</td>
                    <td>ឈ្មោះអតិថិជន</td>
                    <td>ប្រាក់ដើមនៅសល់</td>
                    <td>ប្រាក់ដើមត្រូវបង់</td>
                    <td>ការប្រាក់</td>
                    <td>ផាកពិន័យ</td>
                    <td>ប្រាក់បានបង់</td>
                    <td>សមតុល្យ</td>
                    <td>សម្គាល់</td>
                    <td>កាលបរិឆ្ឆេទ</td>
                </tr>
               	<tr align="center" style="font-weight:bold; font-family:'Khmer OS';">
                    <td ><?php //echo $key+1;?></td>
                    <td><?php //echo$row['date_payment']?></td>
                    <td><?php //echo number_format($row['total_principal'],(!strrpos($row['total_principal'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['principal_permonth'],(!strrpos($row['principal_permonth'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['total_interest'],(!strrpos($row['total_interest'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['total_payment'],(!strrpos($row['total_payment'],"."))? 0 : 2); ?></td>
                    <?php 
                    //$remain = $row['total_principal']-$row['principal_permonth']
                    ?>
                    <td><?php //echo number_format($remain,(!strrpos($remain,"."))? 0 : 2);?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr align="center" style="font-weight:bold; font-family:'Khmer OS';">
                    <td ><?php //echo $key+1;?></td>
                    <td><?php //echo$row['date_payment']?></td>
                    <td><?php //echo number_format($row['total_principal'],(!strrpos($row['total_principal'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['principal_permonth'],(!strrpos($row['principal_permonth'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['total_interest'],(!strrpos($row['total_interest'],"."))? 0 : 2);?></td>
                    <td><?php //echo number_format($row['total_payment'],(!strrpos($row['total_payment'],"."))? 0 : 2); ?></td>
                    <?php 
                    //$remain = $row['total_principal']-$row['principal_permonth']
                    ?>
                    <td><?php //echo number_format($remain,(!strrpos($remain,"."))? 0 : 2);?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                	<td colspan="4"></td>
                	<td></td>
                	<td></td>
                	<td></td>
                	<td></td>
                	<td colspan="2">12,100 $</td>
                </tr>
            </table>
            <br />
             <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>