<?php $frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("LOAN_OUTSTADING");?></title>
<form method="post">
<table style="font-family: 'Khmer OS Content';float: left;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   	</tr>
   	<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement("btn_search");?></td>
   	</tr>
</table>
</form>
<br /><br /><br /><br /><br />
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint" style="width: 100%;">

<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LOAN_OUTSTADING");?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                				
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 13px; font-size:12px;padding: 5px 0px;">
                    <th style="padding:5px 0px;"><?php echo $tr->translate("NUM");?></th>
                    <th style="padding:5px 0px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("LOAN_NO");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("NUMBER_CODE");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("CO_NAME");?></td>
                    <td style="padding:5px 0px;"><?php echo $tr->translate("TERM_BORROW");?></td>
                    <th>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</th>
                    <th>&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</th>
                   
                    <th>&nbsp;<?php echo $tr->translate("LOAN_RETURN_TO_CLIENT");?>&nbsp;</th>
                    <th>&nbsp;<?php echo $tr->translate("PERCENTAGE");?>&nbsp;</th>
                    <th>&nbsp;<?php echo $tr->translate("NOT_TO_REPAY");?>&nbsp;</th>
                </tr>
               <?php 
               $amt_r = 0;$amt_d = 0;$amt_b = 0; $amn_r = 0;$amn_d = 0;$amn_b = 0;$result_b=0;$result_r=0;$result_d=0;
//                print_r($this->loanrelease_list);
               if(!empty($this->outstandloan)) foreach($this->outstandloan as $key =>$row){?>
               <?php 
               if($row['curr_type']==1){
               		$amt_r = $amt_r+$row['total_capital'];
               		$amn_r = $amn_r+$row['total_payment'];
               		$result_r=number_format(($amn_r/$amt_r)*100,2).' %';
               }elseif($row['curr_type']==2){
               		$amt_d = $amt_d+$row['total_capital'];
               		$amn_d = $amn_d+$row['total_payment'];
               		$result_d=number_format(($amn_d/$amt_d)*100,2).' %';
               }else{
               		$amt_b = $amt_b+$row['total_capital'];
               		$amn_b = $amn_b+$row['total_payment'];
               		$result_b=number_format(($amn_b/$amt_b)*100,2).' %';
               }
               ?>
					<tr align="center">
					<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
					<td style="line-height: 12px; white-space: nowrap;">&nbsp;<?php echo $row['branch_name']; ?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['loan_number'];?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['client_id'];?>&nbsp;</td>
					<td align="left" style="font-size:9px; line-height: 13px; white-space: nowrap;">&nbsp;<?php echo $row['client_kh']; ?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['co_name'];?>&nbsp;</td>
					
					<td style="white-space: nowrap;">&nbsp;<?php echo date('d-m-Y',strtotime($row['date_release']));?>&nbsp;</td>
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_capital'],2).' '.$row['currency_type']; ?>&nbsp;</td>
					<td style="white-space: nowrap;">&nbsp;<?php echo number_format($row['total_duration']).$row['pay_term'];?>&nbsp;</td>
					
					<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['total_payment'],2);?>&nbsp;</td>
					<td>&nbsp;<?php 
						
							echo (round(($row['total_payment']/$row['total_capital']),2)*100).' %';
						
						
					?>&nbsp;</td>
					<td>&nbsp;<?php echo $row['total_capital']-$row['total_payment'];?>&nbsp;</td>
					</tr>
				<?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px;" width="100%" cellspacing="0">
                 <tr class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:11px;">
                    <td></td>
                    <td><?php echo $tr->translate("TOTAL_AMOUNT");?></td>
                    <td><?php echo $tr->translate("TOTAL_RECIEPT");?></td>
                    <td><?php echo $tr->translate("PERCENT");?></td>
                    <td><?php echo $tr->translate("TOTAL");?></td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;<?php echo number_format($amt_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_d,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_d;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_d-$amn_d,2);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;<?php echo number_format($amt_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_r;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_r-$amn_r);?>&nbsp;</td>
                </tr>
                 <tr class="style" style="font-weight:bold; line-height: 24px; font-size:11px;">
                    <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amn_b,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo $result_b;?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($amt_b-$amn_b);?>&nbsp;</td>
                </tr>
              </table>
              <br />
              <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
