<?php $tran = $this->tran_schedule;
$client = $this->client;
?>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height:50px;">
 <div dojoType="dijit.layout.ContentPane" region="top" >

 </div>
</div>
<div style=" width:21cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label>សុខាមីក្រូហិរញ្ញវត្ថុ</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'">បញ្ជីចេញប្រាក់ឥណទាន</h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					ផ្ទះលេខ ១៦២ ផ្លូវលេខ ១៥០ សង្កាត់ ទឹកល្អក់១ ទូលគោក ភ្នំពេញ
								<br />TEL :(855) 10 78 55 44
                				</td>
                				<td></td>
                				<td>ឈ្មោះមន្ត្រី ឥណទាន : <?php echo ($client['displayby']==1)?$client['co_khname']:$client['co_enname'] ;?></td>
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
                 <tr class="style" align="center" style="font-weight:bold; line-height: 24px;">
                    <td>លរ</td>
                    <td>លេខកំម្ជី</td>
                    <td>ឈ្មោះអតិថជន</td>
                    <td>ចំនួនប្រាក់បានចេញ</td>
                    <td>អត្រាការប្រាក់</td>
                    <td>រយៈពេលខ្ចី</td>
                    <td>កាលបរិឆ្ឆេទ</td>
                    <td>ឈ្មោះមន្ត្រីឥណទាន</td>
                    <td>ថ្លែរដ្នបាល</td>
                </tr>
               <?php foreach($this->loanrelease_list as $key =>$row){?>
					<tr align="center">
					<td><?php echo $key+1; ?></td>
					<td><?php echo$row['loan_number']?></td>
					<td><?php echo$row['client_id']?></td>
					<td><?php echo$row['amount_collect_principal']?></td>
					<td><?php echo$row['interest_rate']?></td>
					<td><?php echo$row['total_duration']?></td>
					<td><?php echo$row['date_release']?></td>
					<td><?php echo$row['co_name']?></td>
					<td><?php echo$row['admin_fee']?></td>
					</tr>
				<?php }?>
            </table>
    	</td>
    </tr>
</table>
</div>
