<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RETURN_COLLETERAL"));
	$frm=$this->frm_returnCollteral;
?>

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'Returncollteral','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table>
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('collteral_type');?></td>
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><?php echo $frm->getElement('status_search');?></td>
			<td><?php echo $frm->getElement('btn_search');?></td>
		</tr>
		
	</table>
	<?php echo $this->list;?>
</form>
