<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_accountname;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'Accountname','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>Accountname</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td><?php echo $tr->translate("Acount Code")?></td>
							<td><?php echo $frm->getElement('account_id');?></td>
							<td><?php echo $tr->translate("Account NameKh")?></td>
							<td><?php echo $frm->getElement('account_namekh');?></td>
							<td><?php echo $tr->translate("Account NameEg")?></td>
							<td><?php echo $frm->getElement('account_nameeg');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Description")?></td>
							<td><?php echo $frm->getElement('description');?></td>
							<td><?php echo $tr->translate("Type")?></td>
							<td><?php echo $frm->getElement('account_type');?></td>
							<td><?php echo $tr->translate("Option")?></td>
							<td><?php echo $frm->getElement('optionacc');?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("Dispay By")?></td>
							<td><?php echo $frm->getElement('dispay_by');?></td>
							<td><?php echo $tr->translate("Date")?></td>
							<td><?php echo $frm->getElement('date');?></td>
							<td><?php echo $tr->translate("Parent")?></td>
							<td><?php echo $frm->getElement('parent_acc');?></td>
							
						</tr>
						<tr>
						    <td><?php echo $tr->translate("Gotegories")?></td>
							<td><?php echo $frm->getElement('categories');?></td>
							<td><?php echo $tr->translate("Status")?></td>
							<td><?php echo $frm->getElement('status');?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
</script>
