<?php
	$this->headTitle('Add Transfer'); 
	echo $this->headTitle();
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>

<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'tranferco','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
  if(this.validate()) {
  }else{
	return false;
   }
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>TRANSFER_CO</strong></legend>
					<table cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php  echo $frm->getElement('branch_name');?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php  echo $frm->getElement('Date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CODE_CO")?></td>
							<td><?php  echo $frm->getElement('co_code');?></td>
							<td><?php echo $tr->translate("FROM_CO")?></td>
							<td><?php  echo $frm->getElement('formc_co');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TO_CO")?></td>
							<td><?php  echo $frm->getElement('to_co');?></td>
							<td><?php echo $tr->translate("CO_ID")?></td>
							<td><?php  echo $frm->getElement('to_co_code');?></td>
						</tr>
					    <tr>  
					        <td><?php echo $tr->translate("USER_ID")?></td>
							<td><?php  echo $frm->getElement('user_id');?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('Note');?></td>
							<td></td>
							<td></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" name="btn_save" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" label="រក្សាទុក & ចាកចេញ" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<?php $url_close = $this->url(array('module'=>'loan','controller'=>'transferco','action'=>'index'),null,true); ?>
			<a href="<?php echo $url_close ?>">
				<input type="button" value="ចាកចេញ" name="btn_close" label="ចាកចេញ" id="submitButton_Close" dojoType="dijit.form.Button"  iconClass=" dijitIconCancel"/>							
			</a>
		</td>
	</tr>	
</table>
</form>
