 <input type="button" label="បញ្ជីឈប់សំរាក" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-holiday')); ?>';"/>
  
  <input type="button" label="បញ្ជីបុគ្គលិក" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-staff')); ?>';"/>