<title>Report Staff</title>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>

<div style=" width="100%"  margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['brand_Staff'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                			</tr>
			              </table>
		              </td>
		           </tr>   
            </table>
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">  
    	<tr bgcolor="#BBBBBB" >
        	<th>&nbsp;N<sup>0</sup></th>
            <th>&nbsp;StaffID</th>
            <th style="white-space: pre;">&nbsp;Name Khmer</th>
            <th style="white-space: pre;">&nbsp;Name Eng</th>
            <th>&nbsp;Sex</th>
            <th>&nbsp;Phone</th>
            <th>&nbsp;National_id</th>
            <th>&nbsp;Adress</th>
            <th>&nbsp;Degree</th>
            <th>&nbsp;Email</th>
            <th style="white-space:nowrap;">&nbsp;Basic salary</th>
            <th style="white-space:nowrap;">&nbsp;Start date</th>
            <th style="white-space:nowrap;">&nbsp;End date</th>
            <th style="white-space:pre;">&nbsp;Number of Contract</th>
            <th>&nbsp;Shift</th>
            <th style="white-space: pre;">&nbsp;Working hour</th>
            <th>&nbsp;Position</th>
            <th style="white-space: pre;">&nbsp;Branch Name</th>
           <th>&nbsp;Note</th>
         </tr>
       <?php foreach($this->staff_list as $key =>$row){?>
		   <tr style="font-size: 11px;">
		     <td>&nbsp;<?php echo $key+1; ?></td>
		     <td>&nbsp;<?php echo $row['co_code']?></td>
			 <td>&nbsp;<?php echo $row['co_khname']?></td>
			 <td>&nbsp;<?php echo $row['co_firstname']?></td>
			 <td>&nbsp;<?php echo $row['sex']?></td>
			 <td>&nbsp;<?php echo $row['tel']?></td>
			 <td>&nbsp;<?php echo $row['national_id']?></td>
			 <td style="white-space: pre;">&nbsp;<?php echo $row['address']?></td>
			 <td>&nbsp;<?php echo $row['degree']?></td>
			 <td>&nbsp;<?php echo $row['email']?></td>
			 <td>&nbsp;<?php echo $row['basic_salary']?></td>
			 <td>&nbsp;<?php echo $row['start_date']?></td>
			 <td>&nbsp;<?php echo $row['end_date']?></td>
			 <td>&nbsp;<?php echo $row['contract_no']?></td>
			 <td>&nbsp;<?php echo $row['shift']?></td>
			 <td>&nbsp;<?php echo $row['workingtime']?></td>
			 <td>&nbsp;<?php echo $row['position']?></td>
			 <td>&nbsp;<?php echo $row['branch_name']?></td>
			 <td>&nbsp;<?php echo $row['note']?></td>
			</tr>
		<?php }?>
		 <?php for($i=$key; $i<=14;$i++){?>
			<tr align="center">
			 <td><?php echo $i+1; ?></td>
		     <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 <td></td>
			 </tr>
		 <?php }?>
				

    </table>
 </div>