<?php 
//error_reporting(0);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("REPORT HOLIDAY");?>Report Holiday</title>
<div style=" width:21cm; margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';

}
</style>	
 <form name="frm_rptholiday" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-holiday')); ?>" dojoType="dijit.form.Form" method="post">
<table style="font-family: 'Khmer OS Content'; width:100%;">	
	<tr><td align="right">
		<input type="text" name="txtsearch" id="txtsearch" placeholder=" (Holiday Name)"  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search">ស្វែង​រក</button>
	</td></tr>
	<tr>
    	<td align="center">
    	   <div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php echo $this->data['brand_holiday'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        <table align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <tr bgcolor="#BBBBBB">
				        <th><?php echo $tr->translate("NO");?></th>
				        <th><?php echo $tr->translate("HOLIDAY_NAME");?></th>
				        <th><?php echo $tr->translate("DATE");?></th>
				        <th><?php echo $tr->translate("AMOUNT");?></th>
				        <th><?php echo $tr->translate("NOTE");?></th>
				    </tr>
					<?php $amount_day = 0;
					 
					if(!empty($this->holiday_list)) 
						foreach($this->holiday_list as $key =>$row){
					 	$amount_day=$amount_day+$row['amount_day'];
					 	?>
					     <tr align="center">
					        <td><?php echo $key+1; ?></td>
					        <td><?php echo $row['holiday_name']?></td>
					        <td><?php echo $row['start_date']?></td>
					        <td><?php echo $row['amount_day']?></td>
					        <td><?php echo $row['note']?></td>
					    </tr>
					    <?php }?>
					 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
						  <tr align="center">
						        <td><?php echo $i+1; ?></td>
						        <td></td>
						        <td></td>
						        <td></td>
						        <td></td>
						    </tr>
					 <?php }?>
				
				    <tr align="center">
				        <td colspan="2"></td>
				        <th>Total</th>
				        <td><?php echo $amount_day; ?></td>
				        <td></td>
				    </tr>
				   </table><br />
				   <table align="center" width="100%">
				    <tr >
				        <th style="width:20%;border-bottom:1px dashed black;">Approved By</th>
				        <th></th>
				        <th style="width:20%;border-bottom:1px dashed black;">Verifyed By</th>
				        <th></th>
				        <th style="width:20%;border-bottom:1px dashed black;">Prepare By</th>
				   </tr>
				   </table>
			</div>
		</td>
		</tr>	
		</table>
		</form>  		  
 </div>