<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("ZONE_LIST"));
$frm = $this->frm_zone;
?>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<form name="frm_rptholiday" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-zone')); ?>" dojoType="dijit.form.Form" method="post">
<table style="float: right;">
	<tr>
		<td align="right">
			<?php echo $frm->getElement("adv_search");?>
    		<?php echo $frm->getElement('search_status');?>
 			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
   		</td>
	</tr>	
</table>
</form>
<br /><br /><br />
<div style=" width:21cm; margin:0 auto;">


<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm"> 
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	  <div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<!--  <h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2> -->
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $this->data['brand_zone'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr>
                				<td class='style' width="45%" style="font-size: 10px;">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
	
			<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
		    	<tr bgcolor="#BBBBBB" >
		        	<th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo  $tr->translate("NUM");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo  $tr->translate("ZONE_NAME");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo  $tr->translate("ZONE_NUMBER");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo  $tr->translate("DATE");?></th>
		           
		         </tr>
		        <?php if(!empty($this->zone_list))foreach($this->zone_list as $key =>$row){?>
				   <tr align="center" style="font-size: 10px;">
				     <td>&nbsp;&nbsp;<?php echo $key+1; ?></td>
				     <td align="left">&nbsp;&nbsp;<?php echo $row['zone_name']?></td>
					 <td>&nbsp;&nbsp;<?php echo $row['zone_num']?></td>
					 <td>&nbsp;&nbsp;<?php echo $row['modify_date']?></td>
					</tr>
				<?php }?>
				 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
					<tr align="center">
					 <td><?php $key; echo $i+1; ?></td>
					 <td></td>
					 <td></td>
					 <td></td>
				    </tr>
				<?php }?>
		
		    </table><br />
		    <table align="center" width="100%">
				    <tr >
				        <th style="width:20%;">Approved By</th>
				        <th></th>
				        <th style="width:20%;">Verifyed By</th>
				        <th></th>
				        <th style="width:20%;">Prepare By</th>
				   </tr>
			</table>
		 </div>
		</td>
	</tr>
</table>
</div>
</div>