<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("BRANCH_LIST"));
?>	
<?php $frm =  $this->frm_branch;?>
<table style="float: right;">
	
	<tr>	
	 	<td><?php echo $frm->getElement('adv_search') ?></td>
	 	<td><?php echo $frm->getElement('status_search');?></td>
	 	<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button></td>
	 </tr>
</table>
<div style=" width:21cm; margin:0 auto;">
<style>
.style{
	line-height: 20px;font-size: 12px !important;
	font-family: 'Khmer OS Battambang';

}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	<div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:14px; font-family:'Khmer OS Muol'"><label><?php echo $this->data['brand_name'];?></label></h2>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%" style="font-size: 9px;">
                			<tr class='style'>
                				<td width="45%" style="font-size: 9px;">
                					<span style="font-size: 9px;" class="style"><?php echo $this->data['brand_adress'];?></span>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                				<td></td>
                				
                				<td></td>
                			</tr>
			               
		                </table>
		              </td>
		           </tr>   
            </table>
        	<table align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <tr bgcolor="#BBBBBB">
				        <th><?php echo $tr->translate("BR_ID");?></th>
				        <th><?php echo $tr->translate("BRANCH_KHMER");?></th>
				        <th><?php echo $tr->translate("BRANCH_NAMEEN");?></th>
				        <th><?php echo $tr->translate("BRANCH_ADDRESS");?></th>
				        <th><?php echo $tr->translate("BRANCH_CODE");?></th>
				        <th><?php echo $tr->translate("BRANCH_TEL");?></th>
				        <th><?php echo $tr->translate("FAX");?></th>
				        <th><?php echo $tr->translate("OTHER");?></th>
				    </tr>
					<?php 
					 foreach($this->branch_list as $key =>$row){
					 	?>
					     <tr align="center">
					        <td><?php echo $key+1; ?></td>
					        <td><?php echo $row['branch_namekh']?></td>
					        <td><?php echo $row['branch_nameen']?></td>
					        <td><?php echo $row['br_address']?></td>
					        <td><?php echo $row['branch_code']?></td>
					        <td><?php echo $row['branch_tel']?></td>
					        <td><?php echo $row['fax']?></td>
					        <td><?php echo $row['other']?></td>
					    </tr>
					    <?php }?>
				   </table>
			</div>
			</td>
		</tr>
	</table>			
 </div>