<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_holiday;
?>
<title><?php echo $tr->translate("LIST HOLIDAY");?></title>
 <form name="frm_rptholiday" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-holiday')); ?>" dojoType="dijit.form.Form" method="post">
<table style="float: right;">
	 <tr> 
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td> <?php echo $frm->getElement("start_date");?></td>
           <td><?php echo $frm->getElement("end_date");?></td>
		   <td><?php echo $frm->getElement('search_status');?></td>
		   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button></td>
   	  </tr>
</table>
 </form> 
 <style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<br /><br /><br />
<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;">	
	<tr>
    	<td align="center">
    	   <div id="divPrint">
    	  <table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                	<!-- <h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label>(សាខា ទី ២)</label></h2> -->
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_HOLIDAY");?><?php //echo $this->data['brand_holiday'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr >
                				<td class='style' width="45%" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td></td>
                				<td></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        <table id="exportExcel" align="center" border="1" width="100%" style="border-collapse:collapse;font-size: 12px;" bordercolor="black" >
				    <tr bgcolor="#BBBBBB" style="background: #BBBBBB !important;">
				        <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUM");?></th>
				        <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("HOLIDAY_NAME");?></th>
				        <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("DATE");?></th>
				        <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("AMOUNT_DAY");?></th>
				        <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NOTE");?></th>
				    </tr>
					<?php $amount_day = 0;
					 
					if(!empty($this->holiday_list)) 
						foreach($this->holiday_list as $key =>$row){
					 	$amount_day=$amount_day+$row['amount_day'];
					 	?>
					     <tr style="font-size: 10px;" align="center">
					        <td><?php echo $key + 1; ?></td>
					        <td><?php echo $row['holiday_name']?></td>
					        <td><?php echo $row['start_date']?></td>
					        <td><?php echo $row['amount_day']?></td>
					        <td><?php echo $row['note']?></td>
					    </tr>
					    <?php }?>
					 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
						  <tr align="center">
						        <td><?php $key++; echo $key+1; ?></td>
						        <td></td>
						        <td></td>
						        <td></td>
						        <td></td>
						    </tr>
					 <?php }?>
				
				    <tr align="center">
				        <td colspan="2"></td>
				        <th><?php echo $tr->translate('TOTAL');?></th>
				        <td><?php echo $amount_day; ?></td>
				        <td></td>
				    </tr>
				   </table><br />
				   <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
			</div>
		</td>
		</tr>	
		</table>	 		  
 </div>
