<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("Report Staff");?></title>
<meta charset="utf-8">
<title>តារាងបង់ប្រាក់​​ ប្រចាំអាទិត្យ</title>
<form method="post">
<table style="float: right;">
	<tr>
		<td align="right">
			<input type="text" name="txtsearch" id="txtsearch" placeholder=""  dojoType="dijit.form.TextBox"
			 style="width: 320px;  height: 30px;" value='<?php echo $this->txtsearch;?>'/>
			 <button dojoType="dijit.form.Button" showLabel="true" name="btn_search" type="submit">ស្វែង​រក</button>
		</td>
	</tr>
</table>
</form>
<br /><br /><br />
<div style=" width="100%"  margin:0 auto;">

<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<style>
.style{
	line-height: 20px;font-size: 12px;
	font-family: 'Khmer OS Battambang';
}
.MEF2{text-align:center; font-size:10px; font-family:'Khmer MEF2'}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $this->data['brand_title'];?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label>(សាខា ទី ២)</label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $this->data['brand_Staff'];?></h2></td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td width="45%">
                					<?php echo $this->data['brand_adress'];?>
								<br /><?php echo $this->data['phone_brand'];?>
                				</td>
                			</tr>
			              </table>
		              </td>
		           </tr>   
            </table>
			<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">  
		    	<tr bgcolor="#BBBBBB" >
		        	<th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NUM");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("STAFF_ID");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("CO_NAME");?></th>
		            <th​​ style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("STAFF_NAME");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("SEX");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'" ><?php echo $tr->translate("PHONE");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NATIONAL_ID");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("ADDRESS");?></th>
		           <!-- <th>&nbsp;<?php //echo $tr->translate("DEGREE");?></th>-->
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("EMAIL");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("SALARY");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("START_DATE");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("END_DATE");?></th>
		            <!--<th style="white-space:pre;">&nbsp;<?php //echo $tr->translate("NUMBER_OF_CONTROCT");?></th> 
		            <th>&nbsp;Shift<class="MEF2"/th>
		            <th style="white-space: pre;">&nbsp;<?php // echo $tr->translate("WORKING_HOUR");?></th>-->
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("POSITION");?></th>
		            <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRANCH_NAME");?></th>
		           <th style="text-align:center; font-size:10px; font-family:'Khmer MEF2'"><?php echo $tr->translate("NOTE");?></th>
		         </tr>
		       <?php if(!empty($this->staff_list))foreach($this->staff_list as $key =>$row){?>
				   <tr style="font-size: 10px;" align="center">
				     <td>&nbsp;<?php echo $key+1; ?></td>
				     <td>&nbsp;<?php echo $row['co_code']?></td>
					 <td>&nbsp;<?php echo $row['co_khname'] ." - ".$row['co_firstname']?></td>
					 <td>&nbsp;<?php echo $row['sex']?></td>
					 <td>&nbsp;<?php echo $row['tel']?></td>
					 <td>&nbsp;<?php echo $row['national_id']?></td>
					 <td style="white-space: pre;">&nbsp;<?php echo $row['address']?></td>
				<!-- 	 <td>&nbsp;<?php echo $row['degree']?></td>-->
					 <td>&nbsp;<?php echo $row['email']?></td>
					 <td>&nbsp;<?php echo $row['basic_salary']?></td>
					 <td>&nbsp;<?php echo $row['start_date']?></td>
					 <td>&nbsp;<?php echo $row['end_date']?></td>
				<!--   <td>&nbsp;<?php //echo $row['contract_no']?></td>
					 <td>&nbsp;<?php //echo $row['shift']?></td>
					 <td>&nbsp;<?php //echo $row['workingtime']?></td>-->	
					 <td>&nbsp;<?php echo $row['position']?></td>
					 <td>&nbsp;<?php echo $row['branch_name']?></td>
					 <td>&nbsp;<?php echo $row['note']?></td>
					</tr>
				<?php }?>
				 <?php if(!empty($key)) for($i=$key; $i<=14;$i++){?>
					<tr align="center">
					 <td><?php echo $i+2; ?></td>
				     <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
					 <td></td>
<!-- 					 <td></td> -->
<!-- 					 <td></td> -->
<!-- 					 <td></td> -->
<!-- 					 <td></td> -->
					 <td></td>
					 </tr>
				 <?php }?>
						
		
		    </table>
    	</td>
    </tr>
</table>
		<br />
		    <table align="center" width="100%">
				    <tr >
				        <th style="width:20%;">Approved By</th>
				        <th></th>
				        <th style="width:20%;">Verifyed By</th>
				        <th></th>
				        <th style="width:20%;">Prepare By</th>
				   </tr>
			</table>
</div>
</div>