<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Capital Transfer"));
$frm = $this->frm;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'capital','controller'=>'capital','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <?php echo $frm->getElement("search");?>
   <?php echo $frm->getElement('status');?>
   <?php echo $frm->getElement("btn_search");?>
   <?php echo $this->list;?>
</form>


