<?php
	$this->headTitle('Currency Smart | Add Money Stock'); 
	echo $this->headTitle();
	$session_user=new Zend_Session_Namespace('auth');
	$form = $this->frm;
?>	
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.require('dijit.form.Select');	
	dojo.ready(function(){
		addAmountTypeMoney();		
		
	});  
	    
</script>
<style>
<!--
	.tbtable{		
		font-weight: bolder;
		line-height: 40px;
		text-align: center;
	}
	.tbtable .tbheader{
		background-color: #012a15;
		text-align: left;
		color: #fff;
	}
	.tbtable .first{
		background-color: #016315;
		color: #fff;
	}
	.tbtable .first td{
		width: 33.33%
	}
	.tbtable .second{
		background-color: #fff; 
		color: black;
	}
	.nevg-value{
		color: RED;
	}
	.tbtable .second .input-inner {
		margin: 0px;
		padding: 0px;
		width: 99%;	
		border: none;
	}
	
	#dollar.dijitInputInner, #bath.dijitInputInner, #rail.dijitInputInner{
		text-align: center;		
		background-color: #FFFFFF !important;
	}
	
	.bg-white{
		background-color: #FFFFFF !important;		
	}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
}
.smallsize{ width:20% !important;}
</style>
<form action="<?php echo $this->url(array('module'=>'tellerandexchange','controller'=>'echange','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table  cellspacing="10" width="100%">
		<tr>
			<td>
				<fieldset>
					<legend ><strong>អាត្រាប្តូបាក់</strong></legend>
						<table cellspacing="5" cellpadding="0" width="100%">
							<tr>
								<td align="right">សាខា</td>
								<td><?php echo $form->getElement('branch_id');?></td>
								<td align="right">លេខកូដ</td>
								<td><?php echo $form->getElement('number_code');?></td>
								<td></td>
								<td></td>
							</tr>
							<tr>
								<td align="right"></td>
								<td><?php echo $form->getElement('onetomany');?></td>
								<td align="right">Date</td>
								<td><?php echo $form->getElement('date');?></td>
								<td>Customer</td>
								<td><?php echo $form->getElement('cusomer');?></td>
							</tr>
								<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" /></td>
					</table>
					
				<fieldset>
					<legend ><strong></strong></legend>
						<table cellspacing="5" cellpadding="0" width="100%" >
							<tr>
								<td valign="top">
									 <table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
											<tr id="head_title" class="head-title" align="center"></tr>
									</table>
								</td>
							</tr>
							<tr style="border:1px solid #ccc !important;">
								<td align="left" valign="top">
									<input id="add-append"  label="បន្ថែម" dojoType="dijit.form.Button" iconClass="dijitIconApplication" Onclick="addAmountTypeMoney();" />
								</td>
							</tr>
					</table>
				</fieldset>
				<fieldset>
					<legend><strong>បង់ប្រាក់</strong></legend>
					<table>
						<tr>
							<td>ប្រាក់បង់សរុប</td>
							<td>ដុល្លា</td>
							<td><?php echo $form->getElement('payusa');?></td>
							<td>រៀល</td>
							<td><?php echo $form->getElement('payr');?></td>
							<td>បាត់</td>
							<td><?php echo $form->getElement('payb');?></td>
						</tr>
						<tr>
							<td>ប្រាក់ទទួលបាន</td>
							<td>ដុល្លា</td>
							<td><?php echo $form->getElement('getusa');?></td>
							<td>រៀល</td>
							<td><?php echo $form->getElement('getr');?></td>
							<td>បាត់</td>
							<td><?php echo $form->getElement('getb');?></td>
						</tr>
						<tr>
							<td>ប្រាក់អាប់</td>
							<td>ដុល្លា</td>
							<td><?php echo $form->getElement('returnusa');?></td>
							<td>រៀល</td>
							<td><?php echo $form->getElement('returnr');?></td>
							<td>បាត់</td>
							<td><?php echo $form->getElement('returnb');?></td>
						</tr>
					</table>
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>		
</form>
<form id='frm_add_capital' action="<?php echo $this->url(array('module'=>'capital','controller'=>'stock','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('doloar').get('value') == 0 && dijit.byId('bath').get('value') == 0 && dijit.byId('rail').get('value') == 0){
					dijit.byId('doloar').focus();
					return false;
				}*/

				return true;
			} else {
				return false;
			}
	</script>	 
	
	<table class="tbtable" style="margin:10px auto; width:100%; border-collapse: collapse; border:1px solid #ccc;" >
		<tr>
			<td width="50%" valign="top">
			 	<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
					<tr id="head_title" class="head-title" align="center"></tr>
				</table>
			</td>
		</tr>
		<tr style="border:1px solid #ccc !important;">
		</tr>
	</table>
</form>
<script type="text/javascript">
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
		
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
	
}
function checkSelectOption(type,record){
	from =dijit.byId('from_type'+record).get('value'); //dijit.byId('from_type'+record).attr("disabled", true);
	to =dijit.byId('to_type'+record).get('value');
	checkRateDollar(from,to,record);
	
}
function checkRateDollar(from,to,record){//for tab dollar
	url = "<?php echo BASE_URL;?>/tellerandexchange/xchange/check-rate";
	dojo.xhrPost({
	      url: url,
	      load: function(data){
			 // alert(data);
	    	  tmp = dojo.fromJson(data);		    	  
	    	  for(var i=0; i< tmp.length; i++){
	    		  dijit.byId('exchange_rate'+record).attr('value','');
	    		  if(from==2 && to==3 || from==3 && to==2){//dollar to bath
					  dijit.byId('exchange_rate'+record).attr('value',tmp[0].rate_in);
				  }else if(from==2 && to==1 || from==1 && to==2){//dolar to riel
					  dijit.byId('exchange_rate'+record).attr('value',tmp[1].rate_in); 
				  }else if(from==3 && to==1 || from==1 && to==3){
					  dijit.byId('exchange_rate'+record).attr('value',tmp[2].rate_in); 
				  }
		    	  //alert(tmp[0].rate_in);//dollar to bath
		    	  //tmp[1].rate_in dolar to riel
		    	  //dijit.byId('rate_dollar').attr('value',tmp[1].rate_in);
		    	
		    	 // var exchangetobath = dijit.byId("exchangetobath");
		    	  //var exchangetoriel = dijit.byId("exchangetoriel");
	    		  /*if(exchangetobath.checked){
	    			  calcSysble = "*";
	    			  dijit.byId('rate_dollar').attr('value',tmp[0].rate_in);
	    			  totalExchange(1);
				   }else if(exchangetoriel.checked){
					  dijit.byId('rate_dollar').attr('value',tmp[1].rate_in);
					  calcSysble = "*";
					  totalExchange(1);
				   }*/
	    	  }
	    	  
	      },
	      error: function(error){
		      alert(error);	        
	       // alert("Error, please reload page, Try it again.");
	      }
    });
}
curr_dollar_amountoption = '<?php echo $this->currency_type;?>';
	temp='';
	r = 0;
	fund_title=0;
function addAmountTypeMoney(){
			r++;
			if(fund_title!=1){
				thead='<th>លុប</th>';
				thead+='<th>ប្តូពី</th>';
				thead+='<th>មកជា</th>';
				thead+='<th>អតិថិជនពិសេស</th>';
				thead+='<th>អាត្រាប្តូប្រាក់</th>';
				thead+='<th>ចំនួនប្តូរ</th>';
				thead+='<th>ចំនួនទទួលបាន</th>';
				thead+='<th>សម្គាល់ </th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
	        }
			temp='<td style="width:30px !important;"><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			temp+='<td><select style=" width:70%;" id="from_type'+r+'" name="from_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(1,'+r+')"  >'+curr_dollar_amountoption+'</select></td>';
			temp+='<td><select style=" width:70%;" id="to_type'+r+'" name="to_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(2,'+r+')">'+curr_dollar_amountoption+'</select></td>';
			temp+='<td><input type="CheckBox" style=" width:15%;" required="true" name="Customer_good'+r+'" id="Customer_good'+r+'" value="" dojoType="dijit.form.CheckBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="exchange_rate'+r+'" id="exchange_rate'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="recieve1_'+r+'" id="recieve1_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" style=" width:70%;" required="true" name="return1_'+r+'" id="return1_'+r+'" value="" dojoType="dijit.form.NumberTextBox"/></td>';
			temp+='<td><input type="text" name="note1_'+r+'" id="note1_'+r+'" dojoType="dijit.form.TextBox" s/></td>';
			tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
			tmp+="</tr>";
			
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
			    parseContent: true,
			     
			});
			if(dijit.byId("record_row").value!="") {
				var ids = dijit.byId("record_row").value;
				dijit.byId("record_row").attr('value',ids+','+r);
			} else { dijit.byId("record_row").attr('value',r);}

		
	}	
	sub_title=0;
	s=0;

</script>