<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_fixedasset;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>Form Chart Account</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
							<td>Account_No</td>
							<td><?php echo $frm->getElement('account_No')?></td>	
							<td>Account Type</td>
							<td><?php echo $frm->getElement('account_Type')?></td>
							<td>Account Name</td>
							<td><?php echo $frm->getElement('account_Name')?></td>
						</tr>
						<tr>
							<td>Category</td>
							<td><?php echo $frm->getElement('category')?></td>	
							<td>None operation</td>
							<td><?php echo $frm->getElement('none')?></td>
							<td>Parent</td>
							<td><?php echo $frm->getElement('parent')?></td>
						</tr>
						
						<tr>
							<td>Balance</td>
							<td><?php echo $frm->getElement('Balance')?></td>	
							<td>Date</td>
							<td><?php echo $frm->getElement('date')?></td>
							<td>Status</td>
							<td><?php echo $frm->getElement('status')?></td>
						</tr>
						
					</table>
					</fieldset>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
</script>
