<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Chartaccount"));
$frm = $this->frm_search;
$frms = $this->frm_chartaccount;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'chartaccount','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
    <div dojoType="dijit.layout.AccordionPane">
    <table>
    <tr width="20%">
     <td><?php echo $frms->getElement("adv_search");?></td>
     <td><?php echo $frms->getElement("account_Type");?></td>
     <td><?php echo $frms->getElement("parent");?></td>
     <td><?php echo $frms->getElement("category");?></td>
     <td><?php echo $frm->getElement('status');?></td>
     <td><?php echo $frm->getElement("btn_search");?></td>
   </tr>
   </table>
   <?php echo $this->list;?>
</form>
