<?php
	$this->headTitle('Add IL Payment'); 
	echo $this->headTitle();
	$frm = $this->frm_ilpayment;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន បង់ប្រាក់ឥណទានទោល</strong></legend>
					<table class="center" cellspacing="10">
						
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("លេខកូដអតិថិជន")?></td>
							<td><?php  echo $frm->getElement('client_code');?></td>
							<td><?php echo $tr->translate("ស្គែន/បញ្ចូលលេខកូដកម្ចី")?></td>
							<td><?php echo $frm->getElement('loan_number');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះប្រធានក្រុម")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							<td><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់")?></td>
							<td><?php  echo $frm->getElement('collect_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រាក់ដើមនៅសល់")?></td>
							<td align="left"><?php echo $frm->getElement('priciple_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ដើមត្រូវសង")?></td>
							<td><?php echo $frm->getElement('os_amount');?></td>
							<td><?php echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php echo $frm->getElement('total_interest');?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("ប្រាក់ផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('penalize_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ត្រូវបង់សរុប")?></td>
							<td><?php echo $frm->getElement('total_payment');?></td>
							<td><?php echo $tr->translate("កំណត់សម្គាល់")?></td>
							<td><?php echo $frm->getElement('note');?></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
			<td align="center">
			   <input type="su" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave" onclick="submitData();"/>
			   <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="saveprint" dojoType="dijit.form.Button" 
			   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="addDatatogrid();"/>
			</td>
		</tr>
		<tr>
			<td>
				<fieldset>
					<legend><strong>ប្រវត្តិនៃការបង់ប្រាក់</strong></legend>
					<?php echo $this->list;?>
				</fieldset>
		 </td>
	</tr>		
</table>
</form>
<script type="text/javascript">	
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
</script>
<script type="text/javascript">
dojo.ready(function(){
function submitData(){
	var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
				//alert(data);
				
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
function getLoanById(type){
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('group_id').get('value');
	}
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'IlPayment','action'=>'get-loan-detail')); ?>';
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(data) {
				dijit.byId('priciple_amount').attr('value',data.total_priintciple);
				dijit.byId('os_amount').attr('value',data.principal_permonth);
				dijit.byId('total_interest').attr('value',data.total_payment);
				dijit.byId('total_payment').attr('value',data.rate);
				dijit.byId('client_code').attr('value',data.client_number);
				dijit.byId('loan_number').attr('value',data.loan_number);
			},
			error: function(e) {
				//alert(e);
				//alert("Can not get loan by loan number !");
			}
		});
}
