
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Client '));
	
?>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();	
  $frm = $this->frm_loan;?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
var tran_store  = getDataStorefromJSON('','name',null);
function addDatatogrid(){	
	//if(dijit.byId('frm_reciever').validate()) {
		var myNewItem = {
				no: 1,
				id: 1,
				r_id : 1,//dijit.byId('reciever_name').get('value'),
				name: 1,//dijit.byId('reciever_name').get('value'),,
				tel: 1,//dijit.byId('reciever_name').get('value'),,
				fax: 1,//dijit.byId('reciever_name').get('value'),,dijit.byId('reciever_fax').value,
				ac: 1,//dijit.byId('reciever_name').get('value'),,dijit.byId('reciever_acc_no').value,
				bank:1,//dijit.byId('reciever_name').get('value'),, dijit.byId('reciever_bank_name').value,
				cut: 0,
				amt_gave:1,//dijit.byId('reciever_name').get('value'),, dojo.number.format(dojo.number.round(dijit.byId('gave').value)),
				amt: 1,//dijit.byId('reciever_name').get('value'),,dojo.number.format(dojo.number.round(dijit.byId('amount').value)),
				gave: 1,//dijit.byId('reciever_name').get('value'),,dojo.number.format(dojo.number.round(dijit.byId('gave').value)),
				coms: 1,//dijit.byId('reciever_name').get('value'),,dojo.number.format(dojo.number.round(dijit.byId('commission').value)),				
				total_amt: 1,//dijit.byId('reciever_name').get('value'),,dojo.number.format(dojo.number.round(dijit.byId('total').value)),
				status: 1,//dijit.byId('reciever_name').get('value'),,_status,
				img: 1,//dijit.byId('reciever_name').get('value'),,1
		};		

		addDataToGrid(dijit.byId('tran_list'), tran_store, myNewItem);		
		dijit.byId('stackContainer').forward();
}
</script>
<script type="text/javascript">
var baseurl = '<?php echo $baseurl;?>';
dojo.ready(function(){	
    function formatType(value){
		return "<img src='"+ baseurl +"/images/actions/Delete_16.png' alt='delete'>"; 
    }
	
	//load data into data grid 
	tran_list = new dojox.grid.DataGrid({
		store: tran_store,
		autoHeight: true,
		name:'tran_list', 
		structure: [
					{ name: "ល.រ", field:"no",width: "60px",cellStyles: "text-align: center;"}, 
					{ name: "id", field:"id", hidden: "true" },
					{ name: "r_id", field:"r_id", hidden: "true" },
					{ name: "cut", field:"cut", hidden: "true" },				
					{ name: "អ្នក​ទទួល", field:"name", width: "auto", editable: false},			
					{ name: "Tel", field:"tel", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "Fax", field:"fax", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "A/C", field:"ac", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "​ធនាគារ", field:"bank", width: "150px", editable: false},
					{ name: "ប្រាក់​ផ្ញើរ", field:"amt_gave", width: "150px", editable: false},				
					{ name: "កាត់ទឹក", field:"coms", width: "120px", editable: false},
					{ name: "ប្រាក់​ផ្ញើរ", field:"amt", width: "130px", hidden: "true", editable: false},
					{ name: "ប្រាក់​ត្រូវ​បើក", field:"gave_money", width: "130px", hidden: "true" , editable: false},
					{ name: "ប្រាក់​សរុប", field:"total_amt", width: "120px", editable: false},
					{ name: "លុប", field:"img", formatter: formatType, width: "70px", cellStyles: "text-align: center;"}
				],
		
		onRowClick: function(e){
			if(e.cellIndex == 14){
			/*	if (confirm("Are you sure, do you to delete this row?")) { 
					var item = this.getItem(e.rowIndex);						
					tran_store.deleteItem(item);
					tran_store.save();

					tt =  dijit.byId('total_money').get('value') - dojo.number.parse(item.total_amt);
				    tc =  dijit.byId('total_commission').get('value') - dojo.number.parse(item.coms);
				    ta =  dijit.byId('total_amount').get('value') - dojo.number.parse(item.amt);					    
				    		
			        dijit.byId('total_amount').attr('value', ta);
			        dijit.byId('total_commission').attr('value', tc); 
			        dijit.byId('total_money').attr('value', tt); 
			        			
					var count = this.rowCount; 
					var no_deleted = item.no;
					
					//generate number of row after deleted row
					for(var i = 0; i < count ; i++){
				        var _item = this.getItem(i);					        
			            value = _item.no;				            
			            if (value > no_deleted){				            	
				            value -= 1;					                 
				        	tran_store.setValue(_item, "no", value);
				        	tran_store.setValue(_item, "id", value);
			            }				            
				    }
				}*/
			}
		}
	}, "tran_list");
	tran_list.startup();		
		    

  
});
 </script>

<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("Add Client");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10" border=1>
						<tr>
							<td><?php echo $tr->translate("Is Group")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("CO Name")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Currency Type")?></td>
							<td><?php  echo $frm->getElement('currency_type');?></td>
							<td><?php echo $tr->translate("Zone")?></td>
							<td><?php  echo $frm->getElement('zone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Total Amount")?></td>
							<td><?php  echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("Interest Rate")?></td>
							<td><?php  echo $frm->getElement('interest_rate');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Release Date")?></td>
							<td><?php  echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("Period")?></td>
							<td><?php  echo $frm->getElement('period');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("First Payment")?></td>
							<td><?php  echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("NO Time")?></td>
							<td><?php  echo $frm->getElement('time');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Pay Every")?></td>
							<td><?php  echo $frm->getElement('pay_every');?></td>
							<td><?php echo $tr->translate("Repaymet Method")?></td>
							<td><?php  echo $frm->getElement('repayment_method');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("Holiday")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
							<td><?php echo $tr->translate("ID Card(N.)")?></td>
							<td><?php  echo $frm->getElement('id_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Description")?></td>
							<td colspan="3"><?php  echo $frm->getElement('desc');?></td>
						</tr>
						<tr>
							<td colspan="4">
								 <span dojoType="dijit.layout.StackController" containerId="stackContainer"></span>
									<div dojoType="dijit.layout.StackContainer" id="stackContainer">
					    				<div dojoType="dijit.layout.ContentPane" title="Member Loan List">		
											 <div id="tran_list"></div>				
									    </div>  
									    <div dojoType="dijit.layout.ContentPane" id='other' title="ថែមអ្នកទទួល" style="height: 350px" >
					    				<form id="frm_reciever" dojoType="dijit.form.Form"  method="post">
												<fieldset>
													<legend><strong>ព៌ត័មាន ទំនាក់ទំនង អ្នក​ទទួល</strong></legend>
												
												<table>
													<tr>
														<td colspan="2" align="center">
															<input type="button" label="បន្ថែមadd" dojoType="dijit.form.Button" 
																iconClass="dijitIconSave" onclick="addDatatogrid();"/>
														</td>
													</tr>
												</table>	
											</form>
					
					    				</div>
					    			</div>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
							<input type="button" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDatatogrid();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
/*dojo.require("dijit.form.Textarea");
dojo.require("dojox.grid.DataGrid");
dojo.require("dijit.layout.StackContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.date.locale");*/
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require('dijit.form.Form');
dojo.require('dijit.form.FilteringSelect');	
dojo.require('dijit.form.Button');	
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox"); 	
dojo.require("dijit.form.RadioButton");
dojo.require("dojox.grid.DataGrid");
dojo.require("dojo.number");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.StackContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.date.locale");
</script>