<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Staff Permision'));
	$this->headTitle('Open salary | Agent add page'); 
	echo $this->headTitle();
	$frm = $this->frm_permistion;
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.SimpleTextarea");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>

<form action="<?php echo $this->url(array('module'=>'payroll','controller'=>'permission','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				return true;
			}
			return false;
	</script>
		
	<table cellspacing="10" width="95%">
		<tr>
			<td>
				<fieldset>
					<legend><strong>លិខិតអនុញ្ញាត</strong></legend>
					<table cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php  echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("")?></td>
							<td><?php  echo $frm->getElement('');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("បុគ្គលិក")?></td>
							<td><?php  echo $frm->getElement('employee');?></td>
							<td><?php echo $tr->translate("យល់ព្រមដោយ")?></td>
							<td><?php  echo $frm->getElement('approve_by');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃស្នើសុំ")?></td>
							<td><?php  echo $frm->getElement('request_date');?></td>
							<td><?php echo $tr->translate("ប្រភេទ")?></td>
							<td><?php  echo $frm->getElement('type');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ចាប់ពីថ្ងៃ")?></td>
							<td><?php  echo $frm->getElement('from_date');?></td>
							<td><?php echo $tr->translate("ដល់ថ្ងៃ")?></td>
							<td><?php  echo $frm->getElement('to_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ម៉ោង")?></td>
							<td><?php  echo $frm->getElement('time');?></td>
							<td colspan="6">
								<table>
									<tr>
										<td><?php  echo $frm->getElement('all_day');?></td>
										<td><?php echo $tr->translate("All Day")?></td>
										<td><?php  echo $frm->getElement('paid_leave');?></td>
										<td><?php echo $tr->translate("Paid Leave")?></td>
										<td><?php  echo $frm->getElement('every_day');?></td>
										<td><?php echo $tr->translate("Every Day")?></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("មូលហេតុ")?></td>
							<td><?php  echo $frm->getElement('reason');?></td>
							<td><?php echo $tr->translate("Status")?></td>
							<td><?php  echo $frm->getElement('status');?></td>
						</tr>
					</table>
					<div style="text-align: center; margin: 10px 0px;"> 
						<input type="hidden" name="exchangefrom" value="2" />
						<input type="hidden" name="inv_no" value="<?php echo $this->inv_no;?>">
						<input type="reset" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button"/>
						<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" label="រក្សាទុក+ថ្មី" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</div>
				</fieldset>
			</td>			
		</tr>
		</tr>
	</table>		
</form>