
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("TRANSFER_CLIENT_CO"));
$frm = $this->frm_transfer;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferco-client','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <table>
  	<tr>
  	    <td><?php  echo $frm->getElement('note');?></td>
  		<td><?php  echo $frm->getElement('branch_name');?></td>
  		<td><?php  echo $frm->getElement('loan_client');?></td>
        <td><?php  echo $frm->getElement('name_co');?></td>
  	</tr>
  	<tr>
  	    <td><?php echo $frm->getElement('status');?></td>
  		<td><?php echo $frm->getElement('start_date');?></td>
  		<td><?php echo $frm->getElement('end_date');?></td>
  		<td><?php echo $frm->getElement('btn_search');?></td>
  	</tr>
  </table>
  <?php echo $this->list;?>
</form>
