<?php
	$this->headTitle('Add Loan'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'groupDisburse','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន កម្ចីប្រាក់</strong></legend>
					<table cellspacing="10" >
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("ឥណទានវគ្គទី")?></td>
							<td><?php echo $frm->getElement('level');?></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("ឈ្មោះប្រធានក្រុម")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							<td><?php echo $tr->translate("លេខតំបន់")?></td>
							<td><?php  echo $frm->getElement('zone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចេញ")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("រយះពេលខ្ចី")?></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("រយះពេលគិតជា")?></td>
							<td><?php echo $frm->getElement('pay_every');?></td>
							
								
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃយកប្រាក់ដំបូង")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("ម៉ោងយកប្រាក់")?></td>
							<td><?php echo $frm->getElement('time');?></td>
							<td><?php echo $tr->translate("វិធីសាស្រ្ត")?></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃឈប់សំរាក")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
							<td><?php //echo $tr->translate("ID Card(N.)")?></td>
							<td><?php  //echo $frm->getElement('id_no');?></td>
							<td><?php //echo$tr->translate("Description")?></td>
							<td><?php //echo $frm->getElement('desc');?></td>
						</tr>
					</table>
				</fieldset>
				<fieldset>
					<legend><strong>ព៌ត័មាន កម្ចីប្រាក់បុគ្គល</strong></legend>
					<table class="center" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះសមាជិក")?></td>
							<td align="left"><?php echo $frm->getElement('member');?></td>
							<td><?php echo $tr->translate("រូបិយប័ណ្ណ")?> </td>
							<td><?php echo $frm->getElement('currency_type');?></td>
							<td><?php echo $tr->translate("ចំនួនប្រាក់ខ្ចី")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("ការប្រាក់")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td><?php //echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php //echo $frm->getElement('co_id');?></td>
							<td><?php //echo $tr->translate("រូបិយប័ណ្ណ")?></td>
							<td><?php //echo $frm->getElement('currency_type');?></td>
						</tr>
						<tr>
							<td colspan="6"> <input type="button" value="បន្ថែម" label="បន្ថែម" dojoType="dijit.form.Button" 
				 				iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="addDatatogrid();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				<input type="hidden" name="invoice_no" id="invoice_no" >
				<input type="hidden" name="s_name" id="s_name">
		</td>
	</tr>		
	<tr>
		<td align="center">
		 <div id="tran_list"></div>		
		</td>
	</tr>
	<tr>
		<td align="center">
			<input type="su" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="submitData();"/>
			<input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="saveprint" dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="addDatatogrid();"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">	
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	function addDatatogrid(){		
		if(dijit.byId('frm_add_tran').validate()){
			group_id = dijit.byId('group_id').get('value');
			zone = dijit.byId('zone').get('value');
			co_id = dijit.byId('co_id').get('value');
			member = dijit.byId('member').get('value');
			if(group_id=='' || group_id==-1){
				alert('Field Required ! ');
				dijit.byId('group_id').focus();
				return false;
			}else if(co_id=='' || co_id==-1){
				alert('Field Required ! ');
				dijit.byId('co_id').focus();
				return false;
			}else if(zone=='' || zone==-1){
				alert('Field Required ! ');
				dijit.byId('zone').focus();
				return false;
			}else if(member=='' || member==-1){
				alert('Field Required ! ');
				dijit.byId('member').focus();
				return false;
			}
		var myNewItem = {
					no: 1,
					id: 1,
					member_id:dijit.byId('member').get('value'),
					payment_method:dijit.byId('repayment_method').get('value'),
					member: dijit.byId('member').get('displayedValue'),
					currency_type: dijit.byId('currency_type').get('displayedValue'),
					currency_type_id:dijit.byId('currency_type').get('value'),
					total_amount: dijit.byId('total_amount').get('value'),
					interest_rate: dijit.byId('interest_rate').get('value'),
					period: dijit.byId('period').get('displayedValue'),
					//total_amt: dojo.number.format(dojo.number.round(dijit.byId('total').value)),
					img: 1
		};		

			addDataToGrid(dijit.byId('tran_list'), tran_store, myNewItem);	
			clearTextBox();	
		}
	}
</script>
<script type="text/javascript">
//dojo.require("dojox.grid.DataGrid");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
    var tran_store  = getDataStorefromJSON('','name',null);
	var url_submit = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'add')); ?>';
	var tran_status = {};
	var baseurl = '<?php echo $baseurl;?>';
</script>
<script type="text/javascript">
dojo.ready(function(){
function formatType(value){
	return "<img src='"+baseurl+"/images/Delete_16.png' alt='delete'>"; 
}
	//load data into data grid 
	tran_list = new dojox.grid.DataGrid({
		store: tran_store,
		autoHeight: true,
		name:'tran_list', 
		structure: [
					{ name: "ល.រ", field:"no",width: "60px",cellStyles: "text-align: center;"}, 
					{ name: "id", field:"id", hidden: "true" },
					{ name: "member_id", field:"member_id", hidden: "true" },
					{ name: "currency_type_id", field:"currency_type_id", hidden: "true" },
					{ name: "សមាជិក", field:"member", width: "auto", editable: false},			
					{ name: "រូបិយប័ណ្ណ", field:"currency_type", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "វិធីសាស្រគិតប្រាក់", field:"payment_method", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "ចំនួនប្រាក់ខ្ចី", field:"total_amount", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "ការប្រាក់", field:"interest_rate", width: "100px",cellStyles: "text-align: center;", editable: false },
					{ name: "​រយះពេលខ្ចី", field:"period", width: "150px", editable: false},
					{ name: "លុប", field:"img", formatter: formatType, width: "70px", cellStyles: "text-align: center;"}
				],
		
		onRowClick: function(e){
			if(e.cellIndex == 7){
				if (confirm("Are you sure, do you to delete this row?")) { 
					var item = this.getItem(e.rowIndex);						
					tran_store.deleteItem(item);
					tran_store.save();
			    }
			}
		}
	}, "tran_list");
	tran_list.startup();			  
});
function submitData(){
	var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'GroupDisburse','action'=>'addloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),
			content : { 
				    'tran_list':  json_data_t,
				},		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
				//alert(data);
				
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function popupCheckClient(){
	if(dijit.byId('group_id').get('value')==-1){
		 dijit.byId('frm_client').show();
	}
}
function popupCheckCO(){
	if(dijit.byId('co_id').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}
function popupCheckZone(){
	if(dijit.byId('zone').get('value')==-1){
		 dijit.byId('frm_zone').show();
	}
}
function popupCheckDistrict(){
	if(dijit.byId('district').get('value')==-1){
		 dijit.byId('frm_district').show();
	}
}
function popupCheckCommune(){
	if(dijit.byId('commune').get('value')==-1){
		 dijit.byId('frm_commune').show();
	}
}
function popupCheckVillage(){
	if(dijit.byId('village').get('value')==-1){
		 dijit.byId('frm_village').show();
	}
}

var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add-newclient')); ?>';
function addNewClient(){
		dojo.xhrPost({
	    url: url_submit,	
		form: dojo.byId("form_client"),		    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('frm_client').reset(); 
			dijit.byId('frm_client').hide();
		},
		error: function() {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitzone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
		dojo.xhrPost({
	    url: url_submitzone,	
		form: dojo.byId("form_zone"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_zone').reset(); 
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}



</script>
<?php 
 echo $this->frmpupopclient;
 echo $this->frmPopupCO;
 echo $this->frmPopupZone;
 echo $this->frmPopupCommune;
 echo $this->frmPopupDistrict;
 echo $this->frmPopupVillage;
 
 
?>