<?php
	$this->headTitle('EDIT_GROUP_DISBURSE'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
.fullside {
	width: 100%;
	height: 28px !important;
}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'GroupDisburse','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				zone = dijit.byId('zone').get('value');
				co_id = dijit.byId('co_id').get('value');
				client = dijit.byId('group_code').get('value');
				record_row = dijit.byId('record_row').get('value');

				if (client=='' || client==-1){
					alert('Please Select Client Name !');
					dijit.byId('group_code').focus();
					return false;
				}else if(co_id=='' || co_id==-1){
					alert('Please Select CO Name !');
					dijit.byId('co_id').focus();
					return false;
			}else if(zone=='' || zone==-1){
					alert('Please Select Zone !');
					dijit.byId('zone').focus();
					return false;
			}else if(record_row==''){
					alert('Group Disburse Must Have Record !');
					return false;
			}
					rs = checkValidateDate();
			if(rs==false){
              		return false;			
            }
					return true;
			}else {
					return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន ឥណទានទោល</strong></legend>
					<table cellspacing="10"  width="100%" style="margin-top: -10px;">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id'); echo $frm->getElement('id');?></td>
							<td><?php echo $tr->translate("លេខកូដកម្ចី")?></td>
							<td><?php echo $frm->getElement('group_code');?></td>
							<td><?php echo $tr->translate("ឈ្មោះអតិថិជន")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឥណទានវគ្គទី")?></td>
							<td><?php echo $frm->getElement('level');?></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							<td><?php echo $tr->translate("លេខតំបន់")?></td>
							<td><?php  echo $frm->getElement('zone');?></td>
						</tr>
					</table>
				</fieldset>
				<fieldset>
					<legend><strong>ព៌ត័មាន កម្ចីសាច់ប្រាក់</strong></legend>
					<table cellspacing="10" style="margin-top: -10px;">
						<tr>
							<td><?php echo $tr->translate("រយះពេលខ្ចី(គិតជា)")?></td>
							<td><?php echo $frm->getElement('pay_every');?></td>
							<td><?php echo $tr->translate("រយះពេលខ្ចី")?></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("ថ្ងៃចេញ")?></td>
							<td><?php echo $frm->getElement('release_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់ដំបូង")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("ថ្ងៃបញ្ចប់កម្ចី")?></td>
							<td><?php echo $frm->getElement('date_line');?></td>
							<td><?php echo $tr->translate("រូបិយ៍វត្ថុ")?></td>
							<td align="left"><?php echo $frm->getElement('currency_type');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td><?php echo $tr->translate("វិធីសាស្រ្តបង់ប្រាក់")?></td>
							<td><?php echo $frm->getElement('repayment_method');?></td>
							<td><label style="font-size:10px;"><?php echo $tr->translate("រយៈពេលអនុគ្រោះប្រាក់ដើម")?></label >(<label style="font-size:10px;" id="graice_type"></label>)</td>
							<td><?php echo $frm->getElement('graice_pariod');?></td>
						</tr>
						<tr>
							<td><label id="lbl_payment"><?php echo $tr->translate("រយៈពេលបង់រំលោៈដើម")?></label></td>
							<td><?php echo $frm->getElement('amount_collect_pricipal');?></td>
							<td><?php //echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php //echo $frm->getElement('interest_rate');?></td>
							<td><?php //echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php //echo $frm->getElement('interest_rate');?></td>
						</tr>
					</table>
				</fieldset>
				<fieldset>
					<legend><strong>ព៌ត័មាន សងប្រាក់</strong></legend>
					<table cellspacing="10" style="margin-top: -10px;">
						<tr>
							<td><?php echo $tr->translate("ម៉ោងយកប្រាក់")?></td>
							<td><?php echo $frm->getElement('time');?></td>
							<td><?php echo $tr->translate("រយៈពេលបង់(គិតជា)")?></td>
							<td><?php echo $frm->getElement('collect_termtype');?></td>
							<td><?php echo $tr->translate("រយៈពេលបង់")?></td>
							<td><?php echo $frm->getElement('amount_collect');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃឈប់សំរាក")?></td>
							<td><?php  echo $frm->getElement('every_payamount');?></td>
							<td><?php echo $tr->translate("បង់យឺតផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('pay_late');?></td>
							<td><?php echo $tr->translate("បង់មុនថ្ងៃកំណត់")?></td>
							<td><?php echo $frm->getElement('pay_before');?></td>
							
						</tr>
					</table>
				</fieldset>
				
				<input type="hidden" name="invoice_no" id="invoice_no" >
				<input type="hidden" name="s_name" id="s_name">
		</td>
	</tr>		
	<tr>
		<td align="center">
				<input type="text" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
				<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
							<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
				</table>		
		</td>
	</tr>
	 <!--<tr style="border:1px solid #ccc !important;">
		<td align="left" valign="top">
		  <input id="add-append"  label="បន្ថែម" dojoType="dijit.form.Button" iconClass="dijitIconApplication" Onclick="addAmountTypeMoney();" /> 
	   </td>
	</tr>-->
	<tr>
		<td align="center">
			<input type="reset" value="សម្អាត" label="សម្អាត" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="submit" label="រក្សាទុកនិងបិទ" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="រក្សាទុកនិងបន្ថែមថ្មី" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		
		</td>
	</tr>	
</table>
</form>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.ready(function(){
		//addAmountTypeMoney();		
		//setFirstPaymentAndDateLine(3,<?php //echo date('d-m-Y');?>,1);
		//changeCollectType();
		initilize();
	});  
	    
</script>
<script type="text/javascript">	
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_capital"+ids).remove();
		
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_capital"+index).remove();
	}
}
member_option = '<?php echo $this->member_option;;?>';
code_option = '<?php echo $this->code_option;;?>';
temp='';
r = 0;
fund_title=0;
function addAmountTypeMoney(){
		r++;
		if(fund_title!=1){
			thead='<th>លុប</th>';
			thead+='<th>កូដអតិថិជន</th>';
			thead+='<th>ឈ្មោះអតិថិជន</th>';
			thead+='<th>ចំនួនទឹប្រាក់</th>';
			thead+='<th>ថ្លៃរដ្ឋបាល</th>';
			thead+='<th>សម្គាល់ </th>';
			fund_title=1;
			dojo.query("#head_title").append(thead);
        }
		temp='<td style="width:30px !important;"><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		temp+='<td><select readonly="true" style=" width:90%;background:#fff; padding-left:5px;" id="from_type'+r+'" name="from_type'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(1,'+r+')"  >'+code_option+'</select></td>';
		temp+='<td><select readonly="true" style=" width:90%; background:#fff; padding-left:5px;" id="member_id'+r+'" name="member_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(2,'+r+')">'+member_option+'</select></td>';
		temp+='<td><input style=" width:90%;" type="text" required="true" onclick="enableExchangeRate('+r+')" name="debt_amount'+r+'" id="debt_amount'+r+'" dojoType="dijit.form.NumberTextBox"/></td>';
		temp+='<td><input type="text" name="admin_fee'+r+'" id="admin_fee'+r+'" dojoType="dijit.form.NumberTextBox" value="0"/></td>';
		temp+='<td><input type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.TextBox" s/></td>';
		tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
		tmp+="</tr>";
			dojo.query("#t_amountmoneytype").append(tmp);
			dojo.html.set(dojo.byId("row_capital"+r),temp, {
		    parseContent: true,
		     
		});
		if(dijit.byId("record_row").get('value')!="") {
			var ids = dijit.byId("record_row").value;
			dijit.byId("record_row").attr('value',ids+','+r);
		} else { dijit.byId("record_row").attr('value',r);}

	
}
function initilize(){
	<?php if(!empty($this->list_members)) {
		foreach($this->list_members AS $i=>$rs){?>
	r++;
	if(fund_title!=1){
		thead='<th>លុប</th>';
		thead+='<th>កូដអតិថិជន</th>';
		thead+='<th>ឈ្មោះអតិថិជន</th>';
		thead+='<th>ចំនួនទឹប្រាក់</th>';
		thead+='<th>ថ្លៃរដ្ឋបាល</th>';
		thead+='<th>សម្គាល់ </th>';
		fund_title=1;
		dojo.query("#head_title").append(thead);
    }
	temp='<td style="width:30px !important;"><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	temp+='<td><select readonly="true" style=" width:90%;background:#fff; padding-left:5px;" id="client_code'+r+'" name="client_code'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(1,'+r+')"  >'+code_option+'</select></td>';
	temp+='<td><select readonly="true" style=" width:90%; background:#fff; padding-left:5px;" id="member_id'+r+'" name="member_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="checkSelectOption(2,'+r+')">'+member_option+'</select></td>';
	temp+='<td><input style=" width:90%;" type="text" required="true" onclick="enableExchangeRate('+r+')" name="debt_amount'+r+'" id="debt_amount'+r+'" dojoType="dijit.form.NumberTextBox"/></td>';
	temp+='<td><input type="text" name="admin_fee'+r+'" id="admin_fee'+r+'" dojoType="dijit.form.NumberTextBox" value="0"/></td>';
	temp+='<td><input type="text" name="note'+r+'" id="note'+r+'" dojoType="dijit.form.TextBox" s/></td>';
	tmp='<tr style="border:1px solid #ccc;" id="row_capital'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		dojo.html.set(dojo.byId("row_capital"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
	dijit.byId('client_code'+r).attr('value','<?php echo $rs['client_id']?>');
	dijit.byId('member_id'+r).attr('value','<?php echo $rs['client_id']?>');
	dijit.byId('debt_amount'+r).attr('value','<?php echo $rs['total_capital']?>');
	dijit.byId('admin_fee'+r).attr('value','<?php echo $rs['admin_fee']?>');
	dijit.byId('note'+r).attr('value','<?php echo $rs['loan_purpose']?>');

	<?php } }?>
}
/*sub_title=0;
s=0;*/

function calCulateExchange(record,reverse){
	from =dijit.byId('from_type'+record).get('value'); //dijit.byId('from_type'+record).attr("disabled", true);
	to =dijit.byId('to_type'+record).get('value');
	//alert(typeof(from));
	//alert(to);
	xchange_rate = dijit.byId('exchange_rate'+record).get('value');
	//change_amount = dijit.byId('exchange_amount'+record).get('value');
	if(reverse==1){
		change_amount=dijit.byId('amount_exchanged'+record).get('value');
	}else{
		change_amount=dijit.byId('exchange_amount'+record).get('value');
	}
	 if(from==1 || (from ==3 && to ==2)){//dollar to bath
		if(reverse==1){
			amount = change_amount*xchange_rate;
		}else{
			amount = change_amount/xchange_rate;
		}
	  }else if(from==2 || (from==3 && to==1 )){//riel to bath and dollar
		  if(reverse==1){
				amount = change_amount/xchange_rate;
			}else{
				amount = change_amount*xchange_rate;
			}
	  }
	if(reverse==1){
		dijit.byId('exchange_amount'+record).attr('value',amount);
	}else{
		dijit.byId('amount_exchanged'+record).attr('value',amount);
	}
	netTotal();
	
}
function checkValidateDate(){
    	debt_term = dijit.byId('pay_every').get('value');
		if(debt_term==1){
			term_d =1; 
		}else if(debt_term==2){
			term_d =7; 
		}else{
			term_d =30; 
		}
		
		collect_term = dijit.byId('collect_termtype').get('value');
		if(collect_term==1){
			term_c =1; 
		}else if(collect_term==2){
			term_c =7; 
		}else{
			term_c =30; 
		}
		debt_amount = dijit.byId('period').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		if((collect_amount*term_c)>(debt_amount*term_d)){
			alert('រយៈពេលសង់ប្រាក់មិនអាចធំជាង រយៈពេលខ្ចីប្រាក់បានទេ !');
			dijit.byId('collect_termtype').focus();
			return false;
		}
		/*method = dijit.byId('repayment_method').get('value');
		amount_collect = dijit.byId('amount_collect_pricipal').get('value');
		amount_principal = dijit.byId('total_amount').get('value');
		if(method==4 AND (debt_amount*term_d)/(collect_amount*term_c)*amount_collect>amount_principal ){
			
		}*/
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('total_amount').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	
    	collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = dijit.byId('amount_collect').get('value');
		
		amount_payment  = amount_principal/((debt_term*debt_amount)/(collect_term*collect_amount));
		dijit.byId('amount_collect_pricipal').attr('value',amount_payment);
    }
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
dojo.ready(function(){	
	
	//setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
});
//dojo.require("dojox.grid.DataGrid");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
    var tran_store  = getDataStorefromJSON('','name',null);
	var url_submit = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'add')); ?>';
	var tran_status = {};
	var baseurl = '<?php echo $baseurl;?>';
</script>
<script type="text/javascript">
function chechPaymentMethod(){
	
	method_id = dijit.byId('repayment_method').get('value');
	if(method_id==5){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dijit.byId('amount_collect_pricipal').focus();
	}else if(method_id==4){
		dijit.byId('amount_collect_pricipal').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="ចំនួនទឹកប្រាក់បង់ថេរ";
		dijit.byId('amount_collect_pricipal').attr('value','');
		dijit.byId('amount_collect_pricipal').focus();
		setDefaultPaymentAmount();
		}
	else{
		dijit.byId('amount_collect_pricipal').set('readOnly',true);
	}
	if(method_id==1){
		dijit.byId('graice_pariod').set('readOnly',false);
	}else{
		dijit.byId('graice_pariod').attr('value',0);
		dijit.byId('graice_pariod').set('readOnly',true);
	}
}
function submitData(){
	var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function changeCollectType(){
	get_id = dijit.byId('pay_every').get('value');
	dijit.byId('collect_termtype').attr('value',get_id);
	changeGraicePeroid();
	CalculateDate();
}
function changeGraicePeroid(){
	disp_value = dijit.byId('collect_termtype').attr('displayedValue');
	dojo.byId('graice_type').innerHTML=disp_value;
	calCulateFirstPayment();
	
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
var url_getmember = '<?php echo $this->url(array('module'=>'loan','controller'=>'GroupDisburse','action'=>'getclientgroup')); ?>';
function popupCheckClient(){
	if(dijit.byId('group_id').get('value')==-1){
		 dijit.byId('frm_client').show();
	}else{
		group_id=dijit.byId('group_id').get('value');
		//getAllMemberByGroup(group_id);
		dijit.byId('group_code').attr('value',group_id);
	}
}
function getmemberIdGroup(){
	group_id=dijit.byId('group_code').get('value');
	getAllMemberByGroup(group_id);
	dijit.byId('group_id').attr('value',group_id);
}
function getAllMemberByGroup(group_id){
	dojo.xhrPost({
	    url: url_getmember,	
	    content: { 
			'group_id':group_id,
		},		    
		handleAs:"json", 
		load: function(data) {
			for(i=0;i<data.length;i++){
				addAmountTypeMoney();
				dijit.byId('member_id'+r).attr('value',data[i].client_id);
				dijit.byId('from_type'+r).attr('value',data[i].client_id);
				
			}
		},
		error: function(err){
		alert(err);
		}
	});
}
function popupCheckCO(){
	if(dijit.byId('co_id').get('value')==-1){
		 dijit.byId('frm_co').show();
	}
}
function popupCheckZone(){
	if(dijit.byId('zone').get('value')==-1){
		 dijit.byId('frm_zone').show();
	}
}
function popupCheckDistrict(){
	if(dijit.byId('district').get('value')==-1){
		 dijit.byId('frm_district').show();
	}
}
function popupCheckCommune(){
	if(dijit.byId('commune').get('value')==-1){
		 dijit.byId('frm_commune').show();
	}
}
function popupCheckVillage(){
	if(dijit.byId('village').get('value')==-1){
		 dijit.byId('frm_village').show();
	}
}

var url_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'client','action'=>'add-newclient')); ?>';
function addNewClient(){
		dojo.xhrPost({
	    url: url_submit,	
		form: dojo.byId("form_client"),		    
		handleAs:"json", 
		load: function(data) {	
			dijit.byId('frm_client').reset(); 
			dijit.byId('frm_client').hide();
		},
		error: function() {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitzone = '<?php echo $this->url(array('module'=>'other','controller'=>'zone','action'=>'add-newzone')); ?>';
function addNewZone(){
		dojo.xhrPost({
	    url: url_submitzone,	
		form: dojo.byId("form_zone"),		    
		handleAs:"json",
		load: function(data) {	
			//alert(data);
			dojo.byId('form_zone').reset(); 
			dijit.byId('frm_zone').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			alert(data);
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>
<?php 
 echo $this->frmpupopclient;
 echo $this->frmPopupCO;
 echo $this->frmPopupZone;
 echo $this->frmPopupCommune;
 echo $this->frmPopupDistrict;
 echo $this->frmPopupVillage;
?>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	//alert('date release'+date_release);
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('date_line').attr('value',epx_date);
	calCulateFirstPayment();
}
function CalculateDate(){
	pay_term = dijit.byId('pay_every').get('value');
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("release_date").get('value');
	//alert('date first'+release_date);
	
	if(isNaN(amount_date)){
		//alert('សូមបញ្ចលចំនួនរយៈពេល​ !');
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function calCulatePeriod(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = dijit.byId('collect_termtype').get('value');
	amount_date = dijit.byId('amount_collect').get('value');
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
	if(pay_term==3){//month
		mm = a.getMonth()+amount_date+1;
	}else if(pay_term==2){//week
		a.setDate(a.getDate() + (amount_date*7)); 
		var mm = a.getMonth() + 1;
	}else if(pay_term==1){
		a.setDate(a.getDate() + (amount_date)); 
		var mm = a.getMonth() + 1;
	}
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
</script>