<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Group Disburse"));
$frm = $this->frm_search;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'GroupDisburse','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
 <table width="100%">
   		<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement("customer_code");?></td>
   			<td><?php echo $frm->getElement("member");?></td>
   			<td><?php echo $frm->getElement("repayment_method");?></td>
   			<td> <?php echo $frm->getElement('branch_id');?></td>
   		</tr>
   		<tr>
   			
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   			<td><?php echo $frm->getElement('currency_type');?></td>
   			<td><?php echo $frm->getElement('pay_every');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement("btn_search");?></td>
   			<td colspan="3"></td>
   		</tr>
   		<tr>
   			<td colspan="5"><?php echo $this->list;?></td>
   		</tr>
   </table>
   
</form>
