<?php
	$this->headTitle('Add Transfer'); 
	echo $this->headTitle();
	$frm = $this->frm_transfer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>

<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferco-client','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
  if(this.validate()) {
    if(dijit.byId('branch_name').get('value')==''){
     alert('សូមមេតាជ្រើសរើសប្រភេទសាខា');
     dijit.byId('callecterall_type').focus();
     return false;
   	}
	if(dijit.byId('co_code').get('value')==''){
     alert('សូមមេតាជ្រើសរើសប្រភេទកូដ CO');
     dijit.byId('callecterall_type').focus();
     return false;
   	}
    return true;
   }else {
    return false;
   }
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>TRANSFER_CO</strong></legend>
					<table cellspacing="10">
						<tr>	
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php  echo $frm->getElement('branch_name');?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php  echo $frm->getElement('Date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_CLIENT")?></td>
							<td><?php  echo $frm->getElement('name_client');?></td>
							<td><?php echo $tr->translate("CODE_CLIENT")?></td>
							<td><?php  echo $frm->getElement('code_client');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CODE_CO")?></td>
							<td><?php  echo $frm->getElement('co_code');?></td>
							<td><?php echo $tr->translate("NAME_CO")?></td>
							<td><?php  echo $frm->getElement('name_co');?></td>
						</tr>						
					    <tr>  
					        <td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $frm->getElement('status');?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('Note');?></td>
							<td></td>
							<td></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" name="btn_save" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<input type="submit" value="រក្សាទុក & ចាកចេញ" name="btn_save_close" label="រក្សាទុក & ចាកចេញ" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			<?php $url_close = $this->url(array('module'=>'loan','controller'=>'transferco-client','action'=>'index'),null,true); ?>
			<a href="<?php echo $url_close ?>">
				<input type="button" value="ចាកចេញ" name="btn_close" label="ចាកចេញ" id="submitButton_Close" dojoType="dijit.form.Button"  iconClass=" dijitIconCancel"/>							
			</a>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
<!--
	function getClientInfo(type){
		if(type==1){						
			id = dijit.byId("co_code").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
			
		}else if(type==2){
			id = dijit.byId("name_co").get('value');
			dijit.byId("name_co").attr('value',id);
			dijit.byId("co_code").attr('value',id);
		}
		else if(type==3){		
			to = dijit.byId("name_client").get('value');		
			dijit.byId("code_client").attr('value',to);
			dijit.byId("name_client").attr('value',to);
		}else if(type==4){
			to = dijit.byId("code_client").get('value');
			dijit.byId("code_client").attr('value',to);
			dijit.byId("name_client").attr('value',to);
		}
	}
//-->
</script>
