<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Edit Zond Area'));
?>	
<?php  $frm = $this->frm_zone;?>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'Zone','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("Edit Zone Area");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>Zone Name</td>
							<td><?php  echo $frm->getElement('zone_name');?>
								<?php  echo $frm->getElement('id');?></td>
						</tr>
						<tr>
							<td>Zone Number</td>
							<td><?php  echo $frm->getElement('zone_number');?></td>
						</tr>
						
						<tr>
							<td>Status</td>
							<td><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
							<input type="submit" value="GO_SAVE" label="<?php echo $tr->translate('GO_SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="dijit.byId("add_techer").submit();"/>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>