 <input type="button" label="Individual Client" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-individual-client')); ?>';"/>
  
  <input type="button" label="Group Client" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-group-client')); ?>';"/>
  
  <input type="button" label="Client Agreement" dojoType="dijit.form.Button" 
  onclick="window.location = '<?php echo $this->url(array('module'=>'report','controller'=>'payroll','action'=>'rpt-client-agreement')); ?>';"/>
  
 