<meta charset="utf-8">
<table width="80%"  align="center" style="border-collapse:collapse;">
	<tr align="center">
    	<td>
        <h2 align="center">Contract History</h2>
            <table width="80%" align="center" ">
                <tr>
                    <td>Contract Code:</td>
                    <td>03522/14/TSORTP</td>
                    <td> Entry Fees</td>
                    <td>entry_fees</td>
                </tr>
                <tr>
                    <td>2/100032/294:</td>
                    <td></td>
                    <td>No.Installments</td>
                    <td>15</td>
                </tr>
                <tr>
                    <td>Start Date:</td>
                    <td>22/06/2014</td>
                    <td>Interress Rate</td>
                    <td>20,00</td>
                </tr>
                <tr>
                    <td>Loan:</td>
                    <td>20000,00</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Curency:</td>
                    <td>Ghara Code</td>
                    <td></td>
                    <td></td>
                </tr> 
                <tr>
                    <td>loan officer:</td>
                    <td>Noa9</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr >
                    <td>Client Name:</td>
                    <td>Chenda</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr >
                    <td>Pass.No:</td>
                    <td>10332</td>
                    <td></td>
                    <td></td>
                </tr>
            </table><br /><br /><br />
            <table width="80%" border="1" align="center" style="border-collapse:collapse;">
            	<tr bgcolor="#BBBBBB">
            		<th>Ever Type</th>
                    <th>Evert Date</th>
                    <th>Principal</th>
                    <th>Extrano</th>
                    <th>Fee</th>
                    <th>Laon Days</th>
                </tr>
                <tr>
            		<td>&nbsp;&nbsp;LODE</td>
                    <td>&nbsp;&nbsp;22/06/2014</td>
                    <td>&nbsp;&nbsp;10000,00</td>
                    <td>&nbsp;&nbsp;00</td>
                    <td>&nbsp;&nbsp;00</td>
                    <td>&nbsp;&nbsp;0</td>
                </tr>
                <tr>
            		<td>&nbsp;&nbsp;RGLE</td>
                    <td>&nbsp;&nbsp;22/06/2014</td>
                    <td>&nbsp;&nbsp;10000,00</td>
                    <td>&nbsp;&nbsp;00</td>
                    <td>&nbsp;&nbsp;00</td>
                    <td>&nbsp;&nbsp;0</td>
                </tr>
            </table><br /><br /><br />
            <table width="80%" border="1" align="center" style="border-collapse:collapse;">
            	<tr bgcolor="#BBBBBB" align="center">
                	<th>Number</th>
                    <th>Capital Requirement</th>
                    <th>Income Repuirement</th>
                    <th>Trial</th>
                    <th>Paid Trial</th>
                    <th>Paid Capital</th>
                    <th>Expected Dail</th>
                    <th>Paid Date</th>
                </tr>
                <?php for($i=0;$i<=10;$i++){?>
                <tr>
                	<td>&nbsp;&nbsp;<?php echo $i+1;?></td>
                    <td>&nbsp;&nbsp;000.07</td>
                    <td>&nbsp;&nbsp;14000.00</td>
                    <td>&nbsp;&nbsp;00</td>
                    <td>&nbsp;&nbsp;14400.00</td>
                    <td>&nbsp;&nbsp;000.07</td>
                    <td>&nbsp;&nbsp;2201.2014</td>
                    <td>&nbsp;&nbsp;2207.2014</td>
                </tr>
                <?php }?>
            </table>
        </td>
    </tr>
</table>


