<table width="80%" align="center"  style="border-collapse:collapse;margin-left:30px;" >
	<tr >
    	<td><h3>Client personal information</h3>
        	<table width="59%" style="float:left;margin-left:15px;"  >
                <tr >
                    <th >First Name:</th>
                    <td>Thida</td>
                    <td>Gender:</td>
                    <td>F</td>
                </tr>
                <tr>
                    <th>Last Name:</th>
                    <td>K.BOADI PALMAR</td>
                    <td>ID number:</td>
                    <td>10403</td>
                </tr>
                <tr>
                    <th>FatherName</th>
                    <td></td>
                    <td>Date of Birth</td>
                    <td>4/13/1974</td>
                </tr>
                
			</table>
            <img src="../../services_bg_pic.jpg" width="180px"  style="float:right; margin-top:-25px;">
            <h3 style="clear:both; ">Personal Address:</h3> 
            <table width="59%" style="margin-left:30px;clear:both; float:left; border:rgba(0,0,0,1) solid 1px;">
                <tr>
                    <td>District:</td>
                    <td>Ga EasMunicipal</td>
                    <td>City</td>
                    <td>ACCRA</td>
                </tr>
                <tr>
                    <td>Address</td>
                    <td colspan="3">FormKanishe FormKanishe FormKanishe FormKanishe </td>
                    
                </tr>
                <tr>
                    <td>Phone</td>
                    <td colspan="3">00004.922.635</td>
                    
                </tr>
			</table>
            <img src="../../organicplants.jpg" width="180px"  style="float:right; margin-top:-38px;">
            <h3 style="clear:both;">Business Address</h3>
           <table width="59%" style="clear:both; border:rgba(0,17,0,1) solid 1px;margin-left:30px;" >
                <tr>
                    <td>District:</td>
                    <td>Ga Central (New)</td>
                    <td>City</td>
                    <td>ACCRA</td>
                </tr>
                <tr>
                    <td>Address</td>
                    <td colspan="3">FormKanishe FormKanishe FormKanishe FormKanishe </td>
                    
                </tr>
                <tr>
                    <td>Phone</td>
                    <td colspan="3">00004.922.635</td>
                    
                </tr>
                <tr>
                    <td>Phone</td>
                    <td colspan="3">00004.922.635</td>
                    
                </tr>
			</table> 
            <table width="100%" border="1" style="border-collapse:collapse;font-size:12px;margin-left:30px;" bordercolor="black">
            <br/>  	<tr  bgcolor="#BBBBBB" align="center">
                	<th>Contract Code </th>
                    <th>Status</th>
                    <th>Amount</th>
                    <th>OLB</th>
                    <th>Creatin Date</th>
                    <th>Start Date</th>
                    <th>Close Date</th>
                    <th>Group</th> 
                    <th>Late Day</th>
                    <th>ATR</th>
                </tr>
                <tr>
                	<td>&nbsp;&nbsp;02233/11122/111113</td>
                    <td>&nbsp;&nbsp;Closed</td>
                    <td>&nbsp;&nbsp;1.000.00</td>
                    <td>&nbsp;&nbsp;00.0</td>
                    <td>&nbsp;&nbsp;8/22/2014</td>
                    <td>&nbsp;&nbsp;8/5/2013</td>
                    <td>&nbsp;&nbsp;2/28/2014</td>
                    <td>&nbsp;&nbsp;.</td>
                    <td>&nbsp;&nbsp;1,392</td>
                    <td>&nbsp;&nbsp;no</td>
                </tr>
                <tr>
                	<td>&nbsp;&nbsp;02233/11122/111113</td>
                    <td>&nbsp;&nbsp;Closed</td>
                    <td>&nbsp;&nbsp;1.000.00</td>
                    <td>&nbsp;&nbsp;00.0</td>
                    <td>&nbsp;&nbsp;8/22/2014</td>
                    <td>&nbsp;&nbsp;8/5/2013</td>
                    <td>&nbsp;&nbsp;2/28/2014</td>
                    <td>&nbsp;&nbsp;.</td>
                    <td>&nbsp;&nbsp;1,392</td>
                    <td>&nbsp;&nbsp;no</td>
                </tr>
            </table>
          <br/>  <table width="100%" border="1" style="border-collapse:collapse;font-size:12px;margin-left:30px;" bordercolor="black">
            	<tr bgcolor="#BBBBBB" align="center">
                	<th>Savings Code</th>
                    <th>Baland</th>
                    <th>Product Name</th>
                    <th>Product Code</th>
                    <th>Product type</th>
                    <th>Creation Date</th>
                    <th>Closed Date</th>
                </tr>
                <tr>
                	<td>&nbsp;&nbsp;02233/11122/111113</td>
                    <td>&nbsp;&nbsp;-09577</td>
                    <td>&nbsp;&nbsp;BUYSAVE</td>
                    <td>&nbsp;&nbsp;100</td>
                    <td>&nbsp;&nbsp;SAVINT BOOK</td>
                    <td>&nbsp;&nbsp;8/2/2013</td>
                    <td>&nbsp;&nbsp;</td>
                    
                </tr>

            </table>
        </td>
    </tr>
</table>