<meta charset="utf-8">
<title>Report Loan Payment Detail</title>
<div style="margin:0 auto; width:21cm;">
	<table style="margin:0 auto; width:100%; font-style:oblique;" border=1>
         <tr>
            <td  width="10%"><img src="file:///C|/Users/DELL/Desktop/logo.jpg" height="70px"></td>
            <td  width="70%"><h4 style="font-size:14px; font-family:'Khmer OS Muol';​​​" align="center">របាយការណ៏ផ្តល់ឥណទាន</h4></td>
            <td></td>
    	</tr>
        <tr>
        	<td colspan="3">
            	<table width="100%">
                    <tr>
                        <td colspan="2">Branch</td>
                        <td colspan="2">Apple </td>
                        <td>sihanoukville</td>
                    </tr>
                    <tr>
                        <td>Pay </td>
                        <td>Status </td>
                        <td>Normal </td>
                        <td>Loan Pament</td>
                        <td>Pament</td>
                        
                    </tr>
                    <tr>
                        <td>FromData </td>
                        <td>6/13/2014 </td>
                        <td>ToData </td>
                        <td>6/13/2014</td>
                        <td>h</td>
                    </tr>
                    </table>
            </td>
         </tr>
         <tr>
         	<td colspan="3">
            	<table  cellspacing="0" style="margin:0 auto; width:100%; font-style:italic;" border="1">
                    <tr style="color:rgba(0,0,255,1);">
                        <td  style="padding:2px 20px;">date</td>
                        <td  style="padding:2px 20px;">payData</td>
                        <td  style="padding:2px 20px;">code</td>
                        <td  style="padding:2px 20px;">Applicatio</td>
                        <td  style="padding:2px 20px;">month</td>
                        <td  style="padding:2px 20px;">year</td>
                        <td  style="padding:2px 20px;">total</td>
                    </tr>
                    <tr>
                        <td colspan="7" align="center">Credit offic Name: Kev Somnang Amount Rele ase :200,000</td>
                    </tr>
                    <tr>
                        <td colspan="2">Group Name :Meng Sokmean</td>
                        
                        <td>200,000</td>
                        <td colspan="4" rowspan="3"></td>
                    </tr>
                    <tr>
                        <td colspan="2">Village#1</td>
                        <td>200,000</td>
                        
                    </tr>
                    <tr>
                        <td colspan="2">District#2</td>
                        <td>200,000</td>
                    </tr>
                    <tr>
                        <td colspan="2">Time</td>
                        
                        <td>200,000</td>
                        <td>0.1</td>
                        <td>12</td>
                        <td>Desecc</td>
                        <td>Jun,13,2014</td>
                    </tr>
                    <tr>
                        <td colspan="7" align="center">Total :200,000</td>
                    </tr>
                </table>
            </td>
         </tr>
</table>
</div>