
<meta charset="utf-8">
<title>Untitled Document</title>
<table align="center" width="80%" border="1" style="border-collapse:collapse;">
	<tr>
		<td>
            <h2>OBL and LLP per loan</h2>
            15.12.2014 all currencies->Pound
            <table width="100%" align="center" style="border-collapse:collapse;">
                <tr bgcolor="#BBBBBB">
                    <td>Contact Code</td>
                    <td>Start Date</td>
                    <td>Close Date</td>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Loan Officcer</td>
                    <td>Branch</td>
                    <td>Interest</td>
                    <td>OBL</td>
                    <td>Late Day</td>
                    <td>LLP,%</td>
                    <td>LLP</td>
                    <td>District Name</td>
                </tr>
                <tr>
                    <td colspan="13"><b>Note Late</b></td>
                    
                </tr>
                <?php for($i=1;$i<=2;$i++) {?>
                <tr>
                    <td>LDH/14/1l-1/19/31</td>
                    <td>11/6/2014</td>
                    <td>2/6/2015</td>
                    <td>Path</td>
                    <td>Smith</td>
                    <td>AdminAdmin</td>
                    <td>LDH</td>
                    <td>81.0</td>
                    <td>900.00</td>
                    <td>0</td>
                    <td>2</td>
                    <td>18.0</td>
                    <td>London District</td>
                </tr>
                <?php }?>
                <tr bgcolor="#BBBBBB">
                    <td colspan="7"><b>Subtotal-Note Date</b></td>
                    
                    <td>162.00</td>
                    <td>1800.00</td>
                    <td></td>
                    <td></td>
                    <td>36.0</td>
                    <td></td>
                </tr>
                
                 <tr>
                    <td colspan="13"><b>Late form 1 to 30 days</b></td>
                    
                </tr>
                <?php for($i=1;$i<=7;$i++) {?>
                <tr>
                    <td>LDH/14/1l-1/19/31</td>
                    <td>11/6/2014</td>
                    <td>2/6/2015</td>
                    <td>Path</td>
                    <td>Smith</td>
                    <td>AdminAdmin</td>
                    <td>LDH</td>
                    <td>81.0</td>
                    <td>900.00</td>
                    <td>0</td>
                    <td>2</td>
                    <td>18.0</td>
                    <td>London District</td>
                </tr>
                <?php }?>
                <tr bgcolor="#BBBBBB">
                    <td colspan="7"><b>Subtotal-Form 1 to 30 day</b></td>
                    
                    <td>162.00</td>
                    <td>1800.00</td>
                    <td></td>
                    <td></td>
                    <td>36.0</td>
                    <td></td>
                </tr>
                
                <tr>
                    <td colspan="13"><b>Late form 16 to 90 days</b></td>
                    
                </tr>
                <?php for($i=1;$i<=4;$i++) {?>
                <tr>
                    <td>LDH/14/1l-1/19/31</td>
                    <td>11/6/2014</td>
                    <td>2/6/2015</td>
                    <td>Path</td>
                    <td>Smith</td>
                    <td>AdminAdmin</td>
                    <td>LDH</td>
                    <td>81.0</td>
                    <td>900.00</td>
                    <td>0</td>
                    <td>2</td>
                    <td>18.0</td>
                    <td>London District</td>
                </tr>
                <?php }?>
                <tr bgcolor="#BBBBBB">
                    <td colspan="7"><b>Subtotal-Form 16 to 90 day</b></td>
                    
                    <td>162.00</td>
                    <td>1800.00</td>
                    <td></td>
                    <td></td>
                    <td>36.0</td>
                    <td></td>
                </tr>
                
                <tr>
                    <td colspan="13"><b>Late form 91 to 180 days</b></td>
                    
                </tr>
                <?php for($i=1;$i<=2;$i++) {?>
                <tr>
                    <td>LDH/14/1l-1/19/31</td>
                    <td>11/6/2014</td>
                    <td>2/6/2015</td>
                    <td>Path</td>
                    <td>Smith</td>
                    <td>AdminAdmin</td>
                    <td>LDH</td>
                    <td>81.0</td>
                    <td>900.00</td>
                    <td>0</td>
                    <td>2</td>
                    <td>18.0</td>
                    <td>London District</td>
                </tr>
                <?php }?>
                <tr bgcolor="#BBBBBB">
                    <td colspan="7"><b>Subtotal-Form 91 to 180 day</b></td>
                    
                    <td>162.00</td>
                    <td>1800.00</td>
                    <td></td>
                    <td></td>
                    <td>36.0</td>
                    <td></td>
                </tr>
                
                
                <tr bgcolor="#BBBBBB">
                    <td colspan="7"><b>TOTAL</b></td>
                    
                    <td>162.00</td>
                    <td>1800.00</td>
                    <td></td>
                    <td></td>
                    <td>36.0</td>
                    <td></td>
                </tr>
                
            </table>
        </td>
     </tr>
 </table>