<meta charset="utf-8">
<title>Repayment</title>

<table width="80%" align="center" border="1" cellspacing="0">
	<tr>
    	<td>
        	<h2>Repayment</h2>
            <p>5.12.2014.all Currencies-Pound</p>
                <table width="100%" style="border-collapse:collapse;">
                    <tr>
                        <td>Date</td>
                        <td>Contract code</td>
                        <td>first Name</td>
                        <td>Last Name</td>
                        <td>Loan officer</td>
                        <td>product</td>
                        <td>District</td>
                        <td>Branch</td>
                        <td>Early fee</td>
                        <td>Late fee</td>
                        <td>Principal</td>
                        <td>Interest</td>
                        <td>Total</td>
                    </tr>
                    <tr height="40px">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr height="40px">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr bgcolor="#888888">
                        <td>TOTAL</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
             </td>
        </tr>
    </table>
