<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Staff Salary</title>
</head>

<body>
	<h2 align="center">Staff Salary(12/23/2014-1/24/2015)</h2><br/>
	<table width="100%" border="1" style="border-collapse:collapse;font-size: 12px;" bordercolor="black">
    
    	<tr bgcolor="#BBBBBB" >
        	<th>N<sub>0</sub></th>
            <th>StaffID</th>
            <th>Name Khmer</thd>
            <th>Name Eng</th>
            <th>Position</th>
            <th>Branch Name</th>
            <th>Basic Salary</th>
            <th>OT</th>
            <th>Other</th>
            <th>Salary</th>
             <th>Note</th>
         </tr>
      
<!--         <tr align="center"> -->
<!--         	<td>12</td> -->
<!--         	<td colspan="4">TOTAL</td> -->
<!--             <td></td> -->
<!--             <td></td> -->
          
<!--         </tr> -->
    </table>
</body>
</html>