<?php
	$this->headTitle('Add IL Payment'); 
	echo $this->headTitle();
	$frm = $this->frm_ilpayment;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_group_pay' action="<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន បង់ប្រាក់ឥណទានទោល</strong></legend>
					<table class="center" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះប្រធានក្រុម")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("លេខកូដអតិថិជន")?></td>
							<td><?php  echo $frm->getElement('client_code');?></td>
							<td><?php echo $tr->translate("ស្គែន/បញ្ចូលលេខកូដកម្ចី")?></td>
							<td><?php echo $frm->getElement('loan_number');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							<td><?php echo $tr->translate("ថ្ងៃប្រមូលប្រាក់")?></td>
							<td><?php  echo $frm->getElement('collect_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រាក់ដើមនៅសល់")?></td>
							<td align="left"><?php echo $frm->getElement('priciple_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ដើមត្រូវសង")?></td>
							<td><?php echo $frm->getElement('os_amount');?></td>
							<td><?php echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php echo $frm->getElement('total_interest');?></td>
						</tr>
						<tr>
							
							<td><?php echo $tr->translate("ប្រាក់ផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('penalize_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ត្រូវបង់សរុប")?></td>
							<td><?php echo $frm->getElement('total_payment');?></td>
							<td><?php echo $tr->translate("កំណត់សម្គាល់")?></td>
							<td><?php echo $frm->getElement('note');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("បង់ថ្លៃសេវា")?></td>
							<td><?php echo $frm->getElement('service_charge');?></td>
							<td><?php echo $tr->translate("ប្រាក់ទទួលបាន")?></td>
							<td><?php echo $frm->getElement('amount_receive');?></td>
							<td><?php echo $tr->translate("ប្រាក់អាប់")?></td>
							<td><?php  echo $frm->getElement('amount_return');?></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><?php echo $tr->translate("ថ្ងៃទទួលប្រាក់")?></td>
							<td><?php  echo $frm->getElement('date_input');?></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
			<td align="center">
			   <input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave" onclick="submitData();"/>
			   <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="saveprint" dojoType="dijit.form.Button" 
			   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="addDatatogrid();"/>
			</td>
		</tr>
		<tr>
			<td>
				<fieldset>
					<legend><strong>ប្រវត្តិនៃការបង់ប្រាក់</strong></legend>
					<?php //echo $this->list;?>
					<div id='data_table' name='data_table'></div>
					<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
							<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
				</table>
				
				</fieldset>
		 </td>
	</tr>		
</table>
<input type="text" dojoType="dijit.form.TextBox" name="identity" id="identity">
<?php  echo $frm->getElement('reciever');?>
</form>
<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
function submitData(){
	var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addloan')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
				//alert(data);
				
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
// dojo.ready(function(){	
// 	dijit.byId('loan_number').focus();
// 	client_code = dojo.byId("client_code");
// 	dojo.connect(client_code,"onkeyup", function(events) {
// 		key_num = (events.keyCode);
// 		if(key_num==13){
// 			getLoanById(2);
// 		}
// 	});	
	
// 	document = dojo.byId("loan_number");
// 	dojo.connect(document, "onkeyup", function(event) {
// 		key_number = (event.keyCode);
// 		if(key_number==13){
// 			getLoanById(1);
// 		}
// 	});	
// 	/*group = dojo.byId("group_id");
// 	dojo.connect(group, "onchange", function(event) {
// 		key_number = (event.keyCode);
// 		//if(key_number==13){
// 		alert(2);
// 			getLoanById(3);
// 		//}
// 	});	*/

// });
temp='';
r = 0;
fund_title=0;
function getLoanById(type){
	
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('group_id').get('value');
	}
	
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'get-loannumber')); ?>';
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(respone) {
				status='<label style="color:red;">នៅឡើយ</lable>';
				tem='';	is_set=0;
				tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader">ល.រ</th>'
					+'<th class="tdheader"><input type="checkbox" OnChange="checkAll();" name="check_all" id="check_all" /></th>'
					+'<th class="tdheader">កូដអតិថិជន</th>'
					+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
					+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
					+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
					+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
					+'<th class="tdheader">ប្រាក់ការ</th>'
					+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
					+'<th class="tdheader">ស្ថានភាព</th>'
					+'<th class="tdheader">កំណត់សម្គាល់</th></tr>'
				+'</thead>';
				num=0;
				total_payment=0;
				totalos_amount=0;
				total_interest=0;
				for(i=0;i<respone.length;i++){
					inx = i+1;
					status='<label style="color:red;">នៅឡើយ</lable>';
					++num;
					d = new Date(respone[i].date_payment);
					str_day = getDayString(d.getDay());
					curr =getCurrencyType(respone[i].currency_type);
					//date_collect = d.getDate()+'/'+d.getFullMonth()+'/'+d.getFullYear()
					total_payment = total_payment + parseFloat(respone[i].total_payment,2);
					totalos_amount = totalos_amount + parseFloat(respone[i].principal_permonth,2);
					total_interest = total_interest + parseFloat(respone[i].total_interest,2);
					client_id = respone[i].client_id;
					total_principal = respone[i].total_principal;
					principal_permonth = respone[i].principal_permonth;
					interest = respone[i].total_interest;
					payment = respone[i].total_payment;
					id = respone[i].id;
					 tem+= '<tr>';
					    tem += '<td>&nbsp;'+num+'</td>';
					    tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" /></td>';
					    tem += '<td>&nbsp;'+respone[i].client_number+'&nbsp;<input type="text" name="client_id_'+inx+'" id="client_id_'+inx+'" value="'+client_id+'" /></td>';
					    tem += '<td>&nbsp;'+respone[i].name_kh+'&nbsp;</td>';
					    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;<input type="text" name="date_'+inx+'" id="date_'+inx+'" value="'+respone[i].date_payment+'" /></td>';
					    tem += '<td style="white-space: nowrap;">&nbsp;'+respone[i].date_payment+'&nbsp;</td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_principal)+' '+curr+'&nbsp;<input type="text" name="total_priciple_'+inx+'" id="total_priciple_'+inx+'" value="'+total_principal+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].principal_permonth)+' '+curr+'&nbsp;<input type="text" name="principal_permonth_'+inx+'" id="principal_permonth_'+inx+'" value="'+principal_permonth+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_interest)+' '+curr+'&nbsp;<input type="text" name="interest_'+inx+'" id="interest_'+inx+'" value="'+interest+'" /></td>';
					    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_payment)+' '+curr+'&nbsp;<input type="text" name="payment_'+inx+'" id="payment_'+inx+'" value="'+payment+'" /></td>';
						if(respone[i].is_completed==1){
							status = '<label style="color:blue;">បង់រួច</label>';
							if(respone[i].is_approved==1){is_appr='<label style="color:blue;">Approved</label>';}
						}else{
							if(is_set!=1){
								getdataPaymentToForm(respone[i]);
								is_set=1;
							}
							is_appr='';
						}
						tem += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
						tem += '<td>&nbsp;<label style="font-size:10px;">'+is_appr+'</label></td>';
					    tem += '</tr>';
					    if(inx!=1) {
							var identity = dijit.byId('identity').get('value');
							dijit.byId('identity').attr('value',identity+','+inx);
						} else {
							dijit.byId('identity').attr('value',inx);
						}
				}
				dijit.byId('total_payment').attr('value',total_payment); 
				dijit.byId('os_amount').attr('value',totalos_amount); 
				dijit.byId('total_interest').attr('value',total_interest);
				tem+='</table>';
				dojo.byId('data_table').innerHTML = tem;
			},
			error: function(e) {
				alert(e);
			}
		});
}
function popupCheckCO(){
}
function checkAll(i){	
	if($('#check_all').attr('checked')){
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
	}else{
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });
	}
}

function getdataPaymentToForm(data){//use
	dijit.byId('group_id').attr('value',data.group_id);
	dijit.byId('co_id').attr('value',data.co_id);
	dijit.byId('branch_id').attr('value',data.branch_id);
	dijit.byId('total_interest').attr('value',data.total_interest);
	dijit.byId('loan_number').attr('value',data.loan_number);
	dijit.byId('client_code').attr('value',data.group_number);
	dijit.byId('reciever').attr('value',data.collect_by);
	totalReturn();
}
function getDayString(num){
	var days= ["ច័ន្ទ", "អង្គារ", "ពុធ", "ព្រហ","សុក្រ","សៅរ៏","អាទិត្យ"];
	return days[num];
}
function getCurrencyType(type){
	var option=["៛","$","B"];
	return option[type-1];
}
function totalReturn(){
	receive_amount = dijit.byId('amount_receive').get('value');
	total_payment = dijit.byId('total_payment').get('value');
	amonut_return = receive_amount-total_payment;
	dijit.byId('amount_return').attr('value',amonut_return);
}
</script>
