<?php
	$this->headTitle('Add IL Payment'); 
	echo $this->headTitle();
	$frm = $this->frm_ilpayment;
	$client = $this->client;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>	
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>

<form id='frm_add_group_pay' action="<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong>ព៌ត័មាន បង់ប្រាក់ឥណទានទោល</strong></legend>
					<table class="center" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("សាខា")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("ស្គែន/បញ្ចូលលេខកូដកម្ចី")?></td>
							<td><?php echo $frm->getElement('loan_number');?></td>
							<td><?php echo $tr->translate("វិក័យបត្រ")?></td>
							<td><?php echo $frm->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ឈ្មោះប្រធានក្រុម")?></td>
							<td><?php //echo $frm->getElement('group_id');?>
								<input id="group_id">
							</td>
							<td><?php echo $tr->translate("លេខកូដអតិថិជន")?></td>
							<td><?php  //echo $frm->getElement('client_code');?> <input id="client_code"></td>
							<td><?php echo $tr->translate("ឈ្មោះ CO")?></td>
							<td><?php echo $frm->getElement('co_id');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃប្រមូលប្រាក់")?></td>
							<td><?php  echo $frm->getElement('collect_date');?></td>
							<td><?php echo $tr->translate("ប្រាក់ដើមនៅសល់")?></td>
							<td align="left"><?php echo $frm->getElement('priciple_amount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ដើមត្រូវសង")?></td>
							<td><?php echo $frm->getElement('os_amount');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("អាត្រាការប្រាក់")?></td>
							<td><?php echo $frm->getElement('total_interest');?></td>
							<td><?php echo $tr->translate("ប្រាក់ត្រូវបង់សរុប")?></td>
							<td><?php echo $frm->getElement('total_payment');?></td>
							<td><?php echo $tr->translate("ប្រាក់ផាកពិន័យ")?></td>
							<td><?php echo $frm->getElement('penalize_amount');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("បង់ថ្លៃសេវា")?></td>
							<td><?php echo $frm->getElement('service_charge');?></td>
							<td><?php echo $tr->translate("ថ្ងៃទទួលប្រាក់")?></td>
							<td><?php  echo $frm->getElement('date_input');?></td>
							<td><?php echo $tr->translate("កំណត់សម្គាល់")?></td>
							<td><?php echo $frm->getElement('note');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("បញ្ចុះតម្លៃ")?></td>
							<td><?php  echo $frm->getElement('discount');?></td>
							<td><?php echo $tr->translate("ប្រាក់ទទួលបាន")?></td>
							<td><?php echo $frm->getElement('amount_receive');?></td>
							<td><?php echo $tr->translate("ប្រាក់អាប់")?></td>
							<td><?php  echo $frm->getElement('amount_return');?></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><?php echo $tr->translate("ប្រភេទរូបិយបណ្ណ")?></td>
							<td><?php echo $frm->getElement('currency_type');?></td>
						</tr>
					</table>
				</fieldset>
		   </td>
		</tr>
		<tr>
			<td align="center">
			   <input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
			   iconClass="dijitEditorIcon dijitEditorIconSave"/>
			   <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="saveprint" dojoType="dijit.form.Button" 
			   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="showReciept();"/>
			</td>
		</tr>
		<tr>
			<td>
				<div id="mainTabContainer" style=" max-width:1135px;height: 394px;" dojoType="dijit.layout.TabContainer" region="center"  >
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="ការវិភាគបង់ប្រាក់" selected="true">
								 <div id='data_table' name='data_table'></div>
								<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
										<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
								</table>
						</div>
						<div class="tabContentSection" dojoType="dijit.layout.ContentPane"  title="ប្រវត្តិនៃការបង់ប្រាក់" selected="false">
							 <div id='data_table1' name='data_table1'></div>
								<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">
										<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>
								</table>
						</div>
				 </div>
				
		 </td>
	</tr>		
</table>

<input type="hidden" dojoType="dijit.form.TextBox" name="identity" id="identity">
<input type="hidden" dojoType="dijit.form.TextBox" name="record_id" id="record_id">
<input type="hidden" dojoType="dijit.form.TextBox" name="curr" id="curr">
<?php  echo $frm->getElement('reciever');?>
</form>
<div class="dijitHidden">
	
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'បោះពុម្ភ វិក័យបត្រ', onCancel:hideDialog" id="frm_client" style="width:800px">
	<div id="rpt_print" class="print">
	<style type="text/css">
		td.border {
			border-bottom: 1px dashed cadetblue;
		}
		div #rpt_print{font-size:12px !important; margin:0 auto;}
		 
		 .fontsize{ font-size:10px !important; margin:0 auto;}
	</style>
		<table cellspacing="10" class='fullside fontsize'>
				   <tr>
					   	<td align="center" colspan="3">	
					   <table  width="100%" cellspacing="0" cellpadding="0">
					   		<tr style="line-height:10px;">
					   			<td width="25%" rowspan="2" style="valign:top;"><img style="margin-top: 1px;" src="<?php echo $base_url;?>images/logobrand.jpg" height="34px;"/></td>
						   		<td colspan="2" align="right"><strong style="font-family:'KH Koulen';white-space: nowrap;font-size:11px;font-weight:bold; text-align:center;"><?php echo $this->keycode['group_payment_title'];?></strong></td>
							</tr>
					   	</table>
			            </td>	   	        
				   </tr> 
				   <tr>
					   	<td align="center" colspan="6" style="font-family:'KH Koulen'; border-bottom:1px solid #000"><?php echo $this->keycode['group_payment_recipt'];?></td>	   	        
					</tr> 
				   <tr>
					    <td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>កាលបរិច្ឆេទ :</td>
						<td align="right" style="font-size: 8pt;" >
							 <?php echo date('d-m-Y H:i:s');?><br/>
						</td>
				   </tr>
				  
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>ឈ្មោះបុគ្គលិក :</td>
					<td class="border">
						<strong class="fonttel" style="font-size:10px;"><label id="lblinvioice"><?php print($this->user_name);?></label></strong>
					</td>
					
			</tr>
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td>វិក័យបត្រ :</td>
					<td class="border">
								<strong class="fonttel" style="font-size:10px;"><label style="color:blue" id="lbl_reciept_no"></label></strong>
					</td>
					
			</tr>
			<tr class="fontsize">
					<td>ឈ្មោះប្រធានក្រុម :</td>
					<td class="border"><lable id="lbl_group_member"></lable></td>
					<td>លេខកូដអតិថិជន :</td>
					<td class="border"><lable id="lbl_group_code"></lable></td>
					<td>ស្គែន/បញ្ចូលលេខកូដកម្ចី :</td>
					<td class="border"><lable id="lbl_laon_nomber"></lable></td>
					
			</tr>
			<tr class="fontsize">
					<td class="fontsize">សាខា :</td>
					<td class="border"><lable id="lbl_branch_id"></lable></td>
					<td>ឈ្មោះ CO :</td>
					<td class="border"><lable id="lbl_co_id"></lable></td>
					<td>ថ្ងៃប្រមូលប្រាក់ :</td>
					<td class="border"><lable id="lbl_collect_date"></lable></td>
					
			</tr>
			<tr class="fontsize">
					<td>ប្រាក់ដើមនៅសល់ :</td>
					<td class="border"><lable id="lbl_priciple_amount"></lable></td>
					<td>ប្រាក់ដើមត្រូវសង :</td>
					<td class="border"><lable id="lbl_os_amount"></lable></td>
					<td>អាត្រាការប្រាក់ :</td>
					<td class="border"><lable id="lbl_total_interest"></lable></td>
			</tr>
			<tr class="fontsize">
					<td>ប្រាក់ផាកពិន័យ :</td>
					<td class="border"><lable style="color:red" id="lbl_penalize_amount"></lable></td>
					<td>ប្រាក់ត្រូវបង់សរុប :</td>
					<td class="border"><lable id="lbl_total_payment"></lable></td>
					<td>កំណត់សម្គាល់ :</td>
					<td class="border"><lable id="lbl_note"></lable></td>
			</tr>
			<tr class="fontsize">
					<td>បញ្ចុះតម្លៃ :</td>
					<td class="border"><lable style="color:red" id="lbl_discount"></lable></td>
					<td>បង់ថ្លៃសេវា :</td>
					<td class="border"><lable id="lbl_service_charge"></lable></td>
					<td>ថ្ងៃទទួលប្រាក់ :</td>
					<td class="border"><lable id="lbl_date_input"></lable></td>
			</tr>
			<tr class="fontsize">
					<td></td>
					<td></td>
					<td>ប្រាក់ទទួលបាន :</td>
					<td class="border"><lable style="color:red" id="lbl_amount_receive"></lable></td>
					<td>ប្រាក់អាប់ :</td>
					<td class="border"><lable style="color:red" id="lbl_amount_return"></lable></td>
			</tr>
			<tr class="fontsize" style="margin-top:20px;line-height: 60px">
					<td></td>
					<td></td>
					<td colspan="2" align="center">ហត្ថលេខាអ្នកទទួល </td>
					<td colspan="2" align="center">ហត្ថលេខាអ្នកបង់ </td>
			</tr>
			<tr class="fontsize" style="margin-top:20px;line-height: 20px">
					<td></td>
					<td></td>
					<td colspan="2" align="center">.............................. </td>
					<td colspan="2" align="center">.............................. </td>
			</tr>
		</table>
		</div>
		<input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" 
				   iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="print();"/>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>

<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
function showReciept(){
	var client_id = dijit.byId('group_id').get('value');
	if(client_id==""){
		alert("No Result To Show! Please Choose Client and Try again");
		dijit.byId('group_id').focus();
		dijit.byId('branch_id').focus();
		dijit.byId('loan_number').focus();
	}else{
		document.getElementById('lbl_reciept_no').innerHTML = dijit.byId('reciept_no').attr('displayedValue');
		document.getElementById('lbl_group_member').innerHTML = dijit.byId('group_id').attr('displayedValue');
		document.getElementById('lbl_group_code').innerHTML = dijit.byId('client_code').attr('displayedValue');
		document.getElementById('lbl_laon_nomber').innerHTML = dijit.byId('loan_number').attr('displayedValue');
		document.getElementById('lbl_branch_id').innerHTML = dijit.byId('branch_id').attr('displayedValue');
		document.getElementById('lbl_co_id').innerHTML = dijit.byId('co_id').attr('displayedValue');
		document.getElementById('lbl_collect_date').innerHTML = dijit.byId('collect_date').attr('displayedValue');
		document.getElementById('lbl_priciple_amount').innerHTML = dijit.byId('priciple_amount').attr('displayedValue');
		document.getElementById('lbl_os_amount').innerHTML = dijit.byId('os_amount').attr('displayedValue');
		document.getElementById('lbl_total_interest').innerHTML = dijit.byId('total_interest').attr('displayedValue');
	 	document.getElementById('lbl_penalize_amount').innerHTML = dijit.byId('penalize_amount').attr('displayedValue');
	 	document.getElementById('lbl_total_payment').innerHTML = dijit.byId('total_payment').attr('displayedValue');
	 	document.getElementById('lbl_note').innerHTML = dijit.byId('note').attr('displayedValue');
	 	document.getElementById('lbl_discount').innerHTML = dijit.byId('discount').attr('displayedValue');
	 	document.getElementById('lbl_service_charge').innerHTML = dijit.byId('service_charge').attr('displayedValue');
	 	document.getElementById('lbl_date_input').innerHTML = dijit.byId('date_input').attr('displayedValue');
	 	document.getElementById('lbl_amount_receive').innerHTML = dijit.byId('amount_receive').attr('displayedValue');
	 	document.getElementById('lbl_amount_return').innerHTML = dijit.byId('amount_return').attr('displayedValue');
		dijit.byId('frm_client').show();
		
	}
}


dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea");
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");

    var tran_store  = getDataStorefromJSON('','name',null);
	var tran_status = {};
	function print(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	function hideDialog() {		
		dijit.byId("frm_client").hide();
		submitData();
		window.location.href ="<?php echo $this->baseUrl();?>/loan/group-payment";
	}

	// Force them to provide an answer
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('frm_client').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
	
</script>
<script type="text/javascript">
function submitData(){
	//var json_data_t = itemToJSON(dijit.byId('tran_list'));
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_group_pay"),		    
			load: function(data) {	
				alert('ប្រាក់ឥណទានត្រូវបានបញ្ចូលដោយជោគជ័យ !');
				//alert(data);
			},
			error: function(e) {
				alert("Your message could not be sent, please try again!.");
			}
		});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}

var url_submitco = '<?php echo $this->url(array('module'=>'other','controller'=>'co','action'=>'add-newco')); ?>';
function AddNewCo(){
		dojo.xhrPost({
	    url: url_submitco,	
		form: dojo.byId("form_co"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_co').reset(); 
			dijit.byId('frm_co').hide();
		},
		error: function(err) {
			//alert(err);
		//alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
dojo.ready(function(){	
	var client_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->client));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "group_id",
	id: "group_id",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		getLaonPayment(3);
		getAllLaonPayment(3);
}
	}, "group_id");

	var clientCode_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->clientCode));?>
	});
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: clientCode_data}),
	autoComplete: true,
	query: {
		branch_id: "-1"
	},            
	required: false,		           
	name: "client_code",
	id: "client_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		getLaonPayment(2);
		getAllLaonPayment(1);
	}
	}, "client_code");
});
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('group_id').query.branch_id = branch_id;
	dijit.byId('client_code').query.branch_id = branch_id;
	//alert(dijit.byId('branch_id').get('value'));
	dijit.byId('group_id').reset();
	dijit.byId('client_code').reset();
}
temp='';
r = 0;
fund_title=0;
function getLaonPayment(type){
	
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('group_id').get('value');
	}
	
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'get-loannumber')); ?>';
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(respone) {
				status='<label style="color:red;">នៅឡើយ</lable>';
				tem='';	is_set=0;
				tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader">ល.រ</th>'
					+'<th class="tdheader"><input type="checkbox" OnChange="checkAll();" name="check_all" id="check_all" checked="checked" /></th>'
					+'<th class="tdheader">កូដអតិថិជន</th>'
					+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
					+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
					+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
					+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
					+'<th class="tdheader">ប្រាក់ការ</th>'
					+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
					+'<th class="tdheader">ប្រាក់ផាកពិន័យ</th>'
					+'<th class="tdheader">បញ្ចុះតម្លៃ</th>'
					+'<th class="tdheader">ស្ថានភាព</th>'
					+'<th class="tdheader">កំណត់សម្គាល់</th></tr>'
				+'</thead>';
				num=0;
				total_payment=0;
				totalos_amount=0;
				total_interest=0;
				if(respone!=""){
					dijit.byId('currency_type').attr('readOnly','readOnly');
					for(i=0;i<respone.length;i++){
						dijit.byId('curr').attr('value',respone[i].currency_type);
						inx = i+1;
						status='<label style="color:red;">នៅឡើយ</lable>';
						++num;
						d = new Date(respone[i].date_payment);
						str_day = getDayString(d.getDay());
						curr =getCurrencyType(respone[i].currency_type);
						//date_collect = d.getDate()+'/'+d.getFullMonth()+'/'+d.getFullYear()
						total_payment = total_payment + parseFloat(respone[i].total_payment);
						totalos_amount = totalos_amount + parseFloat(respone[i].principal_permonth);
						total_interest = total_interest + parseFloat(respone[i].total_interest);
						client_id = respone[i].client_id;
						total_principal = respone[i].total_principal;
						principal_permonth = respone[i].principal_permonth;
						interest = respone[i].total_interest;
						payment = respone[i].total_payment;
						pay_after = respone[i].pay_after;
						pay_before = respone[i].pay_before;
						date_pay = respone[i].date_payment;
						id = respone[i].id;
						total = total_payment + total_interest;
						//alert(total);
						 tem+= '<tr>';
						    tem += '<td>&nbsp;'+num+'</td>';
						    tem += '<td>&nbsp;<input type="checkbox" class="checkbox" name="mfdid_'+inx+'" id="mfdid_'+inx+'" value="'+id+'" OnChange="calculateTotal('+inx+')" /></td>';
						    tem += '<td>&nbsp;'+respone[i].client_number+'&nbsp;<input type="hidden" name="client_id_'+inx+'" id="client_id_'+inx+'" value="'+client_id+'" /></td>';
						    tem += '<td>&nbsp;'+respone[i].name_kh+'&nbsp;</td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+respone[i].date_payment+'&nbsp;<input type="hidden" name="date_payment_'+inx+'" id="date_payment_'+inx+'" value="'+date_pay+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_principal)+' '+curr+'&nbsp;<input type="hidden" name="total_priciple_'+inx+'" id="total_priciple_'+inx+'" value="'+total_principal+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].principal_permonth)+' '+curr+'&nbsp;<input type="hidden" name="principal_permonth_'+inx+'" id="principal_permonth_'+inx+'" value="'+principal_permonth+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_interest)+' '+curr+'&nbsp;<input type="hidden" name="interest_'+inx+'" id="interest_'+inx+'" value="'+interest+'" /></td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_payment)+' '+curr+'&nbsp;<input type="hidden" name="payment_'+inx+'" id="payment_'+inx+'" value="'+payment+'" /></td>';
						    tem += '<td>&nbsp;'+respone[i].pay_after+'&nbsp;<input type="hidden" name="pay_after_'+inx+'" id="pay_after_'+inx+'" value="'+pay_after+'" /></td>';
						    tem += '<td>&nbsp;'+respone[i].pay_before+'&nbsp;<input type="hidden" name="pay_before_'+inx+'" id="pay_before_'+inx+'" value="'+pay_before+'" /></td>';
							if(respone[i].is_completed==1){
								status = '<label style="color:blue;">បង់រួច</label>';
								if(respone[i].is_approved==1){is_appr='<label style="color:blue;">Approved</label>';}
							}else{
								if(is_set!=1){
									getdataPaymentToForm(respone[i]);
									is_set=1;
								}
								is_appr='';
							}
							tem += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
							tem += '<td>&nbsp;<label style="font-size:10px;">'+is_appr+'</label></td>';
						    tem += '</tr>';
	 					    if(inx!=1) {
	 							var identity = dijit.byId('identity').get('value');
	 							dijit.byId('identity').attr('value',identity+','+inx);
	 							dijit.byId('record_id').attr('value',identity+','+inx);
	 						} else {
	 							dijit.byId('identity').attr('value',inx);
	 							dijit.byId('record_id').attr('value',inx);
	 						}
					}
				}else{
					var clientId = dijit.byId('group_id').get('value');
					var clientCode = dijit.byId('client_code').get('value');
					var loanNumber = dijit.byId('loan_number').get('value');
					if(type==1){
						dijit.byId('group_id').attr('value','');
						dijit.byId('client_code').attr('value','');
					}else if(type==2){
						dijit.byId('loan_number').attr('value','');
						dijit.byId('group_id').attr('value',clientCode);
					}else{
						dijit.byId('loan_number').attr('value','');
						dijit.byId('client_code').attr('value',clientId);
					}
					//alert("No Result!");
					dijit.byId('identity').attr('value',"");
					dijit.byId('priciple_amount').attr('value',0);
					dijit.byId('os_amount').attr('value',0);
					dijit.byId('total_payment').attr('value',0);
					dijit.byId('amount_receive').attr('value',0);
					dijit.byId('discount').attr('value',0);
					dijit.byId('service_charge').attr('value',0);
					dijit.byId('penalize_amount').attr('value',0);
					dijit.byId('total_interest').attr('value',"");
					dijit.byId('amount_return').attr('value',"");
				}
				tem+='</table>';
				dojo.byId('data_table').innerHTML = tem;
				checkAll();
				//calculateDatePay();
			},
			error: function(e) {
				//alert(e);
			}
		});
}
function getAllLaonPayment(type){
	
	if(type==1){
		var loan_number = dijit.byId('loan_number').get('value');
	}else if(type==2){
		var loan_number = dijit.byId('client_code').get('value');
	}else if(type==3){
		var loan_number = dijit.byId('group_id').get('value');
	}
	
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'group-payment','action'=>'get-all-loannumber')); ?>';
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			    'type':type,
			},	
			handleAs:"json",
			load: function(respone) {
				status='<label style="color:red;">នៅឡើយ</lable>';
				tem='';	is_set=0;
				tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
					+'<thead><tr><th class="tdheader">ល.រ</th>'
					+'<th class="tdheader">កូដអតិថិជន</th>'
					+'<th class="tdheader">ឈ្មោះអតិថិជន</th>'
					+'<th class="tdheader" colspan="2">ថ្ងៃបង់ប្រាក់</th>'
					+'<th class="tdheader">ប្រាក់ដើមគ្រា</th>'
					+'<th class="tdheader">ប្រាក់ដើមត្រូវបង់</th>'
					+'<th class="tdheader">ប្រាក់ការ</th>'
					+'<th class="tdheader">ប្រាក់ត្រូវបង់សរុប</th>'
					+'<th class="tdheader">ប្រាក់ផាកពិន័យ</th>'
					+'<th class="tdheader">បញ្ចុះតម្លៃ</th>'
					+'<th class="tdheader">ស្ថានភាព</th>'
					+'<th class="tdheader">កំណត់សម្គាល់</th></tr>'
				+'</thead>';
				num=0;
				
				if(respone!=""){
					for(i=0;i<respone.length;i++){
						inx = i+1;
						status='<label style="color:red;">នៅឡើយ</lable>';
						++num;
						d = new Date(respone[i].date_payment);
						str_day = getDayString(d.getDay());
						curr =getCurrencyType(respone[i].currency_type);
						//date_collect = d.getDate()+'/'+d.getFullMonth()+'/'+d.getFullYear()
						
						//alert(total);
						 tem+= '<tr>';
						    tem += '<td>&nbsp;'+num+'</td>';
						    tem += '<td>&nbsp;'+respone[i].client_number+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+respone[i].name_kh+'&nbsp;</td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+str_day+'&nbsp;</td>';
						    tem += '<td style="white-space: nowrap;">&nbsp;'+respone[i].date_payment+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_principal)+' '+curr+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].principal_permonth)+' '+curr+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_interest)+' '+curr+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+dojo.number.format(respone[i].total_payment)+' '+curr+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+respone[i].pay_after+'&nbsp;</td>';
						    tem += '<td>&nbsp;'+respone[i].pay_before+'&nbsp;</td>';
							if(respone[i].is_completed==1){
								status = '<label style="color:blue;">បង់រួច</label>';
								if(respone[i].is_approved==1){is_appr='<label style="color:blue;">Approved</label>';}
							}else{
								if(is_set!=1){
									getdataPaymentToForm(respone[i]);
									is_set=1;
								}
								is_appr='';
							}
							tem += '<td>&nbsp;<label style="font-size:10px;">'+status+'</label></td>';
							tem += '<td>&nbsp;<label style="font-size:10px;">'+is_appr+'</label></td>';
						    tem += '</tr>';
	 					    
					}
				}
				tem+='</table>';
				dojo.byId('data_table1').innerHTML = tem;
			},
			error: function(e) {
				//alert(e);
			}
		});
}
function popupCheckCO(){
}

function calculateTotal(index){
	total_payment = 0;
	os_amount = 0;
	total_interest = 0;
	priciple_amount = 0;
	penalize_amount = dijit.byId('penalize_amount').get('value');
	discount = dijit.byId('discount').get('value');
	var after_penalize_amount = 0;
	var after_discount = 0;
	var totalAmount = 0;
	
	var ids =dijit.byId('identity').get('value');
	var arrays = ids.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		if($('#mfdid_'+index).attr('checked')){
			if(dijit.byId("identity").get('value')!="") {
				var ids = dijit.byId("identity").value;
				dijit.byId("identity").attr('value',ids+','+index);
			} else { 
				dijit.byId("identity").attr('value',index);
				}
		 }else{
			 var strings = arrays.join(',');
			dijit.byId('identity').attr('value',strings);
		}
    }
	var ids =dijit.byId('identity').get('value');
	var arrays = ids.split(',');
	for(var i=0;i<arrays.length;i++) {
 		var totalPay = $('#payment_'+arrays[i]).val();
		var date_collect = dijit.byId('collect_date').get('value');
		var oneDay = 24*60*60*1000;
		
		
		if($('#mfdid_'+arrays[i]).attr('checked')){
          total_payment = total_payment+parseFloat($('#payment_'+arrays[i]).val());
          os_amount = os_amount+parseFloat($('#principal_permonth_'+arrays[i]).val());
          total_interest = total_interest+parseFloat($('#interest_'+arrays[i]).val());
          priciple_amount =  priciple_amount+parseFloat($('#total_priciple_'+arrays[i]).val()) - parseFloat($('#principal_permonth_'+arrays[i]).val());

          var totalPay = $('#payment_'+arrays[i]).val();

          pay_date = new Date($('#date_payment_'+arrays[i]).val());
    		month = pay_date.getMonth()+1;
    		var datePay = month+'/'+pay_date.getDate()+'/'+pay_date.getFullYear();
			total_date = Math.round((date_collect - pay_date)/(oneDay));
			//alert(total_date);
			if(total_date>0){
				var ps = $('#pay_after_'+arrays[i]).val();
				
				if(ps.length!=0){
				 	if(ps.indexOf("%")!==-1){
				 	   var pps=ps.split("%");
				 	   if(!isNaN(pps[0])){
					 	   //alert(totalPay);
				 		  var rate_day = parseFloat(pps[0])/30;
					 	    var penalize_amount=(totalPay*(rate_day*total_date))/100;
					 	   after_penalize_amount = after_penalize_amount + parseFloat(penalize_amount);
					 	    //alert('penalize:'+after_penalize_amount);
					 	   totalAmount = totalAmount + (parseFloat(totalPay) + parseFloat(penalize_amount));
							//alert(totalAmount);
				 	   }else{
				 		  after_penalize_amount = after_penalize_amount + ps;
				 		 totalAmount = totalAmount + ps;
				 	   }
				 	  }else{
					 	   if(!isNaN(ps)&&ps!=0){
					 		  penalize_amount = parseFloat(ps).toFixed(2);
						 	    after_penalize_amount = after_penalize_amount + ((penalize_amount/30)*total_date);
						 	   totalAmount = totalAmount + (totalPay + penalize_amount);
					 	   }else{
						 	   // batch
						 	    after_penalize_amount = after_penalize_amount + ps;
						 	   totalAmount = totalAmount + totalPay;
					 	   }
				 	  }
				}
				
			}else{
				var ds = $('#pay_before_'+arrays[i]).val();
				if(ds.length!=0){
				 	if(ds.indexOf("%")!==-1){
				 	   var pds=ds.split("%");
				 	   if(!isNaN(pds[0])){
				 		  var rate_day = parseFloat(pds[0])/30;
					 	   var discount=(totalPay*(rate_day*(Math.abs(total_date))))/100;
					 	  after_discount = after_discount + parseFloat(discount);
					 	 totalAmount = totalAmount + (parseFloat(totalPay) - parseFloat(discount));

				 	   }else{
					 	    after_discount = after_discount + ds;
					 	   totalAmount = totalAmount + (totalPay - ds);
				 	   }
				 	  }else{
					 	   if(!isNaN(ds)&&ds!=0){
						 	    discount = parseFloat(ds).toFixed(2);
						 	    after_discount = after_discount + ((discount/30)*(Math.abs(total_date)));
						 	   totalAmount = totalAmount + (totalPay - ((discount/30)*(Math.abs(total_date))));
					 	   }else{
						 	   // batch
						 	    after_discount = after_discount+ds;
						 	   totalAmount = totalAmount + totalPay;
					 	   }
				 	  }
				}
			}
		}else{
		}
	}
	dijit.byId('amount_receive').attr('value',totalAmount);
	dijit.byId('penalize_amount').attr('value',after_penalize_amount.toFixed(2));
    dijit.byId('discount').attr('value',after_discount.toFixed(2));
	dijit.byId('total_payment').attr('value',totalAmount);
	dijit.byId('os_amount').attr('value',os_amount);
	dijit.byId('total_interest').attr('value',total_interest);
	dijit.byId('priciple_amount').attr('value',priciple_amount);
}

function checkAll(index){
	total_payment = 0;
	os_amount = 0;
	total_interest = 0;
	priciple_amount = 0;

	var date_collect = dijit.byId('collect_date').get('value');
	var oneDay = 24*60*60*1000;
	var after_penalize_amount = 0;
	var after_discount = 0;
	var totalAmount = 0;
	if($('#check_all').attr('checked')){
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = true;  
		});
		var ids =dijit.byId('record_id').get('value');
    	var arrays = ids.split(',');
    	
    	for(var i=0;i<arrays.length;i++){
    		var totalPay = $('#payment_'+arrays[i]).val();
    		if($('#mfdid_'+arrays[i]).attr('checked')){
    	          total_payment = total_payment+parseFloat($('#payment_'+arrays[i]).val());
    	          os_amount = os_amount+parseFloat($('#principal_permonth_'+arrays[i]).val());
    	          total_interest = total_interest+parseFloat($('#interest_'+arrays[i]).val());
    	          priciple_amount = priciple_amount+parseFloat($('#total_priciple_'+arrays[i]).val()) - parseFloat($('#principal_permonth_'+arrays[i]).val());

    	        pay_date = new Date($('#date_payment_'+arrays[i]).val());
          		month = pay_date.getMonth()+1;
          		var datePay = month+'/'+pay_date.getDate()+'/'+pay_date.getFullYear();
  				total_date = Math.round((date_collect - pay_date)/(oneDay));
  				if(total_date>0){
  					var ps = $('#pay_after_'+arrays[i]).val();
  					
  					if(ps.length!=0){
  					 	if(ps.indexOf("%")!==-1){
  					 	   var pps=ps.split("%");
  					 	   if(!isNaN(pps[0])){
  					 		  var rate_day = parseFloat(pps[0])/30;
  						 	    var penalize_amount=(totalPay*(rate_day*total_date))/100;
  						 	    after_penalize_amount = after_penalize_amount + parseFloat(penalize_amount);
  						 	   totalAmount = totalAmount + (parseFloat(totalPay) + parseFloat(penalize_amount));

  					 	   }else{
  						 	    after_penalize_amount = after_penalize_amount + ps;
  						 	   totalAmount = totalAmount + ps;
  					 	   }
  					 	  }else{
  						 	   if(!isNaN(ps)&&ps!=0){
  						 		  penalize_amount = parseFloat(ps).toFixed(2);
  							 	    after_penalize_amount = after_penalize_amount + penalize_amount;
  							 	   totalAmount = totalAmount + (totalPay + penalize_amount);
  						 	   }else{
  							 	   // batch
  							 	    after_penalize_amount = after_penalize_amount + ps;
  							 	   totalAmount = totalAmount + totalPay;
  						 	   }
  					 	  }
  					}
  					
  				}else{
  					var ds = $('#pay_before_'+arrays[i]).val();

  					if(ds.length!=0){
  					 	if(ds.indexOf("%")!==-1){
  					 	   var pds=ds.split("%");
  					 	   if(!isNaN(pds[0])){
  					 		  var rate_day = parseFloat(pds[0])/30;
  						 	   var discount=(totalPay*(rate_day*(Math.abs(total_date))))/100;
  						 	  after_discount = after_discount + parseFloat(discount);
  						 	  //alert("dicount"+after_discount);
  						 	 totalAmount = totalAmount + (parseFloat(totalPay) - parseFloat(discount));

  					 	   }else{
  						 	    after_discount = after_discount + ds;
  						 	   totalAmount = totalAmount + (totalPay - ds);
  					 	   }
  					 	  }else{
  						 	   if(!isNaN(ds)&&ds!=0){
  							 	    discount = parseFloat(ds).toFixed(2);
  							 	    after_discount = after_discount + discount;
  							 	   totalAmount = totalAmount + (totalPay - discount);
  						 	   }else{
  							 	   // batch
  							 	    after_discount = after_discount+ds;
  							 	   totalAmount = totalAmount + totalPay;
  						 	   }
  					 	  }
  					}
  				}
    		}
        }
        //dijit.byId('hide_total_payment').attr('value',parseFloat(total_payment.toFixed(2)));
    	dijit.byId('penalize_amount').attr('value',after_penalize_amount.toFixed(2));
        dijit.byId('discount').attr('value',after_discount.toFixed(2));
        dijit.byId('total_payment').attr('value',totalAmount.toFixed(2));
    	//dijit.byId('total_payment').attr('value',total_payment);
    	dijit.byId('os_amount').attr('value',os_amount);
    	dijit.byId('total_interest').attr('value',total_interest);
    	dijit.byId('priciple_amount').attr('value',priciple_amount);
  
	}else{
		dijit.byId('identity').attr('value','');
		$('.checkbox').each(function() { //loop through each checkbox
            this.checked = false; //deselect all checkboxes with class "checkbox1" 
        });
		dijit.byId('penalize_amount').attr('value',0);
        dijit.byId('discount').attr('value',0);
        dijit.byId('total_payment').attr('value',0);
		dijit.byId('total_payment').attr('value',0);
		dijit.byId('os_amount').attr('value',0);
		dijit.byId('total_interest').attr('value',0);
		dijit.byId('priciple_amount').attr('value',0);
	}
}

function getdataPaymentToForm(data){//use
	dijit.byId('currency_type').attr('value',data.currency_type);
	dijit.byId('group_id').attr('value',data.group_id);
	dijit.byId('co_id').attr('value',data.co_id);
	dijit.byId('branch_id').attr('value',data.branch_id);
	dijit.byId('total_interest').attr('value',data.total_interest);
	dijit.byId('loan_number').attr('value',data.loan_number);
	dijit.byId('client_code').attr('value',data.group_id);
	dijit.byId('reciever').attr('value',data.collect_by);
	totalReturn();
}
function getDayString(num){
	var days= ["ច័ន្ទ", "អង្គារ", "ពុធ", "ព្រហ","សុក្រ","សៅរ៏","អាទិត្យ"];
	return days[num];
}
function getCurrencyType(type){
	var option=["៛","$","B"];
	return option[type-1];
}
function totalReturn(){
	receive_amount = dijit.byId('amount_receive').get('value');
	total_payment = dijit.byId('total_payment').get('value');
	amonut_return = receive_amount-total_payment;
	dijit.byId('amount_return').attr('value',amonut_return);
}


</script>
