<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_STAFF_POSITION'));
?>	
<?php  $frm = $this->frm_department;?>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'payroll','controller'=>'department','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="90%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend><strong><?php echo $tr->translate("DEPARTMENT_INFO");?></strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>
							<?php echo $frm->getElement('id');?>
							<?php echo $tr->translate("DEPARTMENT_KH")?></td>
							<td><?php  echo $frm->getElement('department_kh');?></td>
							<td><?php echo $tr->translate("DEPARTMENT_EN")?></td>
							<td><?php  echo $frm->getElement('department_en');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISPLAY_BY")?></td>
							<td><?php  echo $frm->getElement('display');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $frm->getElement('status');?></td>
						</tr>

					</table>	
					<div style="text-align: center; margin: 10px 0px;">
						<input type="submit" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
					</div>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>