<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form_client_blacklist;
//echo  $frm;exit();
?>
<title> <?php echo $tr->translate("CALLECTERALL_TYPE")?></title>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'group','controller'=>'Clientblacklist','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				//return false;
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside'>
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("CLIENT BLACK LIST")?></strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
						    <?php echo $frm->getElement('id');?>
							<td><?php echo $tr->translate("BRANCH")?></td>
							<td><?php echo $frm->getElement('branch')?></td>	
							<td><?php echo $tr->translate("CLIENT_CODE")?></td>
							<td><?php echo $frm->getElement('client_code')?></td>								
							<td><?php echo $tr->translate("CLIENT_NAME")?></td>
							<td><?php echo $frm->getElement('client_name')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PROBLEM")?></td>
							<td><?php echo $frm->getElement('problem')?></td>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><?php echo $frm->getElement('date')?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status')?></td>
					   </tr>
					</table>
					</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" name="btn_save" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");


function getmemberIdGroup(){
	client_code= dijit.byId('client_code').get('value');
	dijit.byId('client_name').attr('value',client_code);
}
function checkMember(){
	client_name= dijit.byId('client_name').get('value');
	dijit.byId('client_code').attr('value',client_name);
}
</script>
