<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Client '));
?>	
<?php  $frm = $this->frm_client;?>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('branch_id').get('value')==''){
					alert('Please Select Branch');
					dijit.byId('branch_id').focus();
					return false;
			    }
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
                if(dijit.byId('situ_status').get('value')==''){
					alert('Province situ_status');
					dijit.byId('situ_status').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("ADD_CLIENT");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME");?>*</td>
							<td><?php echo $frm->getElement('branch_id'); echo $frm->getElement('id');?></td>
							<td><?php echo $tr->translate("IS_GROUP")?></td>
							<td><?php echo $frm->getElement('is_group');?></td>		
							<td><?php echo $tr->translate("GROUP_CODE")?></td>
						   <td><?php echo $frm->getElement('group_code');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("GROUP_NAME")?></td>
							<td><?php echo $frm->getElement('group_id');?></td>
							<td><?php echo $tr->translate("CLIENT_NO")?></td>
							<td><?php echo $frm->getElement('client_no');?></td>
							<td><?php echo $tr->translate("NAME_KHMER")?>*</td>
							<td><?php  echo $frm->getElement('name_kh');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_ENG")?>*</td>
							<td><?php  echo $frm->getElement('name_en');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('sex');?></td>
							<td><?php echo $tr->translate("SITU_STATUS")?>*</td>
							<td><?php  echo $frm->getElement('situ_status');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('national_id');?></td>
							<td><?php echo $tr->translate("JOB_TYPE")?></td>
							<td><?php echo $frm->getElement('job');?></td>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $frm->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHOTO")?></td>
							<td><?php echo $frm->getElement('photo');?></td>
							<td><?php echo $tr->translate("PROVINCE")?>*</td>
							<td><?php echo $frm->getElement('province');?></td>
							<td><?php echo $tr->translate("DISTRICT")?></td>
							<td><input id="district" required="true" ><?php //echo $frm->getElement('district');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("COMMUNE")?></td>
							<td><input id="commune" ><?php //echo $frm->getElement('commune');?></td>
							<td><?php echo $tr->translate("VILLAGE")?></td>
							<td><input id="village" ><?php  //echo $frm->getElement('village');?></td>
							<td><?php echo $tr->translate("STREET")?></td>
							<td><?php  echo $frm->getElement('street');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("HOUSE")?></td>
							<td><?php  echo $frm->getElement('house');?></td>
							<td><?php echo $tr->translate("JOIN_WITH")?></td>
							<td><?php  echo $frm->getElement('join_with');?></td>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('join_nation_id');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
							<td><?php  echo $frm->getElement('relate_with');?></td>
							<td><?php echo $tr->translate("TEL")?></td>
							<td><?php  echo $frm->getElement('relate_tel');?></td>
							<td><?php echo $tr->translate("SPOUSE_NAME")?></td>
							<td><?php echo $frm->getElement('spouse');?></td>							
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php echo $frm->getElement('spouse_nationid');?></td>
							<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
							<td><?php  echo $frm->getElement('guarantor_with');?></td>
							<td><?php echo $tr->translate("TEL")?></td>
							<td><?php  echo $frm->getElement('guarantor_tel');?></td>
							
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top"><?php  echo $frm->getElement('status');?></td>
							<td valign="top"><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('desc');?></td>
							<td valign="top"><?php echo $tr->translate("AUTO_COLLATERAL"); echo $frm->getElement('chackcall');?></td>
							<td><img height="70px" src="<?php echo $this->baseUrl().'/images/'.$this->photo;?>" /></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
						    <input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>

<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.ready(function(){
	var district_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->district));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: district_data}),
	autoComplete: true,
	query: {
		//pro_id: "-1"
		pro_id:"<?php echo $this->row['pro_id'];?>"
	},            
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	value: "<?php echo $this->row['dis_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
				filterCommune();
	    }
	}, "district");

	var commune_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->commune_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: commune_data}),
	autoComplete: true,
	query: {
		//district_id: "-1"
		district_id: "<?php echo $this->row['dis_id'];?>"
	},            
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	value: "<?php echo $this->row['com_id'];?>",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
			filterVillage();
	}
	}, "commune");

	var village_data = new dojo.store.Memory({
	       data: <?php print_r(Zend_Json::encode($this->village_name));?>
	});
	 
	new dijit.form.FilteringSelect({
	store: dojo.data.ObjectStore({objectStore: village_data}),
	autoComplete: true,
	query: {
		//commune_id:"-1"
		commune_id:"<?php echo $this->row['com_id'];?>"
	},            
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
	value: "<?php echo $this->row['village_id'];?>",
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
		onChange: function() {
}
	}, "village");

	
});
function filterDistrict(){
	dijit.byId('district').query.pro_id = dijit.byId('province').get('value');
}
function filterCommune(){
	dijit.byId('commune').query.district_id = dijit.byId('district').get('value');
}
function filterVillage(){
	dijit.byId('village').query.commune_id = dijit.byId('commune').get('value');
}
url_group = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getgroupcode'));?>';
function getGroupCode(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch First');
		dijit.byId('branch_id').focus();
		return false;
	}
	group_id=dijit.byId('group_id').get('value');
	if(group_id==''){group_id=0;}
	if(dijit.byId('is_group').checked ==true){
		is_group=1;
		dijit.byId('group_code').attr('value','');
		dijit.byId('group_id').set('readOnly', true);
		
	}else{
		is_group=0;	
		dijit.byId('group_id').set('readOnly', false);
	}
	
	dojo.xhrPost({
		url:url_group,	
		content:{ 
		    'group_id':group_id,
		    'is_group':is_group,
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {	
			dijit.byId('group_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
client_submit = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientcode'));?>';
function getFunction(){
		getGroupCode();
		branch_id = dijit.byId('branch_id').get('value');
		dojo.xhrPost({
			url:client_submit,	
			content:{ 
			    'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {	
				dijit.byId('client_no').attr('value',data);
			},
			error: function(err) {
			}
		});
}
</script>