<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('VIEW_CLIENT'));
	$rs = $this->client_list;
?>	
<style>
.border-cover {
  border: 1px solid #ccc;
  padding: 0px 4px;
  background: #E5F2F5;
}}
</style>
<table cellspacing="10" width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("VIEW_CLIENT");?></strong></legend>
					<div style=" width:22cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<div id="divPrint" style="width: 100%;">
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME");?>*</td>
							<td class="border-cover "><?php echo $rs['branch_name'];?></td>
							<td><?php echo $tr->translate("IS_GROUP")?></td>
							<td class="border-cover "><?php if($rs['is_group']==1)echo'as Group';?></td>		
							<td><?php echo $tr->translate("GROUP_CODE")?></td>
						   <td class="border-cover "><?php echo $rs['group_code'];?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("GROUP_NAME")?></td>
							<td class="border-cover "><?php echo $rs['parent'];?></td>
							<td><?php echo $tr->translate("CLIENT_NO")?></td>
							<td class="border-cover "><?php echo $rs['client_number'];?></td>
							<td><?php echo $tr->translate("NAME_KHMER")?>*</td>
							<td class="border-cover "><?php echo $rs['name_kh'];?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_ENG")?>*</td>
							<td class="border-cover "><?php echo $rs['name_en'];?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td class="border-cover "><?php echo $rs['sex'];?></td>
							<td><?php echo $tr->translate("SITU_STATUS")?>*</td>
							<td class="border-cover "><?php  echo $rs['sit_status'];?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td class="border-cover "><?php echo $rs['client_d_type'];?></td>
							<td></td>
							<td class="border-cover "><?php echo $rs['nation_id'];?></td>
							<td><?php echo $tr->translate("JOB_TYPE")?></td>
							<td class="border-cover "><?php echo $rs['job'];?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td class="border-cover "><?php echo $rs['phone'];?></td>
							<td><?php echo $tr->translate("PHOTO")?></td>
							<td class="border-cover "><?php //echo $frm->getElement('photo');?></td>
							<td><?php echo $tr->translate("PROVINCE")?>*</td>
							<td class="border-cover "><?php echo $rs['province_en_name'];?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISTRICT")?></td>
							<td class="border-cover "><?php echo $rs['district_name'];?></td>
							<td><?php echo $tr->translate("COMMUNE")?></td>
							<td class="border-cover "><?php echo $rs['commune_name'];?></td>
							<td><?php echo $tr->translate("VILLAGE")?></td>
							<td class="border-cover "><?php echo $rs['village_name'];?></td>							
						</tr>
						<tr>
							<td><?php echo $tr->translate("STREET")?></td>
							<td class="border-cover "><?php echo $rs['street'];?></td>
							<td><?php echo $tr->translate("HOUSE")?></td>
							<td class="border-cover "><?php echo $rs['house'];?></td>
							<td><?php echo $tr->translate("JOIN_WITH")?></td>
							<td class="border-cover "><?php echo $rs['join_with'];?></td>	
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td class="border-cover "><?php echo $rs['join_d_type'];?></td>
							<td></td>
							<td class="border-cover "><?php echo $rs['join_nation_id'];?></td>
							<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
							<td class="border-cover "><?php echo $rs['relate_with'];?></td>														
						</tr>
						<tr>
							<td><?php echo $tr->translate("TEL")?></td>
							<td class="border-cover "><?php echo $rs['join_tel'];?></td>
							<td><?php echo $tr->translate("SPOUSE_NAME")?></td>
							<td class="border-cover "><?php echo $rs['spouse_name']; ?></td>
							<td><?php echo $tr->translate("TEL")?></td>
							<td class="border-cover "><?php echo $rs['guarantor_tel'];?></td>				
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td class="border-cover "><?php echo $rs['guarantor_d_type'];?></td>
							<td></td>
							<td class="border-cover "><?php echo $rs['spouse_nationid'];?></td>
							<td><?php echo $tr->translate("RELATIVE_WITH")?></td>
							<td class="border-cover "><?php echo $rs['guarantor_with'];?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td class="border-cover "><?php echo $rs['remark'];?></td>
							<td valign="top"><?php echo $tr->translate("GUARANTOR_ADDRESS")?></td>
							<td valign="top" class="border-cover "><?php  echo $rs['guarantor_address'];?></td>
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top" class="border-cover "><?php  echo $rs['status'];?></td>
						</tr>
					</table>	
				</div>
				</div>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
