<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm;
?>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.td{width:179px !important;}
</style>
<form id='frm_add' action="<?php echo $this->url(array('module'=>'capital','controller'=>'capital-transfer','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="POST" enctype="application/x-www-form-urlencoded" onload="getAmountFrom();getAmountTo();">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<!-- <table cellspacing="10"> -->
<!-- 	<tr> -->
<!-- 		<td> -->
				<fieldset>
					<legend><strong>Form Capital Transfer</strong></legend>
					<table cellspacing="10"  width="100%">
						<?php //echo $frm->getElement('id');?>
						<tr>
							<td><?php echo $tr->translate("ពីសាខា")?></td>
							<td class="td"><?php echo $frm->getElement('brance_from')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa_from')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath_from')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil_from')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ទៅសាខា")?></td>
							<td><?php echo $frm->getElement('brance_to')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa_to')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath_to')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil_to')?></td>
						</tr>
						<tr>
							<td>Date</td>	
							<td><?php echo $frm->getElement('date')?></td>
							<td>ប្រាក់ដុល្លា</td>
							<td><?php echo $frm->getElement('usa')?></td>
							<td>ប្រាក់បាត</td>	
							<td><?php echo $frm->getElement('bath')?></td>
							<td>ប្រាក់រៀល</td>
							<td><?php echo $frm->getElement('reil')?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("Stutas")?></td>
							<td><?php echo $frm->getElement('status')?></td>
							<td>Note</td>
							<td colspan="3"><?php echo $frm->getElement('note');?></td>
							<td></td>
							<td></td>
							
						</tr>
					</table>
				</fieldset>
				<table cellspacing="10"  width="100%">
					<tr>
						<td align="center"><input type="submit" value="រក្សាទុកថ្មី" label="រក្សាទុកថ្មី" name="save" id="save" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
						<input type="submit" value="បិទ" label="រក្សាទុកបិទ" name="save_close" id="save_close" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave"/>
						<input type="submit" value="បោះបង់" label="បោះបង់" name="cancel" id="cancel" dojoType="dijit.form.Button" iconClass="dijitIconDelete"/></td>
					</tr>
				</table>
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.DateTextBox");

function validateTransfer(type){
	//alert(type);
	if(type==1){
		var usa = dijit.byId('usa').get('value');
		var usa_from = dijit.byId('usa_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(usa > usa_from){
			alert("Money transfer is not enought");
			dijit.byId('usa').attr('value',usa_from);
		}
	}

	if(type==2){
		var bath = dijit.byId('bath').get('value');
		var bath_from = dijit.byId('bath_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(bath > bath_from){
			alert("Money transfer is not enought");
			dijit.byId('bath').attr('value',bath_from);
		}
	}

	if(type==3){
		var riel = dijit.byId('reil').get('value');
		var riel_from = dijit.byId('reil_from').get('value');
		//alert(usa);
		//alert(usa_from);
		if(riel > riel_from){
			alert("Money transfer is not enought");
			dijit.byId('reil').attr('value',riel_from);
		}
	}
}
var getAmount ='<?php echo $this->url(array('module'=>'capital','controller'=>'capital-transfer','action'=>'getamountbybranceid'));?>'; 
function getAmountFrom(){
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance_from').get('value'),
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('usa_from').attr('value',data.amount_dollar);
			dijit.byId('bath_from').attr('value',data.amount_bath);
			dijit.byId('reil_from').attr('value',data.amount_riel);
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}

function getAmountTo(){
	dojo.xhrPost({
	    url: getAmount,	
	    content : { 
		    'brance_id':dijit.byId('brance_to').get('value'),
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('usa_to').attr('value',data.amount_dollar);
			dijit.byId('bath_to').attr('value',data.amount_bath);
			dijit.byId('reil_to').attr('value',data.amount_riel);
		},
		error: function(err) {
			alert(err);
		alert("Your message could not be sent, please try again!.");	        
		}
	});
}
</script>
